### ISSUE TITLE
Tokens function returning wrong values for text_en analyzer

### ISSUE THREAD

**Issue by robhopkins-gl** [arangodb/arangodb#10153]
## My Environment

* 3.5.0:        
* RocksDB:             
* Single Server:       
* Kubernetes:   
* NA:               
* NA:               
* Unbuntu:        
*  32Gb:        
* SSD:        
* NA:              

## Component, Query & Data

AQL query using web interface and with driver:
When used the TOKENS function with the 'text_en' analzyer and the term ends with 'Y' it converts it to an 'i'.  This only happens when the terms ends with Y.

Example query:
It has three terms all with a 'Y':

let tokens = TOKENS("HAS_Y_MIDDLE Y_STARTS ENDWITH_Y", 'text_en')
return tokens
[
  [
    "has_y_middl",
    "y_start",
    "endwith_i"
  ]
]

## Steps to reproduce

1. Run the following query:
  LET tokens = TOKENS("HAS_Y_MIDDLE Y_STARTS ENDWITH_Y", 'text_en')
  RETURN tokens

__Problem__: 
The ENDWITH_Y term is transformed to 'endwith_i'.

__Expected result__:
The ENDWITH_Y term to be transformed to 'endwith_y'.

**Comment by Simran-B** [comment]
The [built-in Analyzers](https://www.arangodb.com/docs/stable/arangosearch-analyzers.html#built-in-analyzers) have case conversion and **stemming enabled**. `ENDWITH_Y` is stemmed (and case-converted) to `endwith_i`. This is the expected behavior. Also see https://snowballstem.org/algorithms/

If you don't want stemming, configure your own [Analyzer](https://www.arangodb.com/docs/stable/arangosearch-analyzers.html) (through the HTTP or JS API).

Using arangosh:

```js
var analyzers = require("@arangodb/analyzers");
var analyzer = analyzers.save("text_en_nostem", "text", {"locale": "en.utf-8", "stopwords": [], "stemming": false}, ["position", "norm", "frequency"]);
```

(I omitted two other properties as they are the default, `"case": "lower", "accent": false"`)

```js
RETURN TOKENS("HAS_Y_MIDDLE Y_STARTS ENDWITH_Y", "text_en_nostem")
```
```json
[
  [
    "has_y_middle",
    "y_starts",
    "endwith_y"
  ]
]
```

**Comment by OmarAyo** [comment]
Hi @robhopkins-gl 

Did you have the chance to read Simran's message ? 

Please provide feedback

Best,

**Comment by OmarAyo** [comment]
Hi @robhopkins-gl 

We did not hear from you recently, we are going to close this ticket

Feel free to reopen it again if needed

Best,
