### ISSUE TITLE
Cannot add unique index for _to in edge collection

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#10170]
I'm on arango 3.4.7 and I wanted to add an unique index on `_to`. For some reason it seems to start indexing but nothing happens. No error nothing. I tried it in the regular html backend of arango.

Maybe its related to #5643?

**Comment by jsteemann** [comment]
@konsultaner: Indexing a larger collection may take some time. 
The web UI of ArangoDB will only show the index once it has been fully created. If index creation fails it should however display an error message eventually, but that may be easy to overlook when continuing working on other things in the web UI.
In order to check if there is any issue with creating that index, can you try starting the index creation from the arangosh instead? The command for creating an index should be something like
```
db.<collection>.ensureIndex({ fields: ["_to"], ... });
```
(if the index is just on `_to` - other index properties will need to be added, such as `type` (mandatory), `unique` (optional), `sparse` (optional).

**Comment by konsultaner** [comment]
I tried it again and it worked. I have no Idea why it did not work the first time. Sorry, I might have done something wrong..
