### ISSUE TITLE
Arangoexport does not handle line feeds when exporting as csv

### ISSUE THREAD

**Issue by brendanwheble** [arangodb/arangodb#10193]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Windows
* __Total RAM in your machine__:        16Gb
* __Disks in use__:        SSD
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
Arangoexport

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:
Create a collection, add a document like this:

{a:"Text \r\n Line",b:"test"}

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Add dataset above
2. Use arangoexport to export as csv 
e.g. arangoexport --query "FOR doc IN setup RETURN {a:doc.a,b:doc.b}" --fields "a,b" --type csv

__Problem__:
When the csv is opened the linefeeds aren't escaped. We end up with two rows instead of one when the file is opened in Excel.

__Expected result__:
A single row

**Comment by jsteemann** [comment]
CSV values that contain line breaks were not treated in a special way, but it is more reasonable to enclose such values in quotes.
The PRs above add the functionality. They are targeting ArangoDB release versions 3.4.9 and 3.5.2

**Comment by brendanwheble** [comment]
Thanks for the speedy turnaround. Nice work!

**Comment by Simran-B** [comment]
Side note: CSV import in Excel is broken since decades (haven't tried the latest Office edition though). There are different ways to get CSV into Excel, but they all behave differently and it's tricky to get UTF-8 data with line breaks within cells into Excel, even more so using a German version where `;` is the field separator instead of `,` (workaround: use tab as delimiter, which should work in all versions). The import assistant for text advances to a new row no matter if you use quote marks or not. Opening via double-click does not have this problem, but the data needs to be encoded in UTF16-LE to not mangle non-ASCII characters from my experience. And if you want to make Excel treat digits as text, then quote marks are not sufficient, you need to append a non-digit character (preferably an invisible tab) to avoid the automatic conversion to a number.
