### ISSUE TITLE
Question: update vs replace

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#10517]
**Question**

Which operation is more expensive in ArangoDB:

A [`replace`](https://www.arangodb.com/docs/3.4/data-modeling-documents-document-methods.html#replace) or an [`update`](https://www.arangodb.com/docs/3.4/data-modeling-documents-document-methods.html#update)?

Does `update` trigger an index rebuild in ArangoDB, or only when you update fields that are part of the index? What about `replace` ?

**Comment by Simran-B** [comment]
Both update and replace create a new document revision, so technically a new document (append-only architecture). Therefore there should be no real difference in performance, although update might be slightly slower because it has to merge attributes.

In the MMFiles storage engine, indexes are built at each server startup as they are held in memory only (except the persistent index type). With RocksDB all indexes are persistent. Whenever a document is changed (new revision), all relevant indexes get updated accordingly. There is at least the primary index, in edge collections also the edge index. Secondary (user-defined) indexes get updated if necessary. Indexes are altered, not rebuilt.

**Comment by gamedev8** [comment]
Ok, thanks @Simran-B
