### ISSUE TITLE
about customizing my own text tokens func in analyzor

### ISSUE THREAD

**Issue by Kuzzzz** [arangodb/arangodb#10521]
hello,
how can i customize my own text tokens function (such as a new zh tokenizer) in analyzor?

**Comment by Simran-B** [comment]
The Chinese text Analyzer does not have a **stemmer** provided by the Snowball library, and checking Wikipedia there does not seem to be a need for it because the language essentially lacks inflection. 

There is **tokenization**, which is provided by the ICU library. It returns more than one character in some cases, e.g. `RETURN TOKENS("供曽人件", "text_zh") // [ "供", "曽", "人件" ]`, but as I don't know Chinese I can only assume that this is correct.

Other options:
- **accent removal**: does not seem to apply to Chinese, but correct me if I'm wrong.
- **case conversion**:  I found something about different number literals, but it does not sound like it would expected to convert the ones to the others by means of converting to "upper" or "lower" case.
  https://www.quora.com/Do-Chinese-characters-have-letter-case-i-e-distinct-upper-and-lower-cases
- **stopword removal**: This is supported as far as I can tell.

The only reason to create a custom Analyzer for Chinese text is therefore one with a stopword list from what I can tell. This can be done e.g. via arangosh:

```js
var analyzers = require("@arangodb/analyzers")
analyzers .save("text_zh_stopwords", "text", { locale:"zh.utf-8", stopwords: ["\u842c", … ] }, ["norm","frequency","position"])
```

Note: Do not leave out `.utf8` or it may mangle your input.

AQL usage example:
```js
RETURN TOKENS("千, 萬", "text_zh_stopwords") // [ "千" ]
```

**Comment by Kuzzzz** [comment]
thanks a lot!  And a more question: if i want to use tokens func to split a chinese sentence into any charactors , such as "今天天气真好" => [“今","天","天","气","真","好”].
How can i do this? (I think may be ngram can help me, but there is no example about ngram in official document )

**Comment by Simran-B** [comment]
You can either do the processing in your application and use ArangoDB simply to store your data, or you have to integrate the desired functionality and compile your own binaries:
https://github.com/arangodb/arangodb/tree/devel/3rdParty/iresearch
https://github.com/arangodb/arangodb/tree/devel/3rdParty/snowball
https://github.com/arangodb/arangodb/tree/devel/arangod/IResearch

**Comment by Kuzzzz** [comment]
Thx! How can i fuzzy match doc`s attributes by LIKE in ArangoSearch?
Such as :  For doc in viewName  SEARCH  doc.name LIKE "%abc%" RETURN doc    when i want to search for the docs which name attribute contains 'abc'.

**Comment by Simran-B** [comment]
For "contains" style searches the only option at the moment is to use an ngram Analyzer like in your example. v3.6.0 will add support for edge ngrams, i.e. the input gets tokenized and then ngrams are created for each token (as opposed to ngrammification of the input as a whole). Fuzzy matching features such as `LIKE` will be added in the future.

**Comment by gnusi** [comment]
@Kuzzzz `LIKE` operator support was recently merged into `devel` branch and will become available in the next feature release.

**Comment by dothebart** [comment]
Hi, 
please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) with many more Arangosearch features is available. Closing as fixed.
