### ISSUE TITLE
Python version requirements

### ISSUE THREAD

**Issue by uchuugaka** [arangodb/arangodb#10524]
Is Python 2 still a build requirement?
End Of Life for Python 2 is coming soon…

**Comment by uchuugaka** [comment]
Is it because of CMake?

**Comment by uchuugaka** [comment]
or because Sphinx-Doc (via CMAKE)?

**Comment by dothebart** [comment]
Hi, 
the ArangoDB internal tools have been python3-ified already. Whats still missing is the GYP of V8, which is currently being worked on at:
https://github.com/arangodb/arangodb/pull/10274
However We're strill struggeling to get it working on Windows, which is why this won't be part of ArangoDB 3.6.

**Comment by uchuugaka** [comment]
Oh good to know!
Thanks for the succinct and clear answer. 
It's ironic that V8 requires Python and GYP ahahahaa.

**Comment by apapsch** [comment]
Hi @dothebart:

> the ArangoDB internal tools have been python3-ified already. Whats still missing is the GYP of V8, which is currently being worked on at:
> https://github.com/arangodb/arangodb/pull/10274
> However We're strill struggeling to get it working on Windows, which is why this won't be part of ArangoDB 3.6.

Your linked PRs have been closed for a while, is Python2 now good to be replaced with v3?

**Comment by dothebart** [comment]
python 2 is no longer supported by later ArangoDB releases for a while now. Which place are you talking about?
