### ISSUE TITLE
_id cannot be indexed in document tree

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#10653]
I have an document that is structured like this:

```json
{
    "_id" : "Invoice/10000",
    "debitor" : {
        "_id" : "Debitor/10000",
        "name" : "A Debitor"
    }
}
```

In Arango 2.4.x I could add an index to the debitor._id field. In my code like this:

```java
ModelService.getCollection(Invoice.class).ensureHashIndex(
    new ArrayList<String>(){{add("debitor._id");}},
    new HashIndexOptions()
);
```

With arango 3.5.x it has become impossible. Is this a bug or a wanted behaviour?

**Comment by Simran-B** [comment]
From [CHANGELOG](https://github.com/arangodb/arangodb/blob/devel/CHANGELOG#L489):

>v3.5.0-rc.5 (2019-07-22)
>------------------------
>…
>* Disallow indexing the `_id` attribute even as a sub-attribute.
>  Previous versions of ArangoDB did not allow creating indexes on the `_id` attribute, but didn't
>  check if an index was created on the `_id` attribute of a sub-attribute, e.g. `referredTo._id`
>  or `data[*]._id`.
>  Such indexes could be created with previous versions of ArangoDB, but they were **non-functional**.
>  From now on, such indexes cannot be created anymore, and any attempts to create them will fail.

**Comment by konsultaner** [comment]
Ok, totally understandabel, but as a user it feels a bit odd. I very often just take models from other collections and store a reduced version of it in the other document. In my case the debitor of an invoice. I would have to change my model serialization for submodels to make it indexable. I do understand the behaviour, but it blows up code and makes it less maintainable for that concrete case.

**Comment by Simran-B** [comment]
@jsteemann Can you share what the exact reason is why `_id` subattributes can't be indexed and estimate how difficult it would be to implement/fix?

**Comment by konsultaner** [comment]
@Simran-B this must be a misunderstanding. I have no Idea why arango does not allow `_id` subattributes to be indexed. I just ment that in my Java code I have a lot of cases where I use  `_id` subattributes.

> Previous versions of ArangoDB did not allow creating indexes on the _id attribute, but didn't
> check if an index was created on the _id attribute of a sub-attribute, e.g. `referredTo._id`
> or `data[*]._id`

Am I right that this is a arangodb bug? I'm kind of confused 😅

**Comment by Simran-B** [comment]
Let me try to explain:

The `_id` consists of the collection name + `/` + document key. The discriminating part is the key, i.e. the `collection-name/` prefix does not add anything to identify a document within a collection, only the key does (it does allow you to identify a document within a database however). A built-in index on `_id` in addition to the primary index on `_key` would be redundant, and collections can be renamed which means the name can change at any time, which would invalidate an entire index on `_id`.

Even though it looks to users as if `_id` would be a system attribute like `_key`, it does not actually exist. It can be seen as computed property, concatenating the current collection name with the document key at query time. It doesn't make much sense to allow users to index the virtual `_id` attribute if they can simply use the `_key` attribute instead, because of the aforementioned problem of collection names changing, but also because it would take a considerable amount of time and code to support this not-really-useful use case.

A side-effect seems to be that sub-attributes called `_id` are not supported either, as that would also require special handling (the attribute has to be materialized to a static string at least). Simply disallowing `_id` attributes in index definitions altogether was presumably the easiest solution.

**Comment by konsultaner** [comment]
@Simran-B ok, totally understand. This is a very complex issue. 

Renaming a collection is something very difficult and immediately breaks the business logic code. I guess renaming a collection happens only in conjunction with a version update of the software using arango db. So for me it looks like renaming the submodel `_id` field should be a part of this refactoring or update respectively. IMO this does not have to be part of the dbms.?

> It doesn't make much sense to allow users to index the virtual _id attribute if they can simply use the _key attribute instead

true, but calling `DOCUMENT()` would need the collection name anyway. One would have to create the `_id` manually.

> A side-effect seems to be that sub-attributes called _id are not supported either, as that would also require special handling (the attribute has to be materialized to a static string at least).

This sounds like it should be materialized anyway, since a submodel `_id` does not necessarily have to also carry a `_key`. What happens with the `_id` in a submodel if no `_key` is part of it?

----

I think closing this issue makes sense here, since this is a matter of philosophy not an issue. Thanks for the clarification 😊
