### ISSUE TITLE
Empty Result, but adding a WARN(false, "") fixes it

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#10785]
## My Environment

arangosh (ArangoDB 3.4.8 [linux] 64bit, using jemalloc, build tags/v3.4.8-0-g0952837c2a, VPack 0.1.33, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0k  
CentOS Linux 7 (Core)

Single Server 150GB Mem, 64 Cores, SSD

## The issue

I have a query that runs the accounting for our erp-system. This worked very well until we moved from a virtual machine to a non-virtual machine with better performance. The problem is that executing this query will return no result. It seems like one collection that has about 3 million entries is not loaded. I wanted to debug the query and added a `WARN(false, "")` and for some reason it worked. The only difference now is, that the perfromance is very poor now. It takes about 10 times longer to compute the query and it runs on one core only.

The same query, the same database version with rocksdb, the same data and without the  `WARN(false, "")` hack will compute on my laptop (win10).

Any Idea? 🤷‍♂️

@mchacki this is the issue to my mail.

**Comment by konsultaner** [comment]
@mchacki @OmarAyo 

After making it possible to reproduce the behaviour again, I ran the profiling. I found a very interesting change in the query when I compared the query with and without the `WARN(false, "")`. It seems like the optimizer is doing something different:

assuming that you have the query I may only post this little difference.

testsystem with `WARN(false, "")`:

```
764   32913       3.14192                           - FOR v  /* vertex */, e  /* edge */, p  /* paths */ IN 1..1  /* min..maxPathDepth */ OUTBOUND #170 /* startnode */  OrderedDish
89   CalculationNode       764   32913       0.37724                             - LET #174 = ((((((p.`vertices`[1].`deliveryDate` == deliveryDateTime) && (p.`edges`[0].`deliveryDate` == deliveryDateTime)) && (p.`edges`[0].`isOrdered` == true)) && (p.`edges`[0].`isCanceled` != true)) && (p.`edges`[0].`isLocked` != true)) && ((accountingMethodEntry.`mealGroupId` == null) || (accountingMethodEntry.`mealGroupId` == p.`vertices`[1].`mealGroupId`)))   /* simple expression */
88   CalculationNode       764   32913       0.00537                             - LET a = WARN(false, "")   /* simple expression */        
```

testsystem without `WARN(false, "")` and no results:

```
87   TraversalNode         764       0       0.01109                           - FOR v  /* vertex */, e  /* edge */, p  /* paths */ IN 1..1  /* min..maxPathDepth */ OUTBOUND #169 /* startnode */  OrderedDish
171  CalculationNode       764       0       0.00084                           - LET #173 = (accountingMethodEntry.`mealGroupId` in [ null, p.`vertices`[1].`mealGroupId` ])   /* simple expression */
```

Live System without `WARN(false, "")` but shows a result;

```
87   TraversalNode         766     437       0.35672                           - FOR v  /* vertex */, e  /* edge */, p  /* paths */ IN 1..1  /* min..maxPathDepth */ OUTBOUND #169 /* startnode */  OrderedDish
171  CalculationNode       766     437       0.00702                           - LET #173 = (accountingMethodEntry.`mealGroupId` in [ null, p.`vertices`[1].`mealGroupId` ])   /* simple expression */

````

I'm not sure if this helps you...

**Comment by konsultaner** [comment]
@mchacki Hi :) Is there anything new on this issue?

**Comment by dothebart** [comment]
Hi, 
I'm sorry that the side communication to this ticket got lost, and for me it doesn't seem to make sense on its own. 

Hence atm I can only provide you with some more general Information how to track at resource usage on your machine.

In https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html we demonstrate whats happening once you reach resource limits like it can be caused by cache poisening. Documents that have to be re-fetched from disk are slower than the ones that come from the block cache. 
By configuring this value smaller or larger you can come to this point earlier in time.

If you want to investigate whats happening with [disk I/O shortage situations, you can use CGroups to "limit" the capabilities of your SUT](https://www.arangodb.com/2019/01/using-the-linux-kernel-and-cgroups-to-simulate-starvation/)

Such a general test to produce the load situation to reproduce something like this is demonstrated in this blog series: https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/ along with what can be measured with the aid of [collecd](https://github.com/collectd/collectd/).

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available now.

**Comment by konsultaner** [comment]
Hi @dothebart 

for all side info you may ask @mchacki. He debugged the issue on our server and found out that under very rare circumstances the indexer took the wrong values. The `WARN(false, "")` changed the indexers choice and made it work. This issue may persist even ini 3.7.

**Comment by dothebart** [comment]
He's a busy man and does lots of stuff. 
Please re-validate whether this has been fixed in 3.7 - some fixes have been done to the indexing code.

**Comment by konsultaner** [comment]
@dothebart Since this issue occurs very rarly in production, I can not just update our production system to 3.7. I will try to test it against some data. I'm pretty sure that this issue persists because @mchacki said that it is not trivial to fix. I'm pretty sure he knows exactly where the issue is located at. He seemed confident that its fixable.

**Comment by konsultaner** [comment]
I ended up rewriting that query part. since @mchacki is too busy to fix it and I cannot write a reproducer I may just close the issue?

**Comment by dothebart** [comment]
ok. If you have a reliable way to reproduce this, don't hesitate to re-open. Sorry this got lost in communication.
