### ISSUE TITLE
ArangoSearch AQL query errors with " 'too many collections/shards' (while optimizing plan)"

### ISSUE THREAD

**Issue by oliverlockwood** [arangodb/arangodb#10787]
## My Environment

* __ArangoDB Version__:        3.4.7
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Docker
* __Configuration__:               3 nodes
* __Infrastructure__:               AWS
* __Operating System__:        Alpine
* __Total RAM in your machine__:        Varies
* __Disks in use__:        Varies
* __Used Package__:              Debian

## Component, Query & Data

__Affected feature__:
ArangoSearch

__AQL query (if applicable)__:
Slightly redacted in the objectType range for simplicity, but otherwise identical.
```
FOR object IN view_our_objects SEARCH object.objectType.name IN [ 'type1', 'type2', 'type3'  ] AND object.objectId == 266394
FOR data_view_all_metadata IN view_all_metadata SEARCH data_view_all_metadata.objectId == object.objectId AND data_view_all_metadata['type'] == 'timeline'
SORT object.objectId DESC, data_view_all_metadata.timestampIn ASC
LIMIT 0, 25
RETURN { 'object' : object, 'annotationMetadata' : data_view_all_metadata }
```

__AQL explain (if applicable)__:
```
Execution plan:
 Id   NodeType            Site  Est.   Comment
  1   SingletonNode       DBS      1   * ROOT
  2   EnumerateViewNode   DBS      1     - FOR object IN view_flex_objects SEARCH object.objectType.name IN [ 'type1', 'type2', 'type3'  ] AND object.objectId == 266394   /* view query */
  4   CalculationNode     DBS      1       - LET #2 = object.`objectId`   /* attribute expression */
 16   RemoteNode          COOR     1       - REMOTE
 17   GatherNode          COOR     1       - GATHER 
 10   ScatterNode         COOR     1       - SCATTER
 11   RemoteNode          DBS      1       - REMOTE
  3   EnumerateViewNode   DBS      1       - FOR data_view_all_metadata IN view_all_metadata SEARCH ((data_view_all_metadata.`objectId` == object.`objectId`) && (data_view_all_metadata.`type` == "timeline"))   /* view query */
  5   CalculationNode     DBS      1         - LET #4 = data_view_all_metadata.`timestampIn`   /* attribute expression */
  8   CalculationNode     DBS      1         - LET #6 = { "object" : object, "annotationMetadata" : data_view_all_metadata }   /* simple expression */
  6   SortNode            DBS      1         - SORT #2 DESC, #4 ASC
 12   RemoteNode          COOR     1         - REMOTE
 13   GatherNode          COOR     1         - GATHER #2 DESC, #4 ASC  /* sort mode: heap */
  7   LimitNode           COOR     1         - LIMIT 0, 25
  9   ReturnNode          COOR     1         - RETURN #6

 

Indexes used:
 none

 

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-up-2
  3   handle-arangosearch-views
  4   move-calculations-down
  5   scatter-arangosearch-view-in-cluster
  6   distribute-filtercalc-to-cluster
  7   distribute-sort-to-cluster
  8   remove-unnecessary-remote-scatter
```

__Dataset__:
The `view_all_metadata` view is unique in our setup in that aggregates across multiple metadata collections.  In this environment there are an unusually large number of such collections (currently 435), each with 3 shards.

__Size of your Dataset on disk__:
Not huge - this is a PoC / demo environment rather than one with vast quantities of data

__Replication Factor & Number of Shards (Cluster only)__:
Replication factor 2, 3 shards per collection.

## Steps to reproduce

1. Run the query

__Problem__:
The Arango Java driver throws an exception with the following stacktrace:
```
com.arangodb.ArangoDBException: Response: 500, Error: 1590 - AQL: error, cluster node: 'PRMR-b353e1c0-8768-42bb-a317-385170dee6be', endpoint: 'tcp://<REDACTED>:8529', error: 'too many collections/shards' (while optimizing plan)
    at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53)
    at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:149)
    at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:128)
    at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42)
    at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:132)
    at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
    at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:79)
    at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:59)
    at com.arangodb.internal.ArangoDatabaseImpl.query(ArangoDatabaseImpl.java:198)
```

__Expected result__:
The query returns as normal.

__Hypothesis__:
My strong suspicion is that we've hit some limit (for which I can't find any documentation) on the maximum number of collections or collection shards that can be targeted by an ArangoSearch query (or possibly any AQL query, I don't know).

As a starting point I'd love to understand what this limit is; then we can explore how to deal with it through configuration changes, ArangoDB server code changes, a modification to our usage of Arango, or some combination of the three.

Many thanks.

**Comment by jsteemann** [comment]
AQL has built-in limits for the number of collections/shards that can be used in a query.
IIRC, the limit currently (since 3.4.0) is 2048 collections in a single-server setup, and 2048 shards in a cluster. 
So the view alone will account for 435 * 3 = 1305 shards. 
I am not sure how many shards the `view_flex_objects` collection has, but if it has lots of shards as well, the query may hit the 2048 shards limit.
If you can somehow consolidate the collections, or reduce their shard number, this should be the easiest way forward.

**Comment by oliverlockwood** [comment]
Thanks for the fast response @jsteemann.

Two follow-up questions:
1. For my understanding, is there any intention to change this limit, or make it configurable in some way?  Or is there at least somewhere I can see this value in code or documentation? (I've searched but to no avail, hence raising this ticket in the first place).
2. `view_flex_objects` is a view over a single backing collection, which again contains just 3 shards. So additively I can't see it exceeding the limit.  However since we're doing two `FOR... SEARCH...` operations (effectively a JOIN between the views) I wonder - could the effect be multiplicative instead, i.e. does that then leave us with 1305 * 3 shards and exceed the limit that way?

**Comment by jsteemann** [comment]
The 2048 collections limit is hard-coded and cannot be changed by configuration or at runtime.
The current limit value of 2048 is in place since ArangoDB 3.4.0. The limit has been 256 before, but the old limit value should not apply here at all.

The limit is mentioned in the documentation here:
https://www.arangodb.com/docs/3.5/data-modeling-operational-factors.html#number-of-databases-and-collections
In the cluster it is a limit for the number of shards.

I tried reproducing the issue with 500 collections, each with 3 shards and a replication factor of 2.

I was able to run the above query successfully, though I didn't insert any data into the underlying collections. Both explain and the actual query worked fine.

This also matches my expectation, as 500 x 3 is less than 2048. Even though the query contains a join, the number of shards should not be multiplicative here. 
I found that on the coordinator what is counted is the number of distinct collections used in all the views, the views themselves plus a cluster-wide identifier per distinct underlying collection. So in case of 2 views with 438 distinct collections, it should end up with 2 + (438 x 2), which is well below the 2048 limit value.
On each database server, the number of shards (hosted by that particular server) should be taken into account, which can be at most 438 x 3. Still below the limit value.

I verified that only a single place in the code can throw this particular error, so I am wondering if the number of underlying collections or the view definitions have changed, and the query actually uses more shards than expected.
A further explanation for the error being raised is that for edge collections of a smart graph, there are actually multiple physical shards used per logical shard. In this case the number of collections/shards that are user-visible is actually lower than the number of collections/shards that are used internally.
But this only applies if you are using smart graphs in the Enterprise edition. Can you comment on whether you are using that?

**Comment by oliverlockwood** [comment]
We are not using the Enterprise edition.  However, in terms of the calculations, I've now identified where my calculations were being confused - while we had 435 *active* things backed by 1 collection each, we also had enough *inactive* things in this environment to bring the total number of collections included in `view_all_metadata` to 849. (I should have looked at this source of truth earlier - my mistake).

```
849 * 3 = 2547
2547 > 2048
```

I now fully understand how we're hitting the shard limit.  Thank you for your help with this.

Regarding the documentation, I'd like to suggest an update to make the **shard** limit clear; the document you linked to only says
>You cannot use more than 2048 **collections** per AQL query

which as discussed is not the issue here.

**Comment by OmarAyo** [comment]
Hi @oliverlockwood 

Good to know that is now sorted out.

@Simran-B can you please make sure that this is documented in a better way in our Documentation ?

Best,

**Comment by oliverlockwood** [comment]
Thanks @OmarAyo.

I guess one other thing to consider would be to improve the error message - so it says something like "too many collections/shards [2547 > 2048] (while optimizing plan)" instead - so people seeing this can immediately see *what* the limit is and how far over they are, without having to revert to the documentation.

**Comment by Simran-B** [comment]
Documentation PR: https://github.com/arangodb/docs/pull/289

**Comment by oliverlockwood** [comment]
I'm happy with the documentation update.  Closing this ticket accordingly.
