### ISSUE TITLE
AQL graph traversal: FILTER p.edge[0].field == "str" is false but included in result (for any "edges" prefix)

### ISSUE THREAD

**Issue by adrpar** [arangodb/arangodb#10829]
## My Environment

* __ArangoDB Version__:        3.6.0
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Kubernetes
* __Configuration__:               default
* __Infrastructure__:               AWS
* __Operating System__:        default as given by kube-arangodb
* __Total RAM in your machine__:        4GB
* __Disks in use__:        
* __Used Package__:              Docker: arangodb/arangodb-preview:3.6.0

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
WITH dog, address, location
FOR person in person
    FOR v,e,p in 1..1 OUTBOUND
        person links
        FILTER (p.edge[0].field == "dogs" and p.vertices[1].age > 0)
            OR p.edge[0].field == "home"
        return v
```

__AQL explain (if applicable)__:
```
Query String (228 chars, cacheable: true):
 WITH dog, address, location
 FOR person in person
     FOR v,e,p in 1..1 OUTBOUND
         person links
         FILTER (p.edge[0].field == "dogs" and p.vertices[1].age > 0)
             OR p.edge[0].field == "home"
         return v
 

Execution plan:
 Id   NodeType                  Site  Est.   Comment
  1   SingletonNode             DBS      1   * ROOT
  2   EnumerateCollectionNode   DBS     10     - FOR person IN person   /* full collection scan, 1 shard(s) */
  9   RemoteNode                COOR    10       - REMOTE
 10   GatherNode                COOR    10       - GATHER 
  3   TraversalNode             COOR     3       - FOR v  /* vertex */, p  /* paths */ IN 1..1  /* min..maxPathDepth */ OUTBOUND person /* startnode */  links
  4   CalculationNode           COOR     3         - LET #6 = (((p.`edge`[0].`field` == "dogs") && (p.`vertices`[1].`age` > 0)) || (p.`edge`[0].`field` == "home"))   /* simple expression */
  5   FilterNode                COOR     3         - FILTER #6
  6   ReturnNode                COOR     3         - RETURN v

Indexes used:
 By   Name   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  3   edge   edge   links        false    false        26.67 %   [ `_from` ]   base OUTBOUND

Traversals on graphs:
 Id  Depth  Vertex collections  Edge collections  Options                                  Filter / Prune Conditions
 3   1..1                       links             uniqueVertices: none, uniqueEdges: path                           

Optimization rules applied:
 Id   RuleName
  1   optimize-traversals
  2   scatter-in-cluster
  3   remove-unnecessary-remote-scatter
```

__Dataset__:
Small test dataset (couple of 10 entries for dog, address, person, and location) - can be shared if needed.

__Size of your Dataset on disk__:

## Steps to reproduce

1. run query

__Problem__:

Running the above query on our sample data set, returns an empty list. It appears, that having a FILTER within a graph traversal containing AND and OR constraints, returns an empty list.

If we run the following query of just having the first constraint
```
WITH dog, address, location
FOR person in person
    FOR v,e,p in 1..1 OUTBOUND
        person links
        FILTER (p.edge[0].field == "dogs" and p.vertices[1].age > 0)
        return v
```
a result set of 15 elements is returned (the results can be provided if needed).

If we separately run the following query of the second constraint
```
WITH dog, address, location
FOR person in person
    FOR v,e,p in 1..1 OUTBOUND
        person links
        FILTER p.edge[0].field == "home"
        return v
```
a result set of 7 elements is returned (the results can be provided if needed).

Running the full query
```
WITH dog, address, location
FOR person in person
    FOR v,e,p in 1..1 OUTBOUND
        person links
        FILTER (p.edge[0].field == "dogs" and p.vertices[1].age > 0)
            OR p.edge[0].field == "home"
        return v
```
however, should return a union of the two contstraints, however only
```
[]
```
is returned.

Replacing the AND operator with an OR however returns results:
```
WITH dog, address, location
FOR person in person
    FOR v,e,p in 1..1 OUTBOUND
        person links
        FILTER (p.edge[0].field == "dogs" or p.vertices[1].age > 0)
            OR p.edge[0].field == "home"
        return v
```
(NOTE: This does not yield the desired result of the initial query but much more, due to `age` being present in persons and not only dogs)

__Expected result__:

A union of the two constraints in between the OR statement (i.e. 15 records + 7 records = 22 records)

I am happy to provide any output, dataset or the Debug Package if needed.

**Comment by Simran-B** [comment]
You seem to have a cluster deployment, but I see similar behavior in 3.4 and single server.

First off, there is a mistake in your query:
` p.edge[0].field` should be
`p.edges[0].field`

Otherwise it will always be false, because there is no `edge` attribute, hence `p.edge`, `p.edge[0]` and `p.edge[0].field` produce `null` and the expression thus `false`.

With this typo corrected, I do get a result:

```js
//WITH dog, address, location
FOR person in person
    FOR v,e,p in 1..1 OUTBOUND
        person links
        FILTER (p.edges[0].field == "dogs" and p.vertices[1].age > 0)
            OR p.edges[0].field == "home"
        return v
```

However, there seems to be a bug.

**person** (document collection)

```json
[{"_key":"287057244","name":"Gerald","age":18},
{"_key":"287056982","name":"Chris","age":34},
{"_key":"287056986","name":"Minerva","age":54},
{"_key":"287056980","name":"George","age":53},
{"_key":"287056984","name":"Ella","age":65},
{"_key":"287056990","name":"July","age":42},
{"_key":"287056976","name":"Peter","age":5},
{"_key":"287056988","name":"Kay","age":4}]
```

**links** (edge collection)

```json
[{"_key":"287057504","_from":"person/287056980","_to":"person/287056988","field":"dogs"},
{"_key":"287057440","_from":"person/287057244","_to":"person/287056984","field":"home"},
{"_key":"287057500","_from":"person/287056986","_to":"person/287056976","field":"dogs"},
{"_key":"287057444","_from":"person/287056982","_to":"person/287056990","field":"home"}]
```

```js
FOR person IN person
    FOR v, e, p IN 1..1 OUTBOUND
        person links
        FILTER p.edge[0].field == "dogs"
        RETURN {
            field: p.edge[0].field,
            cond: p.edge[0].field == "dogs"
        }
```

```js
Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      8     - FOR person IN person   /* full collection scan */
  3   TraversalNode                1       - FOR v  /* vertex */, p  /* paths */ IN 1..1  /* min..maxPathDepth */ OUTBOUND person /* startnode */  links
  6   CalculationNode              1         - LET #8 = { "field" : p.`edge`[0].`field`, "cond" : (p.`edge`[0].`field` == "dogs") }   /* simple expression */
  7   ReturnNode                   1         - RETURN #8

Indexes used:
 By   Name   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  3   edge   edge   links        false    false       100.00 %   [ `_from` ]   base OUTBOUND
  3   edge   edge   links        false    false       100.00 %   [ `_from` ]   level 0 OUTBOUND

Traversals on graphs:
 Id  Depth  Vertex collections  Edge collections  Options                                  Filter / Prune Conditions             
 3   1..1                       links             uniqueVertices: none, uniqueEdges: path  FILTER (p.`edge`[0].`field` == "dogs")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   optimize-traversals
  6   remove-filter-covered-by-traversal
  7   remove-unnecessary-calculations-2
```

```json
[
  { "field": null, "cond": false },
  { "field": null, "cond": false }
]
```

The wrong field name produces a `null` value, the condition evaluates to `false`, but it does not get filtered out. The following FILTER operations produce an incorrect result (non-empty result set, list non-exhaustive):

- `FILTER p.edge[0].field == "dogs"`
- `FILTER p.edg[0].field == "dogs"`
- `FILTER p.ed[0].field == "dogs"`
- `FILTER p.e[0].field == "dogs"`
- `FILTER p["edge"][0].field == "dogs"`
- `FILTER p.edge[0].field != null`

The following on the other hand do not (empty array as expected):

- `FILTER NOOPT(p.edge[0].field == "dogs")`
- `FILTER p.pledge[0].field == "dogs"` (or any attribute name which isn't a prefix of "edge")
- `FILTER p.edge[0] == "dogs"`
- `FILTER p.edge == "dogs"`
- `FILTER null == "dogs"`
- `FILTER false`
- `LET x = {} FILTER x.missing == "dogs"`

For the following it depends on whether `temp` is used again (e.g. `RETURN [v, temp]`). If it is, then the result is correct, otherwise not:

```
LET temp = p.edge[0]
FILTER temp.field == "dogs"
```

It seems to have something to do with the name of the attribute and/or the sub-field access… At least 3.4.7 and 3.6.0 are affected.

**Comment by adrpar** [comment]
Thanks for looking into this and sorry for reporting an erroneous query. If I understand correctly, a fix of the related bug would have caught the error. 

Maybe additionally there could be a hint, that the field name is wrong in the case of using the path object.

**Comment by adrpar** [comment]
Thanks for looking into this and sorry for reporting an erroneous query. If I understand correctly, a fix of the related bug would have caught the error. 

Maybe additionally there could be a hint, that the field name is wrong in the case of using the path object.

**Comment by Simran-B** [comment]
Don't worry, we are happy that your report uncovered subtle bug!

With the bug fix
- `FILTER (p.edge[0].field == "dogs" AND p.vertices[1].age > 0)` always returns nothing
- `FILTER (p.edges[0].field == "dogs" AND p.vertices[1].age > 0)` returns matching records
- `FILTER p.edge[0].field == "home"` always returns nothing
- `FILTER p.edges[0].field == "home"` returns matching records
- `FILTER (p.edge[0].field == "dogs" AND p.vertices[1].age > 0) OR p.edge[0].field == "home"` always returns nothing (null or null == false)
- `FILTER (p.edges[0].field == "dogs" AND p.vertices[1].age > 0) OR p.edges[0].field == "home"` returns records matching the conditions on either side of the OR
- `FILTER (p.edge[0].field == "dogs" OR p.vertices[1].age > 0) OR p.edge[0].field == "home"` returns records where `p.vertices[1].age > 0`
- `FILTER (p.edges[0].field == "dogs" OR p.vertices[1].age > 0) OR p.edges[0].field == "home"` returns all records which match any of the three conditions

So the results would have been different, but might not have pointed you to the typo. The system can't really warn you about this, as it is fairly normal in a schema-less database that some objects don't have certain attributes. Instead, any attempt to access non-existing members returns  a `null` value. You could had looked at the actual values, like `RETURN p.edge[0].field`, then `RETURN p.edge[0]` and `p.edge`, at which point it would become clear that something is wrong because they all are `null`.
