### ISSUE TITLE
the same query works for find by example but not update by example

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#10866]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Nothing special
* __Infrastructure__:               My laptop
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        10Gb in VM, 32GB total
* __Disks in use__:        SSD
* __Used Package__:             tar

## Component, Query & Data

__Affected feature__:
http api, by-example and update-by-example

__AQL query (if applicable)__:
n/a

__AQL explain (if applicable)__:
n/a

__Dataset__:
see below
__Size of your Dataset on disk__:
tiny

__Replication Factor & Number of Shards (Cluster only)__:
n/a

## Steps to reproduce

```
$ python
Python 3.7.3 (default, Apr  3 2019, 19:16:38) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arango
>>> arango.version.__version__
'5.0.0'
>>> a = arango.ArangoClient(hosts='http://localhost:36113')
>>> db = a.db('test_sample_service', verify=True)
>>> c = db.collection('samples')

>>> list(c.all())
[{'_key': '12345678-90ab-cdef-1234-567890abcdef',
  '_id': 'samples/12345678-90ab-cdef-1234-567890abcdef',
  '_rev': '_Z393f0S---',
  'id': '12345678-90ab-cdef-1234-567890abcdef',
  'vers': ['1ff53564-d801-4e5e-bcaa-f9438ddecb65'],
  'acls': {'owner': 'user', 'admin': [], 'write': [], 'read': []}}]

>>> list(c.find({'_key': '12345678-90ab-cdef-1234-567890abcdef', 'acls.owner': 'user'}))
[{'_key': '12345678-90ab-cdef-1234-567890abcdef',
  '_id': 'samples/12345678-90ab-cdef-1234-567890abcdef',
  '_rev': '_Z393f0S---',
  'id': '12345678-90ab-cdef-1234-567890abcdef',
  'vers': ['1ff53564-d801-4e5e-bcaa-f9438ddecb65'],
  'acls': {'owner': 'user', 'admin': [], 'write': [], 'read': []}}]

>>> c.update_match({'_key': '12345678-90ab-cdef-1234-567890abcdef', 'acls.owner': 'user'},
                                  {'acls': {'read': ['foo', 'bar']}})
0

>>> list(c.all())
[{'_key': '12345678-90ab-cdef-1234-567890abcdef',
  '_id': 'samples/12345678-90ab-cdef-1234-567890abcdef',
  '_rev': '_Z393f0S---',
  'id': '12345678-90ab-cdef-1234-567890abcdef',
  'vers': ['1ff53564-d801-4e5e-bcaa-f9438ddecb65'],
  'acls': {'owner': 'user', 'admin': [], 'write': [], 'read': []}}]
```

__Problem__:

The query above works fine for `c.find()` and returns a document as expected, but for `c.update_match()`, using an identical query, it does not match the document.

`c.find()` calls [by-example](https://github.com/joowani/python-arango/blob/master/arango/collection.py#L703-L730) under the hood.

`c.update_match()` calls [update-by-example](https://github.com/joowani/python-arango/blob/master/arango/collection.py#L1738-L1781) under the hood.

__Expected result__:

The update call matches and updates the document.

**Comment by Simran-B** [comment]
While the [HTTP API documentation](https://www.arangodb.com/docs/stable/http/simple-query.html) doesn't go into details about example documents, there is some information in the JS API description:

[Query by Example](https://www.arangodb.com/docs/stable/data-modeling-documents-document-methods.html#query-by-example)
> An attribute name of the form _a.b_ is interpreted as attribute path, not as attribute …

The [Update by Example](https://www.arangodb.com/docs/stable/data-modeling-documents-document-methods.html#update-by-example) documentation does not contain this sentence, but also does not really describe how the example parameter works:
> each document matching the example will be updated with the values from newValue

I'm pretty sure that only byExample() / firstExample() support interpreting dots as attribute path description instead of as literal attribute name, i.e. updateByExample() will try to find a document with `{"acls.owner":"user"}` (literally `"acls.owner"` as attribute name), which does not match the document.

Both methods, byExample() and updateByExample(), support examples with nested attributes:
`{ "acls": { "owner": "user", "admin": [], "write": [], "read": [] } }` matches the document (all nested attributes present and with the right values). `{ "acls": { "owner": "user" } }` does not match, because there is no document with just an `"owner"` sub-attribute. Only byExample() interprets `{"acls.owner":"user"}` as `{ "acls": { "owner": "user", <other properties allowed> } }`.

```js
db._create("samples")

db.samples.save(
  {
    "_key" : "12345678-90ab-cdef-1234-567890abcdef",
    "vers" : [
      "1ff53564-d801-4e5e-bcaa-f9438ddecb65"
    ],
    "acls" : {
      "owner" : "user",
      "admin" : [ ],
      "write" : [ ],
      "read" : [ ]
    }
  }
)

db.samples.byExample({
  _key: "12345678-90ab-cdef-1234-567890abcdef",
  "acls.owner": "user"
}).toArray() // finds the document

db.samples.byExample({
  _key: "12345678-90ab-cdef-1234-567890abcdef",
  acls: { owner: "user" }
}).toArray() // does NOT find the document

db.samples.byExample({
  _key: "12345678-90ab-cdef-1234-567890abcdef",
  acls: { owner: "user", admin: [], read: [], write: [] }
}).toArray() // finds the document

db.samples.updateByExample(
  {_key: "12345678-90ab-cdef-1234-567890abcdef", "acls.owner": "user"},
  { acls: { read: ["foo", "bar"] } }
) // does NOT find the document, no update

db.samples.updateByExample(
  {_key: "12345678-90ab-cdef-1234-567890abcdef", acls:
    { owner: "user" }
  },
  { acls: { read: ["foo", "bar"] } }
) // does NOT find the document, no update

db.samples.updateByExample(
  {_key: "12345678-90ab-cdef-1234-567890abcdef", acls:
    { owner: "user", admin: [], read: [], write: [] }
  },
  { acls: { read: ["foo", "bar"] } }
) // finds & updates the document!
```

I admin that the documentation should clearer state this, but the Simple Queries API was deprecated a long time ago on the other hand (3.4.0), which means it will be removed in a future release. We recommend to use AQL instead, although Simple Queries are actually translated to AQL in the current implementation, to benefit from performance optimizations and to reduce the maintenance costs.

In your example there is not even a need to specify any attributes but the _key, which uniquely identifies a document. You could just do

```
c.update_match(
  {'_key': '12345678-90ab-cdef-1234-567890abcdef'},
  {'acls': {'read': ['foo', 'bar']}}
)
```

or `UPDATE @key WITH @doc IN @@coll` in AQL with the following bind parameters:

```
{
  "key": "12345678-90ab-cdef-1234-567890abcdef",
  "doc": {"acls": {"read": ["foo", "bar"] } },
  "@coll": "samples"
}
```

To find a document without knowing the _key in AQL, you could do:

```
FOR doc IN samples
  FILTER doc.acls.owner == "user" // optionally additional conditions
  LIMIT 1
  UPDATE doc WITH { acls: { read: ["foo", "bar"] } } IN samples
```

**Comment by MrCreosote** [comment]
> In your example there is not even a need to specify any attributes but the _key, which uniquely 
identifies a document.

In practice I only want to update the document if the owner is `user`, hence the additional field in the query.

In any case, it sounds like the answer is 'use AQL'.

Thanks!

**Comment by Simran-B** [comment]
AQL is the way to go IMO. It will work independent of the driver you use and it's future-proof unlike the Simple Queries API. There is magic dot behavior™ in some other places, but I would like to see it removed where it is hard to discover/understand, and improved/unified elsewhere (like in index definitions; there is currently no way to escape a dot, whereas it is possible in data masking definitions).

**Comment by dothebart** [comment]
Closing as solved. 
Please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
