### ISSUE TITLE
Duplicate record issue

### ISSUE THREAD

**Issue by exosiscrypto** [arangodb/arangodb#10878]
## My Environment

* __ArangoDB Version__:        3.6.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Operating System__:        Ubuntu 18.04

__Problem__:
We did replication from 3.5.3

we got duplicate outputs on query from 3.6.0

Front end web interface collection has only unique records but in the query output we getting duplicate records with same doc _key value 2 times

**Comment by maxkernbach** [comment]
Hi @exosiscrypto,

A bit more information is required in order to investigate this issue:

- What exactly do mean by "We did replication from 3.5.3"? Is my understanding correct that the affected query worked as expected in 3.5.3 and produces duplicate records in 3.6.0?
- Could you please provide the query debug package (optimally including an obfuscated example), which is available through the "Create Debug Package" button in the UI "QUERIES" view?

**Comment by exosiscrypto** [comment]
we doing updates in 3.5.3 and replicated that db to 3.6.0

Initial all looked fine, after 2 days of update sudden 1 record came 2  times in the query output of 3.6.0 db but 3.5.3 is fine not getting any issue like that

I rechecked the entries in collection but didn't see any duplicated records

Also the doc _key in the query output was same like
_key 12345 
_key 12345

How primary _key will return 2 times in the query ?

Then we deleted entire db in 3.6.0 and again started replication for testing

Same after 2 to 3 day we get 2 records like this issue having duplicate doc _key

But this issue comes only in query output not in the web view of arangodb

It was simple query "for u in collection return u"

Actually we deleted the db for testing in case we got it again will share picture 

All the time we updating records in 3.5.3 and keeping 3.6.0 as slave (issue came in 3.6.0)

**Comment by maxkernbach** [comment]
Hi @exosiscrypto,

Please note that a master slave setup has the following [limitation](https://www.arangodb.com/docs/stable/architecture-deployment-modes-master-slave-limitations.html):

> replication is only supported between the two ArangoDB servers running the same ArangoDB version. It is currently not possible to replicate between different ArangoDB versions

Since replicating between 3.5.3 to 3.6.0 is not supported, unexpected errors might occur. However, we would be glad to investigate this issue in case you can also reproduce it when replicating between the same versions (e.g. 3.6.0 -> 3.6.0).

Why did you initially replicate between different versions? Would it be possible to upgrade your master deployment to 3.6.0 and check if the issue persists?

**Comment by exosiscrypto** [comment]
ok thanks for the update i am not aware of this info.
I thought we can use any version.
