### ISSUE TITLE
Unable to use core NodeJS modules.

### ISSUE THREAD

**Issue by rasjonell** [arangodb/arangodb#10972]
## My Environment

* __ArangoDB Version__: 3.5.1       
* __Storage Engine__: RocksDB             
* __Deployment Mode__: Single Server       
* __Deployment Strategy__: Manual Start in Docker   
* __Infrastructure__: AWS               
* __Operating System__: MacOS Mojave 10.14.5 (18F132)         
* __Total RAM in your machine__: 16GB        
* __Disks in use__:  500GB SSD       

## Component, Query & Data

__Affected feature__: Foxx service

## Steps to reproduce

1. initiate a foxx service.
2. require core `os` module.
3. try running a function on that module (i.e `os.hostname()`)

__Problem__:
Requiring the `os` module returns an empty object.

__Expected result__:
Requiring the `os` module returns the actual module.

**Comment by Simran-B** [comment]
Hi @rasjonell,
ArangoDB embeds V8 and we implemented some modules known from Node.js, but `os` is not one of them. Compatibility with Node.js is not our goal and there are vast differences between both JavaScript environments, e.g. ArangoDB being multi-threaded and synchronous vs. Node.js being single-threaded at the core and making heavy use of async execution.

Please see https://www.arangodb.com/docs/stable/appendix-java-script-modules.html for the available modules.

**Comment by rasjonell** [comment]
Thank you for the response. I got the error when I tried to use a third-party library that used the `os` module, so I ended up not using it and writing the logic with the available modules. Will close the issue.

Is there a recommended way to handle such scenarios when you need to use code from the 'outside-world' inside Foxx Services?

**Comment by Simran-B** [comment]
@rasjonell There is no silver bullet. One should generally avoid cramming too much functionality into Foxx micro-services and not perform long-running operations, because of the likelihood of external resources affecting the database performance. If you want to do requests to external services which are known to take rather long, then it's probably better to use Node.js. When the data is available, then you can write it into ArangoDB using arangojs.

What does that 3rd party library use the `os` module for? Certain things might be possible to polyfill while other functionality should never be exposed inside of a database system (security and performance reasons).

**Comment by rasjonell** [comment]
The library I was using was for connecting the service to an external logging service, I ended up directly calling the service using the bundled `request` module when all the transactions ended. I used it in a queued job(i.e. call the logging service when the job fails or succeeds), not sure if it is a good practice, though.

**Comment by dothebart** [comment]
Hi, 
You probably want to rather use the regular arangodb log (or RSyslog) and use that to distribute log messages.

**Comment by rasjonell** [comment]
Will look into that. Thank you!
