### ISSUE TITLE
[DOCS] missing information in server options, i.e. `v8-max-heap`

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#11040]
In my arangod.conf I needed to add the following option to fix a V8 out of heap mem error:

```ini
[javascript]
v8-max-heap = 6144
```

according to the [server options doc](https://www.arangodb.com/docs/stable/programs-arangod-javascript.html) this is not possible, but it did work. I found the options in [the arangosh docs](https://www.arangodb.com/docs/stable/programs-arangosh-options.html#javascript).  Is this intentional?

**Comment by Simran-B** [comment]
It is listed here:
https://www.arangodb.com/docs/stable/programs-arangod-options.html#javascript

The detailed option descriptions are hand-written, so they don't necessarily contain all options. However, the goal should be to have a descriptions with example for each option.

I'm not quite happy with the separation of auto-generated options table and the manually written detail pages. I think it would be better to interleave both, but there are technical difficulties. The short descriptions as seen in the tables originate from the code and are dumped from the binaries, whereas the source files with the long descriptions reside in the docs repo. Linking both together would require a different organization, e.g. the long descriptions in a structured format so that they can be matched by option name. But then there is still the issue that some descriptions are really long and wouldn't fit in a table. Can't think of a good design just yet.

**Comment by konsultaner** [comment]
ok, I did not check the root. I only checked the hand written descriptions. Should I close the issue?

**Comment by Simran-B** [comment]
@konsultaner It might not be a bug, but it is certainly an inconvenience. I'm going to close this issue, but I created one in the docs repo to deal with this at some point: https://github.com/arangodb/docs/issues/324
