### ISSUE TITLE
ArangoDB Single Instance as a Docker Container Randomly Crashing

### ISSUE THREAD

**Issue by nicolaselkhoury** [arangodb/arangodb#11044]
## My Environment

* __ArangoDB Version__:  3.5.2       
* __Storage Engine__: RocksDB            
* __Deployment Mode__:  Single Server     
* __Deployment Strategy__: Manual Start in Docker  
* __Configuration__:               
* __Infrastructure__: AWS t3a.small Machine              
* __Operating System__: Ubuntu 16.04       
* __Total RAM in your machine__: 2GB. However, the container's limit is 1.2GB       
* __Disks in use__: SSD       
* __Used Package__:  Docker            

## Component, Query & Data

__Affected feature__: Docker Container crashes and restarts at random intervals

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__: A few megabytes. The database is used for testing purposes

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. On an AWS t3a.small machine, Docker version 19.03.5, build 633a0ea838, Run ArangoDB using the following docker command:

```
docker run -d --name test -v /mnt/test:/var/lib/arangodb3 --restart always --memory="1200m" --cpus="1.5" -p 8529:8529 --log-driver="awslogs" --log-opt awslogs-region="eu-west-1" --log-opt awslogs-group="/docker/test" -e ARANGO_RANDOM_ROOT_PASSWORD=1 -e ARANGO_STORAGE_ENGINE=rocksdb arangodb/arangodb:3.5.2 --log.level queries=warn --log.level performance=warn
```
2. The average number of concurrent connections does not exceed 10.
3. 

__Problem__:
The Docker container unexpectedly restarts at random intervals, and all the connected clients get disconnected. We are unable to find out why the container is restarting and what is causing it. The memory and CPU of the underlying machine are low, and do not have any alarming values. We would like help on what is going on, or at least how to debug further

EDIT:

After further investigation, we found that Docker container running Arango is reaching the memory allocated to it fully. The memory gets filled incrementally ever since the container starts running and it never goes down, until it is filled and the container restarts.

EDIT #2: 

I ran the container with the following command, but it still crashed and caused a socket hangup error on the clients:

```
docker run -d --name test -v /mnt/test:/var/lib/arangodb3 --restart always --memory="1200m" --cpus="1.5" -p 8529:8529 --log-driver="awslogs" --log-opt awslogs-region="eu-west-1" --log-opt awslogs-group="/docker/test" -e ARANGO_RANDOM_ROOT_PASSWORD=1 -e ARANGO_STORAGE_ENGINE=rocksdb arangodb/arangodb:3.5.2 --log.level queries=warn --log.level performance=warn --rocksdb.block-cache-size 256MiB --rocksdb.enforce-block-cache-size-limit true --rocksdb.total-write-buffer-size 256MiB --cache.size 256MiB
```

Why does the memory keeps increasing and does not go down, especially when it is not being used?
__Expected result__:

**Comment by Simran-B** [comment]
Hi @nicolaselkhoury,
can you provide any logs that can help us to understand the issue better?
Also note that 256MB for cache, write buffers etc. is not a lot. If statistics are enabled in the server, then it's not uncommon that memory usage increases over time. Please take a look here for some options to decreasing memory usage: https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html

**Comment by nicolaselkhoury** [comment]
Hi,

Thank you for answering me. Unfortunately, there exists no logs before Arango crashing. I monitored the container's memory consumption using the ATOP tool. While monitoring, I could see the memory consumed by the container incrementally increasing, until the container finally crashes and restarts, and then the memory decreases.

I understand that if statistics are enabled, then the memory usage will increase over time, but I would like to limit the memory consumption somehow and forbid Arango from continuously eating up memory. How can I do that? 

Moreover, why do these commands, which I use when starting the Arango process not work? 
```--rocksdb.block-cache-size 256MiB --rocksdb.enforce-block-cache-size-limit true --rocksdb.total-write-buffer-size 256MiB --cache.size 256MiB```

**Comment by Simran-B** [comment]
The StackOverflow answer is about a configuration file parsing issue (#5414) which was fixed in 3.3/3.4, so it should not matter here. But it could still be worth to check whether the options you specified are actually handed through correctly: https://www.arangodb.com/docs/stable/administration-configuration.html#fetch-current-configuration-options

You say the container RAM limit is 1.2GB. Block cache + write buffers + cache alone make up least 768MiB. But the server executable, data files etc. are also resident in memory, so it could well be that arangod honors the memory limiting options, but because of other things that are loaded into memory you might exceed the RAM limit very quickly. Keep in mind that intermediate and final query results require memory. You might want to set a memory limit for queries: `--query.memory-limit`

There are also other options which you are not using so far (see https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html), for example:

`--rocksdb.max-total-wal-size`
`--rocksdb.dynamic-level-bytes`

You may also try to disable statistics to see how that changes the observed memory usage.

Make sure `overcommit_memory` is **not** set to 2 in your environment, or the server may get OOM killed way before memory is actually running out.

**Comment by maxkernbach** [comment]
Hi @nicolaselkhoury,

Did you have a chance to read Simran's reply?
Was it helpful?

**Comment by maxkernbach** [comment]
Hi @nicolaselkhoury,

Since we have not heard back from you recently, I am closing this issue for now.
Feel free to reopen this ticket if needed.
