### ISSUE TITLE
Query: Matching an Array

### ISSUE THREAD

**Issue by Arun-KumarH** [arangodb/arangodb#11212]
## My Environment

* __ArangoDB Version__:        3.6

## Component, Query & Data

Inline filtering for array does not seem to be returning data as expected.

__AQL query (if applicable)__:
```
for j in users FILTER j.role_associations[* FILTER CURRENT.role == "admin" return CURRENT] return j
```

__Dataset__:
```
let users = [
  {
    name: "normalUser",
    role_associations: [
      {
        role: "user"
      },
      { 
        role: "test" 
      }
    ]
  },
  {
    name: "adminUser",
    role_associations: [
      {
        role: "admin"
      },
      { 
        role: "test"
      }
    ]
  }
];
```

__Problem__:
Will return both the users.

__Expected result__:
Should have returned only `adminUser`

**Comment by maxkernbach** [comment]
Hi @Arun-KumarH,

Your query:
```
FOR j IN users
  FILTER j.role_associations[* FILTER CURRENT.role == "admin" RETURN CURRENT]
  RETURN j
```
is returning both users as expected.

`j.role_associations[* FILTER CURRENT.role == "admin" RETURN CURRENT]` is evaluated to `[]` (empty array).

However, the next step `FILTER []` (FILTER condition on an empty array) returns `true`.

In order to make this inline filter approach work, you could change the query to:

```
FOR j IN users
  FILTER LENGTH(j.role_associations[* FILTER CURRENT.role == "admin" RETURN CURRENT]) > 0
  RETURN j
```

Another approach for the desired result would be:
```
FOR j IN users
  FILTER "admin" IN j.role_associations[*].role
  RETURN j
```

**Comment by Arun-KumarH** [comment]
Thanks for update.
