### ISSUE TITLE
Simplify AQL filtering functionality (was: SELECT COUNT(*) -like query in AQL?)

### ISSUE THREAD

**Issue by nlac** [arangodb/arangodb#1133]
Hi,
perhaps i missed something but i couldn't find any example for expressing the following simple query in AQL: how many users have an age > 20? So the result should be one number. I'm using the aardwark webapp's AQL editor.
Is it possible? I really tried to dig the documentation, sorry if i just was blind:)

**Comment by jsteemann** [comment]
Since 2.6 there exists the possibility to use an inline filter when working with the `[*]` operator like this:
```
RETURN LENGTH(users[* FILTER CURRENT.age > 20])
```
The inline filter can be used for the elements inside the `[*]` operator, and provides the current value in variable `CURRENT`. It also supports applying an optional a limit and a projection.

**Comment by nkanand4** [comment]
@jsteemann this suggested operation returns with a warning make me concerned if this is inefficient to use. Am I doing something wrong?
![screen shot 2017-09-10 at 8 19 40 am](https://user-images.githubusercontent.com/667996/30249376-12a76d1c-9601-11e7-8cbf-dbba2bb55ad5.png)

**Comment by jsteemann** [comment]
@nkanand4 : the two queries
```
RETURN LENGTH(customers[* FILTER CURRENT.contact.phone != null])
```
and
```
RETURN LENGTH(FOR doc IN customers
  FILTER doc.contact.phone != null
  RETURN 1)
```
should produce the same result.
However, I think the execution plans for both queries will be different. As of ArangoDB 3.2, the first query will materialize the entire collection at once, whereas the second query will perform a batch-wise scan through the collection. Thus the second query will be much more efficient (from the point of memory consumption) than the first query. 
Note that this may change over time with further optimizer improvements, so that the first query will also become as efficient as the second one.
