### ISSUE TITLE
FormatMiddleware doesn't "fix" url

### ISSUE THREAD

**Issue by stackmagic** [arangodb/arangodb#1142]
When I use the FormatMiddleware, it doesn't clean up the url as I would expect. Given:

    ctrl.get("/:id", function(req, res) {
        res.json({ 'id': req.params('id') });
    }

And I call /xxx.xml, then the id in the response is 'xxx.xml' instead of just 'xxx'.

    { 'id': 'xxx.xml' }

Additionally, the response is in json but it should be in at least an xml-ish return format. This may be related to 'res.json(...)' but I don't know how else I would send the return-value to the client.

The usecase for me would be to have Foxx serialize to json and xml, chooseable by the caller. Does Foxx have a default serializer for xml the same way as it already serializes objects to json? Am I doing something wrong when returning the result?

**Comment by jsteemann** [comment]
@stackmagic : I just stumpled upon this issue. I can confirm there is no serializer for XML present in ArangoDB. The preferred format will be JSON in ArangoDB, as it is natively supported by both the internals and JavaScript (which is used for scripting inside).

In order to achieve the desired result, your Foxx route would need to determine the "file extension" from the matched parameter (`:id`) and choose a result format based upon that value.
I think using JSON as the internal format will make most sense, and only transforming the result to XML or any other non-JSON format if actually required. 
To convert the JSON into XML, there is no pre-defined function in JavaScript. Rolling your own recursive function that converts JSON to XML is an option, and probably there are also available node_modules out there that can do this.

The final result can be sent to the client via the `res.send(body)` function. It requires `body` to be any UTF-8-encoded string or a Buffer object. If the result data is already present in a file, the file contents can be sent from Foxx via the the command `res.sendFile(filename);`.

In order for the client to pick up the data correctly, it might be necessary to set the `Content-Type` HTTP header as well via `res.set("Content-Type", contentType);`, or even the `Content-Disposition`: `res.set("Content-Disposition", "attachment; filename=\"" + filename+ "\"");`.

**Comment by jsteemann** [comment]
Dynamically creating different response formats based on the user request is definitely doable with a Foxx application, but this is probably application-specific. So my suggestion would be to let Foxx applications handle the different response formats on their own, for those applications that actually require it.

**Comment by jsteemann** [comment]
I suggest handling the output format logic inside the application.
