### ISSUE TITLE
Http document delete invalid entries returns IsSuccessStatusCode=true

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#11453]
* __ArangoDB Version__:         3.6.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    Manual Start
__Infrastructure__:                own
* __Operating System__:        Centos 7

When I send delete http single document ("_api/document/XXX/65833643"),  it returns 404 correctly.

When I'm send a list of invalid document entries to delete via http ("_api/document/XXX"). It returns 

status code 202
IsSuccessStatusCode  true
Arango-Error-Code 1202

It should be an error  too, no?

**Comment by dothebart** [comment]
You should see a list of documents and their stati in the reply. There is no Quorum - all failed - turn to error ;-)

**Comment by imtrobin** [comment]
Ok,. so I assume the other bulk API have same stance? The IsSuccessStatusCode is always true irregardless when the operation is successful or not.

**Comment by dothebart** [comment]
if i.e. auth is invalid that will show in a global error.

**Comment by imtrobin** [comment]
It's inconsistent with your single use API. e.g Delete Document will return 404 if document or key is not found. At least the IsSuccessStatusCode should be false.

**Comment by Simran-B** [comment]
Single and multi-document requests work differently. The HTTP standard had single operations in mind. If you want to delete a certain document but also verify that it's the same revision that you saw on client-side, then you can set an `If-Match` header with the document `_rev` value. This approach does not work for multiple documents in a meaningful and unambiguous way. Instead, we expect you to send a request body with an array of objects, each having a `_key` and `_rev` attribute, and the query parameter `?ignoreRevs=false` to enable the revision check.

The payload could potentially ask the server for the deletion of thousands of documents, which may take a while. The only way for the server to reply with 404 would be after all delete operations were attempted, which would massively delay the server reply. And it's ill-defined what the status code should be if some operations succeeded and others failed. Instead, the server can immediate reply with [202 Accepted as per the specification](https://tools.ietf.org/html/rfc7231#section-6.3.3) and continuously reply with the individual status codes or document meta data. For single document operations this isn't necessary, the server can wait with the reply until the operation was attempted without much delay and send the operation outcome as HTTP status as there is only a single status.

If you want to avoid the multi-document API because of the difference behavior then have a look at [Batch Requests](https://www.arangodb.com/docs/stable/http/batch-request.html). This will be less efficient however.
