### ISSUE TITLE
Changing root password is not working for the build arangodb3e-3.6.2-1.0.x86_64

### ISSUE THREAD

**Issue by gopalkalabe** [arangodb/arangodb#11462]
Hi ,

I am  trying to change root password using the below link:
https://www.arangodb.com/docs/3.6/security-change-root-password.html

It does not work for the build above mentioned  ( both incase of single and fail-over mode)

Best Regards
Gopal

**Comment by OmarAyo** [comment]
Hi @gopalkalabe,

We need some more information in order to understand your issue, kindly reply to the followings:

- which OS are you using ?
- how do you start your arangodb deployment (e.g. using the starter) ?
- which `arangod.conf` did you modify ? (please provide the path)
- please report here the output of: `ps aux | grep arangod`
- what is the output (please attach here) of `require("org/arangodb/users").update("root", "newpassword");`

Thanks

**Comment by Simran-B** [comment]
Hi @gopalkalabe,
we haven't heard from you in a while and have insufficient information to try to reproduce the problem. Feel free to re-open the ticket with more information.

**Comment by sliu2200899** [comment]
I have the same problem about it.

when I execute it in the arango web interface, it shows that 

Query: AQL: syntax error, unexpected identifier near 'require("org/arangodb/users").up...' at position 1:1 (while parsing)

**Comment by dothebart** [comment]
Hi, the statement is not an AQL-Query and is not intended to be run in the webinterface. 
You need to use it in `arangosh` interactive shell.
