### ISSUE TITLE
Replace/Extend HTTP Api with gRPC

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#11499]
Maybe something for 4.0

While developing our own C# driver I noticed all the tedious work of abstracting those HTTP calls would not be necessary for alot of languages if you just implemented a gRPC API like you did for Oasis.

While the HTTP calls are fine supporting VSTREAM with VPACK is not that easy (or well documented)

And it seems to me most of the things you are trying to accomblish with VSTREAM - gRPC provides out of the box

- HTTP 2.0 (yeah I know thats already in your pipline)
- Multiplexing
- Async Response Streaming
- "Server Side Events" (maybe we get something like MongoDB change streams in the future)

Now whats left is a VPACK serializer in more languages  (C# first preferably^^)

**Comment by agrothe** [comment]
Lack of good VelocyStream documentation and lack of a C# implementation has hindered me as well. It would be a huge boost if the .NET community could use something other than HTTP. +1000 for this.

**Comment by dothebart** [comment]
Arangodb itself is built around velocypack. VelocyStream is one of the 3 supported Transports as of 3.7:
- http 1.1
- velocystream
- http 2

A possible gRPC implementation frankensteined into ArangoDB would probably not reach the performance of HTTP2/JSon or even HTTP2/VPack.
Since the development effort of this will not be taken by the ArangoDB Team I will close this as "Won't fix"Thanks for the sugestion.

**Comment by duongphuhiep** [comment]
please correct me if I'm wrong

Most (or maybe all) the ArangoDB Drivers (C#, Java, Go..) are actually based on the [REST API](https://docs.arangodb.com/3.11/develop/http-api/) which means HTTP/JSON (**not HTTP2**).

@coronabytes is suggesting to replace this REST API  with a more performance alternative: HTTP2/gRPC.

In other words, the feature request is that **ArangoDB should expose a Proto interface (instead of exposing an OpenAPI/Swagger interface).**

As long as this feature request is fullfill then 

1. ArangoDB won't need to maintain all these Drivers (C#, Java; Go..) because their codes can be simply generated from the Proto interface.
2. These generated Drivers (HTTP2/grpc) should have more performance / memory efficient than the current Drivers (HTTP/JSON)

**Comment by dothebart** [comment]
However, translating vpack to Protobuf on the arangodb site will void any performance advantage you might get. 
Thats why I used the word "frankenstein".
