### ISSUE TITLE
AQL: can't use bind vars in some places

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#1155]
I've been exploring using bind vars in various places and ways and run across a few cases where I was hoping it would work but it does not:

    arangosh [test]> db._query('FOR @var IN nodes RETURN @var', {"var":"i"} ).toArray()
    JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,11: [ArangoError 1501: syntax error, unexpected bind parameter, expecting identifier near '@var IN nodes RETURN @var' at position 1:5 (while parsing)]
    !    throw new ArangoError(requestResult);
    !          ^

    arangosh [test]> db._query('FOR i IN nodes SORT i.name @order RETURN i', {order: "DESC"} ).toArray()
    JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,11: [ArangoError 1501: syntax error, unexpected bind parameter near '@order RETURN i' at position 1:28 (while parsing)]
    !    throw new ArangoError(requestResult);
    !          ^

    arangosh [test]> db._query('RETURN @expr', {key: "name", val: "Foo", expr: "(FOR i IN nodes FILTER i.@key == @val RETURN i)"} ).toArray()
    JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,11: [ArangoError 1552: bind parameter 'val' was not declared in the query (while parsing)]
    !    throw new ArangoError(requestResult);
    !          ^

I think it would be helpful to expand the ways bind variables can be used.

**Comment by jsteemann** [comment]
Bind parameters can now (as of today in 2.5/devel) be used as keys/attribute names in object literals.
That means your example query does now work:
```js
db._query('RETURN {@key: @value}', {key: "foo", value: "bar"}).toArray()
```
It is now also possible to use calculated attribute names using arbitrary expressions enclosed in `[` and `]`:
```
RETURN { [ CONCAT('foo', 'bar') ] : 'value' }
```

I've also come to conclusion regarding extra types of bind parameters, for example, a special bind parameter type to would allow specifying arbitrary query fragments or expressions.

When such special bind parameter would be found in the query during initial parsing, its actual value would need to be injected into the query string, so parsing could continue as if the bind parameter never existed. This is different from the current bind parameters, for which a value can be inserted later. The current bind parameter values are always JSON (null, boolean, number, string, array, object) and cannot change the meaning of the query. Not knowing the actual bind parameter values isn't a problem during parsing.

However, bind parameters that could change the meaning of a query would need to be fully known and injected instantly when encountered in the query string, otherwise parsing could not continue. This would make parsing more complex.
 
And it wouldn't be possible to continue with such a query (e.g. for explaining, prepared statements etc.) without knowing the contents of the bind parameters.

Additionally, if I understood correctly, these bind parameter types wouldn't be much safer than query string concenation on the client. The number of places at which arbitrary code could be injected into the query would be limited, but still only a single occurrence of such parameter can render a complete query unsafe:
```
// exec: "REMOVE doc IN collection"
FOR doc IN collection @exec

// cond: "true REMOVE doc IN collection //"
FOR doc IN collection FILTER @cond RETURN doc 
```

Therefore I think we should not add extra bind parameter types, at least none that aren't value-only parameters.

**Comment by jsteemann** [comment]
Bind variables are supported in most places now, even for non-value tokens `ASC` and `DESC` inside `SORT`. I think we shouldn't allow bind variables for anything more than this, because if bind variables could contain expressions and keyword tokens etc. they could change the meaning of a query completey. 

This is where application-based string concatenation is required, or, its safer alternative of using a query builder.
