### ISSUE TITLE
LET return an object

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#11572]
* __ArangoDB Version__:        3.6.2

Hi, this AQL returns ["12345"]

```
FOR doc IN TestCollection 
RETURN doc._key

```
But this AQL returns [["12345"]]

```
LET d = (FOR doc IN TestCollection 
              doc._key)
return d

```
Is that intended? I thought LET is just a variable

**Comment by lostpebble** [comment]
I'm getting the same behaviour. And it seems that if I try and do `d[0]` or `FIRST(d)` or `d[**]` at the end, it only returns the first item of the inner array, instead of spreading out the entire inner array as the returned rows as I would expect.

```
LET col = [{ a: 1 }, { a: 2 }, { a: 3 }, { a: 4}]

LET test = (FOR c IN col RETURN c)

RETURN test
// OR
RETURN test[**]
// OR
RETURN FLATTEN(test)
```

returns

```
[
  [
    {
      "a": 1
    },
    {
      "a": 2
    },
    {
      "a": 3
    },
    {
      "a": 4
    }
  ]
]
```

Hence, we don't get a regular list of docs as intended (and get no nice table display in the web view).

---
```
RETURN test[0]
// OR
RETURN FIRST(test)
```

returns

```
[
  {
    "a": 1
  }
]
```

Which can show in the web view, but its only the first row... so not what we were intending.

So these commands seem to actually not work as intended (as far as the end user might expect), because if we have an array that is 2-deep and we pull out the first element we expect to just get the full inner array back.

Is there any way for us to just get the regular flat list array?

---

Ah, just figured it out while finishing this off...

```
FOR ele IN test
  RETURN ele
```

I guess this makes sense in the way AQL works? AQL always expects `RETURN` to be called for each returned row, hence return just basically pushes items to the final returned array? So here we were returning the entire row as a single item, and when we called `FIRST()` it was actually calling it on the array of inner items, and not the final AQL returned array.

**Comment by imtrobin** [comment]
I don't think so. If you look at my example, I am RETURN doc.key, it should not be an array or object but the RETURN d gives me an array of array

**Comment by jsteemann** [comment]
The reason for this behavior is that the result of an AQL query always is an array.
if there is no FOR loop on the top-level of the query, there will be an implicit one (invisible) which will make the result go into an extra array.
That means
```
LET d = (subquery returning an array)
RETURN d
``` 
and 
``` 
FOR d IN ...
  RETURN d
```
are not equivalent.
This behavior may be confusing, but we cannot change it without breaking downwards-compatibility for a lot fo queries.

**Comment by imtrobin** [comment]
Ok, that's makes sense. But I'm don't agree to make an array result implicitly without FOR. It should be up to AQL statement to ensure it returns an array if its a requirement. So I have to flatten my results before I RETURN, either this is not very clear in the docs.

**Comment by Simran-B** [comment]
Queries and subqueries always return an array, which is mentioned on the following documentation pages:
- https://www.arangodb.com/docs/stable/aql/operations-return.html
- https://www.arangodb.com/docs/stable/aql/examples-combining-queries.html
- https://www.arangodb.com/docs/stable/aql/data-queries.html#data-access-queries

**Comment by imtrobin** [comment]
I can work around it, it's just a return without FOR,  an array is created , that is unexpected.
