### ISSUE TITLE
Posting community developed client libraries

### ISSUE THREAD

**Issue by neel** [arangodb/arangodb#11757]
### Documentation / ArangoDB Website

Hello I've developed one C++ EDSL client library [`tash`](https://gitlab.com/neel.basu/tash) for ArangoDB. But I am not getting any place to post it to the arangodb website. Is there anyway to add community developed libraries ?

**Comment by dothebart** [comment]
Hi, 
maybe you want to write a blogpost demonstrating what it does? Its Readme is a bit "compact" ;-)
@MrPieces can probably help you a bit.
We can add it to the drivers page. Will it use fuerte underneath?

**Comment by neel** [comment]
I do not have a blog. It doesnt use fuerte. It uses the HTTP API. It depends on boost and nlohmann json.

**Comment by dothebart** [comment]
Hi, 
I was talking about arangodb.com/blog ;)
I like this format: https://www.arangodb.com/tutorials/tutorial-python/ (so that it walks you through the basic functionality) 
Maybe you can pick some queries from these posts: https://www.arangodb.com/docs/stable/aql/examples.html and demonstrate how to implement it using tash?

**Comment by neel** [comment]
Yes surely I can do that. But what is that format ? Is there any editor ? Can I write it in markdown ?

**Comment by dothebart** [comment]
Hi, 
Sorry for getting back to you so late. 
Yes, markdown is supported.

**Comment by neel** [comment]
@dothebart So is there any registration link ? How can I post ?

**Comment by Simran-B** [comment]
@neel You can open a pull request against the documentation repository: https://github.com/arangodb/docs
You could also write a markdown file and add it to your repository and link it from your main README, so that users find it in the same place. We can then link your repository from the [drivers homepage](https://www.arangodb.com/docs/stable/drivers/#community-drivers).

**Comment by neel** [comment]
@Simran-B Thanks for the reply. I'll need some time to write the docs.

**Comment by neel** [comment]
Added under Section "Community drivers" in `drivers/index.md`. Couldn't find anything related to blog (as mentioned by @dothebart ) in docs repository. 
Made [pull request](https://github.com/arangodb/docs/pull/547).

**Comment by dothebart** [comment]
Hi, 
the [Blog](https://arangodb.com/blog) is hosted on a Wordpress. It can work with markdown. Though available from the same host, its not directly related to the documentation git repository.

**Comment by Simran-B** [comment]
tash was added to the list of community drivers (not yet published live site). @neel If you want to write a blog article for our homepage, you may share a link with the Markdown formatted content here, then I'll forward it to our marketing team.
