### ISSUE TITLE
Fulltext for asian languages

### ISSUE THREAD

**Issue by oneminute** [arangodb/arangodb#1183]
I want to know how to use fulltext index for asian languages like chinese which has no spaces between words.

**Comment by andyhu** [comment]
It would be really nice if ArangoDB supports full text search in all the major languages including CJK ( Chinese, Japanese and Korean) since they don't have a space between different words. OrientDB embedded lucene to do such kind of job. I'm interested that if ArangoDB can integrate with something like Sphinx Search to provide the similar functionality.

**Comment by weinberger** [comment]
Have you seen the Elasticsearch River?
https://github.com/arangodb/elasticsearch-river-arangodb

**Comment by andyhu** [comment]
@weinberger Thanks for the link, I have actually seen it before. However it requires an elasticsearch server being set up and saves a duplicated set of records in ElasticSearch ( and it uses Java ).
But anyway, it might be the best choice if we want to do such kind of jobs. ElasticSearch is very powerful and flexible. It doesn't make sense to duplicate these features in ArangoDB

**Comment by dothebart** [comment]
Most probably we will support this with ArangoDB 3.4

**Comment by maxkernbach** [comment]
With [**ArangoSearch**](https://www.arangodb.com/arangodb-training-center/search/arangosearch/) support for chinese full-text search is implemented in 3.4.

Further information can be found in the [documentation](https://docs.arangodb.com/3.4/Manual/Views/ArangoSearch/).
Please find the latest release in the [download section](https://www.arangodb.com/download/).
