### ISSUE TITLE
IIFE necessary for Foxx apps?

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1232]
It seems like scoping in Foxx works like commonjs, i.e. everything is private to a file unless explicitly exported, so wrapping the whole file content in Immediately-Invoked Function Expression shouldn't be necessary. However, I keep seeing example code that does use IIFEs. Can you please clarify if IIFEs should be used, or if your examples should be updated?

For instance:
https://github.com/arangodb/aye-aye/blob/master/models/todo.js
https://github.com/arangodb/foxx-oauth2/blob/master/providers.js
https://github.com/arangodb/arangodb/blob/devel/Documentation/Books/Users/Foxx/README.mdpp#L85

**Comment by fceller** [comment]
It is not necessary. However, a lot of people prefer to use

    "use strict";

having a IIFE makes that trivial. Otherwise you need to put the "use strict" in each and every function.

**Comment by pekeler** [comment]
I don't think that's true. As long as you put `'use strict'` at the top of the file, it applies to everything in that file. AFAIK the only reason people are used to putting it into IIFEs is so that their scripts can be concatenated with non-strict scripts, but that doesn't happen with Foxx apps.

Let me take this one step further: V8 has a --use_strict option to enforce strict mode globally. I'd vote to turn it on by default in ArangoDB. So I wouldn't have to have `'use strict'` at the top of every file. Because removing boilerplate code like this and IIFEs is a good thing - but is probably a minority opinion :)

**Comment by pluma** [comment]
Having `'use strict'` globally (i.e. at the top of the file) was broken in earlier versions of ArangoDB. @fceller fixed it in (I think) 2.3. A lot of the examples that use IIFEs pre-date that change.

You don't have to use use IIFEs in 2.4 and later. I prefer not using them and try to remove them where they occur in ArangoDB and the officially maintained Foxx apps.

We can't use `--use_strict` because we need to break strict-mode in a few situations (e.g. the `internal` module needs to access and delete globals). Some of those could probably be solved by introducing a global object a la Node.js, but I don't think that's trivial at this point.

**Comment by pekeler** [comment]
Great. OK - Thx!

**Comment by mchacki** [comment]
Just an update.
We are using JSHint to evaluate our Javascript files.
The default configuration of JSHint does not like having "use strict"; in the first line of your file outside of your internal function.
```
"use strict";
function foo() {
  return "test";
}
```
will not pass JSHint

```
function foo() {
  "use strict";
  return "test";
}
```
will pass it

or

```
/*jshint globalstrict:true */
"use strict";
function foo() {
  return "test";
}
```
will pass as well.

For arangodb either version is fine, so if you do not use JSHint you are free to use whichever version you prefer, otherwise just set the option.

**Comment by pekeler** [comment]
@mchacki I haven't tried it, but running JSHint with the `node` option should help with that issue. http://jshint.com/docs/options/#node

**Comment by pluma** [comment]
@pekeler Sadly, that flag does a lot more than just that. It also whitelists a lot of globals ArangoDB does not provide.
