### ISSUE TITLE
Unexpected "Transaction ID us already in use"

### ISSUE THREAD

**Issue by aunikitin** [arangodb/arangodb#12335]
## My Environment

* __ArangoDB Version__:                  3.6.5
* __Storage Engine__:                       RocksDB 
* __Deployment Mode__:                 Single Server
* __Deployment Strategy__:             Manual Start in Docker
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:                  ArangoDb in Docker
* __Total RAM in your machine__:   16gb
* __Disks in use__:                            ssd
* __Used Package__:                        Docker - official Docker library

Hello
I used Stream Transaction in my project.
1. I call transaction begin API and lock all my exhisting collections to write.
2. I try to get document with transaction header.
Sometimes I have unexpected error like "transaction '123' is already in use. ErrorNumber: 28 HttpStatusCode: 500"
I don't understand why it happens, because in this momemnt only trunsaction '123' is running and i don't try to create new one (check with get transaction list API).
In documentation I could found out that error 28 rises when resource is locked, but in my case I tried to read with RocksDB engine.
This exception raises unexpectedly, sometimes all runs good, sometimes not. Db located in my local machine that's why only my code use it in one moment.
Now I resolved this problem with retries policy, but I'd like to know the reason of this behaviour.

**Comment by aunikitin** [comment]
UPD. Okay, this problems didn't resolved with retries policy.
Now I try to read data from db about 5 times with exponential wait policy, but sometimes even 5 retries aren't enough.

**Comment by Simran-B** [comment]
This problem was supposedly fixed in 3.6.5:

* Fixed issue ES-609: "Transaction already in use" error when running
  transaction.
  Added option `--transaction.streaming-lock-timeout` to control the timeout in
  seconds in case of parallel access to a streaming transaction.

Is your Docker image have this exact digest? (It's possible that the initial release was updated shortly after)
https://hub.docker.com/layers/arangodb/arangodb/3.6.5/images/sha256-60d87c56940e9b995f4d1b2a41677a224f2042db2857f770df20fa81227e8618?context=explore

In general, you should avoid sending operations for the streaming transaction in parallel (e.g. async on the client-side), because the server has to serialize the operations anyway. You could try to increase the streaming lock timeout to see if that has an effect:

https://www.arangodb.com/docs/stable/http/transaction-stream-transaction.html#limitations

Can you share details about the transaction operations you use?

**Comment by Simran-B** [comment]
@aunikitin Did you have a chance to look into this again?

**Comment by aunikitin** [comment]
@Simran-B after your comment we removed all parallel query to arango with same transacation id header. Now observing if problem will arise again

**Comment by Simran-B** [comment]
@aunikitin Alright, I'll close the issue for now. Please re-open if you encounter the problem again.
