### ISSUE TITLE
registerTask() with period + offset ignores offset

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1236]
The following code will start printing "bar" to the server console after 3 seconds, ignoring the offset.

    arangosh [_system]>
    tasks.register({
        id: "foo",
        period: 3,
        offset: 60,
        command: "require('console').log('bar');"
    })

It would be a nice feature, if an optional delay would be honored for the first run (wait 60 secs, then run the task every 3 secs). It would allow for something like a backup task to run daily at midnight:

    tasks.register({
        id: "backup",
        period: 60*60*24,
        offset: (new Date().setHours(24, 0, 0, 0) - new Date()) / 1000 |0,
        command: ""
    })

**Comment by pluma** [comment]
I think this is a limitation of the underlying V8 API. @jsteemann ?

**Comment by jsteemann** [comment]
No, the offset is passed correctly from the JS code to into the code that registers the periodic timer event.
I just re-read the event library's documentation and it says that for periodic timers, 

> the offset argument is merely an offset into the interval periods. 

This means `offset` cannot be greater than `interval`, which is why the above code currently does not wait 60 seconds before firing. So the library doesn't support it, and the only way I see to get this functionality to work for offset > period is to register a non-periodic timer with the specified offset first, and when this fires, this can install a periodic timer with an offset of 0.

**Comment by CoDEmanX** [comment]
Thanks for the docs update!

Maybe a cronjob is better suited for backups, since a periodic timer does not take DST, keep years etc. into account.

**Comment by pluma** [comment]
@CoDEmanX Yes, definitely. ArangoDB tasks are not persisted between restarts, among other limitations.
