### ISSUE TITLE
https://docs.arangodb.com/latest/Manual/GettingStarted/index.html gives error in Firefox, Safari, Chrome

### ISSUE THREAD

**Issue by rusty53** [arangodb/arangodb#12390]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by dothebart** [comment]
Hi, 
please note that the ArangoDB documentation can meanwhile be reached at https://www.arangodb.com/docs/stable/ - The above link should provide a 30x - which is definitely not working.

**Comment by Simran-B** [comment]
The server for legacy documentation redirects isn't available anymore. There's now a redirect to the documentation overview page of our website, so that you shouldn't get an error anymore.

The new address for the Getting Started guide is https://www.arangodb.com/docs/stable/getting-started.html

If you're on ArangoDB version 3.4 or older, then please upgrade to a more recent version, as all versions up to 3.4 reached end of life and are not supported anymore.
