### ISSUE TITLE
SEARCH with array doesn't work as the document stated

### ISSUE THREAD

**Issue by homo-sapiens-github** [arangodb/arangodb#12436]
## My Environment

* __ArangoDB Version__:        3.6.4
* __Storage Engine__:             RRocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               n/a
* __Infrastructure__:               own 
* __Operating System__:       MacOS 10.15.6
* __Total RAM in your machine__:        8Gb
* __Disks in use__:        SSD
* __Used Package__:              dmg

## Component, Query & Data

__Affected feature__:
SEARCH with array doesn't work as the document stated

__AQL query (if applicable)__:
```
FOR doc IN item_search
              SEARCH doc.tags == 'B'
              RETURN {title: doc.title, tags: doc.tags}
```

__AQL explain (if applicable)__:
doc.tags is an array. We try to return doc with 'B' in doc.tags. 

__Dataset__:
Collection: item with docs having attributes tags as an array. 
View: item_search

```json
{
  "type": "arangosearch",
  "links": {
    "Items": {
      "analyzers": [ "identity" ],
      "fields": {
        "title": {
          "analyzers": [ "text_en" ]
        },
        "tags": {
          "analyzers": [ "text_en" ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  }
}
```

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

SEARCH with array doesn't work as the document stated. https://www.arangodb.com/docs/stable/aql/operations-search.html#arrays-and-tracklistpositions

```
{
  "value": {
    "nested": {
      "deep": [ 1, 2, 3 ]
    }
  }
}
```
"A View which is configured to index the field value including sub-fields will index the individual numbers under the path value.nested.deep, which can be queried for like:"

```
FOR doc IN viewName
  SEARCH doc.value.nested.deep == 2
  RETURN doc
```

__Expected result__:
Return doc with 'B' in doc.tags

**Comment by Simran-B** [comment]
@homo-sapiens-github Looks like you copied the View definition from the Web UI while the editor is in Tree mode? This makes it really hard to read and reproduce. I adjusted your post. Please set the editor to Code mode before you copy & paste in the future - thanks in advance!

Based on your View definition, I'm pretty confident that the problem is the missing `identity` Analyzer for the field `tags`. While the View default is set to `["identity"]`, you explicitly specify the Analyzers for the `tags` fields as `[ "text_en" ]`. Your `SEARCH` query does not set an Analyzer, thus it will default to `identity`. You can either add the Analyzer to the list, or set the `"text_en"` Analyzer in the query (note that it's a tokenizing Analyzer with stemming and case-folding enabled, which might not be what you want).

Add Analyzer used in query to list of Analyzers for the tags field:

```json
        "tags": {
          "analyzers": [ "identity", "text_en" ]
        }
```

Or adjust the query to use the Analyzer which the tags attribute was processed with using your original View definition:

`SEARCH ANALYZER(doc.tags == 'B', 'text_en')

The `text_en` Analyzer is not applied to the string literal `'B'`! If you actually want to use the `text_en` Analyzer, then you probably want to do `doc.tags == TOKENS('B', 'text_en')[0]` or `doc.tags ALL == TOKENS('B', 'text_en')`.

**Comment by homo-sapiens-github** [comment]
Yes. It works. We can close this issue. 👍
