### ISSUE TITLE
Foxx - Question about synchronous API's

### ISSUE THREAD

**Issue by Phillips126** [arangodb/arangodb#12470]
I am working on an application that is used internally at our company by a few dozen users.  The application is effectively a log of all part numbers which we assign to our products and components.  Aside from being a tool to lookup existing numbers, it can also generate new numbers based on a few parameters the user provides.

Our part number schema requires the first two characters of each part number to indicate the "family" in which this part belongs to.  For example:  "**00**5341" and "**30**6425" are two different families: [00] and [30].

Because of this schema, we wrote a query that looks up the last assigned number for the indicated family and then increments it by the number of parts the user is trying to create (the user can create any number of part numbers, typically 2 - 3 at a time).  The query is typically quite fast (<30ms) but occasionally there is a spike where the query can take 300ms.  

In the unlikely event that two users request part numbers at the exact same time, my guess is we'd get duplicate part numbers which would be a big problem for our company.  Is there a way that I can ensure this can not happen?  I use Foxx as my application is web based.

EDIT - 

I just saw the following line in the Foxx documentation:
> Because the JavaScript code is running inside the database another difference is that **all Foxx and ArangoDB APIs are purely synchronous** and should be considered blocking. This is especially important for transactions...

Does this mean that in my example above, both requests are queued up automatically and complete in sequence - thus preventing my hypothetical problem already?

**Comment by Simran-B** [comment]
If you want to warrant that no other writes occur between two JS API calls, then you should use a transaction. For a non-sharded collection, that could also be an AQL query. You may also want to add an index on the field which stores your number and enable the unique option, so that the uniqueness is guaranteed - or use it as the `_key` attribute value, which is unique by default (keep in mind that it must be a string however).

**Comment by Phillips126** [comment]
@Simran-B, I appreciate your response and apologize for the delay in getting back, I was away on vacation.  Our current deployment is just a single non-sharded collection.  Is this default behavior in our environment using Foxx (per the quote above) or will I need to modify my API?  In the future we'll likely move into a cluster environment to gain the advantages that has - I understand I'll need to use transactions there.  The recommendation of making the field unique is a good one and I will do this.

**Comment by Simran-B** [comment]
@Phillips126 Sorry for the late reply, now it was me who was on vacation. Here are a couple of things that come to my mind:
- In a cluster, Foxx does not run on DB-Servers but Coordinators. If you call JS API methods, then the effects will not be visible immediately to other Coordinators.

- As long as your collection has a single shard, AQL queries are atomic even in cluster (only a single DB-Server is involved, excluding replicas). If you use Foxx and if it's not a single AQL query, then you should use transactions. Although, if you utilize the uniqueness option, then no transaction should be necessary because the system will refuse to store a second document with the same attribute value.

- What you quoted from the docs was written with JS transactions in mind:

  > Because the JavaScript code is running inside the database another difference is that all Foxx and ArangoDB APIs are purely synchronous and should be considered blocking. This is especially important for transactions...

  I believe the intention was to say that you can call several JS API methods after another and they will be executed serially. There is no async execution that would require `.then()`, `await` or similar.

- There are a few differences between single server and cluster:
  - [Transaction limitations in cluster](https://www.arangodb.com/docs/stable/transactions-limitations.html#in-clusters)
  - [Collections cannot be renamed](https://deploy-preview-557--zealous-morse-14392b.netlify.app/docs/3.8/data-modeling-collections-collection-methods.html#rename)
  - [Graph traversals need to declare involved collections](https://www.arangodb.com/docs/stable/aql/operations-with.html) (if they are not implicitly declared)
  - [Non-default shard keys remarks](https://www.arangodb.com/docs/stable/architecture-deployment-modes-cluster-sharding.html#configuring-shards)
  - ...

**Comment by Phillips126** [comment]
@Simran-B Thanks for the information, this has been very helpful.
