### ISSUE TITLE
graph TRAVERSAL with custom visitor and filter

### ISSUE THREAD

**Issue by antokara** [arangodb/arangodb#1253]
This functionality looks very useful and promising but I think there is a case where some optimization could happen.

So I have a graph for hierarchy of lets say, Directories.
These directories are also "connected" with another collection of Files or other attributes.

Now I want to write an AQL that will traverse the graph from a starting/parent point/directory
and retrieve it's children directories BUT filter them depending on the files each directory contains and/or attributes.

Then, the result will be sorted, again using data from the files and/or attributes.

My "problem" is that I have to write a collection/document lookup in the custom Filter
so that on a "first level", children directories which do not match my criteria are not traversed...
(ie, I get the files of that directory or other "connected" documents and make my checks)

Then, I also have to do almost the same thing (lookup the same documents) in the custom Visitor, just to return the values I need to make the SORT in the originating AQL.

Perhaps I am doing it wrong as design/architecture, although I cannot put all the information into a single collection, nor connect them all with graph(s). The issue that I find, is that I have to perform lookups for the same document(s) twice for each vertex (once in filter and then once in visitor). If the custom filter could also return the data instead of the visitor, that would optimize things.

I hope the use case scenario was clear.
Thanks.

**Comment by jsteemann** [comment]
Understood.
For pre-order visitation traversals, the visitor function is currently invoked directly after the visitor. That means one could gain efficiency by combining the two.
For post-order visitation, this will not work, as the filter is executed first, and the invocation of the visitor is deferred until later.
Giving filter functions access to `result` might work, especially as we cannot use the return value of a `filter` function to produce results. This is because `filter` return values are currently already used to determine whether to visit the vertex and/or to expand it.

But overall, adding `result` as 4th parameter to the `filter` function call would work at least for pre-order traversals, and also keep compatibility with existing functions. 

Though the API will get a bit messy. Any suggestions for "fixing" this are welcome.

**Comment by dothebart** [comment]
Hi, 
With ArangoDB 3.0 custom visitor functions aren't supported anymore. 

The current aproach to your problem would be to stack 2 traversals, one doing the real traversal, one doing the look ahead. 

Read more about graphs in general:
https://docs.arangodb.com/3.0/Manual/Graphs/index.html

and the traversal feature over at:
https://docs.arangodb.com/3.0/AQL/Graphs/Traversals.html

We discussed several graph problems with example traversals over at Stackoverflow:
http://stackoverflow.com/search?q=arangodb+graph

Give ArangoDB 3.0 RC2 a testdrive: https://www.arangodb.com/download-preview/
