### ISSUE TITLE
Improve performance of JSON handling with simdjson

### ISSUE THREAD

**Issue by kesavkolla** [arangodb/arangodb#12593]
[simdjson](https://simdjson.org/) offers greater performance for handling large amounts of JSON. This can improve the bulkinserts tremendously. I'd love to see use of simdjson in arangodb.

**Comment by Simran-B** [comment]
Thanks for the suggestion. Our engineering teams discussed simdjson last year in December, but came to the conclusion that it would be a considerable effort with unclear outcome.

The VelocyPack parsing performance might not even be that far away from 3GB/s. But it very much depends on the parsed JSON and what is done with it afterwards, making it difficult to compare. For example, VelocyPack builds internal indexes, which takes the majority of the time. Improving the raw parsing speed alone will not help much - usually, the bottleneck isn't the parsing and ArangoDB rarely parses more than a few kilobytes at a time.

Furthermore, we would have to up the minimum required CPU architecture from Nehalem to Westmere because of the required CLMUL instructions.

**Comment by kesavkolla** [comment]
Good to know that VelocyPack is close enough to simdjson for parsing. I'm going to try use ArangoDB for storing health care data in FHIR JSON format. These FHIR JSON is pretty huge sometimes goes in the order of 50MB. I'm wondering how will ArangoDB handle such large JSON file.

**Comment by dothebart** [comment]
On import you need to make sure that one line corosponds to one document to store. 
Internally the documents are stored velocypack encoded. Large documents can become a problem when they have to be transmitted often between coordinator and db-server in clusters.
