### ISSUE TITLE
Job execution doesn't work on multiple database

### ISSUE THREAD

**Issue by dagarwal82** [arangodb/arangodb#1286]
Here is the sequnce:

1) Deploy the application under _system.
2) Push a job to the queue
3) job executes successfully

4) Add a new database, restart the arangodb and deploy the application there
5) Push a job to the queue to either _system or newly created database
6) Job gets added to the queue but never executes.

7) Delete the newly created database
8) Push the job to the queue of _system. 
9) It gets added but never executes.

10) Restart the arangodb, push the job and it executes. 

Queue and Job Type names utilizes the current database name and therefore there is no name clash

**Comment by pluma** [comment]
This has been fixed in devel and will be part of the 2.6.0 release.

However there's a bigger problem with job types having to be loaded before the queue workers get to the job in question, which causes problems when ArangoDB is restarted and the code that defines the job type hasn't been run again. For that see #1336.
