### ISSUE TITLE
How to specify the password from the file

### ISSUE THREAD

**Issue by Korov** [arangodb/arangodb#12875]
I want to deploy arangodb cluster with ArangoDB Starter, and specify the password from the file

**Comment by Korov** [comment]
just like `arangod -c filename` same

**Comment by dothebart** [comment]
Hi, 
you specify a JWT using `--auth.jwt-secret` which will setup the cluster with the secret to the jwt read from a file.
Next you can run [arangosh with `--server.jwt-secret-keyfile`](https://www.arangodb.com/docs/stable/programs-arangosh-options.html#server) so that its connection will be system level. 
You can then use it to execute javascript - 
```
require("@arangodb/users").replace("root", "my-changed-password");
```
or invoke the `fs` module to load the file with the password. 
https://www.arangodb.com/docs/stable/appendix-java-script-modules-file-system.html
https://www.arangodb.com/docs/stable/programs-arangosh-details.html

**Comment by Simran-B** [comment]
FYI: there is a long deprecated arangod server option `--server.jwt-secret`, which was replaced by `--server.jwt-secret-file`. The starter option `--auth.jwt-secret` expects a file path to read the secret from, so it's equivalent to `--server.jwt-secret-file`.

https://www.arangodb.com/docs/stable/programs-starter-options.html#authentication-options
