### ISSUE TITLE
Could not fetch documents count

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#12899]
## My Environment

* __ArangoDB Version__:        3.6.2
* __Storage Engine__:             RocksDB -->
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Total RAM in your machine__:    1GB (VM) Test 

I left the database running for a long time, when it gives me a "Could not fetch documents count" error  in UI. I reboot , and it's the same. I don't see any out of memory errors.

![image](https://user-images.githubusercontent.com/531606/97126085-de66ff00-1770-11eb-9ae2-c3e797437a25.png)

![image](https://user-images.githubusercontent.com/531606/97126050-ca230200-1770-11eb-872b-9f66399e49bb.png)

**Comment by imtrobin** [comment]
Seems to be the db is corrupted. I can add documents ,but when I delete via AQL ,it say can't be found. And the UI shows negative document.

![image](https://user-images.githubusercontent.com/531606/97158210-16dbfc80-17b4-11eb-91d0-7ee91f584c4e.png)

**Comment by Simran-B** [comment]
@imtrobin Did you upgrade the database directory, and if so, from which version to which version?

**Comment by imtrobin** [comment]
This was upgraded from an older version, I think 3.5 quite a while ago (last year?).  I don't think I had a issue after the upgrade. I stopped working on it for sometime. I just left the server running.

**Comment by Simran-B** [comment]
I've seen similar corruption myself in my local test server, which I randomly upgraded (including non-release versions) over multiple years. It eventually showed a large negative number as document count.

The proper upgrade procedure is to update to the latest patch version, e.g. 3.5.1 to 3.5.6, then to the latest version of the subsequent minor versions, in this example 3.6.8 and then 3.7.3. Skipping minor versions might result in silent corruption. Or perhaps some kind of overflow issue that only occurs after several years? If the server gets shut down because the machine gets shut down, then the write-ahead log should prevent unnoticed corruption because of unexpected termination, but it's possible that there is some very race condition perhaps, which causes this issue.

I suggest that you dump all databases including system collections and restore it into a fresh instance. That should resolve the problem.

**Comment by imtrobin** [comment]
This 's a development server with fake data, so I'm not worried, but I'm concerned for production if I run into these issues. There's no detection ,and no way to recover?

**Comment by imtrobin** [comment]
I'm actually seeing this in another older test deployment which I have not even upgraded, still has 3.5.0

![image](https://user-images.githubusercontent.com/531606/97803082-b7ce2a00-1c82-11eb-95d1-8a696fd31a72.png)

**Comment by imtrobin** [comment]
Hmm, I created a fresh install 3.7.3, and also seeing this

**Comment by Simran-B** [comment]
@imtrobin You say a fresh installation, as in a new database directory? How did you restore the data? Or do you mean that the issue occurs as you create new documents in the new instance?

**Comment by imtrobin** [comment]
A fresh VM centos, fresh install. No restore of data. Yes, it occurs after I create.

**Comment by Simran-B** [comment]
Okay, so fresh 3.7.3 instance with a new database folder, you create documents via the UI but the count is wrong?
What's your browser? Can you try an incognito window to rule out caching issues? (There was a bug which caused a previous collection count to show, but that was fixed quite a while ago)

**Comment by Simran-B** [comment]
Can you also check the browser console (usually F12) if there is anything reported there?
Does arangosh report the same count as the Web UI (both off and both the same value)?
`db.collectionName.count()`

**Comment by imtrobin** [comment]
Incognito works. The console has an error.

GET http://192.168.1.223:8529/_db/Platform/_api/collection/Advertisement/count?_=1605183116740 net::ERR_BLOCKED_BY_CLIENT

So it was due to the adblocker in the brower which blocks the collection with keyword Advertisement. Mystery solved.
