### ISSUE TITLE
Need suggestions on strategy for data modeling in ArangoDB

### ISSUE THREAD

**Issue by tonyabracadabra** [arangodb/arangodb#12962]
I am looking for modeling the following scenario that, a `Workspace` is composed by a list of `Table` plus meta data, and a `Table` is composed by a list of `View`s and a list of `Field`s plus meta data. Since the only relationship we have right here is one to many relationship, I am wondering if it is ideal for me to save all the concepts into one collection of `Workspace`, or I should create a collection for `View`, `Table` and `Field` as well. 

For the one collection strategy, I think this is perfect for deleting a root elements for example, if I were to delete a `Workspace` or a `Table` I don't have to go deep into other collections for deleting all the children elements in the document, which makes the things much easier. But when it comes to updating, for example, for updating a `Field` with `fieldId = 1234` under `Table` with `tableId = 3456` under a `Workspace` with `workspaceId = 4567`, I will first find the workspace with `DOCUMENT`, then go through two for loops in order to locate the field I want to update. Correct me if I am wrong but this is the only possible way I see I can get, unless we can have the within document indexes for `Table` and `Field` so those elements can be find as easy as `workspaceId.tableId.fieldId`. I am wondering if we can do anything like that with arangodb?

For multi collection strategy, which means I will have to keep those concepts in different collections so I will have to scan the full collection every time for querying small documents like `Field`.

**Comment by Simran-B** [comment]
The modeling strategy depends on many factors, which makes it hard to suggest one. Total number of documents expected and their size certainly play a role, but also how often they will be updated. If you put too much data into a single document and need to update parts of it very often, then you might cause unnecessary write contention for instance. Another point is that operations on document level are always atomic, but multi-document operations might not be (primarily in a cluster setup with a sharded collection).

You may want to denormalize your data model in order to avoid cramming too much things into a single document. Nesting `Field`s seems reasonable for example, e.g.

```json
{
  "_key": "{tableId}",
  "fields": [
    { "id": 0, "value": "..." },
    { "id": 1, "value": "..." }
  ]
}
```

If you need to mutate an array like `fields` above, it can be a bit tricky in AQL. But maybe that's not an issue because you use a driver like arangojs to splice the array anyway? Nested objects are easier to update:

```json
{
  "_key": "{tableId}",
  "fields": {
    "field0": "...",
    "field1": "..."
  }
}
```

`UPDATE "{tableId}" WITH { fields: { field1: "new value" } } IN collection`
(will change value of `fields.field1` while `fields.field0` remains as-is)

Nested attributes like `fields.field1` can be indexed. With objects inside arrays there are ways to index them, but there are some limitations.

**Comment by maxkernbach** [comment]
@tonyabracadabra Did you have a chance to read Simran-B's latest comment?
