### ISSUE TITLE
Collection Method Insert documentation

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1303]
Chapter 7.2 Insert
- "It must not contain attributes starting with _." seems to be outdated since _key can be specified.
- "insert is an alias for save" but there's no documentation for save.

**Comment by 13abylon** [comment]
- "It must not contain attributes starting with _." seems to be outdated since _key can be specified.

Thanks for reporting. Will be fixed!

- "insert is an alias for save" but there's no documentation for save.

You can find documentation for save in the old documentations (2.1 and previous). If you want to check for older version, just go here: https://docs.arangodb.com/2.1
