### ISSUE TITLE
Parallel request for auto creating collection returns duplicate name error

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangodb#1306]
Hello,

I used js API to make some requests parallel for getting collection with `autoCreate` true and I got responses with duplicate name error (1207) from some of them. Of course, it's reasonable, one request create a collection automatically if it doesn't exists, and others create failed because of existing collection name. 

However, it's not logical. I think if this case happens, the other parallel requests with `autoCreate` true should be ignored by db side or might return some other kind of error instead of 1207, shouldn't they? For our use, I can not make a difference between this case and normal creating failed.

Bg,
Kevin

**Comment by jsteemann** [comment]
The database has no idea that you are issuing parallel requests to create a collection. So the first request will create the collection and the other ones will be responded to with error 1207 (duplicate name). I think this is unavoidable, because the server does not have the `autoCreate` option that the driver offers.

From my point of view, the driver should be adjusted so it checks for error 1207 when calling its `collection` method with `autoCreate` set. 

@pluma, any thoughts?

**Comment by kevinprotoss** [comment]
Hi jsteemann,

I agree with you.

Best regards,
Kevin

**Comment by pluma** [comment]
This is an error in the JS driver, not ArangoDB itself.
