### ISSUE TITLE
Arangodb cluster options

### ISSUE THREAD

**Issue by TuminD** [arangodb/arangodb#13060]
## My Environment

* __ArangoDB Version__:        3.6.7-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               3 servers - Agent, Coordinator, DBserver roles on each node

Question:
I need to change such Arangodb server options for cluster:
query.memory-limit
query.max-runtime
rocksdb.block-cache-size
rocksdb.total-write-buffer-size
cache.size

Am I right that it should be done in coordinator configs - arangod.conf (on each node) ?
Did not find explicit instructions on where to do this.
https://www.arangodb.com/docs/stable/programs-arangod-options.html

**Comment by maxkernbach** [comment]
Hi @TuminD,

The easiest way to specify ArangoDB server (`arangod`) options with the starter (`arangodb`) is via[ pass through options](https://www.arangodb.com/docs/stable/programs-starter-options.html#passing-through-other-database-options).

Unfortunately not all options in the stated documentation state whether these options should be applied on an Agent, Coordinator or DBserver.

You can use `--coordinators...` for options:
- query.memory-limit
- query.max-runtime

and `--dbservers...` for options:
- rocksdb.block-cache-size
- rocksdb.total-write-buffer-size
- cache.size

**Comment by Simran-B** [comment]
Hi @TuminD, did you have a chance to try the pass-through option?

**Comment by TuminD** [comment]
Hi @Simran-B 

I've tried to specify ArangoDB server options with the starter via pass through options and also via arangod conf file (arangod.conf)
**are these alternative ways to setup server options ?** 

I've check Coordinator's running configuration via arangosh utility:
https://www.arangodb.com/docs/stable/administration-configuration.html#fetch-current-configuration-options

But could not check DBserver running configuration via arangosh:
arangosh --server.endpoint tcp://127.0.0.1:8530 --server.database _system

Got Error message: 'not authorized to execute this request'

**How to check DBserver running configuration?**

**Comment by TuminD** [comment]
Hi @maxkernbach
maybe can you help with these questions (above) ?

**Comment by maxkernbach** [comment]
Hi @TuminD,

Let me explain this with the following a example. A local 3 node cluster is deployed with the starter (**arangodb**) command below:

```
arangodb --starter.local --coordinators.query.max-runtime=20
```

Internally 9 **arangod** processes are started: 3 nodes and one dbserver, coordinator and agent per node.

One of the 9 **arangod** processes (in this case a coordinator):
```
/usr/sbin/arangod -c /home/max/Documents/starter/cluster/local-slave-2/coordinator8549/arangod.conf --database.directory /home/max/Documents/starter/cluster/local-slave-2/coordinator8549/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/cluster/local-slave-2/coordinator8549/apps --log.file /home/max/Documents/starter/cluster/local-slave-2/coordinator8549/arangod.log --log.force-direct false --javascript.copy-installation true --cluster.my-address tcp://localhost:8549 --cluster.my-role COORDINATOR --foxx.queues true --server.statistics true --cluster.agency-endpoint tcp://localhost:8531 --cluster.agency-endpoint tcp://localhost:8541 --cluster.agency-endpoint tcp://localhost:8551 --query.max-runtime 20
```

As you can see in the command, the starter created a configuration file for this coordinator in the directory `/home/max/Documents/starter/cluster/local-slave-2/coordinator8549/arangod.conf`, which is used for this **arangod** process. In addition the option `--query.max-runtime 20` is attached.

So, as shown above, the starter pass through option is not directly written into the config file that the starter (**arangodb**) creates, but rather attached to the single **arangod** process command.

> How to check DBserver running configuration?

Unfortunately, this is not possible. You can connect to a DBserver when specifying a JWT secret with `arangosh --server.jwt-secret-keyfile <path/to/secret>`, but can't retrieve the running configuration as within coordinators since JavaScript transactions are not available on a DBserver.

**Comment by TuminD** [comment]
Hi @maxkernbach 

Thanks for your detailed explanation

> So, as shown above, the starter pass through option is not directly written into the config file that the starter (arangodb) creates, but rather attached to the single arangod process command.

Ок, for example:
Am I right that I can specify Coordinator (or other role) configuration options in two ways?:
1) via pass through options: --coordinators.query.max-runtime=20 
2) via arangod conf file (arangod.conf):
```
[query]
max-runtime = 20
```
And both ways are lead to identical Coordinator configuration?
Or second way is wrong\not recommended?

**Comment by maxkernbach** [comment]
Hi @TuminD,

> Am I right that I can specify Coordinator (or other role) configuration options in two ways?

Yes, it is correct that these are both viable options to change the configuration. You just have to make sure to modify the correct configuration files (created by the starter) and specify pass-through-options on every execution of the starter (`arangodb`).
