### ISSUE TITLE
Performance of querying the edge collection

### ISSUE THREAD

**Issue by dagarwal82** [arangodb/arangodb#1309]
I have an edge collection with 120K documents. It holds field properties sig1 and sig2

{
 "sig1" : "xyz",
 "sig2": "abc"
}

I am executing following query:
FOR e in edgecol FILTER e.sig1=="abc"  || e.sig2=='abc' RETURN e

It takes more than 600 msec or sometime 1 sec. Indexing is done on sig1 and sig2.

Is it expected behaviour or is there a better way to query. I tied traversing as:

FOR e in GRAPH_EDGES("Graph2", {sig:"abc"}, {direction:"any", edgeCollectionRestriction:"edgecol"}) RETURN e

this query is little better but still takes 300-400msec

**Comment by jsteemann** [comment]
I expect that an EXPLAIN for the above query will indicate that the query won't use an index. This is because of the logical or (`||`) on two different attributes, which would require using two different indexes on the same collection and merging the results. This is currently not supported by the optimizer (though of course the feature is on our wishlist).

A fix might be to split the one condition into two subqueries as follows:
```
LET q1 = (FOR e IN edgecol FILTER e.sig1=='abc' RETURN e)
LET q2 = (FOR e IN edgecol FILTER e.sig2=='abc' RETURN e)
FOR doc IN UNIQUE(APPEND(q1, q2))
  RETURN doc
```
which should use the appropriate index in each subquery and then merge the results later on.
This will work ok if there are not too many results. If you are sure that there will be no duplicates, you can also omit the `UNIQUE`.

**Comment by CoDEmanX** [comment]
I assume if there are too many results, they all need to fit into memory, right? Wouldn't this issue be resolved by lazy evaluation?

**Comment by jsteemann** [comment]
I think not in this case, because the uniqueness check requires all results to be present anyway.

**Comment by jsteemann** [comment]
At the moment the workaround for this is to use two queries or subqueries, one for each attribute/filter, and combine their results later. In the long run, this should be fixed by using multiple indexes for one collection from an AQL query. The requires bigger changes to the optimizer and the AQL internals, but would be the proper way to fix it transparently and without needing to adjust AQL queries.

**Comment by CoDEmanX** [comment]
This applies to document collections as well, and also a logical XOR, but not AND and NAND, correct?

Until the planned overhaul, relational DBMS will have a performance advantage for these kinds of queries I guess.

**Comment by jsteemann** [comment]
It has nothing to do with edges or documents. It is simply that when using OR-combined subconditions on different attributes, the optimizer will not use indexes. The problem does not exist for AND-combined conditions or subconditions.

I wouldn't say in particular that *relational* DBMS have a performance advantage here, but rather *DBMSes that can use multiple indexes and combine the results*. So it more depends on how a databases leverages indexes than whether its relational or not.
