### ISSUE TITLE
Aardvark: Weird cursor offsets in query editor.

### ISSUE THREAD

**Issue by NiklasBeierl** [arangodb/arangodb#13117]
## My Environment

* __ArangoDB Version__:        3.5.5-1
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Arch linux with KDE Plamsa.
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__: The query editor in the web interface.
__Problem__:
I will start with a picture:
![Peek 2020-12-01 12-11](https://user-images.githubusercontent.com/22919961/100733832-0fb99700-33cf-11eb-862a-1d46831c2a5c.gif)
(I am aware that there is an error in the query, not relevant here)
So I guess the best way to describe it, is the "cursor" has an offset? This happens pretty often, usually affects some lines and some not and the offset also varies: Usually 1-5 chars. I haven't found a reliable way of getting rid off this behavior.
Browser is latest Google chrome running on Arch linux with KDE Plamsa. I have never encountered this issue in any other text field ever.
If you need additional info on the Arango server, I will have to annoy our sysadmin. 

__Expected result__:
![2020-12-01_12-23-32](https://user-images.githubusercontent.com/22919961/100734490-0bda4480-33d0-11eb-8413-f66be871a658.png)

**Comment by NiklasBeierl** [comment]
Possibly related? https://github.com/ajaxorg/ace/issues/3036

**Comment by dothebart** [comment]
heh, that looks fancy - and scary.
Maybe you've got some special characters in there?
Since there are control characters, that switch sequence left to right?
If you cut'n'paste the query into the github editor, does it behave similar?
does it work if you start all over with a fresh window and *type* the same again?

**Comment by maxkernbach** [comment]
Hi @NiklasBeierl,

The first two characters in line 3 (word `filter`) look weird. Could you try to retype `FILTER` or check if the offset always occurs if there is a `FILTER` statement involved?

**Comment by NiklasBeierl** [comment]
Ill go with the old saying, two pictures say more than two thousand words:
![Peek 2020-12-04 11-41](https://user-images.githubusercontent.com/22919961/101154564-2efe3180-3626-11eb-936b-a37a5d8e894a.gif)

![Peek 2020-12-04 11-42](https://user-images.githubusercontent.com/22919961/101154641-43dac500-3626-11eb-8db6-771eec232069.gif)


Grüße aus dem Donautal!

**Comment by NiklasBeierl** [comment]
I accidentally discoverd a few more "wierd sequences": `ff` `fi` `fl` all seem to produce this offset:
![Peek 2020-12-06 08-11](https://user-images.githubusercontent.com/22919961/101273987-a785ff00-379a-11eb-8a05-a5bf1a72279f.gif)

**Comment by goedderz** [comment]
Looks like a ligature is rendered for some reason. I can't reproduce it. Might be due to the font used on your system. I assume you don't have any custom style sheets applied.

Are you perchance familiar with the chrome debugger and can try to turn off ligatures by setting `font-variant-ligatures: none` for the textbox? Or can you tell which font is used, so we can try to reproduce it ourselves?

**Comment by NiklasBeierl** [comment]
@goedderz You are right on the money. I set `font-variant-ligatures: none` on `#aqlEditor` and the problem is gone. 
I am not aware of any custom styles. I checked my chrome extensions, and while "Stylebot Lite" does tamper with your styles, disabling it didn't fix the issue I am having here.
Here are the computed font-related styles on `#aqlEditor`, hope that helps.
![2020-12-07_16-28-07](https://user-images.githubusercontent.com/22919961/101369991-38e39700-38a9-11eb-8f7a-a0c62dfb0a5e.png)

**Comment by goedderz** [comment]
Thanks @NiklasBeierl. That should allow us to fix it, though I still haven't been able to select a font which reproduces this.

**Comment by Simran-B** [comment]
The query editor doesn't seem to be thrown off when using the Unicode ligature character ﬁ: `ﬁlter`

![image](https://user-images.githubusercontent.com/7819991/101662989-6d428900-3a4a-11eb-8f39-dadcbc29b3e7.png)

**Comment by NiklasBeierl** [comment]
Hmm weird, out of curiosity, I created an html document with nothing but a textarea, set:
```
    font-variant-ligatures: common-ligatures;
    font-family: Monaco, Menlo, "Ubuntu Mono", Consolas, source-code-pro, monospace;
```
and it acted normal. Its only an issue with the aql editor. I guess its because ace doesn't actually use a textarea?

**Comment by goedderz** [comment]
> The query editor doesn't seem to be thrown off when using the Unicode ligature character ﬁ: `ﬁlter`
> 
> ![image](https://user-images.githubusercontent.com/7819991/101662989-6d428900-3a4a-11eb-8f39-dadcbc29b3e7.png)

Interesting, but it is, of course, different. I don't find it unexpected that rendering two characters as a ligature, or having a single character that's a ligature, has a different effect. E.g. if ace counted the number of utf8 code points to align the cursor, that might be a problem. I have no reason to believe that it's the case, just to illustrate the point.

I don't have time yet to look into that in detail, but it looks like this isn't unknown:
https://github.com/ajaxorg/ace/issues/2548
https://github.com/ajaxorg/ace/issues/3037

**Comment by vvrein** [comment]
@NiklasBeierl take a look at here.
https://github.com/ajaxorg/ace/issues/3036#issuecomment-778647000

I think you faced something possibly related to mine case.

**Comment by NiklasBeierl** [comment]
Thanks @vvrein.
What I understood from your comment ist that your issue was caused by a rule in your `.config/fontconfig/fonts.conf`. But this file does not exist on my system. :thinking:

**Comment by vvrein** [comment]
@NiklasBeierl 
The general point of all this strangenesses is that (my pov):
1) Ace expects monospace font
2) Ace calculates the carriage position based on:
   1) single character width
   2) how many characters are from the beginning of the line, to current position

So, broken behavior could be part of "no monospace font got when requested".

---

My system is Arch Linux + Sway + most configs done manually.  
My initial bug was with Gollum editor, and I was able to reproduce same bug on https://ace.c9.io/   
Then, I tried to reproduce bug on https://ace.c9.io/ on other linux machine, but cant.  
Then, I launched new fresh Arch setup in VM, but without any configuration, and tried to reproduce Ace bug, but still can't.  
So, it gave me an idea that bug can be caused with something related to only my system. One more thing is that this bug was in any browser on my system: firefox, google chrome, chromium.  
Then I began to delete/install different fonts, as initially I thought that there was no needed font on my system.  
When I deleted noto-fonts - Ace began works correctly. So it gives me point to further search.  
Then, on some point, I finded out, that my fontconfig was the root cause of the issue!
The only thing left was to find the necessary lines.

```xml
<match>
    <edit mode="prepend" name="family"><string>Noto Sans</string></edit>
</match>
```

Why and for what reason I added those lines to my fontconfig - is a kind of a mystery for me :)
But but I can say for sure that I did it by myself, for whatever reason...
