### ISSUE TITLE
Implement Redis like Sorted Sets/Leaderboards?

### ISSUE THREAD

**Issue by pyros2097** [arangodb/arangodb#1312]
Is is possible to create redis like sorted sets using skip list indexes? Or is it better to use the key value store (I can't seem to find the documentation on the key/value store)? And will its performance still match for huge sorted sets?

**Comment by jsteemann** [comment]
There is no direct equivalent to a Redis sorted set in ArangoDB, but the same can be achieved using a unique skiplist index. Here's an example, using a collection named `highscores`:
```js
/* create collection */
db._create("highscores");
/* index by score attribute */
db.highscores.ensureIndex({ type: "skiplist", unique: false, fields: [ "score" ] });
/* create 100k users with random scores */
for (var user = 0; user < 100000; ++user) { 
  db.highscores.insert({ _key: "user" + user, score: Math.floor(Math.random() * 10000) }); 
}
/* get the 5 users with lowest scores */
db._query("FOR h IN highscores SORT h.score ASC LIMIT 5 RETURN h").toArray();
/* get the 5 users with highest scores */
db._query("FOR h IN highscores SORT h.score DESC LIMIT 5 RETURN h").toArray();
```
I have used the `_key` attribute for storing the user id, because `_key` is always present and unique, making it ideal for storing unique user ids. Using the `_key` attribute for storing user ids ensures that no user will be present twice in the collection. Note that there are restrictions for what can be stored inside `_key`, but if your user ids are numeric, you can store stringified user ids in `_key`.

The two AQL queries for finding users with lowest & highest scores will use the skiplist index on `score` for sorting, so they will only look at very few documents. They should be very fast.
Inserting a user into the `highscores` collection will also populate the skiplist index automatically. 

Inserting into a skiplist should have about logarithmic complexity on average though that is not guaranteed. This is because the skiplist is a probabilistic data structure and internally it will be flipping coins. In theory therefore there is a chance that becomes badly balanced. But in practice it should be quite close to an average logarithmic complexity.

**Comment by jsteemann** [comment]
If you're interested, there's now also a blog article about the subject:
https://www.arangodb.com/2015/04/creating-multi-game-highscore-lists/

**Comment by pyros2097** [comment]
Nice blog post comparing redis and arangodb. So we plan to use transactions to update the highscore list but checking the docs each transaction locks the collection so wont it make it non-scalable for a huge number of games. So I thought why not create a new collection for every game but then what are the collection limits in arangodb?

**Comment by jsteemann** [comment]
AFAIK there is no hard-coded limit for the number of collections in the ArangoDB code. 

However, each collection will require at least one active file descriptor while the server is running, at least when the collection is loaded and contains any data. Collections containing documents may need extra file descriptors. 
The operating system will probably limit the number of file descriptors by default to some low value (e.g. 256 or 1024. You can validate how much were configured by executing `ulimit -n` in the same shell / environment that arangod runs in. On Windows, the max. number of file descriptors the arangod process can use is limited to 2048.

Additionally, each collection will use some memory for indexes and book keeping. Index memory usage does not grow 100% proportionally with the number of documents in a collection. This is because the basic index memory allocations are not optimized for empty collections. 

Having many individual but small collections may therefore in total cost more memory than having just one or a few.

**Comment by jsteemann** [comment]
Closing as answered.
