### ISSUE TITLE
external v8

### ISSUE THREAD

**Issue by flosse** [arangodb/arangodb#1316]
Is it possible to use an external v8 build? Are there any config flags? (same question for zlib etc.)

**Comment by jsteemann** [comment]
Short answer: no

Long answer:
We previously had an optional to build using an external V8 library. We removed it in ArangoDB 2.4 because ArangoDB required an exact match V8 version and not just any V8. On many systems the default V8 packages were far too old, and building with the system packages therefore failed. We got several tickets opened because of the system V8 version not matching the one expected by ArangoDB.

At some point we removed the option altogether because it was easier and less error prone to use the V8 version bundled with ArangoDB. This also led to the removal of the option to use an external ICU library: as V8 now includes ICU, and V8 is bundled, ArangoDB will use the ICU bundled and built with its V8.

Then there's the 3rd party libraries libev and zlib. Those are also bundled and built with ArangoDB. There was an option to use an external libev before ArangoDB 2.4, but it was also removed when the other options were removed.

**Comment by flosse** [comment]
@jsteemann Thx for your answer.
The reason I'm asking: I'm going to pack arango for [nix](http://nixos.org/nix/) / [nixos](http://nixos.org/) where every dependency can be described uniquely (checked with sha256), so there wouldn't' be a "maybe it works" but a reproducible build :-)
So if there is a trick to use external dependencies, it would be nice to build it in a nix-way otherwise I'll pack it as big binary blob ;-)

**Comment by jsteemann** [comment]
@flosse: I see this would be working if all the required dependencies would be built with the correct version, too. But at the moment there is no way to tell ArangoDB's configure to use any external libraries. So it's probably better to go with the all-in-one blob.

And by the way, many thanks for building a nix package of ArangoDB!
