### ISSUE TITLE
Inconsistent db._create() syntax

### ISSUE THREAD

**Issue by AzuraMeta** [arangodb/arangodb#1318]
I attempted to use the third form of db._create:
db._create(collection-name, properties, type)

Example:
db._create("test", {}, "edge");

This works fine from arangosh. 
However, if I try to use it in a Foxx App (setup script), I get the following error:
[ArangoError 3005: failed to execute script File: scripts/setup.js Error: [ArangoError 10: usage: _create(\<name\>, \<properties\>)]]

Note: The other 2 versions of the function, with name and properties, or just name, seem to work fine.

**Comment by jsteemann** [comment]
It turned out that the 3-parameter version of `db._create()` was only supported from the ArangoShell. Because it was mentioned in the manual, I have now added the 3-parameter version for the server-side as well, meaning it can be used from within a Foxx app etc.

The fix will become available with 2.5.3.
