### ISSUE TITLE
Collection used as expression operand - how to avoid?

### ISSUE THREAD

**Issue by rotatingJazz** [arangodb/arangodb#1332]
I am getting this warning (2.4.3):

````
Warnings:

[1577], 'collection 'mycollection' used as expression operand'
````

I have a set of filters that may be optionally applied and I am doing something like this:
````
            LET byCity = []

            /* This block is optionally inserted in the AQL query by the server-side logic */
            LET byCity = (
                FOR p IN mycollection
                      /* Do stuff here */
                RETURN p
            )
            
            /* Remove empty list, find smaller */
            LET pools = (FOR i IN [byCity, mycollection]
                SORT LENGTH(i) ASC
                FILTER LENGTH(i) > 0
            RETURN i)

            /* Now, run the query over byCity or the full collection */
            FOR p IN pools[0]
                      /* Do stuff here */
            RETURN p
````

The query works but how can I restructure this to avoid the warning?

**Comment by jsteemann** [comment]
The warning is raised because of the part `FOR i IN [byCity, mycollection]`.
This will extract all documents from the two named collections and place them into the original list, so you'll effectively end up with something like `FOR i IN [ [ byCity1, byCity2, ... ], [ mycollection1, mycollection2, ... ] ]`.
This should work in general but is very inefficient because it will materialize all documents from the collections into the array. In case one of the collections contains a substantial number of documents this will become slow.
I think what you're actually looking for is to dynamically pick a collection, based on some runtime expression. 

This is not what AQL is very good at at the moment. The query execution plan and all optimizations are done *before* the query is executed. Picking a collection dynamically at runtime will prevent any optimizations for collection access (e.g. index usage). If somehow the decision which collection to use can be moved out of the query, the actual query could use just one collection (which can still be passed as a bind parameter to the query). This will remove the warning and make the query probably much more efficient. Still, a pre-decision needs to be made somehow to determine which collection to actually use in the query. 

There are a few options for this, with writing a server-side function which quickly determines the collection to use being the most efficient option.

**Comment by rotatingJazz** [comment]
Thank you very much @jsteemann ! Efficiency is of my concern and now I understand AQL better. I'll do the selection server side and keep AQL cleaner. :+1:
