### ISSUE TITLE
Question: preferred way to add dbservers to a production cluster?

### ISSUE THREAD

**Issue by nlac** [arangodb/arangodb#1335]
Hi, could you give me some hints about what is the preferred way to add further dbservers (and coordinators but that is less important) into a cluster running in production? An obvious goal is the minimal downtime and of course, no data loss.

What particulary makes me think is a note on the swagger ui, for the endpoint ```PUT /_api/collection/{collection-name}/properties```: 
"some other collection properties, such as type, isVolatile, *numberOfShards* or shardKeys cannot be changed once a collection is created."

**Comment by nlac** [comment]
I ask it because i think it can be a common scenario: let's say a production environment starts with a cluster having 4 physical dbserver - each collection is configured to have eg. 16 shards, 4/dbserver. Then, when the traffic and the stored data is massively growing, one may add +8 physical dbservers to the system.
The actual questions: 
* what will happen with the collections after the new dbservers have been added to the cluster? (the cluster plan has been modified to use all the 12 dbservers).
* won't be any data loss? 
* will the collections be re-balanced across all the clusters? 
* isn't it a problem that the number of shards isn't equal any more to the recommended sql(n_of_dbservers)?
* is the way it currently handled is final and ok?

**Comment by Dashue** [comment]
Interesting questions, I find myself wondering the same and unfortunately I can't say I've found much documentation around scaling more than that it's supposed to be "a matter of clicks".

**Comment by fceller** [comment]
We are currently finishing the Apache Mesos integration which will provide this.

**Comment by m0ppers** [comment]
For 3.0 most of the questions have been addressed and I will resolve the issue :)

When running the cluster on a cluster operating system which integrates with ArangoDB (currently DC/OS / Mesos) the UI will feature fancy up- and downscale buttons. A cluster OS integration (https://github.com/arangodb/arangodb-mesos-framework for mesos) can then take these numbers and launch more coordinators/dbservers.

These will integrate into the ArangoDB cluster. From there on the servers will be used for NEW collections/shards.

There is no AUTOMATIC rebalancing.

However you can manually trigger rebalancing and shards will be moved to the new servers then.

This can be done HOT without shutting down anything (however this may take a long while of course because there might be GBs to move between servers).

The numberOfShards key can still not be changed after creation. However it is perfectly fine to start with 4 dbservers and create collections with 16 shards.

So if you are in a cluster you should always take care to create enough shards so upscaling still makes sense (or you have many different collections).
