### ISSUE TITLE
more global objects

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1344]
Would it be possible to make everything that's sort-of-kind-of compatible with node's global objects also a global in Arango? The motivation would be to increase compatibility with npm packages.

Specifically, I'd be interested in using https://github.com/motdotla/dotenv which expects process and console being globals.

List of node's globals:
https://nodejs.org/api/globals.html

**Comment by pluma** [comment]
Fixed in 1edfcd3.

The following Node-compatible globals exist in ArangoDB:

* __dirname
* __filename
* console\* (added)
* exports
* module
* require
* process (added)
* Buffer\*\*

The following Node-specific globals are incompatible with ArangoDB:

* setTimeout
* clearTimeout
* setInterval
* clearInterval

\* Note that `console` in Foxx apps refers to the API-compatible Foxx console, which logs to the database instead of to stdout / disk.

\*\* I'm not entirely sure where `Buffer` gets injected, but it seems to always be there.

**Comment by CoDEmanX** [comment]
Doesn't ArangoDB's `internal` module provide implementations of timeout and interval functions?

**Comment by pluma** [comment]
There are only stub implementations. Those functions only work with an event loop, which ArangoDB doesn't provide.

**Comment by pekeler** [comment]
Nice - Thanks!
