### ISSUE TITLE
[2.5.3] Windows: HTTP API - incorrect path in errorMessage

### ISSUE THREAD

**Issue by clintwood** [arangodb/arangodb#1353]
As an example (curl or browser):
`http://localhost:8529/_db/test-db/_api/document/test1/15107652942` on a non-existent document handle returns an unnecessarily escaped path `\/_api\/document\/test1\/15107652942` in the json response body:
`{"error":true,"errorMessage":"document \/_api\/document\/test1\/15107652942 not found","code":404,"errorNum":1202}`

**Comment by fceller** [comment]
I believe that happens because

  http://www.json.org/

escapes "/" in JSON. I must say, I do not why that is necessary, but the string definition does contain "\/".

**Comment by jsteemann** [comment]
This is definitely valid JSON. The RFC mentions that the solidus must be escaped:
https://tools.ietf.org/html/rfc7159#page-8

**Comment by CoDEmanX** [comment]
I understand the following:
Every character can be escaped (in the form `\u0000`), but you would not do that for standard characters such as A-Z. 
Then there are a few shorthand escapes, so that it's not required to type `\u000D` for a line break: `\n` is the shorthand, which results in the same codepoint.
`/` can be escaped as `\/`, but not mandatory. It's seems to me like a fix for flawed browser engines, because </script> could occur inside a script block, but isn't the end tag (a string with this character sequence).
Someone mentioned embedding problems with XML/XHTML, so an escape might be necessary under certain circumstances. But it's definitely not a must to escape every single slash - especially in JSON in contrast to JS.
See: http://stackoverflow.com/questions/4264877/why-is-the-slash-an-escapable-character-in-json
Am 01.06.2015 1:13 nachm. schrieb Jan <notifications@github.com>:This is definitely valid JSON. The RFC mentions that the solidus must be escaped:
https://tools.ietf.org/html/rfc7159#page-8

**Comment by jsteemann** [comment]
JSON parsers should handle the escaped solidus just fine. At least the solidus is mentioned in the specs as an escapable character, and I am not aware of any counterexamples, with JSON parsers failing to unescape them.

**Comment by clintwood** [comment]
Thanks for taking a look at this but I'm not seeing this done for document `_id`s or for any document field values either so it looks inconsistent, hence me raising the issue...

In node/iojs/Chrome/IE/Firefox (admittedly recent versions) the json response body above does indeed parse correctly using `JSON.parse(...)` into:
```
{ error: true,
  errorMessage: 'document /_api/document/test1/15107652942 not found',
  code: 404,
  errorNum: 1202
}
```
Yet if you take the resulting json object and push it through `JSON.stringify(...)` you get:
```
{"error":true,"errorMessage":"document /_api/document/test1/15107652942 not found","code":404,"errorNum":1202}
```

I have to say I haven't seen `/` escaped that often, however, it's not an issue for me right now it just looked inconsistent.

**Comment by CoDEmanX** [comment]
Why does it say
/_api/document/test1/15107652942?
Shouldn't it be just the collection name and document key?

**Comment by jsteemann** [comment]
@clintwood : escaping the solidus is optional, so a `JSON.stringify()` is free to escape it or not.
@CoDEmanX : I think having the path component inside the error message does not provide a real benefit, and I would opt to have the path removed and simply opt for returning the error message "document not found" (which is the error message corresponding to error 1202).
Returning the path, the collection name or the document key does not seem to provide any benefit here. Removing these components from the error message will also make it more consistent with the error messages thrown inside the server (e.g. in Foxx etc.) where you would simply get a "document not found" error message, too.

**Comment by clintwood** [comment]
@jsteemann, understood, thanks for the reply.
