### ISSUE TITLE
NEIGHBORS not working in 2.6.0-alpha3

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1354]
This query worked until yesterday, before the update:
````
FOR c IN NEIGHBORS(categories, productCategorySort, "products/263741", "outbound") RETURN c
````

I can provide some test data, but maybe you can try to reproduce with random data, usually it returns a list with `vertex` and `edge` but now I get only `_key` values in a simple array. Donno what else from graph API might be affected...

Thanks!

**Comment by CoDEmanX** [comment]
Well, seems to do what the (devel) documentation says:
> NEIGHBORS(vertexcollection, edgecollection, startvertex, direction, edgeexamples, options):
> Returns _id values of all distinct neighbors that are directly connected to the vertex startvertex as an array.
It was different in 2.5 however, you probably want to set the option `includeData`:
https://docs.arangodb.com/devel/Upgrading/UpgradingChanges26.html
Am 01.06.2015 4:48 nachm. schrieb Razvan Grigore <notifications@github.com>:This query worked until yesterday, before the update:

FOR c IN NEIGHBORS(categories, productCategorySort, "products/263741", "outbound") LIMIT 2 RETURN c


I can provide some test data, but maybe you can try to reproduce with random data, usually it returns a list with vertex and edge but now I get only _key values in a simple array. Donno what else from graph API might be affected...

Thanks!

**Comment by jsteemann** [comment]
If it changed, then it should also be noted in the CHANGELOG...
Have to clarify with @mchacki whether the change is actually intentional or an unwanted side-effect.

**Comment by razvanphp** [comment]
Ok, then maybe you want to move more arguments into options (i.e. direction), like the general graph function already uses:
https://docs.arangodb.com/devel/Aql/GraphOperations.html

I just used `FOR` in `FOR` instead of `NEIGHBORS`, because of the significant speed difference, so I'm fine with any change anyway.

**Comment by jsteemann** [comment]
`NEIGHBORS` was improved in 2.6 as well, at least for many cases. `NEIGHBORS` in 2.6 will by default also return the document `_id`s only, same as `GRAPH_NEIGHBORS`. This can be changed by adding the option `{ includeData: true }` as mentioned above.

Have you tried in 2.6 whether a `FOR ... IN ... FOR ... IN ...` is still much faster than a `NEIGHBORS()` query?

**Comment by razvanphp** [comment]
I measured the difference now, the performance is comparable, but only without specifying a `LIMIT`.

When I add a limit on the edge collection (411081 documents) the `NEIGHBORS` takes the same amount of time ~2,2 s while the `FOR` takes only ~0.9 s.

Another downside of the new `NEIGHBORS` format is that now it only includes the vertexes, and not the edges anymore, and I need them in this case.

**Comment by jsteemann** [comment]
@razvanphp : yes, `NEIGHBORS` will currently not honor any `LIMIT` specified outside, so it will fully construct its result, which is then only used partially outside. This is true for all AQL functions at the moment. Regarding the result format of `NEIGHBORS`: @mchacki: was this change (NEIGHBORS not returning the connected edges anymore) intentional?

**Comment by mchacki** [comment]
@razvanphp The change NEIGHBORS does not return edges anymore was intentional.
NEIGHBORS should be only the distinct set of neighboring vertices.
We have modified the EDGES function to optionally include the vertices now, as the edges are not producing distinct sets.

So if you have a NEIGHBORS function before 2.6 like:

    NEIGHBORS(<vertexCollection>, <edgeCollection>, <vertex>, <direction>, <example>)

you can now (2.6) use:

    EDGES(<vertexCollection>, <edgeCollection>, <vertex>, <direction>, <example>, {includeVertices: true})

to get the exact same result as before.

Hope this solves your problem.
