### ISSUE TITLE
Foxx OAuth2 server implementation

### ISSUE THREAD

**Issue by itsezc** [arangodb/arangodb#13551]
The current implementation of `@arangodb/foxx/oauth2` only supports an OAuth 2 client, even though authentication in general is fully supported in Foxx, an OAuth 2 server is missing. Existing modules on NPM heavily rely on promises thus rendering them unusable in a Foxx env, making it challenging and cumbersome to create an OAuth server.

**Comment by pluma** [comment]
There's no universal solution for building your own OAuth 2 server, which is why Foxx doesn't provide an implementation out of the box. Providing a generic implementation would still leave the user with a lot of exposed wires they'd have to connect manually as well as the herculean task of writing your own frontend. I've implemented an OAuth 2 server in Foxx before but it's closed source and used the 2.8 API so it's nothing I can share, sadly. Looking at any of the many available OAuth 2 flow diagrams you can find on the Internet (and the [OAuth 2 spec](https://tools.ietf.org/html/rfc6749)) should point you in the right direction if you want to do it yourself, though.

Some general pointers:
* requests authorized with OAuth 2 always use "bearer" authentication
* auth tokens are always tied to a (third-party) client per user
* clients are identified by a public client ID and a private client secret (or API token)
* permissions are called "scopes" and you have to decide how granular you make them
* there can be more than one auth token for the same client and user, e.g. because they include different scopes
* OAuth 2 consists of both authentication (resolving the auth token to a user) and authorization (determining whether the granted scopes are sufficient for what the client attempts to do on the user's behalf and whether the user even has permission to do so)
* the `authorization_code` grant type is the easiest to implement and supported by most OAuth 2 clients

That said, if you are going to implement an OAuth 2 server you probably want to implement OpenID Connect, which builds on OAuth 2 and fills in some of the gaps.

**Comment by Simran-B** [comment]
Closing as answered and because there is no intention from our side to provide a generic implementation.
