### ISSUE TITLE
Can the batch api used together with stream transactions?

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#13552]
Hi, 
Is the batch api supposed to work with stream transactions?
"x-arango-trx-id" seems to be ignored inside the multipart or the batch request itself. (tried both)
Is the scenario even supported? I'd say rolling back a batch atomically should be. (Lots of gharial operations for example)

C# code with a transaction wrapping a batch - the transaction does not get comitted
```
var trx = await Arango.Transaction.BeginAsync("test", new ArangoTransaction
{
    Collections = new ArangoTransactionScope
    {
        Write = new List<string> { "test" }
    }
});
var batch = Arango.Transaction.CreateBatch(trx);

var r1 = Arango.Document.CreateAsync(batch, "test", new Entity
{
    Key = "1",
    Name = "a"
});

var r2 = Arango.Document.CreateAsync(batch, "test", new Entity
{
    Key = "2",
    Name = "b"
});

await Arango.Transaction.ExecuteBatch(batch);
await Arango.Transaction.AbortAsync(trx);
```

resulting multipart content
```
--ArangoBatch
Content-Type: application/x-arango-batchpart
x-arango-trx-id: 19456
Content-Id: 8875952a-b190-4742-b39d-b825e7a780a6

POST /_db/CI-51f97c4a-f0b8-4cf2-895a-3faa182918cf-test/_api/document/test HTTP/1.1

[{"_key":"1","Name":"a","Value":0}]

--ArangoBatch
Content-Type: application/x-arango-batchpart
x-arango-trx-id: 19456
Content-Id: 45c4124e-ffef-4abe-b9c8-eadd1882fa48

POST /_db/CI-51f97c4a-f0b8-4cf2-895a-3faa182918cf-test/_api/document/test HTTP/1.1

[{"_key":"2","Name":"b","Value":0}]

--ArangoBatch--
```

**Comment by Simran-B** [comment]
What driver is this?

According to engineering, it should work if for every contained request in the batch the transaction header is set individually and if all operations in the batch are supported by streaming transactions. This combination is apparently not tested however.

**Comment by coronabytes** [comment]
My own driver
https://github.com/coronabytes/dotnet-arangodb

Test (not exactly the same - and it's writte so it "works"):
https://github.com/coronabytes/dotnet-arangodb/blob/master/Core.Arango.Tests/BatchTest.cs

It seems to me x-arango-trx-id is just ignored inside the batch part headers.

**Comment by Simran-B** [comment]
After some testing with and without batching, I come to the same conclusion that the `x-arango-trx-id` header field is ignored. The batched operations are executed individually, independent of the stream transaction.

_batch.txt_

```
--ArangoBatch
Content-Type: application/x-arango-batchpart
x-arango-trx-id: <trxId>
Content-Id: 1

POST /_db/_system/_api/document/test HTTP/1.1

[{"_key":"1","Name":"a","Value":0}]

--ArangoBatch
Content-Type: application/x-arango-batchpart
x-arango-trx-id: <trxId>
Content-Id: 2

POST /_db/_system/_api/document/test HTTP/1.1

[{"_key":"2","Name":"b","Value":0}]

--ArangoBatch--
```

_stream_batch.sh_

```bash
#!/bin/bash
HOST=http://localhost:9930
TRX_ID=$(curl -sS -X POST --data '{"collections":{"write":["test"]}}' $HOST/_api/transaction/begin | jq --raw-output '.result.id')
echo ""
echo "Transaction ID: $TRX_ID"
RESPONSE=$(sed -e "s/<trxId>/$TRX_ID/g" batch.txt | curl -sS --dump-header header.tmp -X POST --data-binary @- --header 'Content-type: multipart/form-data; boundary=ArangoBatch' $HOST/_api/batch)
echo ""
echo "Server Response:"
cat header.tmp
echo "$RESPONSE"
sleep 1
echo ""
# Bulk document operations don't return a global error in case of conflicts!
#if grep -q -i -E 'X-Arango-Errors: [0-9]+' header.tmp; then
if [[ $RESPONSE == *"\"error\":true"* ]]; then
  echo "Error in batch request, aborting transaction..."
  curl -sS -X DELETE $HOST/_api/transaction/$TRX_ID
else
  echo "Committing transaction..."
  curl -sS -X PUT $HOST/_api/transaction/$TRX_ID
fi
```

```
> ./stream_batch.sh

Transaction ID: 1921

Server Response:
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
Content-Type: multipart/form-data; boundary=ArangoBatch
Server: ArangoDB
Connection: Keep-Alive
Content-Length: 647

--ArangoBatch
Content-Type: application/x-arango-batchpart
Content-Id: 1

HTTP/1.1 202 Accepted
Server:
Connection: Close
Content-Type: application/json; charset=utf-8
Content-Length: 50

[{"_id":"test/1","_key":"1","_rev":"_cIyqwxm---"}]
--ArangoBatch
Content-Type: application/x-arango-batchpart
Content-Id: 2

HTTP/1.1 202 Accepted
Server:
X-Arango-Error-Codes: {"1210":1}
Connection: Close
Content-Type: application/json; charset=utf-8
Content-Length: 143

[{"error":true,"errorNum":1210,"errorMessage":"unique constraint violated - in index primary of type primary over '_key'; conflicting key: 2"}]
--ArangoBatch--

Error in batch request, aborting transaction...
{"code":200,"error":false,"result":{"id":"1921","status":"aborted"}}
```

- Stream transaction is started
- The first document is inserted successfully
- The second fails because of a duplicate key
- The transaction is aborted
- First document: *exists*

_stream.sh_ (no batching)

```bash
#!/bin/bash
HOST=http://localhost:9930
TRX_ID=$(curl -sS -X POST --data '{"collections":{"write":["test"]}}' $HOST/_api/transaction/begin | jq --raw-output '.result.id')
echo ""
echo "Transaction ID: $TRX_ID"
RESPONSE1=$(curl -sS -X POST --data '{"_key":"1","Name":"a","Value":0}' --header "x-arango-trx-id: $TRX_ID" $HOST/_db/_system/_api/document/test)
RESPONSE2=$(curl -sS -X POST --data '{"_key":"2","Name":"b","Value":0}' --header "x-arango-trx-id: $TRX_ID" $HOST/_db/_system/_api/document/test)
echo ""
echo "Server Response 1:"
echo "$RESPONSE1"
echo ""
echo "Server Response 2:"
echo "$RESPONSE2"
sleep 1
echo ""
if [[ $RESPONSE1 == *"\"error\":true"* || $RESPONSE2 == *"\"error\":true"* ]]; then
  echo "Error in requests, aborting transaction..."
  curl -sS -X DELETE $HOST/_api/transaction/$TRX_ID
else
  echo "Committing transaction..."
  curl -sS -X PUT $HOST/_api/transaction/$TRX_ID
fi
```
```
> ./stream.sh

Transaction ID: 1937

Server Response 1:
{"_id":"test/1","_key":"1","_rev":"_cIyuCZK---"}

Server Response 2:
{"code":409,"error":true,"errorMessage":"unique constraint violated - in index primary of type primary over '_key'; conflicting key: 2","errorNum":1210}

Error in requests, aborting transaction...
{"code":200,"error":false,"result":{"id":"1937","status":"aborted"}}
```

- Stream transaction is started
- First document is inserted successfully
- Second one fails because of a duplicate key
- Transaction is aborted
- No first document in the database as expected

I studied the batch request handling code for a while and can confirm that no header fields except `Content-Type` and `Content-Id` appear to be forwarded ([code](https://github.com/arangodb/arangodb/blob/3ea214be59191a189f6565d48d1d65e3cb948695/arangod/RestHandler/RestBatchHandler.cpp#L508-L536)). This mainly affects the transaction ID field and `If-Match` / `If-None-Match` for single document operations.

I talked with jsteemann from engineering and he believes that the batch API was introduced around ArangoDB v1.1 or v1.2, mainly to allow for bulk document operations, and that driver support is probably low. The batch API isn't really maintained anymore and predates [multi-document support](https://www.arangodb.com/docs/stable/http/document-working-with-documents.html#bulk-document-operations) in the document API that was added in v3.0. There aren't that many cases where the batch API is still useful, and we decided to [deprecate](https://github.com/arangodb/docs/pull/671) it from v3.8.0 on.

**Comment by coronabytes** [comment]
ok, I tossed the batch implementation in the driver
