### ISSUE TITLE
cant reach cluster management on web interface

### ISSUE THREAD

**Issue by gregzuro** [arangodb/arangodb#1356]
https://docs.arangodb.com/Sharding/HowTo.html 

says: "Note: Once you switch cluster.disable-dispatcher-interface to false, the usual web front end is automatically replaced with the web front end for cluster planning."

First, 'disable-dispatcher-interface' is not a valid option:

```
/usr/sbin/arangod: unrecognized option 'cluster.disable-dispatcher-interface'
Did you mean one of these? --cluster.disable-dispatcher-kickstarter  --cluster.disable-dispatcher-frontend
2015-06-01T19:08:42Z [21141] ERROR cannot parse config file '/etc/arangodb/arangod.conf': illegal option
2015-06-01T19:08:42Z [21141] FATAL cannot parse command line arguments
```

If I, instead, set ```disable-dispatcher-frontend = false```, then restart, then go to ```http://localhost:8529/```, I am taken to: ```http://localhost:8529/_db/_system/_admin/aardvark/standalone.html```,
which does not allow me to configure any cluster-related things.

If I try replacing ```standalone``` with ```cluster``` in that last URL, then I get the cluster management screen.

This latter step isn't documented anywhere that I've seen.

After configuring the cluster and launching, ```http://localhost:8529/``` still goes to ```http://localhost:8529/_db/_system/_admin/aardvark/standalone.html``` and there is no reference to cluster things anywhere.

**Comment by pluma** [comment]
`http://localhost:8529/` should 301 (Moved Permanently) redirect to `http://localhost:8529/_db/_system/_admin/aardvark/index.html` which should then 302 (Found) redirect to either `standalone.html` or `cluster.html` depending on whether it's running in cluster mode. Manipulating the URL yourself shouldn't be necessary.

Apparently it's using a 301 redirect instead of a 302. I'm assuming you already visited the web admin frontend in the browser before activating cluster mode, so the browser remembers the 301 redirect and doesn't hit the `index.html` route at all. That's a bug.

**Comment by pluma** [comment]
Note that there's no way for ArangoDB to fix this if you've already been redirected in the browser before. You may need to kill the browser cache, which depends on the browser you're using.
