### ISSUE TITLE
Link https://docs.arangodb.com/Installing/README.html is broken

### ISSUE THREAD

**Issue by abelyaevskiy** [arangodb/arangodb#1370]
I followed link https://docs.arangodb.com/Installing/README.html named "User Manual" from section "More Information" on main project's github page https://github.com/arangodb/arangodb and got  "The requested URL /Installing/README.html was not found on this server." error

**Comment by jsteemann** [comment]
I think instead of https://docs.arangodb.com/Installing/README.html, the link should rather be https://docs.arangodb.com/Installing/index.html, or even simpler:  https://docs.arangodb.com/Installing/

Replacing *README.html* with *index.html* or omitting it will also fix other broken links of the same sort. 
There has been a change in the links setup a while ago, and theoretically *README.html* should behave the same as *index.html*. Obviously this is not the case, so I will have it fixed for the arangodb.com website.

**Comment by 13abylon** [comment]
Every README.html is now redirected to index.html as soon as the documentation ist build
