### ISSUE TITLE
Integrating ArangoDB with Meteor/Apollo

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1376]
Nothing on the [roadmap](https://www.arangodb.com/roadmap/) yet, but as mentioned here: 

https://www.youtube.com/watch?v=Ew7KcjJX-68

there will apparently support for Meteor in future version - how awesome is that?!

Is this something to be expected for ArangoDB 3.x in a year or so, or is it more of a short-term goal?

**Comment by pekeler** [comment]
Oh, nice!

**Comment by leosa83** [comment]
:+1:

**Comment by mikeifomin** [comment]
Any news about? Any code draft/snippet for meteor?

**Comment by dothebart** [comment]
We're watching it closely but currently you are focused on other things.

**Comment by friday** [comment]
There's also work from the Meteor side on GraphQL support, which ArangoDB supports now via Foxx. That's not a perfect substitute for performance and feature parity, but it could be more fitting for many meteor devs.

**Comment by mikeifomin** [comment]
@friday yes GraphQL is future of webdev and the future of the Meteor too.

The main issue is with "true" reactivity. Like with mongo oplog or RethinkDB.
I mean for now the only one way to make reactive changes for ArandoDB is to pool(re-fetch) a database request. 

With such pooling approach a developer select the golden mean between a database load and frontend responsiveness.
But approach with reading oplog in MongoDB showed itself critical in a real production with huge amount of a database writes. Mainly because each node instance reads all oplog.
And incoming changes in the Meteor [ddp-batching](https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.3.3-ddp-batching-beta.0) trying to solve this performance-oplog problem for huge production.

So my question was "Is there a implemented method in ArangoDB to subscribe on the database changes?"
- - - 
Now with regards to issues:
I found some some repo https://github.com/kantele/k-livedb-arango. Not sure about a stability of it.

There is one more interesting layer for solve the problem of multi-data-sources (read multi database)
 [Apollostack](https://medium.com/apollo-stack/introducing-the-apollo-graphql-data-stack-5d005312cbd0) (by Meteor team)

**Comment by pluma** [comment]
Just cross-referencing #602 because it is relevant for anyone asking about plans on supporting reactivity in ArangoDB (live queries, streams etc).

**Comment by dothebart** [comment]
@mikeifomin there has been some chatter with the author over at the google group: https://groups.google.com/forum/#!topic/arangodb/3YD5fuS-UW8

**Comment by tcastelli** [comment]
Any update on the matter?

**Comment by pluma** [comment]
@tcastelli It seems clear at this point that Meteor's [long-term goal is based on Apollo instead of developing case-by-case integrations](https://github.com/meteor/meteor/blob/devel/Roadmap.md#graphql-data-sql-rest-performance) for each database.

There are currently three ways to integrate ArangoDB with Apollo:

1. You can use the Apollo client against a GraphQL service directly (see [https://docs.arangodb.com/3.1/Manual/Foxx/GraphQL.html](Foxx documentation) for using GraphQL in ArangoDB)
2. You can integrate the [Apollo server](https://github.com/apollostack/graphql-server) with ArangoDB itself by using [arangojs](https://github.com/arangodb/arangojs) directly in your schema resolvers.
3. You can write your own custom REST endpoints (using Foxx) and use those in your schema resolvers instead of using arangojs.

As far as I can tell there is no way to provide a general-purpose solution for Apollo but with help from the community we could provide a guide demonstrating these scenarios.

---

Addendum: This issue is originally about a direct Meteor integration but I think that has now become irrelvant.

There were some community-supported Meteor integrations for other databases but because Meteor originally announced they wanted to offer their own integrations (which now seems to have been superseded by switching to Apollo) many of them seem to be unmaintained: at a quick glance, neither MySQL, CouchDB nor Postgres have seen any commits since 2015.

If there is not enough interest in the Meteor community in having direct integrations for MySQL, CouchDB or Postgres, I strongly doubt ArangoDB would fare any better. I think it's worth keeping an eye on Apollo and if any of you have any ideas how we could make ArangoDB/Foxx easier to use with Apollo, I'd love to hear your comments.

**Comment by dothebart** [comment]
At the current state its safe to say that we can't put resources in this. We will support community projects if somebody wants to start an implementation, but for now we will only support [arangojs](https://github.com/arangodb/arangojs#arangodb-javascript-driver)

Therefore I will close this ticket as `won't fix`.
