### ISSUE TITLE
Maximum number of DB connections？

### ISSUE THREAD

**Issue by MrLiuhhh** [arangodb/arangodb#13819]
## My Environment

* __ArangoDB Version__:        3.7.5
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter 
* __Operating System__:        Suse 12 x86

## Component, Settings
__Problem__:
Hi, 
    I'm trying to set the maximum number of connections to the database through the command parameters during the startup phase. 
    However, I did not find the relevant parameter settings,just find this `--network.max-open-connections` in the [url](https://www.arangodb.com/docs/3.7/programs-arangod-network.html). 
    Does the database have the maximum number settings of connections? And Can I limit the number of sessions of a single user and the number of sessions of different services?

Thanks~

**Comment by dothebart** [comment]
hm, any specific reason why you want to do this inside of arangodb? 
You should be able to do this using iptables, as https://unix.stackexchange.com/questions/309387/iptables-limit-inbound-connections-to-docker-container explains?

**Comment by MrLiuhhh** [comment]
> hm, any specific reason why you want to do this inside of arangodb?
> You should be able to do this using iptables, as https://unix.stackexchange.com/questions/309387/iptables-limit-inbound-connections-to-docker-container explains?

hi，We want to use arangodb for our project recently and want to know some specifications. Because some relational databases usually indicate the maximum number of connections, but I can't find the description in arangodb docs.
For the limit the number of sessions or different service，we just want to whether arangodb has such a capacity. If it has ,it is better~

**Comment by dothebart** [comment]
ArangoDB uses [Boost ASIO](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio.html) for connection management; This solves the [C10k Problem](https://en.wikipedia.org/wiki/C10k_problem) for ArangoDB.

Another important fact is, that the HTTP/2 and VST protocols allow async requests internally, so the number of active tcp connection can't be related to the workload in terms of jobs active in the system anymore.

To sumarize, no, ArangoDB doesn't have this feature, since its not a good way to control the load on the system anyways. 

However, you should strive to work with connection keepalive to keep the cost of *establishing* new connections as low as possible.

**Comment by MrLiuhhh** [comment]
> ArangoDB uses [Boost ASIO](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio.html) for connection management; This solves the [C10k Problem](https://en.wikipedia.org/wiki/C10k_problem) for ArangoDB.
> 
> Another important fact is, that the HTTP/2 and VST protocols allow async requests internally, so the number of active tcp connection can't be related to the workload in terms of jobs active in the system anymore.
> 
> To sumarize, no, ArangoDB doesn't have this feature, since its not a good way to control the load on the system anyways.
> 
> However, you should strive to work with connection keepalive to keep the cost of _establishing_ new connections as low as possible.

I got it.I will close this issue.
Thank you very much for your patience~
