### ISSUE TITLE
Change how documentation links work

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1390]
Author
    ArangoDB GmbH
Contributors
    No contributors 
Links

        Download API Documentation -> http://127.0.0.1:8529/_db/_system/_admin/aardvark/foxxes/docu/testmailgun

Only gives a json document.

**Comment by pluma** [comment]
This doesn't sound like something app-specific. What exactly is the expected behaviour? I think that URL still points to the old Swagger code, so if it gives back a JSON document now, that's all it ever did.

In that case the URL should instead point to the new Swagger JSON file, i.e. I need to update the URL in the frontend.

**Comment by pluma** [comment]
I think that link is currently not very helpful at all. Who needs the generated JSON as an explicit link in the UI? @mchacki can I just replace that link with a link to the API Documentation standalone page?
