### ISSUE TITLE
Write lock during index removal

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#13984]
## My Environment

* __ArangoDB Version__:        3.7.10
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   systemd
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Total RAM in your machine__:        128 GB
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Document write during index removal

__Dataset__:
Any collection with a few million documents, leading to a relatively long index removal time (> 10mn)

## Steps to reproduce

1. trigger (from aardvark) the deletion of an existing index, in collection C
2. try to write (using ArangoJS) a document to his collection C
3. a write lock prevents writing during the time of index deletion

__Problem__:
On large collections, index removal time may reach tens of minutes, during the which collection cannot record new documents. On a write-heavy production setup, this means that removing an index implies a quite long downtime.

__Expected result__:
Ability to write to a collection while indexes are being removed

Thank you for considering this,
Greetings,

Mathias

**Comment by jsteemann** [comment]
@matcho : potentially this just got fixed in 3.7.11, via https://github.com/arangodb/arangodb/pull/13711

The changelog entry for this PR was:

> * When dropping a collection or an index with a larger amount of documents, the
>  key range for the collection/index in RocksDB gets compacted. Previously, the
>  compaction was running in foreground and thus would block the deletion
>  operations.
>  Now, the compaction is running in background, so that the deletion operations
>  can return earlier.
>  The maximum number of compaction jobs that are executed in background can be
>  configured using the new startup parameter
>  `--rocksdb.max-parallel-compactions`, which defaults to 2. 

3.7.11 has not yet been released, but it would be cool if you could eventually check whether this fix already helps in your case too. There should already be 3.7 nightlies (community edition, not recommend for production) available for testing at https://download.arangodb.com/nightly/3.7/index.html, in case you are willing to try this in a test environment.

**Comment by matcho** [comment]
Hi @jsteemann 

Great news ! You read my mind :)

Just tested the 3.7.11-nightly.20210415 and it seems to work, though aardvark does not show the blue "deleting index" label on collections panel anymore; I guess it's expected because if it is non-blocking, then it's not necessary to point out that an index is being deleted. Still, a "pending/running administration jobs" list in aardvark would be nice, but that's another topic.

We'll run more tests when 3.7.11 is out but this looks great !

**Comment by jsteemann** [comment]
@matcho : I guess the label could still be shown, but only for a very small amount of time, so it is likely missed by the web UI.
The reason is that the index deletion normally is pretty quick even for large indexes. For larger collections we simply dispatch a DeleteRange(...) command to RocksDB, which does not do a physical cleanup of the index data, but simply "remembers" them to be invalid. The physical cleanup is then done eventually, when the data ranges are compacted.

The compaction is what can be take a long to time to finish. 
The previous behavior was to perform this compaction under a lock that also prevented the modification of the list of indexes, which is obviously undesired.
Now we are executing the compaction in background, without holding that lock.

For larger collections I would guess that the fraction of time for index deletion is less than 1% and that compaction amounts for 99+% of time. So very likely the actual index deletion is not seen by the web interface as it is rather quick.
You are right, there is currently no list of pending/currently running compactions anywhere, so the fact that a compaction is still ongoing is somewhat hidden.

I will now try to add metrics for the compactions so that it can at least be tracked via that easily. 3.8 will allow peeking into server metrics via the web UI, so I hope this will help.

**Comment by matcho** [comment]
OK, I understand the behavior better now. Thank you very much !
Feel free to close ticket, I guess.
