### ISSUE TITLE
Search for documents filtering from dates

### ISSUE THREAD

**Issue by fmsouza** [arangodb/arangodb#1400]
I searched in the online documentation and couldn't find anything about search dates in the database, even through AQL.

I have a collection where the data is inserted around every 20 seconds, and it contains it's last update time. I need to retrieve the most recent data for given indexes. How can I do that? Am I able to do it with ArangoDB? My application is written in node.js.

**Comment by CoDEmanX** [comment]
There are some AQL date functions, mainly to convert between different representations:

https://docs.arangodb.com/Aql/DateFunctions.html

There is also stated, that dates are either stored as numbers (microseconds since January 1st 1970), or as strings like "2014-05-07T14:19:09.522Z". There is no Date type, because there is none in JSON.

A numeric date representation can be sorted by its value. Date strings can be sorted alphabetically because of their format `year-month-dayThour:minute:second.msZ` - the character "2" comes after "1" (0x32 > 0x31) etc.

Thus, a simple SORT DESC should do the trick. If you want all records up to a certain date, a conversion to a numeric format is required (of the stored dates as well as the date for the filter criterion).

**Comment by fceller** [comment]
@fmsouza 

You need to create a collection and add a skip-list index on your date attribute. Store the attribute as suggested by @CoDEmanX 

For example (arangosh):

db._create("ticks");
db.ticks.ensureSkiplist("date");
db.ticks.save({ date: 123456791 });
db.ticks.save({ date: 123456790 });

And then use AQL to query for the TOP 5:

db._query("FOR u IN ticks SORT u.date DESC LIMIT 5 RETURN u").toArray()

**Comment by fmsouza** [comment]
Thank you very much, guys. I'll try this.

Em sex, 3 de jul de 2015 04:47, Frank Celler <notifications@github.com>
escreveu:

**Comment by CoDEmanX** [comment]
I was wrong about `>`, `>=`, `<` and `<=` searches, you don't need to convert anything as long as both dates are in iso 8601 format and share the same UTC offset (timezone differences).

You can simply `FILTER doc.date > "2015-07-01T00:00:00.000Z"` or actually `"2015-07-01"`, because every timestamp will be greater than that date (no need to write out a bunch of zeros).

If your timestamps are in different timezones however, a conversion will be required. Here's an example how to get utc+00:00 timestamp from a utc+02:00 timestamp:

    LET localtime = "2015-07-04T20:15:00.000+0200"
    RETURN {
        Germany_DST: localtime,
        UTC: DATE_ISO8601(localtime)
    }

Result (2 hours subtracted for Zulu time):

    {
        "Germany_DST": "2015-07-04T20:15:00.000+0200",
        "UTC": "2015-07-04T18:15:00.000Z"
    }

**Comment by fmsouza** [comment]
Oh. Awesome! Thank you CoDEmanX :D

**Comment by CoDEmanX** [comment]
@fceller: BC dates like "-753" will actually fail in comparisons and not sort properly (negative dates < positive dates, but order is reversed among negative dates), and the behavior of `DATE_*` functions is a bit odd:

`DATE_ISO8601()` throws an error for `"-2012-01-01T00:15:00.000+02:00"`, but accepts `-2012-01-01` **although the minus is not preserved** and `"-002012-01-01T00:15:00.000+02:00"` works just fine. `-00year` and `+00year` appear to be the [correct notations](https://de.wikipedia.org/wiki/ISO_8601#Geltungsbereich_der_Jahreszahlen) if dates before 1583 are used, thus `-2012-01-01` should actually fail, shouldn't it?

`DATE_TIMESTAMP()` returns `null` if the input is invalid, but should actually throw an error like `DATE_ISO8601()` and also ignores the minus for an badly formatted date like `-0753`:

  ```
return [date_iso8601(date_timestamp("-0753")), date_iso8601(date_timestamp("-000753-01-01"))]
  [
    "0753-01-01T00:00:00.000Z",
    "-000753-01-01T00:00:00.000Z"
  ]
```

**Anyway**: It works fine if the proper formatting for negative years is used and the date is converted to milliseconds since 1970-01-01:

```
for d in [
        {ms: date_timestamp("-000001"), year: "1 BC"},
        {ms: date_timestamp("-000753-01-01"), year: "753 BC"},
        {ms: date_now(), year: CONCAT(date_year(date_now()), " AD")}
    ]
sort d.ms
return d
```
Result:
```
[
  {
    "ms": -85929552000000,
    "year": "753 BC"
  },
  {
    "ms": -62198755200000,
    "year": "1 BC"
  },
  {
    "ms": 1436391996556,
    "year": "2015 AD"
  }
]
```
