### ISSUE TITLE
Sorting with different sort directions and skiplist not possible ? 

### ISSUE THREAD

**Issue by nvdnkpr** [arangodb/arangodb#1404]
I read in the documentation that when using a skiplist index a sorting for different directions is not using the skiplist index. 

One of the typical but simpler examples would be sorting by age (descending) and name (ascending) in the same query to show a list of names by ages then names. How would one model (and achieve a good performance) without using an index ?

**Comment by fceller** [comment]
@nvdnkpr do you know where you did read about this? I'm asking because we did a lot of improvements in this area and newer versions support skip-list with different sort directions.

For example:

```
var explain = require("org/arangodb/aql/explainer").explain;
arangosh [_system]> explain("FOR u IN test SORT u.age DESC LIMIT 10 RETURN u");
Query string:
 FOR u IN test SORT u.age DESC LIMIT 10 RETURN u

Execution plan:
 Id   NodeType         Est.   Comment
  1   SingletonNode       1   * ROOT
  7   IndexRangeNode      0     - FOR u IN test   /* reverse skiplist index scan */
  5   LimitNode           0       - LIMIT 0, 10
  6   ReturnNode          0       - RETURN u

Indexes used:
 Id   Type       Collection   Unique   Sparse   Selectivity Est.   Fields   Ranges
  7   skiplist   test         false    false                 n/a   `age`    [  ]

Optimization rules applied:
 Id   RuleName
  1   use-index-for-sort
  2   remove-unnecessary-calculations-2
```

and

```
var explain = require("org/arangodb/aql/explainer").explain;
arangosh [_system]> explain("FOR u IN test SORT u.age ASC LIMIT 10 RETURN u");
Query string:
 FOR u IN test SORT u.age ASC LIMIT 10 RETURN u

Execution plan:
 Id   NodeType         Est.   Comment
  1   SingletonNode       1   * ROOT
  7   IndexRangeNode      0     - FOR u IN test   /* skiplist index scan */
  5   LimitNode           0       - LIMIT 0, 10
  6   ReturnNode          0       - RETURN u

Indexes used:
 Id   Type       Collection   Unique   Sparse   Selectivity Est.   Fields   Ranges
  7   skiplist   test         false    false                 n/a   `age`    [  ]

Optimization rules applied:
 Id   RuleName
  1   use-index-for-sort
  2   remove-unnecessary-calculations-2
```

**Comment by nvdnkpr** [comment]
Hello Frank,
I read it [here](https://docs.arangodb.com/IndexHandling/IndexBasics.html) in the first paragraph after the code example
```
FILTER doc.value1 == ...
FILTER doc.value1 < ...
FILTER doc.value1 > ...
FILTER doc.value1 > ... && doc.value1 < ...
...
```
_In order to use a skiplist index for sorting, the index attributes must be specified in the SORT clause of the query in the same order as they appear in the index definition. **Sort orders cannot be mixed, i.e. the sort orders specified in the SORT clause must all be either ascending (optionally ommitted as ascending is the default) or descending.**_

I tested the index and the sorting with the names data you provide and it worked. I created an indes for ```name.last``` and ```name.first``` and created a query first sorting "DESC" by last name and then "ASC" by first name. Using EXPLAIN in the AQL Editor it showed me that the index was used properly.

I also removed the ```name.first``` part and it still worked, since it was created in this order.

I think that the paragraph that I was citing is a little bit outdated :smile:

**Comment by fceller** [comment]
Thanks for spotting it. It is indeed outdated.

**Comment by CoDEmanX** [comment]
> Thanks for spotting it. It is indeed outdated.
I'm not sure how to read this paragraph. It seems to be talking about multi-attribute indexes.
The statement about sort orders might actually mean that you cannot have different sort orders for a combined index.
E.g. `db.example.ensureSkiplist("a", "b");` will index the combination of fields `a` and `b`. If I understand correctly, it can be utilized if the user queries for `a` or `a and b` (as long as both are either ASC or DESC), but not `b` (all or leftmost fields in the order the indexed fields were defined).

**Comment by CoDEmanX** [comment]
I created some test data, added a skiplist index for `fields: ["a", "b"]` and tried to sort in opposing directions and it is actually supported:

```
Query string:
 for d in test
     sort d.a desc, d.b asc
     return d

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexRangeNode       3     - FOR d IN test   /* skiplist index scan */
  3   CalculationNode      3       - LET #1 = d.`a`   /* attribute expression */   /* collections used: d : test */
  4   CalculationNode      3       - LET #3 = d.`b`   /* attribute expression */   /* collections used: d : test */
  5   SortNode             3       - SORT #1 DESC, #3 ASC
  6   ReturnNode           3       - RETURN d

Indexes used:
 Id   Type       Collection   Unique   Sparse   Selectivity Est.   Fields   Ranges
  7   skiplist   test         false    false                 n/a   `a`, `b`     [  ]

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-up-2
  3   use-index-for-sort
```

Not supported is `SORT d.b` and `SORT d.b, d.a` in whatever direction, because the combined index is defined as `["a", "b"]`, not `["b", "a"]`. If there were 3 fields in the index like `["a", "b", "c"]`, one could `SORT d.a, d.b, d.c` or `SORT d.a, d.b` or `SORT d.a`, but nothing else (`SORT d.b, d.c` would not use the index).

**Comment by jsteemann** [comment]
Using the skiplist index to retrieve documents in ascending or descending index order is definitely possible.
However, it is not possible to use different sort orders for the same index in a single query when the index is a combined index.
For example, if the index is on `["a", "b"], then using `SORT a ASC, b DESC` will **not** use the index. `SORT a ASC, b ASC` will use it, and `SORT a desc, b DESC` will use it too.
So the cited paragraph only applies to using different sort orders for the attributes of a combined skiplist index in a single query.

**Comment by CoDEmanX** [comment]
@jsteemann: `use-index-for-sort` is applied if you mix sort orders however, so the index seems to be partially used at least (probably the first sort on `a`, but not the second on `b`, otherwise `remove-unnecessary-calculations-2` would be applied like if it is if sort order is the same on all indexed fields).

I wonder what it means performance-wise. I assume it would be quite fast if a `b` attribute is rare or has the same value within the group of records with the same `a` attribute.

**Comment by jsteemann** [comment]
@CoDEmanX : yes, `use-index-for-sort` is still applied in this case, but there will still be an extra sort step (as can be seen by the `SortNode` in the execution plan). The extra sort step may still be expensive, at least it will be more expensive than using an index-only scan (which is not possible in this case).

However, using the index here before the extra sort step can still can speed things up (at least it did in my quick tests). I guess this is due to better locality of the to-be-sorted elements.

**Comment by jsteemann** [comment]
I have updated the docs (see above commit). Hope it's easier to understand now.
