### ISSUE TITLE
3.4.2.1-Cross-Site-Scripting

### ISSUE THREAD

**Issue by doroniz** [arangodb/arangodb#14073]
Hi, I came across this report and I do not find a mention of it here does anyone know if this has been addressed, or is it still relevant?

https://packetstormsecurity.com/files/151724/ArangoDB-Community-Edition-3.4.2-1-Cross-Site-Scripting.html

Thanks

**Comment by dothebart** [comment]
3.4.2-1 is from Feburary 2019 and pretty outdated.
3.4 and 3.5 have already run out of official support for a while. The currently supported versions are 3.6 and 3.7, with 3.8 to be released soon.
The particular error has been fixed in some follow-up release to 3.4.2-1.
Do you mind trying with a currently supported release? The latest stable releases at the moment should be 3.6.13 and 3.7.10.
Thanks.
