### ISSUE TITLE
Search for words with dots by prefix

### ISSUE THREAD

**Issue by Minstel** [arangodb/arangodb#14201]
## My Environment

* __ArangoDB Version__:      ArangoDB 3.7.10 [linux] 64bit
* __Storage Engine__:           RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
Searching for words that contain dots (like filenames) by prefix.

__AQL query (if applicable)__:
```
FOR item IN FULLTEXT('files_collection', 'data', 'prefix:some_file.ex'))
RETURN item
```

__Problem__:
I tryed to use fulltext search to look for filenames and stumbled on issue that if prefix has dot, it can not find anything. As I now understand from issue https://github.com/arangodb/arangodb/issues/13138, that's due to the way fulltext index works.
What is the most efficient way to still make this work?

**Comment by Simran-B** [comment]
Full-text tokenization gets rid of characters that are considered word boundaries, so this is not going to work.

What you can do is
- not use an index, but that will be slow
- use a range query a la `FILTER item.data >= "some_file.ex" AND item.data < "some_file.ey`, but you will need some application logic to calculate the string `some_file.ey`
- or use ArangoSearch, which supports index-backed prefix searching but has the drawback of not being immediately consistent

Example ArangoSearch View definition:

```json
{
  "links": {
    "files_collection": {
      "fields": {
        "data": {
          "analyzers": ["identity"]
        }
      }
    }
  }
}
```

Example query:

```js
FOR item IN files_view
  SEARCH ANALYZER(STARTS_WITH(item.data, "some_file.ex"), "identity")
  RETURN item
```

This will be case-sensitive, but you can create a custom `norm` Analyzer and change the Analyzer in the View definition and query accordingly to make it case-insensitive.

The performance of `STARTS_WITH()` should be the same or slightly better than with `LIKE(item.data, "some_file.ex%")`.

Edge _n_-grams would be the fastest option for a prefix search, because the query can then be a simple lookup like `item.data == "some_file.ex"`. Edge _n_-grams example:

```
s
so
som
some
some_
some_f
some_fi
some_fil
some_file
some_file.
some_file.e
some_file.ex
some_file.exe
```

However, you need to define the maximum length upfront and for high numbers, the index can grow quite large. They are also available as an option for `text` Analyzers only. In the upcoming 3.8 you could create an AQL Analyzer to implement edge _n_-grammification yourself though.

**Comment by Minstel** [comment]
@Simran-B Ok, thank you, that gives some clarification.

It seems though that this is an awkward limitation for fulltext index. Because sometimes any symbol, not only dot, can be a part of the word. And it would be great to easily find them, without any complex workarounds. For example, special symbols can be considered a part of word if they are escaped before saving.

**Comment by Minstel** [comment]
@Simran-B 
> The performance of STARTS_WITH() should be the same or slightly better than with LIKE(item.data, "some_file.ex%")

So `LIKE` solution will also work pretty fast?

**Comment by Minstel** [comment]
@Simran-B Ah, you probably mean using `LIKE` with arango search. Just discovered that option.

**Comment by Simran-B** [comment]
Yes, the ArangoSearch variant of LIKE that is accelerated by a View index:
https://www.arangodb.com/docs/stable/arangosearch-wildcard-search.html
(pardon the markup issue on that page, will fix that shortly)

The full-text index, as well as `text` Analyzers, tokenize text using ICU. Whatever it considers as word boundaries gets split into separate tokens and the characters that are the boundary get removed. This cannot easily be changed, but with ArangoSearch wildcard search you can treat the whole input string as one token and search for any contained characters with index acceleration.

**Comment by Minstel** [comment]
@Simran-B Ok, thank you very much!
