### ISSUE TITLE
URI as _key

### ISSUE THREAD

**Issue by damooo** [arangodb/arangodb#14227]
Namaste.
Currently _key naming conventions are too restrictive. And we cannot use URIs as _keys for `/` is not allowed. Using URIs is standard pattern in semantic world. we can use arango with json-ld serialization and techniques like reification of statements to represent rdf data efficiently in arango. The only issue is the naming convention of _keys. It doesn't allow unicode either. 

It would be helpful and logical to support at the very least URIs in _keys, if not IRIs.

Thanks again for your great work.

**Comment by dothebart** [comment]
If we allowed all characters in `_key`, then several of our assumptions would break:
- re URIs in `_keys`: first of all, our `_id` values are a concatenation of collection name, `/` and the value of `_key` . Because until now no `/` characters can appear in `_key`, we can easily tell the collection name part and the key part of an `_id` value apart. If we now would allow `/` in keys, there is no unambiguous way to determine the collection part and the key part (e.g. for a key such as `foo/doesnt/like/mushrooms`). This would affect all graph traversals immediately.
- re Unicode in `_keys`: here the assumption was that `_key` values can never contain any non-ASCII characters, so we can get away with a cheap and very quick memcmp-based key comparator in RocksDB. This is a lot faster than a Unicode-aware comparator. The same is true for our edge index, which also makes this assumption. If we now allowed arbitrary Unicode characters inside `_keys`, we will not be able any more to use the primary index to return keys in sorted order, or do proper range scans on them. That is, unless we somehow add a Unicode comparator to the primary index, but this would probably slow it down a lot.

So you see while at first it may be a desireable choice to have this, it isn't on a closer look and was forbidden by a carefully crafted decision. 
Hence I will close this feature request as "won't fix".

**Comment by damooo** [comment]
Thanks for reply @dothebart.
And
- I want to emphasize on the fact that **UTF-8 lexicographic byte order equals the Uni-
code code point order, so sorting UTF-8 works naturally.**  **We can use memcmp to compare utf-8 encoded strings**. **The stated difficulty in utf-8 sorting is a misconception**. The encoding is compact, compatible wit h ASCII, and self-synchronizing. It’s also a prefix code, so it can be decoded from left to right without any ambiguity or lookahead. No char’s encoding is a substring of any other, or even of a sequence of others, so we can search for a char by just searching for its bytes, without worrying about the preceding context.

- collection names bars `/` from their name. Thus determining `colln`, `_key` from `_id` is deterministic. Here is python statement for example
```py
colln, _key = _id.split("/", maxsplit=1)
```
This is completely backword compatible, without any regression. 

Thus liberalizing _key naming may not give any headache at all, But only embraces international communities, And allows for much natural expression of identities, slugs, urls. Like we can add a blog entry like "/blog/a/b/c", or we can have a dictionary entry or wiki entry of non english language. And also enables to use it for natural storing of json-ld docs, which is evolving pragmatic standard to serialize rdf graphs, getting embraced by many industries. And so on 

I sincerely request you to revisit this.
Thanks for your work.
