### ISSUE TITLE
removeByExample does not work at all when using the dot notation

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#14254]
## My Environment
Version 3.7.11
RocksDB
Ubuntu Linux

`removeByExample` does not work when using the dot notation.

You can replicate the issue with this simple script 

```
db._createDocumentCollection("house");
db.house.insert({ owner: { key: "123" }});
db.house.removeByExample({"owner.key":"123"});
```
It will return 0.

**Comment by dothebart** [comment]
Hi, 
please have a look at the implementation which is building AQL from your parameters:
https://github.com/arangodb/arangodb/blob/devel/js/server/modules/%40arangodb/arango-collection.js#L242
your parameters are translated into bind variables in `buildExampleQuery` function:
https://github.com/arangodb/arangodb/blob/devel/js/server/modules/%40arangodb/arango-collection.js#L46
```
    parts.push('doc.@att' + i + ' == @value' + i);
    bindVars['att' + i] = key;
    bindVars['value' + i] = example[key];
```
so you see, dot notation isn't supported here, since they're part of a string, and there is no way to differentiate that in this place. 

Please note that simple queries are deprecated and should not be used anymore; using AQL should easily solve your problem.

**Comment by Simran-B** [comment]
Simple Queries are indeed deprecated since v3.4.0, but the JS API interface is not. It's unclear whether the dot-notation is also deprecated or not.

`byExample()` and `firstExample()` both support the dot notation, but not the other methods. For them, you need to use a nested object `{ owner: { key: "123" } }`. This syntax is supported by all of the by example methods.

**Comment by gamedev8** [comment]
@dothebart  @Simran-B ok thanks I just noticed this page https://www.arangodb.com/docs/stable/http/simple-query.html where it says Simple Queries are deprecated. I will update my code.

**Comment by gamedev8** [comment]
@Simran-B @dothebart just so I'm clear. In future how would the following need to be rewritten?
```
db._createDocumentCollection("house");
db.house.insert({ owner: { key: "123" }});
db.house.removeByExample({"owner.key":"123"});
```

We'd have to replace the insert(...) and removeByExample(...) with `db._query(...)` ?

**Comment by dothebart** [comment]
yes,

**Comment by gamedev8** [comment]
@dothebart  Ok thanks
