### ISSUE TITLE
Foxx dependencies questions

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1427]
I've read https://www.arangodb.com/2015/05/foxx-dependencies-for-more-composable-foxx-apps/ and have a bunch of questions:

- When specifying the dependencies in a manifest, do the keys have any meaning? Or is it just the key I can use when programmatically accessing `applicationContext.dependencies`?
- After adding a dependency, I noticed in Aardvark an error message with my app "Out of order - Some dependencies have not yet been set up." Would be useful if Aardvark gave me an idea how to solve this.
- Eventually, I found a dependencies button on my app's page in Aardvark and entering any value (even just a space) makes the error go away.
  - Are the labels the capitalized keys from the manifest?
  - Why are the labels postfixed with "*"?
  - What am I supposed to enter here? The mount point of the dependency?
  - Where is my entry saved to?
  - Why can't I just enter whatever value is expected here also in the manifest?
- Do dependencies work across databases?
- Is there any (plan for) auto-install of dependencies, similar to how npm installs dependencies?

**Comment by pluma** [comment]
> When specifying the dependencies in a manifest, do the keys have any meaning? Or is it just the key I can use when programmatically accessing `applicationContext.dependencies`?

The keys are just the local alias (to help disambiguate between multiple dependencies on the same type of Foxx app, for example). They have no intrinsic meaning.

> After adding a dependency, I noticed in Aardvark an error message with my app "Out of order - Some dependencies have not yet been set up." Would be useful if Aardvark gave me an idea how to solve this.
> Eventually, I found a dependencies button on my app's page in Aardvark and entering any value (even just a space) makes the error go away.

The error message just means you need to open the dependencies dialog. As long as you haven't specified mount points for each dependency, the app will refuse to run. This is intentional. There is currently no support for optional dependencies.

We should probably include some tips on remedying the errors as a tooltip or something, though.

> Are the labels the capitalized keys from the manifest?

Yes.

> Why are the labels postfixed with "*"?

All mandatory fields throughout the dialogs are marked with an asterisk. Currently all dependencies are mandatory, so they all have an asterisk.

> What am I supposed to enter here? The mount point of the dependency?

Yes.

> Where is my entry saved to?

Just like the configuration, the data is stored with a copy of the manifest in a system collection that keeps track of mounted apps.

> Why can't I just enter whatever value is expected here also in the manifest?

The idea of dependencies is that they let you depend on other Foxx apps without having to make any assumptions about where they are mounted. You can have more than one copy of the same app mounted in different places.

> Do dependencies work across databases?

No, as Foxx apps are database-dependent. If you need your apps to work across different databases you probably should interact via an HTTP API.

> Is there any (plan for) auto-install of dependencies, similar to how npm installs dependencies?

Something like this, yes. That's why the documentation already specifies a format consisting of the app name and semver version range. The current functionality is a stop gap.

In an ideal world you'd be offered a dropdown of matching mounted apps with an additional option to install and use another app.

**Comment by pekeler** [comment]
Thank you! That helps me switching to sessions-jwt.

Just one follow up question: Why would one want to have multiple copies of the same app (at different mount points)?

**Comment by dothebart** [comment]
if you have a multi tennant system, that may be an option.

**Comment by pluma** [comment]
I agree that having one app depend on more than one copy of the same app is more of an edge case. But keep in mind that Foxx apps can be anything from a configurable implementation of some functionality (like the sessions apps) to a full-blown web app (e.g. a blog).

**Comment by CoDEmanX** [comment]
Apps might also depend on another app, but different versions (e.g. version before and after a breaking change).

**Comment by pekeler** [comment]
@pluma can you please also provide an example of how to use foxx-manager to set-dependencies?
```
foxx-manager --server.database "mydb" set-dependencies /myapp '{"sessions": {"definition": "sessions-jwt:^1.0.0", "title": "Sessions", "current": "/sessions"}}'
```
comes back with `Reconfigured dependencies of Application` but then
```
foxx-manager --server.database "mydb" dependencies /myapp
```
doesn't show my latest changes.

**Comment by pluma** [comment]
@pekeler you should only need to provide the actual values, i.e.

```sh
foxx-manager --server.database "mydb" set-dependencies /myapp sessions=/sessions
```

**Comment by pekeler** [comment]
Thanks @pluma - that works.

Seems like foxx-manager should report an error message if the value for set-dependencies is nonsensical or missing. And your example would be a good addition to the documentation. :)

**Comment by pluma** [comment]
I've created tickets to track the two problems.
