### ISSUE TITLE
Truncating big collection takes too long

### ISSUE THREAD

**Issue by diegogub** [arangodb/arangodb#1459]
Hello, I'm using arangodb 2.6.5, truncating a collection with Total: 487275 document(s)
Arango process run into 100% cpu usage and it seems it will never finish to truncate collection. As I needed to continue with development I had to drop the collection and re-created. 

Thanks!

**Comment by jsteemann** [comment]
I guess it's an issue with non-unique hash indexes. Can you check what kind of indexes are present for this collection? If there's non-unique, non-sparse hash indexes with lots of duplicate index entries, then this is going to be slow at the moment. We're currently working on a fix for this.

**Comment by CoDEmanX** [comment]
I experienced slow performance as well on truncating a test collection with a few million documents through aardvark. Only one CPU core was fully used though, and there was a lot of disc activity.

I ultimately killed arangod and deleted the entire var/lib/arangodb folder, which was a matter of seconds instead of minutes or hours.

There was no index but the one on document keys that is created by the system. Own build of v2.7.0-devel on Windows 8.1 with SSD drive.

**Comment by diegogub** [comment]
Yes, I have few hash indexes with many duplicated values. thanks!

**Comment by jsteemann** [comment]
@diegogub : the problem with slow deletions from non-unique hash indexes with lots of duplicate values is fixed in devel. The fix will be included in 2.7.
@CoDEmanX : truncation is effectively the `remove` operation carried out for all the documents in the collection. `truncate` will write one deletion marker per deleted document, so it will also cause I/O.
`db._drop(collectionName)` is probably the fastest method to get rid of an entire collection. 

The downside is that it does not delete only the documents, but also the collection itself, with its properties and index definitions.

**Comment by CoDEmanX** [comment]
I see. So it would be much faster to temporarily store the collection meta data, then drop it entirely, recreate and apply the stored settings to the new collection. I thought truncate in the web interface would more or less do that, and not "delete all documents" individually. Would it be faster though if it was carried out as transaction?

**Comment by jsteemann** [comment]
`collection.truncate()` is carried out in a transaction already. But it will individually delete all documents, and if this goes wrong in the middle, the transaction will be aborted and rolled back. 
Contrary, `collection.drop()` (or `db._drop(collection)`) simply removes the collection from the list of available collections and performs the deletion in the background. This does not need to remove the documents individually, but drops all data at once by deallocating all data structures. 

Dropping and re-creating a collection together with all index descriptions will therefore be faster than truncating if the total cost of the drop, create and the additional ensureIndex calls is lower than the cost of truncate. Where exactly the threshold is depends on too many factors to give a good estimate here. A reasonably safe assumption is that when a collection contains millions of documents, then dropping and re-creating should likely be faster than deleting documents one by one.

**Comment by jsteemann** [comment]
Please find below some figures comparing the hash index deletion performance in 2.6 and 2.7/devel, in case the index contains many duplicates.
The test script creates 100k documents with just two distinct index values in a non-unique hash index. Insertion is fast, but deletion (truncate) is slow in 2.6. due to the many collisions:
```js
db._create("c");
for (var i = 0; i < 100000; ++i) {
  db.c.insert({ value: i % 2 });
}
db.c.ensureIndex({ type: "hash", fields: [ "value" ] });
var s = internal.time(); 
db.c.truncate(); 
time() - s;
```
Result for 2.6: 8.969213962554932 s
Result for 2.7/devel: 0.3163719177246094 s

That's quite ok, given the fact that `truncate` doesn't only remove elements from the index but also writes deletion markers for each document into the WAL.
