### ISSUE TITLE
Does arangodb provide some of vitess features?

### ISSUE THREAD

**Issue by bitsnaps** [arangodb/arangodb#14640]
Hello,

I'm just curious how arangodb is compared to [vitess](https://github.com/vitessio/vitess) DB clustering system, does it help for things like: shard-routing, horizontal scaling... or any idea where to use one over the other for large amount of data ?

Regards

**Comment by dothebart** [comment]
ArangoDB offers Sharding in clustered setup. The only choice left to the valuable user is the number of shards to split a collection into, we sugest twice the number of instances, so with future adding more DB-Servers scaling becomes possible. The rest of the choices is handled by the database internally.

If I get that correctly, Vites depends on mysql as backend? So the use case would be to scale out a database to offer (my)SQL?

ArangoDB otoh offers AQL as query language. AQL feels more natural to people used to imperative programming than SQL. On top of that AQL is intended to work with documents, so instead of denormalizing everything SQL like, you can keep structured data.
Even moreso, ArangoDB offers [graph traversals](https://www.arangodb.com/docs/stable/graphs.html) which can be modeled as 2x Joins per step in SQL at the time being, which quickly becomes pretty clumsy (once you want to traverse deeper) - execution performance set aside. 

Did this answer your question?

**Comment by bitsnaps** [comment]
Well, I'm not sure if I get it, AFAIK ArangoDB community edition [supports clusters with sharding](https://github.com/arangodb/arangodb/issues/12095#issuecomment-652996107), and I don't know how traversals perform on multiple shards on scale, I wish to see a thorough [benchmark](https://www.arangodb.com/performance/) for that specific purposes, Vitess is backed on top of MySQL but theoretically it can plugged to any DB engine according to [their CTO](https://www.youtube.com/watch?v=E6H4bgJ3Z6c), they're working to support PostgreSQL as well.
