### ISSUE TITLE
Consider supporting GraphQL in foxx

### ISSUE THREAD

**Issue by tychota** [arangodb/arangodb#1468]
Hi, discovering ArangoDB after using a lot of OrientDB : I'm not sure how open are the dev so please close it if you find this unrealistic or not good for upstream.

Facebook just published his "data-driven" framework (codename : [Relay](https://github.com/facebook/relay)). One month before, they opensource the draft RFC specification of a new *query language* (but it is more than this, consider it as a replacement for REST) (codename : [GraphQL](http://facebook.github.io/graphql/)) and even a [js technical preview](https://github.com/graphql/graphql-js).
This GraphQl allow some people developing a type system (like haskell one) rather than building multiple custom endpoint while preventing multi roundtrip that can make rest so slow.
[An interesting video about this concept](https://www.youtube.com/watch?v=WQLzZf34FJ8).

So my feature request (note that I can participate probably) is two include this functionality in foxx. That should be rather easy since there is already a graphql-js paquage, a [graphiql](https://github.com/graphql/graphiql) (web-ide). Then integrate the creation of the graph system in webui (more works). But I think, it is worth it since it would allow building easy descriptive app, in node, using arango.

WDYT ?

**Comment by CoDEmanX** [comment]
I have mixed feeling after seeing that video and thumbing through the spec. It seems to be a lot, but not a graph query language (as the name suggests). Looks more like a meta language to me, that thinks of data in objects and relationships (that's why they call it **graph** QL). In its simplest form it's not much more than a JSON dialect however, which leaves out attribute values (it queries for them by attribute keys) and with XML-like ability for reification, although it's actually more like a function call with keyword arguments. That's for the query part. There seems to be a completely different part to describe models with similar features like seen in reactive client-side frameworks such as React.js and Ember.js (I'm referring to model fragments in particular). The syntax looks clean, but would have to dive deeper to evaluate.

I don't see how this could be added to Foxx, seems more like a complete replacement for model / joi schema / routing / endpoint description. And I think Foxx would really have to go, so that GraphQL can be handled by Arango's core directly - otherwise there wouldn't be much of a performance gain. But there seems to be a collision between AQL and GraphQL as well... The simpler parts of a query can also be expressed with GraphQL, but things like graph queries can only be wrapped by GraphQL. That would be like a function call, but what if you don't want the raw result back? That's where it gets messy IMO.

**Comment by tychota** [comment]
Yes it's more a complete replacement to REST.
Has you stated, it is surely not great to integrate it in foxx. Maybe create another interface (codename : boosie, if i understand the ref to foxx correctly ^^)

**Comment by doublerebel** [comment]
:+1: for some kind of GraphQL support in ArangoDB

**Comment by weinberger** [comment]
There will be a experimental support in the next weeks. Stay tuned :)

**Comment by mikeholmesuk** [comment]
I'd be happy to help trial this if you're looking for volunteers using ArangoDB in anger out in the wild? Graph DBs are very new and localised where I am at the moment (like, localised to me currently) and this sort of feature could be really useful for opening these up for more people.

**Comment by clintwood** [comment]
+1 But this could probably be an additional core interface (much like AQL) accessible via HTTP API rather than in foxx.  It would be great to have this built in!

The attraction for me is that currently, I find most of my REST API's end up doing AQL queries to ArangoDB because I generally need some form of composition of end results.  It seems like graphQL facilitates composition extremely well!!

C'mon, be the first noSQL DB to support this natively :wink:

**Comment by pluma** [comment]
Sadly there's no way to automatically generate GraphQL schemas for collections, so it's of little use "out of the box". With the changes in #1508 ArangoDB code is able to import and use GraphQL in principle but we still need a non-async (i.e. promise-less) wrapper to make any use of it in ArangoDB code (which is always executed synchronously and therefore doesn't support promises).

I see GraphQL as more of an alternative to Foxx models (i.e. RESTful APIs). Using it will likely work similarly to how you would currently use Foxx models/repositories.

**Comment by pluma** [comment]
Just an update: the necessary changes have landed in devel and you can now use GraphQL by installing `graphql-sync` from npm (which is a thin wrapper around `graphql` that does away with the promise-related logic).

**Comment by clintwood** [comment]
Thanks for the feedback @pluma!  Will take a look but since I purely use the ArangoDB REST API's I will probably handle graphQL in a layer in my server-side API.  I'm already using KoaJS and yield on  Promises (HTTP Requests to ArangoDB) so hoping to get some parallelism via this in graphQL.

**Comment by fceller** [comment]
@pluma can we close this issue?

**Comment by pluma** [comment]
@fceller I think so. Is 2.7 still correct? I thought we decided to postpone the new `require` implementation until 2.8 to give it a little more time to discover any unknown incompatibilities.

**Comment by fceller** [comment]
@pluma yes, you are right. Changed to 2.8.

**Comment by outre99** [comment]
Has anybody tried to use ArangoDB with Relay / Graph QL.  Wondering what's the best way to generate a schema.js from the actual database.  Would hate to have to manually redefine all of the collections / documents.  Is there a metadata export or something like that?
Thanks.

**Comment by dothebart** [comment]
Have a look at https://www.arangodb.com/2016/02/using-graphql-nosql-database-arangodb/ for more details.

**Comment by pluma** [comment]
@outre99 There's a question in the comments section of that article about the `schema.json` file Relay seems to expect: https://www.arangodb.com/2016/02/using-graphql-nosql-database-arangodb/#comment-2545199830

**Comment by outre99** [comment]
Thanks for a lightning fast response Pluma.  Varayut and I have been trying to figure this part out together.
