### ISSUE TITLE
Filter on DateTime don't use index 

### ISSUE THREAD

**Issue by ppiccolo** [arangodb/arangodb#1546]
Hello, suppose the following document inside an edge collection  :

```
{
  "task_id": 460,
  "freq": 1,
  "kind": "web",
  "type": "Social activity",
  "unique": "Organization/480786013375-Person/485359770815",
  "dt_first_seen": "2015-06-25T04:56:58",
  "dt_last_seen": "2015-06-25T04:56:58"
}
```

fields task_id, dt_first_seen, dt_last_seen are inside a Skip-list sparse index
there is also an hash index on task_id filed

the folllowing AQL, don't use the supposed index 

```
LET x = (
for c in Connections
    filter  ((c.dt_first_seen >= "2015-06-11T17:21:39") && (c.dt_last_seen <= "2015-08-14T13:32:13") && c.task_id == 460)
    return c
)

return x
```

this is the explain output :

```
Query string:
 LET x = (
 for c in Connections
     filter  ((c.dt_first_seen >= "2015-06-11T17:21:39") && (c.dt_last_seen <= "2015-08-14T13:32:13") 
 && c.task_id == 460)
     return c
 )
 return x

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   SubqueryNode         1     - LET x = ...   /* subquery */
  2   SingletonNode        1       * ROOT
  9   IndexRangeNode     296         - FOR c IN Connections   /* hash index scan */
  4   CalculationNode    296           - LET #4 = c.`dt_first_seen` >= "2015-06-11T17:21:39" && c.`dt_last_seen` <= "2015-08-14T13:32:13" && c.`task_id` == 460   /* simple expression */   /* collections used: c : Connections */
  5   FilterNode         296           - FILTER #4
  6   ReturnNode         296           - RETURN c
  8   ReturnNode           1     - RETURN x

Indexes used:
 Id   Type   Collection    Unique   Sparse   Selectivity Est.   Fields      Ranges
  9   hash   Connections   false    true               0.34 %   `task_id`   [ `task_id` == 460 ]

Optimization rules applied:
 Id   RuleName
  1   use-index-range
```

any suggestion ?

tnx in advance

**Comment by mchacki** [comment]
Hi @ppiccolo,

it seems reasonable that the skiplist-index should be preferred over the task_id index.
Could you send us the output of
`getIndexes()`
on your collection?
This would help us to debug the issue.

best
Michael

**Comment by ppiccolo** [comment]
Sure ... 

```
db.Connections.getIndexes()
[ 
  { 
    "id" : "Connections/0", 
    "type" : "primary", 
    "fields" : [ 
      "_key" 
    ], 
    "selectivityEstimate" : 1, 
    "unique" : true, 
    "sparse" : false 
  }, 
  { 
    "id" : "Connections/480418618559", 
    "type" : "edge", 
    "fields" : [ 
      "_from", 
      "_to" 
    ], 
    "selectivityEstimate" : 0.3823936641559592, 
    "unique" : false, 
    "sparse" : false 
  }, 
  { 
    "id" : "Connections/480419011775", 
    "type" : "hash", 
    "fields" : [ 
      "task_id", 
      "type", 
      "unique" 
    ], 
    "selectivityEstimate" : 1, 
    "unique" : true, 
    "sparse" : true 
  }, 
  { 
    "id" : "Connections/523655535807", 
    "type" : "hash", 
    "fields" : [ 
      "task_id" 
    ], 
    "selectivityEstimate" : 0.0033783783783783786, 
    "unique" : false, 
    "sparse" : true 
  }, 
  { 
    "id" : "Connections/523971353791", 
    "type" : "skiplist", 
    "fields" : [ 
      "task_id", 
      "dt_first_seen", 
      "dt_last_seen" 
    ], 
    "unique" : false, 
    "sparse" : true 
  } 
]
```

**Comment by jsteemann** [comment]
I think in this case the skiplist index **must not** be used because the index is declared sparse.

The skiplist index is created on attributes `task_id`, `dt_first_seen` and `dt_last_seen`, in this order.
The filter condition is `task_id == 460 && dt_first_seen >= "2015-06-11T17:21:39" && dt_last_seen <= "2015-08-14T13:32:13"`.

In general, a skiplist index can be used if all index attributes are used in a query or if a left-most prefix of the attributes is used in the filter condition. However, it needs to stop after the first index attribute which is not an equality condition. 

In the above example, the skiplist index can be used to scan the range from `[ task_id = 460, dt_first_seen = "2015-06-11T17:21:39" ]` to `[ task_id = 460, dt_first_seen = max value ]`. It cannot use the condition on the third index attribute `dt_last_seen`. 
While in general a skiplist index can support such condition and query the range, in this case it won't be used because it's declared sparse. Sparse indexes will (intentionally) exclude all documents in which any of the index attributes are not set or contain the value `null`. Because the condition only covers two of the index attributes, the optimizer cannot safely determine that the range does not contain any documents in which one of the index attributes would have been null.

For example, an imagined document `{ task_id: 460, dt_first_seen: "2015-06-11T17:21:39", dt_last_seen: null }` would be included in the range, but it won't be present in the index as the index is declared sparse. Therefore using the index for answering the query would potentially suppress documents like this one, so the optimizer chose to not use the index. 

If you want the skiplist index to support that query, the index needs to be declared non-sparse.

**Comment by ppiccolo** [comment]
Ok have a sense, I'll give it a try with non-sparse index

**Comment by ppiccolo** [comment]
Solved tnx to all
