### ISSUE TITLE
foxxes api undefined path

### ISSUE THREAD

**Issue by hkernbach** [arangodb/arangodb#1547]
API GET: http://localhost:8529/_db/_system/_admin/aardvark/foxxes ...
returns invalid/broken path.

example: /some_valid_path/undefined/_system/sessions/APP

**Comment by pluma** [comment]
The `root` property on Foxx apps is missing and doesn't seem to be saved to the collection anymore.

**Comment by pluma** [comment]
I've committed a fix that will prevent this problem in the future and also fixes any broken system apps. I'm not sure how to fix this for non-system apps mounted on the devel version before the fix. The path resolution logic is in manager-utils, which is in common (rather than server) whereas the other Foxx logic is in server (rather than common).

This does not affect 2.7, just the post-require devel branch.

**Comment by pluma** [comment]
Okay, it now defaults to the current APP_PATH rather than a relative path `"undefined"`. This should at least solve the affected apps while the earlier commit takes care of future apps.
