### ISSUE TITLE
Database freeze when concurrent access and aql data modification is used 

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1551]
Hi, we have following application written in JS:
tasker script - uses queries and insert/updates data, data sends as tasks to workers
updater script - receives data from workers and inserts them to database.

Tasker and updater run concurrently and each only in one instance. There is a lot of queries and inserts/updates.

When we started to use data modification queries, we run into a problem with complete database freeze. Database is stuck, doesn't response, you can't get console or web access etc. It can't be reloaded (service restart in Debian). Process must be manually killed.

Here is our trouble query which freezes database and runs in loop in Tasker:

let intPrefix=(
          for intL3 in vIntL3
            filter length(GRAPH_EDGES ("network", intL3, { edgeCollectionRestriction: "eDevIntL3"}))==0 && intL3.status=="error"
              for cef in GRAPH_EDGES("network", intL3, { edgeCollectionRestriction: "eCef", includeData: true})
                return cef.prefix)
        let cachePrefix=(
          for prefix in vTraceCache
            return prefix.prefix)
        for prefix in minus(flatten(intPrefix),cachePrefix)
        insert {prefix: prefix, status: "ready" } in vTraceCache

When we remove insert, and return only data a insert them in separate save function it works. In our lab, it's reproducible. It gets stuck always on this query, but after different number of repetition. It's not on the first occurrence of this command. So it seems there has to be some other access to data from Updater script. Unfortunately we are not able to recreate some simple example which wouldn't require to run whole application in our lab. Is there a way how to enable some low level debugging or how we can help you to troubleshoot this issue?

**Comment by dothebart** [comment]
since the database can't know which collections you're going to combine here now, you have to specify that you're going to work with them in advance, so proper locking can be done:
https://docs.arangodb.com/Transactions/TransactionInvocation.html
Most probably 2.8 is going to be able to throw exceptions in this situation.

**Comment by roman1720** [comment]
Collection vTraceCache used in data modification is used only in one process Tasker. When data modification insert is removed, it works fine. I don't understand how it relates to locking and transaction. Can you explain pls?

**Comment by dothebart** [comment]
while multiple readers on a collection are allowed, just one writer is allowed. plus while there are readers, no writer will be able to pass the lock into its writing operation. Only one at a time will be first given the write lock. if you then have queries still doing read on the collection, that later on want to write, and there already is another one waiting for writing, no one else will be able to start writing.

**Comment by jsteemann** [comment]
I hope [this page from the manual](https://github.com/arangodb/arangodb/blob/devel/Documentation/Books/Users/Transactions/LockingAndIsolation.mdpp) can shed some light on why the issue can occur.
The deadlock detection mentioned on that page was added to ArangoDB 2.8 recently to avoid such problems. Note that 2.8 is currently still in development. 

In versions 2.7 and 2.6, deadlocks can occur for read-write queries or transactions that access multiple collections and that do not declare all the collections they will access in the query string or in the transaction description.

In the example query above, the problem seems to be caused by the `GRAPH_EDGES` functions, which will internally consult the collection `_graphs` and read edges from some other collections not directly mentioned in the query string, so the AQL parser cannot detect these. When the query is executed, it will be discovered that these further collections need to be accessed and they will be add to the transaction's list of collections *lazily*. This is not a problem per se. But if several of such operations run simultaneously, then the order in which collection locks get acquired will become totally undeterministic, and there is the potential for deadlocks. 
The only sensible way to prevent this from happening is to use an automatic deadlock detection mechanism, which is in place since 2.8. The downside of such mechanism is that it will abort transactions when a deadlock occurs (which is of course desirable because otherwise there'll be no progress) but it will also change the API. Due to the deadlock detection mechanism, queries and transactions in 2.8 can be aborted and fail with error 29 (`deadlock detected`), which is something that never happened in earlier versions and thus client code did not need to care about.
To work around the problem in 2.7, it may help to use function `EDGES()` instead of `GRAPH_EDGES()`. The reason is that `EDGES()` allows specifying the edge collection name as part of the query string, e.g. `EDGES(eDevIntL3, intL3, "outbound")` and `EDGES(eCef, intL3, "outbound")` (provided the connected edges are outbound edges and `intL3` contains a document handle). That may also help mitigating the problem until 2.8 is GA.

**Comment by roman1720** [comment]
Thanks Jan! What's your philosophy about having functions in two version - aql graph (edges) and graph module (graph_edges). Which way you will support and develop in future?

**Comment by dothebart** [comment]
In general we announce that we deprecate features in one Release in the [changelog](https://docs.arangodb.com/NewFeatures/NewFeatures27.html), tag their documentation chapters with exclamation marks and will usually remove them in the next. So a deprecation announcement in 2.6.x would have happened in 2.7. But, we always have an open ear for our users; Its worth wile [to follow the changelog](https://github.com/arangodb/arangodb/blob/devel/CHANGELOG) and start a discussion in doubt.

There is no general recommendation which to choose over the other.
The [EDGES functions](https://docs.arangodb.com/Aql/GraphFunctions.html) may work on collections that are not managed by the graph module, and thus may not be visible in the graph viewer. It however has lesser overhead by not doing graph management. 

[The GRAPH_EDGES family](https://docs.arangodb.com/Aql/GraphOperations.html#graph_edges) is the more recent implementation. It only works on managed graphs that you can also browse in the [graph viewer](https://docs.arangodb.com/WebInterface/index.html#graphs-tab). 

So far there is no ongoing discussion whether to deprecate either of those yet.

**Comment by dothebart** [comment]
ArangoDB 2.8 with the [new traversal functions](https://docs.arangodb.com/devel/Aql/GraphTraversals.html) is now in beta. (Please note, devel already moved on, therefore the example lines aren't correct for 2.8 anymore, replace `@arangodb` with `org/arangodb` )
