### ISSUE TITLE
Recursive Unset

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangodb#1555]
Sorry, it's not an issue, just one question from mine.

How can I update a document to recursive unset some attributes in the document? 

So far I only find `UNSET` function on object, however I guess it doesn't support recursive.
I can image another way is implementing a user function for that.
I'm not sure whether it's possible to update like the following?

```
for u in users
  filter u.id == 'test'
  update u with USER::FUNC::UNSET(u)
```

btw. How can I use some external dependencies such as lodash in the user function? Or is it possible to require `UNSET` function of ArrangoDB in my user function so as to extend it?

Bg,
Kevin

**Comment by CoDEmanX** [comment]
Can you give an example for "recursive unset"?

It might be possible to achieve with AQL alone, if the depth is limited. Have a look at the ATTRIBUTES() function.

**Comment by dothebart** [comment]
does this example: https://docs.arangodb.com/AqlExamples/DataModificationQueries.html#altering-substructures work for your data?

**Comment by kevinprotoss** [comment]
for example, the following document

```json
{
  "name": "test",
  "label": "test label",
  "user": {
    "name": "test user"
  }
}
```

I want to remove both `name` and `user.name` property within the document. This means, I had to unset the `name` property recursively. 

Bg,
Kevin

**Comment by kevinprotoss** [comment]
@dothebart 

I guess it does't work for my use case. The query must collect and modify the substructure recursively, not only a  known property.

**Comment by kevinprotoss** [comment]
Does ArangoDB support the dot notation in the UNSET function?

If yes, I can first select all attribute names and unset all of them once

**Comment by kevinprotoss** [comment]
Well, I have implemented a custom function in AQL for such use case, and update document by calling it.

If you guys know some other better solution, I'm glad to hear about that as well.

**Comment by CoDEmanX** [comment]
It doesn't really has something to do with recursion. It's about unsetting nested / sub-attributes.

`UNSET(doc, "user.name")` is not possible, it will look for an attribute key `"user.name"` and not `"user"` with a sub-attribute key `"name"`.

What's weird: if you do `UNSET(doc.user, "name")`, it will actually remove that attribute, but also other attributes.

Baseline:

```js
FOR doc IN test
    FILTER doc._key == "usr1"
    RETURN doc

/* [
  {
    "name": "test",
    "label": "test label",
    "user": {
      "name": "test user"
    },
    "_id": "test/usr1",
    "_rev": "34569358006",
    "_key": "usr1"
  }
] */
```

Unset in action:

```js
FOR doc IN test
    FILTER doc._key == "usr1"
    RETURN UNSET(doc.user, "name")

/* [
  {}
] */
```

If there's another key in the user object...

    "user": {
      "name": "test user",
      "another": "attribute"
    }

... and you run the same query, then that extra attribute will survive:

```js
[
  {
    "another": "attribute"
  }
]
```

@dothebart: this looks like a bug, or at least a limitation of UNSET(). It seems to work on documents, but not objects (sub-attributes in documents).

**Comment by kevinprotoss** [comment]
Does that mean a new function `UNSET_RECURSIVE` has been added?

**Comment by jsteemann** [comment]
@CoDEmanX : I think `UNSET()` currently works as announced. For example, if there are the following two documents in a collection:
```json
[ 
  { 
    "name" : "test", 
    "label" : "test label", 
    "user" : { 
      "name" : "test user" 
    } 
  }, 
  { 
    "name" : "test", 
    "label" : "test label", 
    "user" : { 
      "name" : "test user", 
      "another" : "attribute" 
    } 
  } 
]
```
The following query will then delete the attribute `name` from the attribute `doc.user`:
```FOR doc IN collection RETURN UNSET(doc.user, "name")```
```json
[ 
  { 
  }, 
  { 
    "another" : "attribute" 
  } 
]
```
Referring to an attribute named "user.name" will not remove the sub-attribute. This is because there is no proper way to distinguish between an attribute named `user.name` and the sub-attribute `name` in an attribute `user` just by looking at the string `"user.name"`. It could mean both. 
So `UNSET()` currently cannot do this, the same as related functions such as `KEEP()`.

@kevinprotoss : I have added a function `UNSET_RECURSIVE` to devel/2.8, but it works slightly differently: it will remove the named attribute(s) in the document itself and all its sub documents, e.g. if you do `UNSET_RECURSIVE(doc, "value")` for a document `{ foo: { value: 2 }, bar: { value: 42, test: true } }`, then the result would be `{ foo: { }, bar: { test: true } }`.

**Comment by jsteemann** [comment]
So using a user-defined AQL function is currently the most sensible way to achieve the result.

**Comment by CoDEmanX** [comment]
@jsteemann: That looks buggy to me, because it doesn't remove `doc.user.name` only, but also `doc.user.another` as well as `label`?!

I see why @kevinprotoss mentioned recursion now that you explained how `UNSET_RECURSIVE()` removes attributes at any nesting level.

**Comment by jsteemann** [comment]
@CoDEmanX : the above result is correct. The `UNSET()` function will return the document passed into it, minus some attributes removed. The input to `UNSET()` in this case is not `doc`, but `doc.user`. 

For the first document ```{ "name" : "test",  "label" : "test label",  "user" : { "name" : "test user"  } }```, the value of attribute `doc.user` is just `{ "name" : "test user" }`. 
When removing the `name` attribute from it, what remains is `{ }`.

For the second document ```{ "name" : "test", "label" : "test label", "user" : { "name" : "test user", "another" : "attribute" } }```, the value of attribute `doc.user` is `{ "name" : "test user", "another" : "attribute" }`. 
When removing the `name` attribute, the result is `{ "another" : "attribute" }`.

So it looks good.
The confusion probably arose because there `UNSET` was expected to work on the original document (`doc` in this case), but it only works on its first argument.

**Comment by CoDEmanX** [comment]
Yeah you're right. So the following query would be needed:

    FOR doc IN collection RETURN MERGE(UNSET(doc, "user"), {user: UNSET(doc.user, "name")})

**Comment by jsteemann** [comment]
@CoDEmanX : I think so.
