### ISSUE TITLE
Index makes aql return wrong result

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1583]
Hi

I have following collection with one property bar:

for d in foo return d.bar
[
  "one",
  "two",
  "two",
  "one"
]

With this AQL a get correct result:

for d in foo
 filter d.bar in ["one","two"]
  sort d.bar desc
   limit 0,4
    filter d.bar=="one"
     return d.bar
[
  "one",
  "one"
]

But when I apply index on d.bar:  db.foo.ensureIndex({ type: "hash", fields: [ "bar" ]});
either hash or skiplist, then I get with same AQL wrong result:

[
  "two",
  "two",
  "one",
  "one"
]

Arangodb 2.7.0

**Comment by jsteemann** [comment]
Confirmed. The optimizer removes the second filter via rule `remove-filter-covered-by-index` as it thinks the filter condition is already covered by the index lookup.

**Comment by jsteemann** [comment]
Affects ArangoDB 2.7 and before. Works as expected in 2.8 as filter condition handled was completely changed in that branch.

**Comment by jsteemann** [comment]
Fixed in 2.7.2 and 2.6.12.

**Comment by roman1720** [comment]
Hi it's not fixed in 2.8beta1

Without index:

for d in foo
filter d.bar in ["one","two"]
sort d.bar desc
limit 0,2
filter d.bar=="one"
return d.bar

returns []

with index

[
  "one",
  "one"
]

**Comment by jsteemann** [comment]
When I tried the query last time I found it did not work in 2.7 & 2.6, but in 2.8. So I fixed it in 2.7 & 2.6 only.
Now I retried the query in 2.8 and for some reason it shows the problem. Seems I was wrong last time when I said it worked there. Maybe I was testing in a wrong instance.

However, it's now fixed in 2.8 and devel as well. Note that the fix is not included in 2.8b2 as that version was already built before the fix.
