### ISSUE TITLE
Levenshtein distance, is it implemented?

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#1585]
Hi there,
I see in the C code that there is a levenshtein distance calculation function. But AFAIK, it is not implemented in AQL. Are there any plans to implement it? It would be very useful!
Thanks!

**Comment by jsteemann** [comment]
AQL currently does not have a levenshtein distance function, but it's trivial to add one yourself using a JavaScript custom AQL function like this:

```js
require("org/arangodb/aql/functions").register("my::levenshtein", function (a, b) {   
  if(a.length === 0) return b.length;    
  if(b.length === 0) return a.length;     
  var matrix = [];    
  var i;   
  for(i = 0; i <= b.length; i++){     
    matrix[i] = [i];   
  }    
  var j;   
  for(j = 0; j <= a.length; j++){     
    matrix[0][j] = j;   
  }    
  for(i = 1; i <= b.length; i++){  
    for(j = 1; j <= a.length; j++){     
      if(b.charAt(i-1) == a.charAt(j-1)){         
        matrix[i][j] = matrix[i-1][j-1];       
      } else {         
        matrix[i][j] = Math.min(matrix[i-1][j-1] + 1, Math.min(matrix[i][j-1] + 1, matrix[i-1][j] + 1));        
      }     
    }   
  }    
  return matrix[b.length][a.length]; 
});
```

The actual function code is from [here](https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#JavaScript).

You can then call the function `my::levenshtein()` from within an AQL query as any other function.

**Comment by miguel-porto** [comment]
Thank you for the helpful reply!
However, I guess a native implementation, as the one that you've [done here](https://github.com/arangodb/arangodb/blob/7bd9f03cb1a9e5efc0cfad9e0176366d6aa74149/lib/Basics/levenshtein.cpp), would probably be faster when you need to compare with thousands of names. I'll try this javascript solution and see how it goes, anyway!
Thanks!

**Comment by jsteemann** [comment]
Yes, a native implementation may be faster when called often. 
However, it's not there at the moment, requires proper implementation and testing, new binaries being built etc. 
Therefore I wanted to present a solution that works right now.

**Comment by miguel-porto** [comment]
Sure, thank you. I'll try it.

**Comment by CoDEmanX** [comment]
The performance of a single Levenshtein calculation is usually not so important, because of ~n² complexity if you compare each and every string with all others. For 1 million strings, there would be 1 trillion calculations. No matter what the speed difference between JS and C++ is, it will last weeks, months or even years.

Algorithms like Soundex might be more suitable for some use cases, if you can filter by example (equality). Or use Levenshtein with a (small) sliding window to massively reduce the number of required calculations if your problem allows that.

**Comment by miguel-porto** [comment]
Hmmm. I guess soundex wouldn't work for my case, since what I need is to match user input against scientific names, not common words. I'll see how can I optimize this javascript function (e.g. I can restrict the calculation to words that start with the same letter, as the user usually does not misspell the first letter; or use a cut off distance within the function to abort...).
Thanks for the hints anyway.

**Comment by kkdd** [comment]
Hello,
Will ArangoDB allow pluggable native functions in the future?

**Comment by dothebart** [comment]
Yes, we have been discussing this lately. In the end you would only have to implement an .so / .dll with a special hook registering the AQL-functions into the table (which is currently static).
We also ported most functions from .js to c++ with the 2.8 release - since the cost of making data visible in .js functions can't be ignored.
I.E appinding json values to a string:
https://github.com/arangodb/arangodb/blob/devel/arangod/Aql/Functions.cpp#L887
which is registered here:
https://github.com/arangodb/arangodb/blob/devel/arangod/Aql/Executor.cpp#L239
However, this will also require to have a stable and mature API for those plugins, which we currently don't know when we will get it. 
The other solution for getting your own implemented native function running is to send a pull request ;-)

**Comment by miguel-porto** [comment]
Yeah it would be great to provide a simple means of plugging in user defined functions in native code. Just like the MySQL UDFs, which I used a lot in other projects, and are fairly simple to implement in C, yet very powerful in speed. I usually have special needs for the queries, which require some processing to be done in the native code, usually against a BLOB of a C array/structure. (looking forward for the BLOB support also! actually, for me a "BSOB" would be enough!)

**Comment by lvitaly** [comment]
Does AQL have something similar to soundex function at latest versions?

**Comment by Simran-B** [comment]
There is no built-in support for Soundex or related functions. You could implement it in JS like the Levenshtein function however.

**Comment by Simran-B** [comment]
v3.4.0-RC.4 is out for testing and comes with a LEVENSHTEIN_DISTANCE() function: https://docs.arangodb.com/3.4/AQL/Functions/String.html#levenshteindistance

**Comment by maxkernbach** [comment]
Closing - As already stated, both the [LEVENSHTEIN_DISTANCE() function](https://docs.arangodb.com/3.4/AQL/Functions/String.html#levenshteindistance) and the [SOUNDEX() function](https://docs.arangodb.com/3.4/AQL/Functions/String.html#soundex) are implemented since v.3.4.0-RC.4.

**Comment by Simran-B** [comment]
It was actually in the first preview release already (v3.4.0-preview.1), which means also in RC.1, but it wasn't in milestone0. See the respective Git(Hub) tags.
