### ISSUE TITLE
java.lang.ClassNotFoundException: com.arangodb.velocypack.VPackModule even with jackson-dataformat-velocypack jar added.

### ISSUE THREAD

**Issue by Moubassher** [arangodb/arangodb#15908]
## My Environment

* __ArangoDB Version__:        3.0

* __Operating System__:       Windows 10
* __Total RAM in your machine__:        8 GB
* __Disks in use__:        HDD

## Component, Query & Data

__Affected feature__:
Java driver

## Steps to reproduce

1. Add the two required jar files manually (Eclipse -> build path -> user libraries -> add jars).
2. Initiate a connection with ArangoDB using either of the line of code above.
3. run.

__Problem__:

I cannot initialize a connection with arangodb using the official Java driver, following the tutorial on the official website. 
`ArangoDB arango = new ArangoDB.Builder().host("127.0.0.1", 8529).build();`

or 
`ArangoDB arango = new ArangoDB.Builder().serialize(new ArangoJack()).build();`

both throw a ClassNotFoundException, even when I add Jackson-dataformat-velocypack jar (manually).
My IDE is Eclipse and I do not use a build tool; neither Maven nor Gradle. 

__Expected result__:
a connection is established, database created with:
ArangoDatabase db = arangoDB.db(DbName.of("mydb"));
db.create();

**Comment by rashtao** [comment]
Since you add jars manually, please consider that there are required transitive dependencies that you should add as well. You can find these libraries referenced in the driver pom file.
In your specific case, the exception you get (`java.lang.ClassNotFoundException: com.arangodb.velocypack.VPackModule`) is because `com.arangodb:velocypack` is missing.

**Comment by Moubassher** [comment]
@rashtao, aha! thank you! rookie mistake.
