### ISSUE TITLE
Arangosh: Registering User Functions returns false for new function ?

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1600]
in arangosh, registering a new user function returns 'false' as if there was some errors in the registration. Registering again the same function  returns true. 
Looks like a bug.

**Comment by jsteemann** [comment]
The function `register()` function in module `org/arangodb/aql/functions` returns `true` when it replaces an existing AQL function of the same name, and `false` otherwise. 
In case the function code is invalid, it throws an exception.

So it actually behaves as intended. I'll update the docs so this become clear.

**Comment by jsteemann** [comment]
The function's return value behavior is now documented.
