### ISSUE TITLE
Concern about configurability

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1602]
Feel free to close this issue right away as this is an abstract/philosophical issue. I just wanted to express my concern after reading the change log for 2.8 beta1 about the proliferation of configuration settings. Every time a new setting is added, the product becomes more difficult to use and likely also more buggy.

For 2.8, four new configuration settings were added for replication to the existing nine settings if I counted correctly. For simplicity, let’s assume these are all just boolean flags. Instead of 512 test cases to make sure replication is working correctly with every different configuration (100% test coverage), you now have to test 8,192 test cases. If they’re all optional configs, the number of required test cases would be even larger.

Aren’t the actual number of legitimate use cases for replication much smaller? For example, couldn’t there be a couple of sensible hardcoded values for all those wait times and timeout settings so all I as a user would have to specify is whether the network between my databases is good or bad (i.e. just one boolean setting). Or even better, have ArangoDB figure it out automatically. Furthermore, what’s the harm in always includingSystem? Or what’s the harm in always being verbose?

I also noticed `--server.hide-product-header`. Couldn't we just expect power users who care about this to run ArangoDB behind nginx?

As a user, I hope ArangoDB is not turning into [this type of monstrosity](https://dev.mysql.com/doc/refman/5.5/en/mysqld-option-tables.html) over time where one needs to hire consultants to get the database optimized.

You guys are the experts. Please make as many sensible decisions for me as possible.

@fceller

**Comment by baslr** [comment]
`I also noticed --server.hide-product-header. Couldn't we just expect power users who care about this to run ArangoDB behind nginx?` Since ArangoDB is OSS I think power users would just compile the header out. I did this, saves cpu cycles and traffic ;)

**Comment by dothebart** [comment]
being able [to hide the server header was requested via stackoverflow](http://stackoverflow.com/questions/33587717/modify-header-server-arangodb)

**Comment by jsteemann** [comment]
Requirements such as `server must not reveal make and version` are common in security audits, even if the benefit is low.

**Comment by fceller** [comment]
@pekeler I would like to keep the issue open as a reminder. We discuss how to simplify the configuration (maybe using certain pre-sets), but no final solution has emerged yet.

**Comment by dothebart** [comment]
Regarding the timing settings - one wants to be able to configure timeouts that wouldn't be feasible for regular production use i.e. if you run a replication slave behind a DSL so you can have your offsite backup.

In general our goal is to provide a configuration in the installation process that works out of the box for what we think can be used in a production environment. 

We're for shure not heading for the monstrocity of mysql. Therefore we quicker deprecate & remove features in concequence. Unlike ...

    cat /etc/postgresql/9.4/main/postgresql.conf |grep -v ^$ |grep =  | grep ^# |wc -l 
                                                  614      -> 240   -> 40 lines

Our config is only 60 lines long, but doesn't have the commented out default setting as postgres does. Maybe rather taking the path of postgres could ease the process of altering the configuration?

**Comment by dothebart** [comment]
With arangodb 3.2 we have introduced several measures to get this done and have arangodb figure out sensible defaults on its own.

 - we analyse how many cores the system offers, and adopt:
  - the number of worker threads we run
  - the number of V8 contexts we initialize on startup, and if neccessary spawn more during runtime
 - we have introduced the [arangodb starter binary that is now packaged with arangodb](https://github.com/arangodb-helper/arangodb#starting-an-arangodb-cluster-the-easy-way) that will take care of bringing together a working cluster environment. 
 - we analyse settings in the linux kernel, and if these values seem odd to us offer the users hints that they may need to be changed

However, we can't anticipate all usecases, and they may also have contrary requirements to whats good "for most". Thus all these automatic adoptations need to be configurable and are - Thus the number of available configuration options massively increased from the time this issue was created. 

So I'll basically think that we did our best to work on this issue and you don't require an Arango-DBA to operate most usecases.

I will close this now.
