### ISSUE TITLE
Arangodb fetches result from database when undefined value in any of the collection.*Example query

### ISSUE THREAD

**Issue by onimisionipe** [arangodb/arangodb#1604]
Whenever I make a query like this collection.byExample({field: undefined}), Arango db tends to return results even when there's no match for the document. I had to place some hacks by using ternary to convert undefined variables to null

**Comment by dothebart** [comment]
This is a side effect of how the javascript `JSON.stringify works.

    arangosh> a={a:undefined}
    { 
      "a" : undefined 
    }
    arangosh> JSON.stringify(a)
    {}

so you effectively specify an empty filter. 

The better way to achieve this is to use AQL (that doesn't suffer from this javascript heritage): 

    arangod> db._query("FOR w IN _users FILTER w.foo != undefined RETURN w").toArray()
    [ 
      { 
        "_id" : "_users/2190325", 
        "_rev" : "2190325", 
        "_key" : "2190325", 
        "user" : "root", 
        "userData" : { 
        }, 
        "authData" : { 
          "active" : true, 
          "changePassword" : false, 
          "simple" : { 
            "method" : "sha256", 
            "hash" : "a4212c472de9d6c3890ab927589bad223c1319a3fbdc3993c8f1dc3aecd033b5", 
            "salt" : "htfK53wHH9sd44uq" 
          } 
        } 
      } 
    ]
    arangod> db._query("FOR w IN _users FILTER w.foo == undefined RETURN w").toArray()
    [ ]

**Comment by onimisionipe** [comment]
Alright.. Thanks

**Comment by CoDEmanX** [comment]
@dothebart: Your queries raises a "collection not found" error. I think one should use the following code instead:

    FOR w IN _users FILTER NOT HAS(w, "foo") RETURN w

**Comment by dothebart** [comment]
oh, you're completely right. I had a collection named `undefined`. and 
a.getExtra()
{ 
  "stats" : { 
    "writesExecuted" : 0, 
    "writesIgnored" : 0, 
    "scannedFull" : 1, 
    "scannedIndex" : 0, 
    "filtered" : 1 
  }, 
  "warnings" : [ 
    { 
      "code" : 1577, 
      "message" : "collection 'undefined' used as expression operand" 
    } 
  ] 
}

would have pointed that out...

**Comment by jsteemann** [comment]
There is no value such as `undefined` in AQL. 
`collection.byExample(example)` should work fine, however, there's one thing about it that's maybe not clear:
if the `example` object contains undefined values, these will be omitted when `JSON.stringify()` is called. An object such as `{ foo : "bar", baz: undefined }` will simply turn into `{"foo":"bar}` after JSON stringification. The stringification is required because ArangoDB's HTTP API is JSON-based. An empty example object (i.e. `{}`) will match all documents in a collection, and that's probably what was confusing in the first place.

The workaround is to do a check on the client side for empty example objects and not send the request to the server if you want no results for this case.

Or to use an AQL query for fetching the results:
`FOR doc IN collection FILTER doc.@attr1 == @value1 && doc.attr2 == @value2 ... RETURN doc`

Note that here there would be the same problem, as `undefined` values will be completely omitted when serializing them via `JSON.stringify()`. So this probably requires a client-side check, too.
The simplest way of achieving this will be: `JSON.parse(JSON.stringify(value))`. This will strip all non-JSON values from the original value, and this is what will be left when sending data from the client to ArangoDB.
