### ISSUE TITLE
Return distinct and pagination

### ISSUE THREAD

**Issue by alxxyz** [arangodb/arangodb#16222]
How to paginate when we need to return distinct documents?
```
FOR user IN users
FILTER ...
LIMIT 10, 10
RETURN DISTINCT user
```
In this case first is executed `LIMIT` and only after that the `DISTINCT`, which is not correct.

**Comment by ysmu** [comment]
Try
```
FOR user IN users
  FILTER ...
  COLLECT distinct_user = user
  LIMIT 10
  RETURN distinct_user
```

**Comment by alxxyz** [comment]
`COLLECT` changes the order of results, so it doesn't work in my case

**Comment by jsteemann** [comment]
> `COLLECT` changes the order of results, so it doesn't work in my case

That is true, but technically speaking, the order of the returned documents is undefined in your original query anyway:
```
FOR user IN users
FILTER ...
LIMIT 10, 10
```
If you want to ensure a specific order of results, you should use a `SORT` crtierion, e.g.
```
FOR user IN users
  FILTER ...
  SORT ...
  COLLECT distinct_user = user
  LIMIT 10
  RETURN distinct_user
```
Please note that the `SORT` will be expensive if there is no index available for it, so you normally want to run on the sort on an indexed attribute, e.g.
```
FOR user IN users
  FILTER ...
  SORT user._key
  COLLECT distinct_user = user
  LIMIT 10
  RETURN distinct_user
```
That said, if you are applying `COLLECT` or `RETURN DISTINCT` on full documents, they will always be distinct, because each document in a collection will at least have different `_key` values.

**Comment by alxxyz** [comment]
Yes I use `SORT`
```
FOR user IN users
FILTER ...
SORT user.createdAt
LIMIT 10, 10
RETURN DISTINCT user
```
Is `SORT` used in `COLLECT` order? It doesn't work for me

**Comment by jsteemann** [comment]
Sort order is not used by `RETURN DISTINCT`, but it should be used when using an explicit `COLLECT` statement:
```
FOR user IN users
  FILTER ...
  SORT user.createdAt
  COLLECT distinct_user = user
  LIMIT 10
  RETURN distinct_user
```
But as mentioned before, using `RETURN DISTINCT` or `COLLECT` on full documents will not provide any benefit, because each document will differ from each other at least by its `_key` value.
So I guess you will need some other criterion for determining uniqueness, otherwise all documents are considered unique anyway, and the DISTINCT/COLLECT is pointless.

**Comment by alxxyz** [comment]
I thought a simple example will be enough, this is my real query
```
FOR product IN products FILTER product.sellerId == @sellerId
FOR review IN reviews FILTER review._to == product._id
SORT review.createdAt DESC
COLLECT productId = review._to 
LIMIT 10, 10
RETURN productId
```
The query return alphabetically sorted ID's, but I need them to be sorted by created date

**Comment by mpoeter** [comment]
Try this:
```
FOR product IN products FILTER product.sellerId == @sellerId
FOR review IN reviews FILTER review._to == product._id
COLLECT productId = review._to AGGREGATE createdAt = MAX(u.createdAt)
SORT createdAt DESC
LIMIT 10, 10
RETURN productId
```

**Comment by alxxyz** [comment]
It works, thanks
