### ISSUE TITLE
Problem with the ternary operator

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangodb#1624]
Hi, 

 I have following aql where I want first to check IP in vTask collection and if it isn't stored there then I need try to select from other collection.

In other words I don't want make a select from both collections, if I have stored IP in vTask, it's not necessary. But Arango always run also second query according to execution plan.

```
let tasks=(for task in vTask filter task.ip == '10.67.125.125' return task)
return length(tasks) == 0 ? (for l3 in vIntL3 filter l3.ip == '10.67.125.125' return l3) : (tasks)
```

**Comment by jsteemann** [comment]
This is a general issue with subqueries: 
they are always pulled out of sub-expressions and executed on their own in the surrounding scope. That means if you write something like `FILTER cond ? (sub1) : (sub2)` the query will be rewritten to `LET temp1 = (sub1) LET temp2 = (sub2) FILTER cond ? temp1 : temp2` and both subqueries will be executed. The same is true for `FILTER sub1 || sub2`, or `FILTER sub1 && sub2` when any of the operands is a subquery.

**Comment by Kurtas** [comment]
So there is no way how do conditional subqueries?

**Comment by jsteemann** [comment]
At least no obvious way comes to my mind. There is one which should work if the condition is runtime-dependent and the optimizer cannot figure out the condition value at compile time.
It requires repeating the condition in the subquery that follows the ternary, and its negation in the other subquery: 
```
let tasks=(for task in vTask filter task.ip == '10.67.125.125' return task)
let isempty = length(tasks) == 0
return isempty ? 
  (filter isempty for l3 in vIntL3 filter l3.ip == '10.67.125.125' return l3) : 
  (filter ! isempty return tasks)
```

**Comment by Kurtas** [comment]
Thanks, but your aql according to explain also uses both collections.
Probably there is now way how to do it. You can maybe add this into feature requests :)

Thanks, Wish happy christmas to whole Arango team

**Comment by jsteemann** [comment]
I think that even though the explain shows the two subqueries being placed on the main level unconditionally, the extra filter inside the true-part subquery should prevent it from being executed:
```(filter isempty for l3 in vIntL3 filter l3.ip == '10.67.125.125' return l3)```

In the above if `isempty` is true, then there shouldn't be reads from the vIntL3 collection. You can validate if it reads from it by modifying that part as follows:
```(filter isempty for l3 in vIntL3 filter fail('should not get here!') && l3.ip == '10.67.125.125' l3)```
If `isempty` is false, then it should not go into the subquery and access the collection. If `isempty` is true, then it should do it of course. The `fail()` function I used is just a quick test to show that the branch is actually executed, because it will make the query abort with the specified message.

Merry christmas to you too!

**Comment by miguel-porto** [comment]
Hi,
I think this is an important issue, I vote up for implementing optimization of the ternary, the `||` and the `&&` operators! They should not evaluate more than is strictly needed to proceed.
Best!

**Comment by dothebart** [comment]
@miguel-porto this was implemented with the 2.8 release.
You should be able to see indices used for || combined `FILTER` statements using the db._explain() command.

**Comment by jsteemann** [comment]
@miguel-porto : I think the issue is about the ternary operator and lazy evaluation. Boolean expressions are actually evaluated lazily, with the exception of subqueries, which are pulled out of expressions and executed independently (and *before* the expression that contained them). That means subqueries will eagerly be executed at the moment and not lazily.

**Comment by miguel-porto** [comment]
Yes, the issue is as @jsteemann describes: subqueries are always evaluated, no matter the value of the condition. The workaround proposed above is simple and definitely works, but... it's a workaround ;-)

**Comment by miguel-porto** [comment]
The problem is that people who are not aware of this, may be experiencing important performance issues with no apparent reason! (like I was, then I found this issue)
Because in other languages these three operators behave as expected: they stop evaluating operands as soon as they don't need to.
best!

**Comment by Simran-B** [comment]
Note that the ternary operator can now be run with native C++ code, which should make some queries faster. How it is evaluated did not change however. See https://groups.google.com/d/msg/arangodb/Nx49F-VNAU8/v1R7YXHzAQAJ
