### ISSUE TITLE
run "RETURN LENGTH(users)" get Warnings

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1627]
I want to get the rows number of users, but when i run
```
RETURN LENGTH(users)
```
i get warning:

```
[1577], 'collection 'users' used as expression operand'
```
 How can I restructure this to avoid the warning?

**Comment by realdog** [comment]
Maybe .....
```
for user in users COLLECT WITH COUNT INTO number return number
```
???????????

**Comment by CoDEmanX** [comment]
I think there shouldn't be a warning for this particular kind of query. Workarounds may require additional computation time and memory, which is probably not what you want just to silence a warning. On the other hand, the optimizer might be able to make it just as efficient as `RETURN LENGTH(...)`. But the code would still be less intuitive. Apart from your `COLLECT` workaround, you could also do:

    LET count = (
        FOR user IN users RETURN 1
    )
    RETURN LENGTH(count)

I'm pretty sure though that this will use a lot more memory, because of the temporary variable `count` with a bunch of ones (could be anything actually).

**Comment by jsteemann** [comment]
The by far fastest method currently seems to be `FOR doc IN users COLLECT WITH COUNT INTO length RETURN length` if the collection contains a considerable amount of documents. However, I agree it makes sense to have the optimizer handle this automatically.

**Comment by jsteemann** [comment]
2.8 will now optimize calls to `LENGTH(collection-name)` internally and not emit a warning for them.
