### ISSUE TITLE
AQL function for setting array value at index

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1639]
It'd be immensely useful if there was an easy way to set the value of an array at a given index.

Let's say I have an array of an unknown size > X and I want to change the value of the array at index X. Unless I've missed something obvious, currently you'd have to do it like this:

```
LET newArray = UNION(
  SLICE(@array, 0, @x),
  @value,
  SLICE(@array, @x + 1)
)
```

Instead I would like to see something similar to `REMOVE_NTH`, e.g.

```
LET newArray = REPLACE_NTH(@array, @x, @value)
```

**Comment by defvoid** [comment]
Sounds like the Javascript `splice` function(?).

**OT**
It might be wise to not depend on elements order in a mutable array. Some languages, like Javascript IIRC, do not guarantee the order and database systems might change the index order for optimizations or what if another user/update changes it.

**Comment by CoDEmanX** [comment]
@defvoid: Are you talking arrays or objects? Element positions in arrays do not change by itself, but only if you mutate arrays explicitly. The JavaScript standard did not guarantee order for object keys, but if I understand correctly, it does since ECMA2015 (insertion order).

JavaScript's splice method would indeed allow pretty much every possible array mutation: `SPLICE(index, deleteCount[, element1[, element2[, elementN...]]])`

A deleteCount of 0 could be used to insert elements at *index*. An index of 0 would `UNSHIFT()`, `LENGTH(array)` `APPEND()` at the end. Likewise, `POP()` and `SHIFT()` could be emulated by not passing any elements to `SPLICE()` and a delete count of 1 at the desired index.

**Comment by dothebart** [comment]
https://www.arangodb.com/docs/devel/aql/functions-array.html#replace_nth is part of Arangodb 3.7
