### ISSUE TITLE
Update in 2.8b3 not modified document

### ISSUE THREAD

**Issue by gendalf** [arangodb/arangodb#1648]
After update o 2.8b3 update query stop working. Sample
```
For P In Product
    FILTER P.spec["broken property"] != null
    UPDATE P WITH { spec: UNSET( P.spec, "broken property" )  } IN Product
RETURN NEW
```
After query NEW == OLD

```
For P In Product
    FILTER P.spec["broken property"] != null
    REPLACE P WITH MERGE(P, { spec: UNSET( P.spec, "broken property" )  }) IN Product
RETURN NEW
```
Working fine

**Comment by jsteemann** [comment]
Can you provide an example value for the `spec` attribute for which it is not working? Thanks.

**Comment by gendalf** [comment]
Object keys have utf8 cyrillic names, broken key-pair in this sample was "диамтр"

```
spec {
    "ширина" : 265,
    "высота": 70,
    "индекс нагрузки" : 115,
    "диаметр": 17,
    "диамтр": 17,
    "индекс скорости": "H"
}
```

Before updating, I am test result with
```
For P In Product
    FILTER P.spec["диамтр"] != null
RETURN { spec: UNSET( P.spec, "диамтр" )  } 
```
And get normal result object without wrong property. But update not change record. 
Also I am tried remove index from 'spec' (hash index spec[*]), not helped, restart arangodb instance also.

In 2.7 I use updating operations with this data many times

**Comment by jsteemann** [comment]
I think the behavior hasn't changed in version 2.8 compared to 2.7 and previous versions. The behavior is actually "feature" (though one may debate its usefulness).

The original document looks like this: 
```json
{
  "spec": {
    "ширина" : 265,
    "высота": 70,
    "индекс нагрузки" : 115,
    "диаметр": 17,
    "диамтр": 17,
    "индекс скорости": "H"
  }
}
```
and obviously the `диамтр` attribute was misspelled and should be removed.
`UNSET(p.spec, "диамтр")` correctly produces a new object without that attribute:
```json
{
  "spec" : { 
    "ширина" : 265, 
    "высота" : 70, 
    "индекс нагрузки" : 115, 
    "диаметр" : 17, 
    "индекс скорости" : "H" 
  } 
}
```
The actual problem is now in how the *UPDATE* works: *UPDATE* will by default attempt to merge all specified attributes with the attributes that are already present in the to-be-updated document. So in this case it will try to (recursively) merge the `spec` attribute in the original document with the modified `spec` attribute (the one that lacks the misspelled attribute). Merging the two will produce an object that again has the `spec` attribute (from the original document) so it looks like no update is happening.
The merging behavior can be controlled with appending an option to the `UPDATE` part of the query: `OPTIONS { mergeObjects: false }`. With merging turned off, the above query would become:
```
FOR P IN Product 
  FILTER P.spec["диамтр"] != null 
  UPDATE P WITH { spec: UNSET( P.spec, "диамтр" ) } IN Product OPTIONS { mergeObjects: false }
```
I agree *REPLACE* is not a good substitute for *UPDATE* here, as *REPLACE* will completely rewrite the target document and not keep any attributes that are not present in the replace document. *UPDATE* is indeed the operation of choice here, though its default merging behavior may come as a surprise.

Long-term it may be more useful to have *UPDATE* operations overwrite the specified attributes without merging, but have a separate *MERGE* operation for doing this.

**Comment by gendalf** [comment]
Thanks @jsteemann, there is documentation for latest all available OPTIONS syntax?

**Comment by jsteemann** [comment]
The [online documentation page for AQL operations](https://docs.arangodb.com/Aql/Operations.html) has a section **UPDATE** with a subsection **Setting query options**. This lists the options `mergeObjects`, `keepNull`, `waitForSync` and `ignoreErrors`.

Note: that documentation page is rather long, and it was split up in a later version of ArangoDB so that *update* got its [own page](https://docs.arangodb.com/devel/AqlOperations/Update.html).
