### ISSUE TITLE
Defining Endpoint to Database within arangosh

### ISSUE THREAD

**Issue by thurt** [arangodb/arangodb#1651]
```
connected to ArangoDB 'tcp://127.0.0.1:8529' version: 2.7.3 [standalone], database: '_system', username: 'root'

arangosh [_system]> db._listEndpoints()
[ 
  { 
    "endpoint" : "tcp://0.0.0.0:8080", 
    "databases" : [ ] 
  }, 
  { 
    "endpoint" : "tcp://127.0.0.1:8529", 
    "databases" : [ ] 
  } 
]

arangosh [_system]> db._createDatabase('new', [], [])
true

arangosh [_system]> db._listEndpoints()
[ 
  { 
    "endpoint" : "tcp://0.0.0.0:8080", 
    "databases" : [ ] 
  }, 
  { 
    "endpoint" : "tcp://127.0.0.1:8529", 
    "databases" : [ ]    <------------- shouldn't 'new' database be listed here ?
  } 
]
```
Can I modify the endpoint to database mappings with arangosh? I want _system database at 127.0.0.1 and 'new' database at 0.0.0.0 .

related: http://stackoverflow.com/questions/33855269/how-to-add-arangodb-database-to-endpoint/33872454

a non-arangodb solution described here: https://docs.arangodb.com/cookbook/MakingFoxxAppAccessible.html

**Comment by jsteemann** [comment]
When there are multiple endpoints mapped, the server saves them in a file `ENDPOINTS` in the server's data directory.
There is no way to modify the endpoints at runtime since 2.6 and 2.7. That possibility got removed in that version because it required using some lock which led to undesired contention when processing incoming HTTP requests.

If you're happy to modify the `ENDPOINTS` file manually, then you can map databases to the endpoints. The file has a structure listing an array of databases per endpoint key like this:
```json
{
  "tcp://127.0.0.1:8531" : ["_system", "abc"],
  "tcp://127.0.0.1:8530" : ["test"]
}
```
If more than one database is listed per endpoint key, then the first one will also be the default database for that endpoint (which will be used when no database name is specified in the URL).

**Comment by thurt** [comment]
Thanks Jan--
This is working now. 

I noticed a small problem when executing foxx-manager and arangosh: It looks like I cannot connect using <code>--server.endpoint tcp://0.0.0.0:8080</code> from the local machine. I'm guessing this a networking/OS factor not an Arango factor since 0.0.0.0 is a broadcast channel (?).

I am instead using <code>--server.database "public"</code> to connect directly to my "public" database from the local machine. I just listed both databases on 127.0.0.1 in <code>var/lib/arangodb/ENDPOINTS</code> so everything makes good sense.
``` javascript
{
  "tcp://0.0.0.0:8080": ["public"],
  "tcp://127.0.0.1:8529": ["_system", "public"]
}
```

**Comment by jsteemann** [comment]
Exactly, `0.0.0.0` is not an IP you can connect to from a client. 
It is a "special" address used to indicate "all local IPv4 addresses" in a server context. And in client context, it means [something different](https://en.wikipedia.org/wiki/0.0.0.0), but no local arangod server's address.
