### ISSUE TITLE
connected components function requested

### ISSUE THREAD

**Issue by kkdd** [arangodb/arangodb#1660]
Hello,
I would appreciate ArangoDB's introducing a connected-component function to AQL.
The example of expected operation and (not-optimized) function's code is as follows:

``` javascript
print(FOR p IN myfunctions::graph::connected_components(graph_example, "to") RETURN p)
  [
    [ 0,1,2,3,4,6 ],
    [ 5,7 ]
  ]

graph_example = [
  {"_key": "0", "to": ["1", "2", "3"]},
  {"_key": "1", "to": ["2"]},
  {"_key": "2", "to": []},
  {"_key": "3", "to": ["4", "6"]},
  {"_key": "4", "to": []},
  {"_key": "5", "to": ["7"]},
  {"_key": "6", "to": []},
  {"_key": "7", "to": []]}
]

//       0
//     / | \
//    1--2  3
//          | \
//          4  6
//    5--7

aqlfunctions.register("myfunctions::graph::connected_components",
function (graph, to) {
  var G = {}, seen = [], components = [], push = Array.prototype.push;
  graph.forEach(function(n){G[n._key] = n.to})
  function notVisted(n) {return seen.indexOf(n) === -1;}
  function traverse(n) {
    seen.push(n);
    var nodes = [n];
    G[n].forEach(function(m){
      if (notVisted(m)) push.apply(nodes, traverse(m));
    });
    return nodes;
  }
  for (var n in G) {
    if (notVisted(n)) components.push(traverse(n));
  }
  return components;
}
)
```

**Comment by roman1720** [comment]
+1 I that would be very useful

**Comment by dothebart** [comment]
Since you need to visit all nodes you have, sounds like it will not scale well regardless whether implemented in AQL or not.
Currently AQL has the limitation that you can't  modify variables once assigned. You would definitely need that to do something like this. 
This limitation was well chosen, since thats the only way to enshure the possibility of many optimizations. 
So once such a `stack` or `temporary storage` would be implemented, a detection of its presence would instantly disable many optimizations.

To get better performance, you would probably have a top level query which iterates vertices filtering for a tag limiting it with 1. From that you would start an [ArangoDB 2.8 traversal](https://docs.arangodb.com/2.8/Aql/GraphTraversals.html) setting the already mentioned tag to all related vertices. You would run this query over and over, until no more items are found. You could probably then use `collect`to get graph vertices grouped - maybe limiting it to 1 so you also have a good starting point.

**Comment by dothebart** [comment]
Create the sample graph:

    var createTraversalExample = function() {
      var g = Graph._create("structured_graph",
        [Graph._relation("connecting", "item", "item")]
      );
      var c0 = g.item.save({name: "0", _key: "0"})._id;
      var c1 = g.item.save({name: "1", _key: "1"})._id;
      var c2 = g.item.save({name: "2", _key: "2"})._id;
      var c3 = g.item.save({name: "3", _key: "3"})._id;
      var c4 = g.item.save({name: "4", _key: "4"})._id;
      var c5 = g.item.save({name: "5", _key: "5"})._id;
      var c6 = g.item.save({name: "6", _key: "6"})._id;
      var c7 = g.item.save({name: "7", _key: "7"})._id;
      g.connecting.save(c0, c1, {});
      g.connecting.save(c0, c2, {});
      g.connecting.save(c0, c3, {});
      g.connecting.save(c1, c2, {});
      g.connecting.save(c3, c4, {});
      g.connecting.save(c3, c6, {});
      g.connecting.save(c5, c7, {});
      g.connecting.save(c0, c1, {});
      return g;
    };

**Comment by CoDEmanX** [comment]
I wonder if the Pregel framework could be used to identify (strongly) connected components in distributed graph...

**Comment by kkdd** [comment]
Determining connected components can be used to get [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN). Its graph is generated as follows:
```
LET graph_example = (
  LET radius = 100
  FOR p IN geojson_points
    LET neigh = (
      FOR q IN WITHIN(points, p.geometry.coordinates[1], p.geometry.coordinates[
0], radius)
        RETURN q._key
    )
    FILTER LENGTH(neigh) > 1
    RETURN {"_key": p._key, "to": REMOVE_VALUE(neigh, p._key)}
)
print(FOR p IN myfunctions::graph::connected_components(graph_example, "to") RETURN p)
```

**Comment by disharmonized** [comment]
+1

**Comment by Simran-B** [comment]
Meanwhile, the Pregel graph processing system offers three different algorithms to determine connected components:

https://www.arangodb.com/docs/stable/graphs-pregel.html#connected-components
