### ISSUE TITLE
Variance in size of backup

### ISSUE THREAD

**Issue by ericfiala** [arangodb/arangodb#1677]
We do periodic backups using something like

arangodump --server.database "wdt" --include-system-collections true --output-directory ....

Is there reason why the size of these backups would fluctuate ?  (increases in size the longer it's been since restart, goes back down to small size once the restart occurs)

these are small sizes 5mb to 20mb - and everytime we've restored them they have been sane - but what could contribute to this difference?

**Comment by baslr** [comment]
arangodump saves revisions to.

```
cat test_098f6bcd4621d373cade4e832627b4f6.data.json
{"type":2300,"key":"2260451821842","rev":"2260454115602","data":{"_key":"2260451821842","_rev":"2260454115602","a":"c"}}
{"type":2300,"key":"2260451821842","rev":"2260619462930","data":{"_key":"2260451821842","_rev":"2260619462930","a":"d"}}
```

**Comment by jsteemann** [comment]
arangodump will stream the contents of the collection datafiles to the client. The more datafiles, and the more data contained in the datafiles, the bigger a backup will be.

The are thus multiple reasons for increasing backup sizes:
* the total number of documents in a collection grows, so the datafiles contain more documents, or there are more datafiles than in previous backups.
* the number of deletions in a collection grows, so the datafiles contain more of them. deletions may be kept for a long time in the datafiles, but they are very small space-wise.
* documents are updated often. In case of an update, a new document revision is written to the datafile, and old (outdated) and new (current) document revisions may coexist in parallel. If many outdated revisions are present in datafiles, the compaction should eventually clean the datafiles. So overall this shouldn't lead to a steady increase if the number of alive documents keeps about constant.
* this may have been caused by issues #1596 and #1662, which have led to the compaction not cleaning the datafiles under some circumstances, leading to datafile growth, and thus a growth of backups.

If possible, can you re-try with 2.7.5 when it's available?

**Comment by dothebart** [comment]
2.7.6 is now available for Download containing @jsteemann s fixes.
