### ISSUE TITLE
Very large database file sizes

### ISSUE THREAD

**Issue by specimen151** [arangodb/arangodb#1713]
I have some test-databases with probably no more than 20 vertices, and five of these databases. On my file system this is more than 1 GB of data. I realize that storage is cheap, but come on, this is ridiculous, and SSD's are not *that* cheap. And backups to a remove server would most certainly benefit.

Is there any "compact job" or similar I should've run? I observe that 7-zipping all of this results in 133 kB.

**Comment by mchacki** [comment]
Hi this is intended behavior.

In fact we reserve some space on the disk and memory to write to. It is way faster to allocate a large file before and fill it as data is stored than to reallocate every time new data is inserted.
Also each database requires some space for system collections, which is a necessary overhead. However if you insert a reasonable amount if data this overhead is not really recognizable as it will not grow further.

So we have a disk footprint of ~300 MB per Database + All your data (which we expect to be way more than 300 MB in real use cases)

The reason why you can 7-zip it to such a small size is because these files are in your use-case mostly empty (just reserved, no data). So i can assure you it is not if you store  20 vertices and use 1 GB it means if you store 200 vertices you need 20GB. It will be ~ 1GB as well.

**Comment by CoDEmanX** [comment]
Related: #1074

**Comment by specimen151** [comment]
Good to know. I guess I should limit the number of test-databases then (e.g. for unit-testing). And for backups I can anyway zip it. Thanks for answering.
