### ISSUE TITLE
Generate UUID in Foxx

### ISSUE THREAD

**Issue by phal0r** [arangodb/arangodb#1736]
Hi Guys,

i have a scenario, where i want to clone documents and create new uuid's inside foxx. There seems to be no integrated way (at least i didn't found one), so i tried to include [node-uuid](https://github.com/broofa/node-uuid), but it requires either getRandomValues() from the WHATWG proposed crypto modules for browsers or randomBytes() from the node.js crypto module. I saw that the Foxx crypto module is there, but empty a.k.a. not implemented yet. Do you have any suggestions for a workaround?

**Comment by pekeler** [comment]
I forked shortid to use Math.random instead of crypto, and use it in my own Foxx app. https://github.com/pekeler/shortid

**Comment by phal0r** [comment]
@pekeler 

thanks for your fast answer. I guess this is the way I will take for now, too. Maybe someone from arango can elaborate on plans that exist or may not exist for the crypto module.

**Comment by pluma** [comment]
My naive assessment (i.e. without knowing what the C++ part looks like) would be that we could provide an implementation of `randomBytes` to make the module work correctly. I'm fairly certain the underlying code already exists (we already have code for generating random numbers and ascii), we'd just need to expose a function that returns a `Buffer` of the given length to JS.

Minor caveat: we have to make sure we don't introduce any accidental bias (especially when trimming the number of bytes) and that the source of pseudorandomness is cryptographically secure. Otherwise implementing it would do more harm than good. I'll open a ticket.

If you just need a random value, try `require('org/arangodb/crypto').getRandomAlphaNumbers()` or `require('org/arangodb/crypto').getRandomNumbers()`.

**Comment by phal0r** [comment]
@pluma 

Thanks for your answer. I guess everything is better than Math.random, so thank you for your insights and I will definitely try that.

**Comment by Simran-B** [comment]
V8 4.9 implements a better Math.random(), but it's still not cryptographically secure:

http://v8project.blogspot.de/2015/12/theres-mathrandom-and-then-theres.html?m=1

**Comment by phal0r** [comment]
@pluma

It's ge**n**RandomNumbers :) The closest working solution i came up with, is the following:

```javascript
var rnd = [];
for(var i=0,len=16;i<len;i++) {
    rnd[i] = parseInt(genRandomNumbers(3),10) & 0xff;
}
return rnd;
```

But I have no idea about the quality of the randomness to be honest. At least it's working for now.

**Comment by pluma** [comment]
@phal0r Oops, you're right.

I'm pretty sure you're introducing bias by discarding bits but I don't know the underlying implementation well enough to say whether it's a safe source of randomness to begin with.

**Comment by dothebart** [comment]
I can only advise that we had a similar thing in native code, which would fail to produce random enough values now and then. The Windows CI uncovered that eventually in the unittests...

**Comment by baslr** [comment]
nodes `crypto.randomBytes` https://github.com/nodejs/node/blob/773b9016aab9ccaf4eb6acdde07bbeef309e4647/src/node_crypto.cc#L5340

calls openssls RAND_bytes https://github.com/nodejs/node/blob/6fff47ffacfe663efeb0d31ebd700a65bf5521ba/deps/openssl/openssl/crypto/rand/rand_lib.c#L155

good advice would be to read from `/dev/random` for strong crypto (key creation …) or `/dev/urandom` for uuids.

**Comment by baslr** [comment]
this should to the trick. On *NIX. https://github.com/baslr/ArangoDB/commit/2612824f57489bc2f8bdd7ebb19eb7c1c54bb1dc
```
arangosh [_system]> a  = require ('@arangodb/crypto')
arangosh [_system]> a.randomBytes(10).toString('hex')
a85e96fef3916497a018

arangosh [_system]> a.randomBytes(10).toString('hex')
cc3a13f6ce84235ef7a1
```

**Comment by pluma** [comment]
I'm closing this as the question has been answered. The feature request is in #1739.
