### ISSUE TITLE
Aardvark better support of browser backbutton

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1749]
When looking at the documents of a collection, going from page 2 to page 3, I'd like to be able to use the browser backbutton to go back to page 3.

When I'm on page 2, click on a document, and then use the back button, I'd like to be back on page 2.

**Comment by baslr** [comment]
among other things, this caused me to start an [alternative](/DUOUNO/ArangoDB-view) frontend for ArangoDB.

`When I'm on page 2, click on a document, and then use the back button, I'd like to be back on page 2.`
I guess this is fixed in devel https://github.com/arangodb/arangodb/commit/6d1efde3851bc0e841067c67d36c7b644e57465e

**Comment by hkernbach** [comment]
Yep, this is fixed in devel.

**Comment by pekeler** [comment]
Excellent!
