### ISSUE TITLE
Foxx 'jsonwebtoken' dependencies require crypto

### ISSUE THREAD

**Issue by boudah** [arangodb/arangodb#1753]
Hi !

I'm trying to use jsonwebtoken node module to implement JWT authentication between my Foxx microservices but it failed as signing or verifying JWT since some dependencies requires crypto (crypto.createHmac function) :
**crypto.createHmac is not a function (in jwa node module)**

Since implementing a JWT authentication between microservices is a good way for a microservices architecture, how can I implement it with Foxx app?

Is it possible to use authentication library like passportjs ?

Thank you !
Florian

**Comment by pluma** [comment]
Hi @boudah,

since there are several differences between Node's and ArangoDB's crypto support, the crypto module can be found at `org/arangodb/crypto`. This sadly means most npm modules that depend on node's crypto module won't work in ArangoDB. I also just noticed the module isn't mentioned in our documentation.

Luckily we provide a JWT implementation in the crypto module which makes it easy to implement JWT auth yourself: https://github.com/arangodb/arangodb/blob/2.8/js/common/modules/org/arangodb/crypto.js#L181-L299

If you prefer a pre-built solution you can also use the JWT session storage for Foxx sessions: https://github.com/arangodb-foxx/util-sessions-jwt

**Comment by boudah** [comment]
Hi @pluma,

The JWT implementation will fit my needs !

thanks for your reply
