### ISSUE TITLE
How to Upload a Photo in foxx ? please help me

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangodb#1767]

**Comment by baslr** [comment]
Hi, maybe this blogpost helps: http://jsteemann.github.io/blog/2014/10/15/handling-binary-data-in-foxx/
docs cookbook section: https://docs.arangodb.com/cookbook/FoxxBinaryFileUploads.html

**Comment by AmmarMohamed** [comment]
this method add meta data to the photo then then the photo do not open in the server !!

**Comment by jsteemann** [comment]
Have you tried the example app that is linked in the blog post?
Its "store" HTTP POST handler creates some meta data for the file as you mentioned, but it also stores the received file on disk. 
Otherwise the "fetch" HTTP GET handler in the app wouldn't be able to return the stored file.

The app shows how to store a file on the server using ArangoDB/Foxx. The file contents are stored separate from the file meta data in this app. This is because arbitrary files are expected to contain binary data, and no JSON values.

**Comment by dothebart** [comment]
@AmmarMohamed please elaborate in a bit more details what you have, and what you want. Maybe you can post your current code state and tell whats missing? To view pictures in the browser, you have to specify the `content-type`-HTTP-header when delivering the image. @jsteemann s blog does that.

**Comment by dothebart** [comment]
closing because of missing feedback.
