### ISSUE TITLE
Improve vertex edit form on graph

### ISSUE THREAD

**Issue by likemusic** [arangodb/arangodb#1774]
At the moment, edit form have fixed size (500px) and button "Save" is not visible on my notebook.
I fix css, for more adaptive view: button "Save" already in bottom, and editor have vary height depends on screen height. 

May be it will be helpful:
- Screenshot: https://yadi.sk/i/bP0QHo7lpyQ2R
- Modified css: https://yadi.sk/d/tT1XrJEVpyQ7r
- Diff with context lines: https://yadi.sk/i/btWitrjcpyQPv

I don't change scss-files because I couldn't convert `\js\apps\system\_admin\aardvark\APP\frontend\scss\style.scss` to style.css, because have error:
`Sass::SyntaxError: ".query-toolbar" failed to @extend "%toolbar".
The selector "%toolbar" was not found.
Use "@extend %toolbar !optional" if the extend should be able to fail.` and I don't find definition of `%toolbar` in exists scss-files.

**Comment by hkernbach** [comment]
Ups, thank you for the tip and a possible solution. Had to adjust it a bit, because some things got messed up with the original document editor. It is now fixed in devel branch.

How did you tried to generate the css files? I added a small section to the README_maintainers file. There you see how the files are usually generated: 
https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#front-end-webui
