### ISSUE TITLE
using the 'Fuerte' C++ lib

### ISSUE THREAD

**Issue by bencz** [arangodb/arangodb#17896]
Hi!
I have a C++ project that I want to change from mongodb to arangodb, how I can use the 'fuerte' SDK on my project ?
It's possible to use it on windows too ?

Also, I saw that the old 'fuerte' repo is closed, and moved to this repo.....

https://www.arangodb.com/2017/11/introduction-fuerte-arangodb-c-plus-plus-driver/

**Comment by dothebart** [comment]
Hi, 
Since fuerte only offers the base layer protocol implementation (http1.1/http2/velocystream) and no API implementation, its of limited use to most applications, since often architectural design decisions will not fit in. 
Its probably the best approach to use https://github.com/arangodb/velocypack and an http2 client implementation that suits your needs best. 

The API is documented here: https://www.arangodb.com/docs/stable/http/ 
and as pointed out there can be interactively be browsed with the Swagger WebUI.

**Comment by bencz** [comment]
Oook!
Nice, mo problem!!
Thanks!
