### ISSUE TITLE
How can we prevent a big gap between WAL and latest sequence number

### ISSUE THREAD

**Issue by zurferr** [arangodb/arangodb#18020]
## My Environment

* __ArangoDB Version__:        3.9.2 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Amazon Linux
* __Total RAM in your machine__:        16Gb
* __Disks in use__:        SSD
* __Used Package__:       Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Start-up of Arango

__Size of your Dataset on disk__:
<5 GB

## Steps to reproduce

1. Service was running for multiple days.
Parameters: 
```
--http.keep-alive-timeout=60 --rocksdb.wal-archive-size-limit 20971520 --server.statistics false --rocksdb.max-total-wal-size 20480000 --rocksdb.write-buffer-size 40960000 --rocksdb.total-write-buffer-size 1638400000 --rocksdb.block-cache-size 1638400000 --rocksdb.cache-index-and-filter-blocks --rocksdb.cache-index-and-filter-blocks-with-high-priority --rocksdb.pin-l0-filter-and-index-blocks-in-cache --rocksdb.pin-top-level-index-and-filter --cache.size 1638400000
```
2. The question is exactly what went wrong

__Problem__:
```
2023-01-26T14:30:32Z [1] INFO [fe333] {engines} RocksDB recovery starting, scanning WAL starting from sequence number 3380384673, latest sequence number: 3832283900
2023-01-26T15:34:58Z [1] INFO [a4ec8] {engines} RocksDB recovery finished, WAL entries scanned: 452301041, recovery start sequence number: 3380384673, latest WAL sequence number: 3832283900, max tick value found in WAL: 1224196673, last HLC value found in WAL: 1755981480530542593
```

__Expected result__:
Not a big backlog of the sequence number. Any hints on how to avoid or minimize this are appreciated. 
And faster startup since, now it took more than 1 hour.

**Comment by jsteemann** [comment]
The following factors exist that can lead to WAL files being retained for longer:
* the WAL isn't garbage-collected for the first 3 minutes after server startup. This value can be configured using the startup option `--rocksdb.wal-file-timeout-initial` if it is too high. However, it should not explain such large difference.
* using any sort of replication (e.g. running in cluster mode, active failover mode, or using the server-to-server replication manually). In this case, the leader may need to retain some WAL files because the followers haven't caught up or are still WAL tailing. Same when the replication APIs are invoked by client applications even without using the actual replication. If you are not using any sort of replication and are not using the replication APIs from client applications, then this cannot cause the problem.
* for every write operation to a collection there are also some deferred operations which are first buffered and only executed once after the write operation returns to the caller. To execute these buffered operations the WAL files need to be retained as well. This can only be a cause if the number of write operations is very high. You should also find corresponding warnings in your logfile about "slow background settings sync" in this case.
* as the issue was reported for version 3.9.2 and the option `--rocksdb.wal-archive-size-limit` was used: there has been a bugfix in 3.9.4 w.r.t. to handling the WAL archive size limit. So I suggest upgrading to latest 3.9.
Thanks!

**Comment by zurferr** [comment]
Wow, thanks for the fast response. Will update for sure and check out the rest.

**Comment by jsteemann** [comment]
Hi @zurferr : no need to close the ticket until confirmed that the upgrade actually remedies the issue. Feel free to reopen anytime.
Thanks!
