### ISSUE TITLE
Fulltext search with a filter with a nested object

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#1802]
This seems like a bug, but not 100 % sure.

I have a database entry like:

``` json
  {
    "_type" : "http://sharejs.org/types/JSONv0",
    "local" : {
      "username" : "ukk",
      "status": "registered"
    },
    "_id" : "users/7b14e2cf-6a01-4a95-87ad-36861739c314",
    "_rev" : "826224821557",
    "_key" : "7b14e2cf-6a01-4a95-87ad-36861739c314"
  }
```

(1) If I do a query like this, I get this as a result:

```
arangosh [some]> db._query('FOR c IN FULLTEXT(users , @v0 , @v1 , @v2) FILTER c.@v3 != null RETURN c', { v0: 'local.username', v1: 'prefix:ukk', v2: 10, v3: '_type' });
[object ArangoQueryCursor, count: 1, hasMore: false]
```

(2) But if I do a query like this, I don't get any results:

```
arangosh [some]> db._query('FOR c IN FULLTEXT(users, @v0 , @v1 , @v2) FILTER (c.@v3 == @v4 && c.@v5 != null) RETURN c', { v0: 'local.username', v1: 'prefix:ukk', v2: 10, v3: 'local.status', v4: 'registered', v5: '_type' });
[object ArangoQueryCursor, count: 0, hasMore: false]
```

(3) Then, if I do a query like this, I get the result:

```
arangosh [some]> db._query('FOR c IN FULLTEXT(users, @v0 , @v1 , @v2) FILTER (c.@v3.@v4 == @v5 && c.@v6 != null) RETURN c', { v0: 'local.username', v1: 'prefix:ukk', v2: 10, v3: 'local', v4: 'status', v5: 'registered', v6: '_type' });
[object ArangoQueryCursor, count: 1, hasMore: false]
```

(4) If I do a query like this, I also get the result:

```
arangosh [some]> db._query('FOR c IN users FILTER c.@v3 == @v4 && c.@v5 != null RETURN c', { v3: 'local.status', v4: 'registered',   v5: '_type' });
[object ArangoQueryCursor, count: 1, hasMore: false]
```

---

Seems like I should get the result with query in `(2)`? 

Using arango 2.8.6.

**Comment by dothebart** [comment]
Well, yes its a bug, but in the other direction than you think. Let me elaborate:

One has to know that there are different representations of documents inside of arangodb; the on-disk format (shaped json) and structured json. Fetching documents directly from the collection uses the shaped json, FULLTEXT() will transform it into the memory json. Attributes are accessed via different code paths; that have in your case different 'features' since they see different strings for the attribute access. To get a better idea of whats going on inside the database, we can use the `db._explain()` Facility:

    db._explain('FOR c IN FULLTEXT(test2, "local", "prefix:ukk") FILTER c.@v3 == @v4 && c._type != null RETURN c', {v3: 'local.status', v4: 'r
    Query string:
     FOR c IN FULLTEXT(test2, "local", "prefix:ukk") FILTER c.@v3 == @v4 && c._type != null RETURN c
    
    Execution plan:
     Id   NodeType            Est.   Comment
      1   SingletonNode          1   * ROOT
      2   CalculationNode        1     - LET #1 = FULLTEXT(test2   /* all collection documents */, "local", "prefix:ukk")   /* simple expression */
      3   EnumerateListNode    100     - FOR c IN #1   /* list iteration */
      4   CalculationNode      100       - LET #3 = ((c.`local.status` == "registered") && (c.`_type` != null))   /* simple expression */
      5   FilterNode           100       - FILTER #3
      6   ReturnNode           100       - RETURN c

Node 4 has the core of the problem; If you have a closer look at it you see its doing  `c."local.status"`, so its trying to access something like this: 

    {
        "local.status": true
    }

And you're expecting it to do:

    {
        local: {
           status: true
        }
      }

so while the json accessor does the first thing, which is the correct thing to do here, the shaped json gets a string with the access that it splits at the dots, resulting in the second thing. ArangoDB 3.0 doesn't have that distinction in Memory anymore; so you then will be able to access attributes with dots in them across all facilities. 

I guess you'd like to compute the attribute access string somewhere, and have it splitted at the dots, right? So while I will label this `won't fix` for 2.8, in 3.0 we will enable you to express this by putting a list into the bind parameter: 

    { v3: ["local", "status"],...}

so: 

    FOR doc IN collection FILTER doc.@what == 'bla' RETURN doc

with bind values

    { what: [ "a", "b" ] }

will reference `doc.a.b`

Thanks for raising this and the awareness attribute access via bind variables :+1:

**Comment by ile** [comment]
Hi,

Ok, but in `(4)` the explain seems similar:

```
arangosh [some]> db._explain('FOR c IN users FILTER c.@v3 == @v4 && c.@v5 != null RETURN c', { v3: 'local.status', v4: 'registered',   v5: '_type' })
Query string:
 FOR c IN users FILTER c.@v3 == @v4 && c.@v5 != null RETURN c

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      6     - FOR c IN users   /* full collection scan */
  3   CalculationNode              6       - LET #1 = ((c.`local.status` == "registered") && (c.`_type` != null))   /* simple expression */   /* collections used: c : users */
  4   FilterNode                   6       - FILTER #1
  5   ReturnNode                   6       - RETURN c

Indexes used:
 none

Optimization rules applied:
 none



```

So the difference is the FULLTEXT, but on the surface this seems like an inconsistency? I mean, I don't change much here, but still functionally it's a lot different (doesn't return the result)?

**Comment by dothebart** [comment]
Yes, and as I tried to explain, this a bug up to the ArangoDB 2.8 release that this actually works by referencing `c.local.status` instead of  `c."local.status"`. 

In ArangoDB 2.8 the FULLTEXT() function will emit a structure that is different to the direct on disk representation (emitted by `FOR c IN collection `).

The implementation for this different structure is implemented properly to be able to address `c."local.status"`.  ArangoDB 3.0 only knows a single representation from on disk data through out the source, which then will also be able to properly handle the `c."local.status"` for `FOR c IN collection`)

**Comment by ile** [comment]
Ok ok, that was clear. Got it. Thank you.

**Comment by ile** [comment]
Hmm, did I miss something after all? This doesn't seem to work in 3.0:

```
127.0.0.1:8529@some> db._query('FOR c IN auths FILTER c.@v0 == @v1 RETURN c', { v0: 'local.reg.token',     v1: 'b1c1ea413529e35b02d2' });
[object ArangoQueryCursor, count: 0, hasMore: false]
```

But this does:

```
127.0.0.1:8529@some> db._query('FOR c IN auths FILTER c.@v0.@v1.@v2 == @v3 RETURN c', { v0: 'local', v1: 'reg', v2: 'token',     v3: 'b1c1ea413529e35b02d2' });
[object ArangoQueryCursor, count: 1, hasMore: false]
```
I thought the format `'local.reg.token'` was going to be "universally" supported everywhere (ie. in queries with or without FULLTEXT) in 3.0?

**Comment by Simran-B** [comment]
Please try the following:

    { v0: ['local', 'reg', 'token'], ... }

**Comment by ile** [comment]
Yes, that works, thank you!

This means less work for me, so I prefer this to the "longer" format (@v0, @v1, @v2)...

**Comment by ile** [comment]
In FULLTEXT this `['string1', 'srting2']` didn't work, one has to use `'string1.string2`. 

A little confusing...
