### ISSUE TITLE
Transaction in node js 

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangodb#1815]
the transaction in arangojs driver doesn't run ?? is there any wrong  code or is there an bug!!

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
```
editSchools_admin:function (obj) {
        var doc=obj.gg;
        var doc2=obj.adminAccount;
		
	var action = String(function (){
      return db.database("g")
                 .then(function (mydb) {
                     console.log("Fdvndfgnkdgdeza");
                     var edge = {"role": "gg"};
                     return mydb.collection('gg').then(function (collection) {
                         return collection.save(gg).then(function (res) {
                             var schoolsHQSAdmin = res;
                             return mydb.collection('gg').then(function (collection) {
                                 return collection.save(gg).then(function (res1) {
                                     var gg = res1;
                                     return {"gg": gg, "gg": gg}
                                 }).then(function (res2) {
                                     var gg = {"role": "gg"};
                                     return mydb.edgeCollection('gg').then(function (collection) {
                                         console.log(res2);
                                         return collection.save(
                                             edge,
                                             res2.gg,
                                             res2.gg
                                         );
                                     });
                                 })
                             });
                         });

                     });

                     // return [gg , gg];
                 });

		});
		
		return db.database('gg')
            .then(function (mydb).transaction({write :['gg','gg','gg']}, action);
    }

```

**Comment by baslr** [comment]
JavaScript code executed in ArangoDB is synchronous.

https://docs.arangodb.com/Transactions/TransactionInvocation.html

https://github.com/arangodb/arangojs#transactions

Simple example:
```es6
var db = require('arangojs')();
var action = String(function () {
    // This code will be executed inside ArangoDB!
    var db = require('org/arangodb').db;
    return db._query('FOR user IN _users RETURN u.user').toArray<any>();
});
db.transaction({read: '_users'}, action)
.then(result => {
    // result contains the return value of the action
});
```

**Comment by AmmarMohamed** [comment]
yes i use this code @baslr

**Comment by baslr** [comment]
@AmmarMohamed 

your action code is asynchronous.

```es6
var action = String(function (){
  var db = require('db');
  var schoolsWay = db.use('SchoolsWay'); // dont know if this is correct?

  var edge = {"role": "SchoolHQ"};
  schoolsWay.SchoolsHQSAdmins.save(schoolsHQ.adminAccount)
});
```
and so on. Also schoolsHQ is not defined.

**Comment by pluma** [comment]
@AmmarMohamed I'm assuming you're using the driver from Node.js because it was written to be used in Node.js or browsers, not inside ArangoDB itself (where you can just use the ArangoDB API directly, which is synchronous as @baslr pointed out).

In node.js (and browsers) all network I/O is asynchronous. Historically this required using callbacks. In modern JavaScript the better solution is generally to use promises. The JavaScript driver for ArangoDB supports both interfaces though you should use promises IMO.

In your code example you're returning a promise (calling `then` on a promise returns another promise for the `then` function's result) and calling `String` on the promise directly. Because the code that resolves the promise is executed asynchronously and the code that returns the promise is executed synchronously, the return value of the function is the promise itself and you're calling `String` on a promise that is still pending.

**There is no synchronous way to get the value of a promise, even if it is already resolved/rejected.**

Here's a mostly-accurate guide on how promises work: http://www.html5rocks.com/en/tutorials/es6/promises/

Here's a terser and more technical explanation from MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

If you want a more complete introduction into asynchronous JavaScript I also recommend Kyle Simpson's wonderful book series "You Don't Know JS", especially the book *Async & Performance* that is available on GitHub for free: https://github.com/getify/You-Dont-Know-JS/tree/master/async%20%26%20performance

**Comment by AmmarMohamed** [comment]
Great , But now I need to use  transaction function in arangojs what can I do to run the function successfully I have tested  asynchronous and synchronous doesn't run  @pluma

**Comment by pluma** [comment]
Ah, I misunderstood what you're trying to do. The code in the action doesn't use the JS driver but the ArangoDB API itself, which is slightly different as it is (as @baslr pointed out) synchronous. The code outside that function also looks like it is using an older version of the driver (i.e. 3.x rather than 4.x). I think your code should look something like this, but it's hard to tell as you seem to have introduced a few reference errors while anonymizing it:

```js
function (args) {
  var action = String(function (args2) {
    // This code runs inside ArangoDB!
    // args is not available here
    var db = require("org/arangodb").db;

    // Create a user from the supplied arguments
    var usersCollection = db._collection('users');
    var user = args2.user;
    var meta = usersCollection.save(user);
    Object.assign(user, meta);

    // Create an admin role from the new user to an existing school
    var rolesCollection = db._collection('roles');
    var schoolId = args2.schoolId;
    var role = {"role": "admin"};
    meta = rolesCollection.save(user._id, schoolId, role);
    Object.assign(role, meta);

    return [user, role];
  });

  // Switch what db the Database object represents
  db.useDatabase('schooldb');
  // pass in args to the function (as "args2")
  return db.transaction(['users', 'roles'], action, args);
}
```

**Comment by dothebart** [comment]
@AmmarMohamed Did the answer fullfill your needs? If not, whats missing? If, can you close the issue?
