### ISSUE TITLE
Performance of DOCUMENT() function in AQL

### ISSUE THREAD

**Issue by jurrian** [arangodb/arangodb#1828]
I've done some benchmarking and found that the DOCUMENT() function seems to be much slower than iterating and filtering.
My benchmark test:

Setting up a test table with some dummy content
```
FOR i IN 1 .. 100000
  INSERT { value: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."} IN test
)
```

**Filter iteration benchmark**
```
LET x = (

FOR i IN 1 .. 1000000
  FOR z IN test
    FILTER z._key == '2999473087761'
  RETURN z
)

RETURN LENGTH(x)
```
Takes 6.567 s

**Document function benchmark**
```
LET x = (

FOR i IN 1 .. 1000000
  RETURN DOCUMENT('test', '2999473087761')
)

RETURN LENGTH(x)
```
Takes 21.965 s

Why is the Document function so much slower than the Iteration?
I haven't found an anwer explaining the difference or any reason why the document function shouldn't  be used. What I've found is that the [Document function has recently been updated](https://www.arangodb.com/2015/12/aql-function-speedups-in-2-8/).

A [similar question ](http://stackoverflow.com/questions/33135854/arangodb-get-document-by-id-with-cache-per-query)can be found here but doesn't really address the difference.

Intuitively, I would think that searching a collection on the primary _key attribute (I guess using a binary tree) should be way faster than iteration over all of them.

Is there any reason why I shouldn't be using the Document function to resolve id's?
I'd like to have a well performing function to get a single item by index in a collection without having to write FOR IN FILTER constructions all the time.

**Comment by dothebart** [comment]
The answer is easy. Try running: 

     db._explain(<your query>)

You will see that the version with the `FILTER` does an index lookup, which then will fetch one document with the matching `_key` from the collection. 

Your second loop doesn't use indexes for filtering. Its basically looking up each document in the index, and building up the result. Once you've got that result with all documents ready, you `LENGTH()` it, and throw it away.

**Comment by jsteemann** [comment]
@jurrian: sorry for the confusion, but I think the answer is not quite complete yet. 

It's correct that the explain output does not show any index usage for the `DOCUMENT()`-based variant of the query. However, `DOCUMENT()` will always use the primary index behind the scenes. And looking up a document via its primary key still has amortized complexity of O(1), regardless of whether this is done via a `FOR doc IN collection FILTER doc._key == ...` or `DOCUMENT()`.

The difference between the two is how the results are processed later: `DOCUMENT()` is a function call internally, and the function results will be fully materialized. So you'll end up with an array of materialized documents for variable `x`, and this materialized array will be passed into the `LENGTH()` function later in the query.
When using the `FOR ... FILTER` variant of the query, there is a shortcut that allows returning a simple pointer to the found documents, so you're ending up with an array of pointers only. This is much cheaper, so this variant wins the competition.
Note that the above is true for the pre-3.0 branches. Starting with 3.0, there will be less internal materialization of data for function calls, so in 3.0 using the `DOCUMENT()` variant will also get much cheaper.
Also note that one advantage of the DOCUMENT-based solution it is more flexible because the collection name can be dynamic and specified in a variable or expression, where as the `FOR ... FILTER` variant needs the collection name to be known at query compile time.

**Comment by jurrian** [comment]
So will the DOCUMENT-based solution be the best practice after the release of 3.0? Please correct me if I'm wrong @jsteemann, so the DOCUMENT-based solution will in time be faster than the FOR ... FILTER method or will it be equally as fast?
If that's true it would resolve the point I'm addressing, but also in an elegant way.

**Comment by jsteemann** [comment]
`DOCUMENT()` will still be a different in 3.0 because it's fully dynamic (collection names not known until execution time), so it _may_ lose a bit (but not much) to the `FOR ... FILTER` approach.
However, the goal is to make the `DOCUMENT` function about as fast as the FOR ... FILTER alternative. 

The FOR ... FILTER-based approach also has the advantage that it may theoretically use other indexes. `DOCUMENT()` is tied to querying the primary index with the `_key = ...` condition, but the `FOR ... FILTER` theoretically is not. 
I say theoretically because at the moment `FOR .. FILTER` on _key will always use the primary index on `_key`, the same as the `DOCUMENT()` function will do. But that may change in the future. The FOR ... FILTER approach may benefit from general optimizer improvements and use other conditions and indexes, whereas the `DOCUMENT()` function has no insight into the rest of the query and therefore will be limited to using the primary index on `_key`. But for now (3.0) that difference is theoretical.

**Comment by dothebart** [comment]
3.0 RC2 is available for Download & testing - eager to hear your feedback ;-) https://www.arangodb.com/download-preview/

**Comment by jurrian** [comment]
I have ran my benchmark as specified in my first post.
The results are truly amazing!

**Filter iteration benchmark:**
_2.8.5_: 6.567 s
_3.0.0_: 3.043 s
_Performance_: 216% faster

**Document function benchmark**
_2.8.5_: 21.965 s
_3.0.0_: 0.947 s
_Performance_: 2319% faster

I've done this a couple of times and the results seem pretty accurate.

I think it is safe to say that using the document function should be the new best practice.

**Comment by jsteemann** [comment]
Thanks for taking the time for repeating the benchmark in 3.0.0.
I am glad that 3.0.0 is a lot faster than 2.x in your tests as well. 
We're also trying to close the gap between the FILTER-based and the DOCUMENT-based solution, by optimizing the FILTER-based lookups. Work on this is still ongoing.

By the way, are you going to publish the numbers anywhere? If so, could you let us know? (our marketing is obviously interested in things like this)

**Comment by jsteemann** [comment]
We pushed some improvements for the lookups in the past few days, and I wanted to keep you updated with the results.
Here's the document creation & selection queries that I compared in current 2.8, current 3.0 and the devel branches:
**Insertion**:
```js
db._drop("test"); 
db._create("test"); 
time = require("internal").time; 
q = `FOR i IN 1 .. 100000 
     INSERT { _key: CONCAT("test", i), value: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."} IN test`; 
s = time(); 
db._query(q); 
result = time() - s;
```
**Selection**:
```js
q1 = `LET x = (FOR i IN 1 .. 1000 * 1000 FOR z IN test FILTER z._key == 'test9974' RETURN z) RETURN LENGTH(x)`; 
q2 = `LET x = (FOR i IN 1 .. 1000 * 1000 RETURN DOCUMENT('test', 'test9974')) RETURN LENGTH(x)`; 
time = require("internal").time; 
s = time(); 
db._query(q1); 
resultFilter = time() - s;  
s = time(); 
db._query(q2); 
resultDocument = time() - s; 
```

**Results for insertion**:
* 2.8: 0.388430118560791 s
* 3.0: 0.27876877784729004 s
* devel: 0.2644670009613037 s

**Results for selection-based query**:
* 2.8: 1.7981820106506348 s
* 3.0: 1.7445998191833496 s
* devel: 0.8118541240692139 s

**Results for DOCUMENT function-based query**: 
* 2.8: 5.349531173706055 s
* 3.0: 0.5659470558166504 s
* devel: 0.4674558639526367 s

So we got a bit closer again, but still there's some gap left. And we're still eager to fix this difference.

**Comment by jsteemann** [comment]
However, closing for now, as the original question is answered.
