### ISSUE TITLE
accessing collection.properties().isSystem or collection.count() without loading

### ISSUE THREAD

**Issue by kkdd** [arangodb/arangodb#1833]
I would like not-loading collections when accessing collection.properties().isSystem or collection.count().
I have tested that the following loads collections and doesn't run fast:

```
$ cat listCollections.js
#!/usr/local/bin/arangosh --javascript.execute
print("\033[1m" + db._name(), "\033[0m");
db._collections().forEach(function(c){if (!c.properties().isSystem) print(c._name,
 c.count())})
//db._collections().forEach(function(c){if (c._name[0]!='_') print(c._name)}) // This doesn't load collections.
$
```

**Comment by baslr** [comment]
you can use the http call  `GET /_db/_system/_api/collection`. But this will give you only access to the `isSystem` property.

**Comment by dothebart** [comment]
Its currently not possible to access statistics of that sort without loading the collection. We may be able to get at least *some* available, but definitely not *all*. The document count could be part of that *some*. Adding feature request label therefore.

**Comment by grexe** [comment]
oh no I just ran into this and I'm surprised this issue is still open:(

I *need* to check the size of a collection and (pre)load it into memory in our server application if the number of documents exceeds a given limit, sothat the first client access does not take too long.
The journal size is not a good indicator I guess, and sadly the API does not provide me with the size of the datafile, so what should I do?
Alternatively, ArangoDB could support setting custom properties on collections, such as `large`, or provide another estimate (e.g. database size), or store the number of documents per collection in a system collection?

**Comment by grexe** [comment]
for my usecase, #1821 which is still open would also make a lot of sense, any progress there?

**Comment by dothebart** [comment]
with the new rocksdb engine in ArangoDB 3.2 opening collections won't be that resource intense anymore.

**Comment by jsteemann** [comment]
@grexe: with ArangoDB 3.2 we do offer an alternative storage engine based on RocksDB. The RocksDB-based storage engine provides instant loading of collections (loading is a no-op there), so count, properties and figures should be accessible instantly there. The behavior of the other storage engine (which is the default and only storage engine in 3.1) has not changed.

**Comment by grexe** [comment]
that's great to hear, will keep an eye on 3.2 tech previews then.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing the rocksdb storage engine is now available for download - Closing.
