### ISSUE TITLE
UDF not appearing when listing UDFs, but still usable

### ISSUE THREAD

**Issue by normanuber** [arangodb/arangodb#1837]
Ref: https://github.com/arangodb/arangodb/issues/1213

I think that ticket pretty much explains this.

Arango 2.8.9

Using the web interface shell:
JSH>  require("org/arangodb/aql/functions").toArray();
==> [ ]

JSH>  require("org/arangodb/aql/functions").toArray("udf");
==> [ ]

JSH>  require("org/arangodb/aql/functions").unregisterGroup("udf")
==> 0

but my traversal still works.
TRAVERSAL(devices, interface_link, device._id, "outbound", {
    strategy: "breadthfirst",
    order: "preorder",
    itemOrder: "forward",
    followEdges: [ { link_type: "upstream" } ],
    filterVertices: "udf::filterDevice",
    uniqueness: {"vertices": "path"},
    paths: true
  }).

If I modify the filterVertices function to a undefined function then it complains, as expected.

**Comment by normanuber** [comment]
Ah weird, after posting this the query no longer works O.o. Is there a cache or something I don't know about?

**Comment by Simran-B** [comment]
User-defined AQL functions are stored in a system collection `_aqlfunctions` in the database they were registered in.

Is it possible that you initially tried to remove it from a different database? (Happened to me once, I didn't realize that I registered it in two different databases and unregistered it not from the one I was looking at, but the other one)

Or perhaps it took abnormally long to delete the document in `_aqlfunctions`? Was it still in use maybe, so that it was still in memory until the completion of a traversal that was ongoing?

**Comment by normanuber** [comment]
I dropped the old database and started anew with the same name and was wondering why I was still able to use it. I'm guessing it took longer than it should have to clear that.

**Comment by dothebart** [comment]
@normanuber the things you execute in `jsh>` are done in the browser unless you execute code that does the remoting to the ArangoDB server like `db._queyr(....)`. Please note that you should rather use pattern matching traversals for your queries ([see here for more details on pattern matching traversals](https://docs.arangodb.com/2.8/Aql/GraphTraversals.html))

**Comment by normanuber** [comment]
Well, it was working in both which is why I wondered if it was cached. I was refreshing my web page with the udf and was shocked it was working. I'll try again to rebuild the database sometime and see if it happens again.

**Comment by dothebart** [comment]
@normanuber any news on this? or could we close this?
