### ISSUE TITLE
API inconsistent with manifest.json in developer mode

### ISSUE THREAD

**Issue by jakobrosenberg** [arangodb/arangodb#1851]
v2.8.9

I create a new service called ´´test´´ with two collections ´´collection1´´and ´collection2´´

Swagger shows CRUD for both collections as expected.

I remove ´´collection1´´from manifest.json and Swagger occasionally includes it on refresh.

I re-add ´´collection1´´to manifest.json and Swagger occasionally shows both collections. Out of ten refreshes only the fourth refresh correctly showed both collections.

Is this expected?

**Comment by dothebart** [comment]
do you see that in the rendered swagger json or just in the graphical output of swagger.io?

**Comment by pluma** [comment]
This problem will no longer occur when using the new Foxx API in ArangoDB 3.0 but may still be present in services running in the legacy compatibility mode for ArangoDB 2.x services. It's caused by a known limitation of the old Foxx internals and non-trivial to change. Basically not every V8 thread is running the same version of the service and some HTTP requests may end up hitting those outdated versions.

Doing a "proper" upgrade with the service bundle should correct this and the problematic behaviour can be avoided entirely by running the server with a single V8 thread (which is obviously not recommended for production).

Please give ArangoDB 3.0.0-rc2 a try. We've provided an extensive guide for migrating 2.x services to the new 3.0 API as well as guide for running 2.x services in the legacy compatibility mode to make the transition easier.
