### ISSUE TITLE
Getting '401' unauthorized in foxx service after disabling all authentication in config file

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1888]
Team,
  I was getting http 401 unauthorized in foxx service after disabling authentication in all the config files.

Later I commented out the below lines in foxxes.js and it started working.

anonymousRouter.get('/docs/*', module.context.apiDocumentation(
  (req, res) => {
    //console.warnLines("Test Message "+req.suffix);
    if (req.suffix === 'swagger.json' && !req.arangoUser) {
      //res.throw('unauthorized');
    }
    return {
      appPath: decodeURIComponent(req.queryParams.mount),
      indexFile: 'index-alt.html'
    };
  }
));

I realised that req.arangoUser was coming 'undefined'.

Regards,
Sajeev

**Comment by dothebart** [comment]
One needed to check whether: 
    internal.authenticationEnabled()

is set too. Thanks for reporting.

**Comment by sajeevpr** [comment]
Also I could see that eventhough the service was throwing 401, it was executed in the server despite 401.

**Comment by dothebart** [comment]
the throw() line you commented out is directly responsible for the 401 - so thats the place where processing will stop.

**Comment by sajeevpr** [comment]
Yes agreed. But its worth validating.

**Comment by pluma** [comment]
@sajeevpr the web interface is a Foxx service, so ArangoDB doesn't prevent access to it when a request contains no credentials. However it still parses and validates the credentials, so the Foxx service can check the `arangoUser` (which is the username ArangoDB has verified, or `undefined` if no credentials were provided or they weren't valid) to protect against unauthenticated access where needed. This check of course happens within the Foxx service itself.

This is why the Foxx service that provides the web interface can serve you a login page at all -- otherwise instead of a login page you'd only see a 401 straight from ArangoDB itself with no clue on how to authenticate.

Foxx handles HTTP error responses by allowing you to throw a specific error representing the error status code you wish to respond with using `res.throw`. So throwing the error is the correct behaviour when authentication is enabled. It passes back through the routing stack and is translated into the appropriate (JSON) error response by Foxx itself.

**Comment by sajeevpr** [comment]
ok. Thank you all
