### ISSUE TITLE
Feature request: capped skiplist index

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1908]
In my use case I have a collection with a property id which is the _key as a number.

the id has a skiplist index to query fast the item with the highest id
`FOR doc IN docs SORT doc.id DESC LIMIT 1`

All indices for the collection are ~1,18 GB. I removed the index for id and indices are now ~0,727 GB. So 39 % memory saved.

It would be nice to have a skiplist index which covers only a configurable subset of the collection.
In my case only one document.

```es6
ensureIndex({type:'skiplist', fields:['id'], keep:1, rule:'>'});
// > means insert only when greater than smallest element
```

**Comment by dothebart** [comment]
After a short discussion with @jsteemann we see the point from a user perspective, but don't see a way how this could be implemented on the server side - for this reason I would like to decline this feature request.

The problem here is, that on each insert/update/delete the server would have to re-evaluate the pointer of this highest number with varying cost (and the probability of a full table scan) - which will be really hard to explain to users, why a single document delete takes ages. You may say - in my usecase the biggest ID is never deleted, so this cost won't apply for me - but the database has to provide a generic implementation that takes these cases into account. 

If you want to spare memory, you'd probably best maintain this via a second collection, containing one document with the current `id` and the `_id` of the document in question inside of the real collection. If you know that you don't need to do a re-election to an eventually existing lower number you're set.

**Comment by dothebart** [comment]
Closing as discussed in slack.
