### ISSUE TITLE
arangodb 3.11.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [arangodb/arangodb#19115]
## My Environment

* __ArangoDB Version__:       3.11.0

## build failure log

```
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/utils/utils.h:333:29: error: integer value 31 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]
  static constexpr T kMax = static_cast<T>(kNumValues - 1);
```

See full build log in here, https://github.com/Homebrew/homebrew-core/actions/runs/5085853623/jobs/9155128035
relates to https://github.com/Homebrew/homebrew-core/pull/131916

**Comment by dothebart** [comment]
hi,
Please note that a custom clang is required to compile ArangoDB on MacOS.
See https://github.com/arangodb/arangodb/blob/3.11/VERSIONS for details.
Further we recommend using Linux docker containers to run ArangoDB on Macos, since its next to impossible to get a stable capable CI covering MacOS with full ArangoDB coverage these days.

**Comment by Simran-B** [comment]
As the compiler that ArangoDB requires can apparently not be used for homebrew (https://github.com/Homebrew/homebrew-core/pull/109923#discussion_r975171543), ArangoDB does no longer support, maintain, nor endorse homebrew from version 3.10 on. The recommended way of running ArangoDB on macOS is to use the official Docker image.

https://www.arangodb.com/docs/stable/installation-mac-osx.html
