### ISSUE TITLE
Consideration Needed: Upgrade V8 and Transition from GYP to GN Build System

### ISSUE THREAD

**Issue by Jingwiw** [arangodb/arangodb#19116]
Is there a plan to upgrade V8? I've attempted to build on a riscv64 architecture machine, but the older V8 lacks support for riscv64. Simply replacing the V8 source code seems unfeasible. I tried replacing it with the version 11.6.19 code, but it results in the error：
"gyp: Error importing pymod_do_main module (detect_v8_host_arch): No module named 'detect_v8_host_arch' while trying to load ../gypfiles/all.gyp." 

Also, I noticed that the newer version of V8 recommends using GN for building instead of GYP. Is there any plan to replace the build system?

**Comment by dothebart** [comment]
I can't tell when the next V8 upgrade is gonig to happen.
However, if, its going to be copied from the nodejs source, since the maintain the gyp-files.

**Comment by Simran-B** [comment]
There is at least one additional issue with newer V8 versions: The pointer compression introduced in v9.2 limits the memory to 4 GB, and it's unclear whether the option to opt out will remain available.

**Comment by u382514** [comment]
Understandable that it would be a lot of work however to stay competitive, and a legitimate database solution, these features need to stay up to date, swapped out or deprecated. Otherwise expectations won't meet reality. 

For Instance, we love the Foxx microservice feature for rapid prototyping and even use it in smaller production systems. It's positioned in way that makes it much easier to modularize, break-off and scale out as the system grows. Unfortunately we've had to dumb down code that would work in a stable node.js environment to work in Foxx. The experience makes you second guess if this database is being actively worked on.   

I'd like to see movement in upgrading the V8 engine as well.

**Comment by dothebart** [comment]
ArangoDB 3.12.2 is available with a laer V8. 
We remained with gyp since ninja doesn't support gnu-jobserver.
