### ISSUE TITLE
Sort and bindVars

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangodb#1917]
When i run this query on 3.0.1:
`{
query: "FOR i in collection SORT @someAttribute return i",
bindVars:{someAttribute: 'i.lastName'}
}
`
The result not/randomly sorted. These type of queries worked on 2.7 perfectly. Is this change intentional?

Environment: Ubuntu 15.10 64bit, arangoDB 3.0.1, tested from js driver and ArangoDB web interface too.

**Comment by CoDEmanX** [comment]
I think the query should rather be:

    { query: "FOR i IN collection SORT i.@someAttribute return i", bindVars:{someAttribute: 'lastName'} } 

It's possible that `i.lastName` worked in 2.x because of the inconsistent handling of dots in attribute keys (they were interpreted as sub-element access instead of literally in many places).

`i.lastName` in 3.x will look for an attribute "i.lastName" (if at all) and not an attribute `i` with a sub-attribute `lastName`.

**Comment by legikaloz** [comment]
I've tried this formula too, but originally with another dot in the variable :`data.lastName`. How to pass a bindvar with one or more dot(s)?

**Comment by Simran-B** [comment]
This is probably the query you are looking for:

    FOR doc IN test SORT doc.@var RETURN doc

With bind variable:

    { "var": [ "data", "lastName" ] }

Although it's also possible to:

    SORT doc.@x.@y
    { "x": "data", "y": "lastName" }

Have a look here:

https://docs.arangodb.com/3.0/Manual/ReleaseNotes/UpgradingChanges30.html#attribute-names-and-parameters

**Comment by legikaloz** [comment]
Thanks, I overlooked that in the release notes. It'd be great to mention this in the doc too.

**Comment by jsteemann** [comment]
:+1: for adding it to the docs.

**Comment by jsteemann** [comment]
@Simran-B : would you be so kind to add this to the docs? thanks!

**Comment by Simran-B** [comment]
Yep, already assigned myself on Trello. Closing it here.

**Comment by jsteemann** [comment]
Thanks!

**Comment by Simran-B** [comment]
The following documentation change adds more details about bind parameters: https://github.com/arangodb/arangodb/commit/e363290a66e7465cfab9239f6ae11a6a37614fae

@legikaloz: is this sufficient or do you think the description should be more thorough?

**Comment by legikaloz** [comment]
Sorry for my late reply. I've read the changes. 

> Note that { "attr": "a.b.c" } would return the value of an attribute called a.b.c, not the value of attribute c with the parents a and b as [ "a", "b", "c" ] would.

I think this sentence is really important so I'd give a little more emphasis on it (i almost overlooked that in the extended docs)

**Comment by Simran-B** [comment]
I agree, but I would like to post-pone that. We have several remarks in the docs that deserve to be highlighted. My idea is to write a plugin for Gitbook so that we can add colored boxes with icons for several types of emphasis (info, warning, ...). To avoid coding it twice, we should first do the upgrade to Gitbook 3.x. Some things are still buggy in that version, and I would actually like to get rid of the intermediate step with the preprocessor as we use it at the moment. This will take some time to sort out.
