### ISSUE TITLE
Access database from Foxx service

### ISSUE THREAD

**Issue by oastashev** [arangodb/arangodb#1925]
Hi,

Is it possible to access custom database from Foxx service deployed in '_system' database?

Details: 
1. In just installed ArangoDB creating database 'test'. So we have two databases: '_system' and 'test'. 
2. Then deploying  service 'test_service' in database '_system'.
3. Now I want access database 'test' from service 'test_service'. Is it possible? 

ArangoDB v3.0.0

**Comment by dothebart** [comment]
Foxx services are only allowed to access the databases they're deployed to. 
Since they're intended to be self contained and possibly be installed multiple times, they add a prefix to their collection names. Thats however not enforced - you can also access collections without that prefix - but should handle errors accordingly (if it doesn't exist...)

**Comment by oastashev** [comment]
Hm... As for me, it makes sense to give "_system" services ability to access any databases and any collections for monitoring or supervision purpose or any other "superuser" needs.

Anyway thank you for response.

**Comment by pluma** [comment]
I think you could switch databases inside a Foxx service running in the `_system` database (as long as you switch back afterwards) but even if it is possible (and I'm not sure it is) this is certainly not recommended.

IMO if you want to interact with other databases running in the same cluster/server, you probably don't actually want to have multiple databases.
