### ISSUE TITLE
High vulnerability in runc cli tool - Update to version 1.1.5 needed 

### ISSUE THREAD

**Issue by JPaulAlf** [arangodb/arangodb#19275]
## My Environment

* __ArangoDB Version__:        3.10
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Infrastructure__:               AWS
* __Operating System__:       Linux 
* __Used Package__:         https://download.arangodb.com/arangodb310/RPM/x86_64

__Problem__:

I hope this message finds you well. I wanted to reach out to you regarding a potential security issue that has been reported in the "runc" cli tool version 1.1.4.

Recently, a high vulnerability was reported in this tool, and I wanted to bring it to your attention in case you haven't already seen it. The details of the vulnerability can be found here: 
- https://nvd.nist.gov/vuln/detail/CVE-2023-27561
- https://nvd.nist.gov/vuln/detail/CVE-2023-28642

To address this issue, I strongly recommend updating the "runc" cli tool to version 1.1.5.
I was wondering if you have any information on when there will be a release with a fix for this security risk?

Thank you for your attention to this matter, and happy coding! 💪🏻😎

**Comment by JPaulAlf** [comment]
@dothebart Thank you, i will just want to confirm if the package/tool is from ArangoDB. Thanks for your quick response!! :)

**Comment by JPaulAlf** [comment]
@dothebart  Thank you, i will just want to confirm if the package/tool is from ArangoDB, since our CVE tool show those high CVEs related to "runc" and we don't use it.

Yes, that is the package/tool.

Thanks for your quick response!! :)

**Comment by JPaulAlf** [comment]
@dothebart I have rechecked the CVEs and they come from the usr/bin/arangodb path, so I assume they come from the ArangoDB package, since that's the package's directory. 

![Screenshot 2023-06-21 at 12 48 46 PM](https://github.com/arangodb/arangodb/assets/66691893/968e98c1-401b-485c-87f5-1fda4fb0dd7f)

**Comment by nikita-vanyasin** [comment]
Hello @JPaulAlf !
1) if you are using Kubernetes then you probably using official Docker images and not RPM package? In this case arangodb binary is not executed at all.
2) What exact version of 3.10 package you are using? The latest `v3.10.8` contains [latest](https://github.com/arangodb-helper/arangodb/releases/tag/0.15.8) arangodb binary which has `runc` updated to `v1.1.5`

In general we trying to update all dependencies before releasing new version for latest available security fixes. Please let me know if this issue is still relevant to you. I'll move the ticket to relevant repo 👌🏻 

Best,
Nikita

**Comment by JPaulAlf** [comment]
@nikita-vanyasin Thanks for the info, I was using ArangoDB 3.10.5, I will update my Dockerfile to the latest version of ArangoDB 3.11 available and see if the CVEs are still there 👏
