### ISSUE TITLE
"unregistered collection used in transaction" should indicate which collections were illegally accessed

### ISSUE THREAD

**Issue by hbCyber** [arangodb/arangodb#1943]
I am submitting complex Javascript transactions to ArangoDB 3.0.x -- and sometimes I forget to declare some of the collections, of which I have many. Please note that I use 'allowImplicit = false' to ensure that my transactions are serializable.

It's already quite the task to go through all my Javascript to figure out which collections I need to declare, but when I encounter this error, I have no indication with respect to which collection is missing.

Suggest adding the collections which caused the issue to the error. For example:
"unregistered collection used in transaction: account"

**Comment by jsteemann** [comment]
Which ArangoDB version are you using? I am asking because I remember some similar issue ("unregistered collection used in transaction") has been resolved in 3.0.1.
If the error persists with 3.0.1 or newer, then there may indeed be a non-declared collection being used in the transaction. 
When we fixed the issue for 3.0.1 we also checked whether we could add the collection name to the error message. It turned out that the error is generated in some internal function that returns an error code only and not message string and additionally does not have access to the collection name (but only the id). We may try catching the error in some layer above it where we still have access to the collection name.

**Comment by hbCyber** [comment]
Just happened to me today with 3.0.2, thanks for the details, looking forward to see if it will be resolved

**Comment by jsteemann** [comment]
I have committed a fix for this in the devel branch. I am not 100% sure if this handles all possible occurrences of that particular error, but at least it did report the collection name in the tests I did.
I would like to let the patch hang around in devel for a few days to check if it has any side effects. If not, I will be happy to commit it in 3.0 as well.

**Comment by hbCyber** [comment]
That's amazing, that will really speed up my development. Thanks a lot!

**Comment by jsteemann** [comment]
Backported fix to 3.0.

**Comment by Simran-B** [comment]
@jsteemann: Is #1954 somehow related?

**Comment by jsteemann** [comment]
Fix included in 3.0.4, which was released today.
