### ISSUE TITLE
Doc site is quite slow,can you provide instruction about how to compile documentation?

### ISSUE THREAD

**Issue by AlexLuya** [arangodb/arangodb#1951]
Hello,
     Can't find a way how to do,can you guys provide a way how to do in README?

**Comment by weinberger** [comment]
Did you see that you can download it as a PDF or ebook? Maybe it is a
workaround for now.

https://docs.arangodb.com/3.0/Manual.pdf


Am 19. Juli 2016 um 16:57:44, Luya Alex (notifications@github.com) schrieb:

Hello,
Can't find a way how to do,can you guys provide a way how to do in README?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arangodb/arangodb/issues/1951>, or mute the thread

**Comment by AlexLuya** [comment]
Thanks,I knew it,html will be prefered.

**Comment by dothebart** [comment]
the html tarball can be found here: https://docs.arangodb.com/documentation.tar.gz

**Comment by Simran-B** [comment]
Instructions on how to compile the documentation (if really desired) can be found here:
https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#documentation

**Comment by dothebart** [comment]
I hope you meanwhile found the tarball? feel free to reopen if not.
