### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by tthil** [arangodb/arangodb#1955]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 2.8
- [ ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: OS X
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

This is my query and its very slow. What could I do to enhance the performance?
The accommodation collection has ~14,000 documents and suppliers ~6,000 documents.

Query string:

    FOR sup IN @suppliers
      FOR supplier IN suppliers
        FILTER supplier._key == CONCAT(sup, @countryCode)
        RETURN { 
           supplier: supplier, 
           accommmdations: (
               FOR prod IN @products
                   FOR acc IN accommodations     
                       FILTER acc.productID == prod && 
                              acc.supplierId == supplier.supplierId && 
                              acc._key == CONCAT(acc.productID, @countryCode)
                       RETURN acc
           )
       }

    Execution plan:
     Id   NodeType                   Est.   Comment
      1   SingletonNode                 1   * ROOT
      2   CalculationNode               1     - LET #6 = [ "8119", "4803" ]   /* json expression */   /* const assignment */
      3   EnumerateListNode             2     - FOR sup IN #6   /* list iteration */
     17   IndexNode                     2       - FOR supplier IN suppliers   /* primary index scan */
     14   SubqueryNode                  2         - LET #4 = ...   /* subquery */
      7   SingletonNode                 1           * ROOT
      8   CalculationNode               1             - LET #10 = [ "49809", "49816", "45250", "36842", "39872" ]   /* json expression */   /* const assignment */
      9   EnumerateListNode             5             - FOR prod IN #10   /* list iteration */
     10   EnumerateCollectionNode   69405               - FOR acc IN accommodations   /* full collection scan */
     11   CalculationNode           69405                 - LET #12 = (((acc.`productID` == prod) && (acc.`supplierId` == supplier.`supplierId`)) && (acc.`_key` == CONCAT(acc.`productID`, "THA")))   /* simple expression */   /* collections used: acc : accommodations, supplier : suppliers */
     12   FilterNode                69405                 - FILTER #12
     13   ReturnNode                69405                 - RETURN acc
     15   CalculationNode               2         - LET #14 = { "supplier" : supplier, "accommodations" : #4 }   /* simple expression */   /* collections used: supplier : suppliers */
     16   ReturnNode                    2         - RETURN #14
    
    Indexes used:
     By   Type      Collection   Unique   Sparse   Selectivity   Fields       Ranges
     17   primary   suppliers    true     false       100.00 %   [ `_key` ]   ((supplier.`_key` == CONCAT(sup, "THA")))
    
    Optimization rules applied:
     Id   RuleName
      1   use-indexes
      2   remove-filter-covered-by-index

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

**Comment by jsteemann** [comment]
I have created the following test dataset for reproduction:
```js
db._create("accommodations"); 
for (i = 0; i < 14000; ++i) { 
  var id = String(i);  
  db.accommodations.insert({ supplierId : String(i % 401), productID : String(i), _key: String(i) + "THA"  });
}
db._create("suppliers"); 
for (i = 0; i < 6000; ++i) {
  db.suppliers.insert({ supplierId : String(i), _key: String(i) + "THA" });
}
```
I have used the following bind parameters when running the query:
```
bind = { 
  products: [ "1234", "4432", "3324", "5993", "4958" ], 
  suppliers: [ "8119", "4803" ], 
  countryCode: "THA" 
};
```
Not sure if those are appropriate, but it was the best I could come up with given limited information about the dataset.

First of all, the query runs a few times faster in my 3.0 than in my 2.8 ArangoDB, though the execution plans are identical in both versions.

The main problem of the query seems to be that it does not use any index on `accommodations` in the subquery, and will always perform a full collection scan. I am not sure if there are any indexes on `supplierId` or `productID` in `accommodations`, but it seems there aren't. The index on `_key` cannot be used to look up a document from `accommodations` in this query, because the filter condition on `_key` refers to the document itself: `(acc._key == CONCAT(acc.productID, "THA")`. In order for this to work, the document must be fetched first and the attribute `productID` must be extracted. Then this would provide the condition for the `_key` index lookup. However, the document has already been fetched, so no index will be used. Worse, this action will be performed for all documents from the collection.
The key to making this query run faster is therefore to get rid of the full collection scan on `accommodations`. This can be achieved by either indexing `supplierId` or `productID` in that collection. But the best tuning will be to change the filter condition on `_key` from `(acc._key == CONCAT(acc.productID, "THA")` to some condition like `(acc._key == CONCAT(prod, "THA"))` which does not refer to the document on both sides of the expression. Not sure if this particular condition is appropriate, but as long as you don't refer to the document on both sides of the condition, the index on `_key` will be used.

**Comment by jsteemann** [comment]
The above will help in both 2.8 and 3.0, though the query runs a lot faster with and without the modifications in my 3.0 when comparing it to my 2.8 build.

**Comment by tthil** [comment]
Thank you jsteemann.
Works perfect. By changing the condition the response went from over 3 min to 2 sec.

**Comment by tthil** [comment]
How could I get the result to be nested like this:
{supplier:{
  supplierId: "12345",
  accommodations: [
    {ID:1, name: accom1}, {ID:2, name: accom2}...]
  },
  supplier:{
    supplierId: "67890",
    accommodations: [
    {ID:3, name: accom3}, {ID:4, name: accom4}...]
  }....
}

**Comment by jsteemann** [comment]
Try changing the `RETURN` part of the query like this:
```
RETURN { 
  supplier: supplier.supplierId,  /* return only Id of supplier */
  accommmdations: (
    FOR prod IN @products
      FOR acc IN accommodations     
      FILTER /* ...  use filter condition as usual */
      RETURN { 
        ID: acc.ID,  /* attribute that contains accommodation id */
        name: acc.name  /* attribute that contains accommodation name */
      }
  )
}

**Comment by tthil** [comment]
Thank you jsteemann.
But I need the whole supplier document with the accommodation list inserted as an array.

**Comment by jsteemann** [comment]
```
RETURN { 
  MERGE([
    supplier, 
    { accommmdations: (FOR prod IN @products ... RETURN ...) }
  ])
}
```

**Comment by tthil** [comment]
I get a error message when I use MERGE.
{"errorNum":1512,"errorMessage":"unknown variable 'use of unknown variable 'MERGE' in object literal near '([\n        supplier: supplier.su...' at position 5:14' (while parsing)"}

**Comment by jsteemann** [comment]
I think my previous answer had superfluous square brackets around the MERGE. It should rather be:
```
RETURN MERGE([
  supplier, 
  { accommmdations: (FOR prod IN @products ... RETURN ...) }
])
```

**Comment by Simran-B** [comment]
Shouldn't it be like this?

```js
RETURN MERGE(
  supplier,
  { accommodations: (FOR prod IN @products ... RETURN ...) }
)
```

It should return the full supplier document with an additional attribute `accommodations` with the sub-query result (which is an array).

**Comment by tthil** [comment]
Thank's.
Worked!
