### ISSUE TITLE
process.env properties could be overriden with unit tests

### ISSUE THREAD

**Issue by ilearnio** [arangodb/arangodb#1973]
In short, when you set `process.env.SOMETHING = 'foo'` somewhere in Mocha unit tests and then run tests, it constantly overrides the env value so it doesn't flip back to previous value even after tests are already passed.

PS: Arangodb 3.0.3, OS X El Captain

TL; DR;

I'm running my arangod process by passing an env variable like so:

``` bash
export ARANGO_ENV='development'; \
arangod \
  --server.authentication=false \
  --server.endpoint tcp://127.0.0.1:8529 \
  --http.trusted-origin 'http://localhost:3100' \
  --javascript.app-path $(shell pwd)/foxx_apps \
  --javascript.startup-directory /Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb3/js \
  --database.directory /Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/var/lib/arangodb3 \
```

So that I can detect the current environment using `process.env.ARANGO_ENV`. It works fine.

In my `manifest.json` I have the following unit testing configuration:

``` json
"tests": [
  "test/init.js",
  "**/__tests__/**/*.js"
]
```

And in the very first test file ("test/init.js") I have this line `process.env.ARANGO_ENV = 'test'` which overrides this env variable from 'development' to 'test', which is useful in my case.

When I'm running the server and firing some api requests via http, the `ARANGO_ENV` is "development", when I then running tests (via browser) it overrides to "test" which is ok, but the problem is that it doesn't flip back to "development" after tests are passed

**Comment by pluma** [comment]
Yes, changes you make to the global environment will persist after the tests are completed. There is currently no way to avoid this.

In the long run we may want to run tests in one-off V8 contexts but this would come at a significant performance cost.

**Comment by dothebart** [comment]
Since process.env simply maps the processes environment to js, and there is just one environment per process (which is shared across all threads and all available V8 Contexts) I don't see any good way to implement this outside. 

The best way to achieve this is to store the setting in the setup routine, and flip it back in the teardown method. However, this way meanwhile all other currently running threads will also see this environment variable state.

I don't see a way how foxx or arangod could be able to do this for you; 

My next best guess would be that having an own database for the unittest foxx apps, and working with this database name as an indicator could be a viable approach.

**Comment by pluma** [comment]
The safest solution is probably to set `process.env.ARANGO_ENV` in each test suite's `setup`/`before` function and then reset it in the `teardown`/`after` function. As tests are executed synchronously and the `env` object is not shared between threads, this would not affect any other code. However this makes it useless when e.g. perfoming HTTP requests against ArangoDB itself (which would likely be handled by contexts unaware of these changes).

For this reason I don't recommend messing with globals in your tests at least not if you depend on that state outside the test code itself.
