### ISSUE TITLE
"2023-09-09T06:30:00.000Z" == "2023-09-09T06:30:00Z" is false

### ISSUE THREAD

**Issue by Queatz** [arangodb/arangodb#19747]
Is it expected that a datestring with `.000` is not equal to one which only descrbes seconds?

## My Environment

* __ArangoDB Version__:        3.11.2

## Component, Query & Data

__Affected feature__:
AQL

__AQL query (if applicable)__:
```
return "2023-09-09T06:30:00.000Z" == "2023-09-09T06:30:00Z"
```

## Steps to reproduce

1. Excecute AQL `return "2023-09-09T06:30:00.000Z" == "2023-09-09T06:30:00Z"`
2. Expect `true` but get `false`

**Comment by dothebart** [comment]
Hi, 
since arangodb only knows strings in there, this is just a string comparison, and hence these strings are obviously non equal. 
You should normalize your date strings https://www.arangodb.com/docs/stable/aql/functions-date.html to be able to compare them. 
If you want to use indices,  normalization  would best be done during ingesting the data.
