### ISSUE TITLE
Bugs in negated `instanceof` expressions

### ISSUE THREAD

**Issue by gorosgobe** [arangodb/arangodb#19795]
`in` and `instanceof` expressions in JS
```js
a in obj;
a instanceof C;
```
can be negated by grouping them and applying the `!` operator, i.e.

```js
!(a in obj);
!(a instanceof C);
```

Applying the `!` operator incorrectly (on the LHS operand) leads to bugs:
```js
!a in obj; // will evaluate to false, unless obj has a "true" or "false" key
!a instanceof C; // will evaluate to false, unless C overrides instanceof with a @@hasInstance method
```
For more information, please see these [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#not_an_instanceof) and [the no-unsafe-negation recommended Eslint rule](https://eslint.org/docs/latest/rules/no-unsafe-negation).

I have found several potentially problematic instances of the above bugs in your codebase:
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/arangodb/arangodb%24+lang:javascript+/%5C%21%5B%5B:alnum:%5D%5D%2B+instanceof+%5B%5B:alnum:%5D%5D%2B/+-file:%5C.min%5C.js%24+count:all&patternType=standard&sm=1&groupBy=repo

**Comment by dothebart** [comment]
Hi, 
thanks for letting us know. 
https://github.com/arangodb/arangodb/pull/19796 fixes the found instance in our own testcode; since this is not shipped with production, it will not be backported. 
Sigma.js is a complete library which is going to be replaced soon. 
The 3rd instance is v8-testcode which as well is not part of the final product and hence will not be fixed.
