### ISSUE TITLE
Info Wall Recovery finished succesfully

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#1997]
## my environment running ArangoDB
- [x] 3.0
- [x] Windows, version: 8

I Inserted ten million document to a collection. in another query in duration of Insert ten millions of document I canceled my process.
now when I run ArangoDB server, I see follow image:
![utyuytu](https://cloud.githubusercontent.com/assets/13764362/17692561/8a6b0ff0-63af-11e6-9620-10c86bb402ca.PNG)

now I cant use ArangoDB server!
what I must be do?

**Comment by jsteemann** [comment]
Is the arangod process busy at that stage, i.e. is it using CPU or is it causing notable disk activity?
If yes, then it is probably loading a collection or rebuilding indexes. This may take a while, especially if the data does not fit in the available RAM. If data does not fit in RAM, you will like see the server causing disk read activity.

**Comment by namnik** [comment]
@ jsteemann : yes it's eventually was finished...
another question: I want to store milliard document in ArangoDB, is it ok? didn't have any problem about performance and speed?
thanks a lot

**Comment by jsteemann** [comment]
In general you will need as much RAM as the combined size of the documents and their indexes.
Otherwise ArangoDB will fall back to disk activity for almost every operation, which will heavily slow down the server.
We are currently working on a version that will lower the RAM requirements, but it will take some time until it will be released.
