### ISSUE TITLE
important questions on the key value

### ISSUE THREAD

**Issue by alexblattner** [arangodb/arangodb#2004]
the following are questions about automatically generated key values only:
1.how does the key value generate a value? what is the procedure itself?
2. what is the string lenght limit? what characters will be used?

i would apreciate it if i could get a response as fast as possible because there is no information about my questions in your official website.

**Comment by jsteemann** [comment]
> 1.how does the key value generate a value? what is the procedure itself?

The _key value will be automatically generated by the server if the _key attribute is not provided in a document. The generated _key is always a string containing numeric digits. _key values reflect chronological time in the sense that _key values generated later will contain higher numbers than _key values generated earlier. But the exact _key value that will be generated by the server is not exactly predictable. 
There is also the option to use an autoincrement _key generator on a single server. In order to do so, create the collection like this:
`db._create("test", { keyOptions: { type: "autoincrement", increment: 1 } });`
This will create _key values with an increment of 1, starting at value 1.
Note that the _key values will still be strings, so sorting by them will use the string sort (e.g. "100" < "99").

> 2. what is the string lenght limit? what characters will be used?

There are some restrictions for _key values in general, listed here:
https://docs.arangodb.com/3.0/Manual/DataModeling/NamingConventions/DocumentKeys.html

Auto-generated keys will obey these restrictions. Whatever key generator is used, the auto-generated _key values will contain numeric digits only. 

Note that all the above concerns ArangoDB 2.x and 3.0.

**Comment by Simran-B** [comment]
Added Jan's explanation to the docs regarding the currently used format for document keys.

@alexblattner: does it answer your question?

**Comment by dothebart** [comment]
Closing as answered.
