### ISSUE TITLE
Issue with DELETE /_api/cursor/{cursor-identifier} endpoint's http status code

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#2008]
Hello! I am using ArangoDB version 3.0.5.

According to ArangoDB REST API documentation:

```
DELETE /_api/cursor/{cursor-identifier}:
 
202: is returned if the server is aware of the cursor.
404: is returned if the server is not aware of the cursor. It is also returned if a cursor is used after it has been destroyed.
```
When I call this endpoint it *always* seems to return a 404, even when the cursor with a given ID exists.
Is this an intended behaviour? 

Thanks,
Joohwan

**Comment by jsteemann** [comment]
It works for me whenever I try it.

**Create cursor**
```
curl -X POST http://127.0.0.1:8529/_api/cursor --data '{"query":"FOR i IN 1..20 RETURN i","batchSize":10,"ttl":900}' --dump - --basic --user "root:"
HTTP/1.1 201 Created
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 259

{"result":[1,2,3,4,5,6,7,8,9,10],"hasMore":true,"id":"298923533","extra":{"stats":{"writesExecuted":0,"writesIgnored":0,"scannedFull":0,"scannedIndex":0,"filtered":0,"executionTime":1.659393310546875e-4},"warnings":[]},"cached":false,"error":false,"code":201}
```
**Delete cursor**
```
curl -X DELETE http://127.0.0.1:8529/_api/cursor/298923533 --dump - --basic --user "root:"
HTTP/1.1 202 Accepted
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 43

{"id":"298923533","error":false,"code":202}
```

The 404 error in your case probably arises because the cursor has automatically expired on the server. The default time-to-live for a cursor is currently 30 seconds, so if there is a delay of more than 30 seconds between creating/reading from the cursor and deleting it, the server will return a 404 error on the deletion attempt. 
As you can see above, I have adjusted the *ttl* value in the cursor creation request so that my example is easier to reproduce. 

Can you confirm this is working for you as well?

**Comment by joowani** [comment]
Hi Jan,

Yes you were right it *was* the issue with TTL.
Thanks very much for looking into it!

Regards,
Joohwan
