### ISSUE TITLE
Arithmetic doesn't seem to work when using shorthand syntax

### ISSUE THREAD

**Issue by specimen151** [arangodb/arangodb#2016]
Feature request/inconsistency
---
Arithmetic doesn't seem to work when using shorthand syntax. I'm not saying it's a bug, but it would be nice if this would work:

```
for n in 1..0
RETURN { n -1 }
```

In ArangoDB 3.0.5 it will give a syntax error, but in the full form

```
for n in 1..0
RETURN { n: n -1 }
```
works.

When returning an object with many parameters, the shorthand syntax is so nice, it's a shame to loose it.

Of course, if this makes parsing slow or problematic, it's not that important, so you decide. In which case I'd update the documentation with some limitations on the shorthand.

**Comment by jsteemann** [comment]
The syntax error you're seeing is intentional in AQL.

The shorthand syntax in AQL is similar to the one that is used in JavaScript.
If in an object literal no colon is used to separate a property name from the value, the specified property must be an identifier (i.e. a variable name).

The following works in JavaScript, as the property is an identifier (`n`):
```js
n = 1; 
a = { n }; 

{ 
  "n" : 1 
}
```
The following does not work in JavaScript, as the property is an expression (`n - 1`):
```js
n = 1;
a = { n - 1 }; 

JavaScript exception: SyntaxError: Unexpected token -
!n = 1; a = { n - 1 };
!               ^
stacktrace: SyntaxError: Unexpected token -
```
An expression cannot be given a trivial property name in all cases, as this would require stringifying the expression. For example, what should be the property name for the expression `n - 1`? Should it be `"n"`? Or `"n - 1" or `"n-1"`. Because it is not fully intuitive what the outcome should be, this is not supported at all, neither in JavaScript nor in AQL.

**Comment by specimen151** [comment]
It's an interesting question what the property name would be for `n-1`, didn't think of that, just assumed `n`. Put that way, I can see problems for more "interesting" expressions. Shared syntax with JavaScript is also a good argument.

Closing the issue, thanks for a comprehensive answer, just needed to understand.
