### ISSUE TITLE
arangoimport progress issue when in spawned shell 

### ISSUE THREAD

**Issue by berry4u** [arangodb/arangodb#20270]
## Windows

* __ArangoDB Version__:        3.8.6
* __Deployment Mode__:       Single Server
* __Operating System__:       Windows 10 

when arangoimport is used in a spawn cmd shell of Node.js the progress data is not displayed in stdout using the following code: 

child.stdout.setEncoding('utf8');
child.stdout.on('data', (data) => {
			process.stdout.write(` ${data}`);
		});

All data are correctly displayed except the progress, which are displayed correctly when executed in window cmd shell in the following form:
2023-12-04T19:08:50Z [41896] INFO [9ddf3] {general} processed 1048575 bytes (3%) of input file
2023-12-04T19:08:50Z [41896] INFO [9ddf3] {general} processed 1553256 bytes (10%) of input file
...

**Comment by jsteemann** [comment]
The progress notification of arangoimport are written out using ArangoDB's logger. 
The log output can be written to stdout or a file, based on configuration.
The config file (on Linux) can be found in a location such as `/etc/arangodb3/arangoimport.conf`. I don't know exactly where the config file can be found on Windows, however, if you don't know where it is, the config file location can be passed as an argument to arangoimport when invoking it, e.g. `arangoimport -c /path/to/arangoimport.conf ...`.
The entry in the config file that determines where to log to is
```
[log]
file = ...
```
or
```
[log]
output = ...
```
The latter is slightly more flexible. You can use whatever output file location that is convenient and then capture the log file from nodejs.
Documentation on it can be found here: https://docs.arangodb.com/stable/components/tools/arangoimport/options/#--logoutput
If the output location for logging is already set correctly, I guess that setting the option
```
[log]
foreground-tty = true
```
will also help. Otherwise, if arangoimport is not run in a terminal, the logger will only log to regular files but not to stdout.

Btw all options can be passed to arangoimport as command-line arguments when invoking it, e.g. `arangoimport --log.foreground-tty true --log.output ...`.

**Comment by dothebart** [comment]
Please note that ArangoDB 3.8 is EOL; you should upgrade to at least 3.10 if not 3.11.

**Comment by berry4u** [comment]
I am afraid I have not explained my problem well.
the arangoimport logs are well displayed in stdout except for the progress lines.
As you can see, the following two logs are obtained with the same command but the first directly in cmd shell and the second in a spawn process. As you can see, the second one is missing the two progress lines 

![image](https://github.com/arangodb/arangodb/assets/33978204/ac7c6705-b347-4137-a676-cba6d6ab3884)

![image](https://github.com/arangodb/arangodb/assets/33978204/cb03d638-308b-4c1f-87fc-8889862a53b1)

**Comment by Simran-B** [comment]
```js
const { spawn } = require("node:child_process");

let child = spawn(
  "C:\\Program Files\\ArangoDB3 3.11.6\\usr\\bin\\arangoimport.exe", [
    "--file", "file.csv",
    "--type", "csv",
    "--server.endpoint", "tcp://127.0.0.1:8529",
    "--server.authentication", "false",
    "--server.database", "TestImport",
    "--create-database",
    "--collection", "coll",
    "--create-collection",
    "--log.foreground-tty",  // <-----------------------------
  ]);

child.stdout.setEncoding("utf8");

child.stdout.on("data", data => {
  process.stdout.write(data.toString());
});

child.stdout.on("close", code => {
  console.log("Exit code:", code);
});

child.stdout.on("error", err => {
  console.log("Error:", err.message);
});
```

<img width="770" alt="image" src="https://github.com/arangodb/arangodb/assets/7819991/107e6b48-64b0-47d0-a0ab-ea95806abaf6">
