### ISSUE TITLE
Agency not working after v3.0.5

### ISSUE THREAD

**Issue by Calpicow** [arangodb/arangodb#2044]
Tried spinning a new set of 3 agencies with v3.0.6 and v3.0.7. Logs look good, but coordinators/primaries/curl can't connect.

Rolled back to v3.0.5 and works fine. Using official Docker images.

**Comment by dothebart** [comment]
A DC/OS setup works flawless for me [tm].
So without more details about your setup I won't be able to do anything with this.
There have been fixes to the agency in .6 and .7, so I'd urge you to get it updated.

**Comment by Calpicow** [comment]
I've found that this behavior is flaky. Sometimes it would start up but not respond to any connections. Naturally, a bigger agency cluster will increase the chances of this happening. I changed my health check from TCP to HTTP and it eventually works after restarting a few times.

**Comment by kvahed** [comment]
I thing that I know, what is hindering you. in order to be able to claim any distributed safety of the stem brain of the cluster, we had to make some crucial bug fixing. the test was the so called jepsen test, which is an open-source effort, which you will find here: github.com/aphyr/jepsen. 
could you do the following, please: start the agents with the following additional parameters: 
--agency.election-timeout-min 2.0 --agency.election-timeout-max 10.0

**Comment by kvahed** [comment]
Fixed in 3.0.10

**Comment by Simran-B** [comment]
Looks like this issue should be closed (internal Trello ticket was already archived).
