### ISSUE TITLE
Accessing multiple database collections from AQL

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2046]
Dear Team,
  It would be nice to have a feature to access multiple database collections from AQL.

Thanks & Regards,
Sajeev Ramakrishnan

**Comment by dothebart** [comment]
Hi, 
AQL doesn't know about databases, and lives inside of one database.
Since user authentication from i.e. foxx is on database level, it would be a security problem if you could easily change the database during the query. 
So, thanks for the sugestion, but we are definitely not going to implement this - thus I will close this now.

**Comment by sajeevpr** [comment]
ok. But many RDBMS systems give synonyms to read data from other schemas. I was thinking in this lines.

**Comment by Simran-B** [comment]
Doesn't schema translate to table, not database?

**Comment by sajeevpr** [comment]
Schema translates to set of tables, views, stored procedures, triggers etc. in Oracle RDBMS. One physical Oracle RDBMS can hold multiple schemas.
