### ISSUE TITLE
Datafile corrupt

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#2049]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [*] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [*] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Hi I'm getting datafile corrupt errors in log:

2016-09-12T12:33:42Z [12111] WARNING marker in datafile '/var/lib/arangodb3/databases/database-1/collection-61-1304205633/journal-71.db' points with size 1876415457 beyond end of file
2016-09-12T12:33:42Z [12111] ERROR datafile '/var/lib/arangodb3/databases/database-1/collection-61-1304205633/journal-71.db' is corrupt
2016-09-12T12:33:42Z [12111] ERROR {datafiles} cannot open datafile '/var/lib/arangodb3/databases/database-1/collection-61-1304205633/journal-71.db': corrupted datafile
2016-09-12T12:33:42Z [12111] ERROR cannot open document collection from path '/var/lib/arangodb3/databases/database-1/collection-61-1304205633'
2016-09-12T12:33:42Z [12111] ERROR ArangoError: corrupted collection

I have vmware machine running db and after db restart errors appear in log. I have snaphost of this state, so I tried to upgrade db to latest 3.0.7, but after restart corruption is again there. I'm attaching log file. How can I help to troubleshoot it?

Thanks Roman
[arangod.zip](https://github.com/arangodb/arangodb/files/467320/arangod.zip)

**Comment by jsteemann** [comment]
It looks like there are issues with the following two files:

* /var/lib/arangodb3/databases/database-1/collection-61-1304205633/journal-71.db'
* /var/lib/arangodb3/databases/database-72153482/collection-72153509-453528689/journal-72153519.db

Maybe the database was shut down in an unclean state or there is a filesystem problem. Do you have any information on whether there was a crash before or it the OS reports any errors for the filesystem the database directory is located in?

To recover, can you copy your entire database directory to a safe location so the datafiles can be debugged?

Apart from that, restarting ArangoDB with option `--database.ignore-datafile-errors true` should load the data from the datafiles that can safely be recovered. It will stop at data it cannot safely read, so it may recover less documents than were originally present in the affected collections.

**Comment by dothebart** [comment]
Hi, 
If possible can you send us the datafiles in questions via dropbox or such for deeper analysis? 
If you require an NDA signed in advance, we can do that.
Contact us via hackers at arangodb dot com for the details please.

**Comment by roman1720** [comment]
I send you affected datafiles. There was no crash, last start was without problems, problem occurred after rebooting database (service arangodb3 stop... start). I will try to check filesystem for possible errors.

**Comment by roman1720** [comment]
I tried to restore vm from backup. Arango started without any corruptions, then I restarted arango and corruptions occured. I will send you datafiles before and after restart so you can compare it.

**Comment by jsteemann** [comment]
I have had a look at the datafiles which were mentioned in the startup errors. They seem to contain seemingly random data at the locations mentioned.
Normally this should not happen, as datafiles created by ArangoDB are initialized with NUL bytes (the whole file gets filled with the NUL byte when the file is initially created) and then the file is written in an append-only fashion by ArangoDB. ArangoDB will not overwrite any existing parts of datafiles.
When a chunk is written to a datafile by ArangoDB, ArangoDB will flush it and eventually sync it to disk.
When a datafile is full, ArangoDB will flush it and wait for the disk sync to return success. On regular shutdown, ArangoDB will also flush all open files and wait for the disk to confirm the sync.

As the corruption happened despite that, and in two files, I suspect this is due to VM settings. We have seen VMs that deferred the actual physical file write operations very much, so that physical files did not actually receive all writes when the shutdown occurred. This may have happened here as well.

I am not sure if there are any VM settings that affect the filesystem buffering or durability that could help fix this, but maybe you can have a look.

To recover with these files, there are the startup options `--database.ignore-datafile-errors true` and `--wal.ignore-logfile-errors true`. Setting these options will load collections with corrupted datafiles, but it will stop loading datafiles at the first chunk of data that looks suspicious. Setting these option at startup will therefore allow you to start arangod, but it may lead to data loss in the affected collections. 

It would be really good to find out if there's any VM setting affecting this so it can be either adjusted there or fixed in the arangod code if reproducible and a major issue. Thanks!

**Comment by dothebart** [comment]
Which filesystem do you use on the directories where the database files are located? Ext4?

**Comment by roman1720** [comment]
It's ESXi server with ssd sata disk. VM has Ext4. We will try to play with VM settings.

**Comment by roman1720** [comment]
So we found source of problem. ESXi server was reporting 13GB of free disk space, but actually it was running out of space and this caused problem with db corruption.
