### ISSUE TITLE
Slow query log timestamp does not respect use-local-time

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#2051]
## my environment running ArangoDB

I'm using the latest ArangoDB 2.8.11 on Linux Debian Jessie 8 deb repo.
## the problem

In our config we have:

```
[log]
use-local-time = true
```

Log files indeed use the local time, but the web interface query management (active and slow queries) + the replication backlog timestamps use the GMT time.

It would be really great for debugging to know the actual time when the slow query was logged so we can correlate with other logs and fix the problems.

**Comment by dothebart** [comment]
hm, probably related to https://github.com/arangodb/arangodb/issues/1042

**Comment by dothebart** [comment]
Ok, slow queries were easy. Log lines are passed along from RestAdminLogHandler.cpp as UTC integer timestamps; thus the frontend would have to handle this.

**Comment by dothebart** [comment]
will be part of the 3.1 release.

**Comment by razvanphp** [comment]
If you are also planning a 2.8 release, it would be great to backport it. Thanks!

**Comment by jsteemann** [comment]
Just browsing through the open issues...
The problem has been fixed in 3.1 and higher, but we cannot backport that fix to 2.8 easily now, as the 3.1 version of the code is highly incompatible with the 2.8 code. Additionally it would require building an entire 2.8 release. 
I therefore suggest closing this issue now.
