### ISSUE TITLE
Fetching strategy

### ISSUE THREAD

**Issue by thierry-github** [arangodb/arangodb#2076]
Hi,

My compagny is considering moving from OrientDB to ArangoDB.
Is there some AQL syntax or way to achieve OrientDB SQL fetchplan ?

Thanks.

**Comment by Simran-B** [comment]
> The aim of fetch plans is to pre-load connected records in one shot.

I'm not an OrientDB expert, but it seems like it loads records lazily in general. Fetch plans can be used to make it load records more eagerly apparently.

In ArangoDB, you can write your traversals in AQL. There is only a single server roundtrip for a query, regardless of the traversal depth. Traversals use edge indexes, which are held in memory. It's super fast to read them and therefore to traverse. Loading the full vertex and optionally the edge documents may require harddrive / ssd access (if the collection is not fully loaded into RAM), but is generally fast as well (Arango uses memory-mapped files). A user-specified fetching strategy is not really required.

Can you tell us more about your use case though?

**Comment by thierry-github** [comment]
@Simran-B 
first, thanks for your quick response.

We want to strore documents with properties bound to documents.
For example, we have an invoice document bound to a Customer with a property named "Cust"
Documents are connected with edges. 
From a document managment perspective, we need to manage content versioning. Thus, document are not connected directly to the document targeted by the property (Cust) but to an intermediate document (called proxy) who responsability is to idenfity document's current version with a specific edge named CurrentVersion

[Document]Invoice -> [Edge]Property -> [Document]Customer_Proxy -> [Edge]CurrenVersion -> [Document]Customer_Data

What we want to do is to get Customer data when we get invoice document, in the simplest way

we already have done it this by using  :
- using anonymous graph approach with traversal
- using AQL Joins approach between Edge

Here is sample graph command 

FOR invoice IN invoices
  FOR vertex, edge IN 0..2 OUTBOUND invoice._id
    propery , currentVersion
    return { key :  vertex._id , edge : edge , value : vertex }

but we found that result is quit bit complex to analyse ( may be we just dont know how to do it right !)

How can we get result like  (or kind of) ?
{  
       invoice  : { invoideID : 12 , shippingDate : ...} ,
       customer  : { name : "Customer one" , CustID : "158-47" ...}
} 

In your resonse, you said 

> Traversals  use edge indexes, which are held in memory. It's super fast ...

am i right if i think that using joins on edges indexes (_from, _to ) is fast too ? 

Thanks for your  response and congratulations for your good job on ArangoDB !

**Comment by Simran-B** [comment]
Been thinking about this for a while and 4 different data models came to my mind:

1. In your current model, an Invoice is linked to a Customer record via a Proxy. There is supposed to be a single CurrentVersion edge from a Proxy to a Customer record. This can't be ensured on the database level however. You actually need a transaction to delete the CurrentVersion edge in order to make another Customer record (new revision) the current version by inserting a new edge and getting rid of the old one. That seems sub-optimal. I wonder if there would be additional edges to link the Proxy to all (former) Customer records.

2. `currentVersion: true` could just be a flag of one of the edges that link Invoices with Customers via the Proxy. You would keep all edges created between Proxies and Customer records. But this would still require a transaction to update the existing edge (remove currentVersion attribute) and to insert the new Customer record as well as the edge to link it to the Proxy. A way to avoid that would be to use an increasing version number or timestamp instead of a boolean (leaving the previously existing edges untouched). If you follow the edge with the highest number / most recent timestamp, you'll get to the latest Customer record. You can actually remove the intermediate Proxy with this model altogether.

3. You could store the latest customer data in a single Customer record, and have a special attribute that holds the old revisions in an array of objects. There would be no Proxy in this model. The benefit: the attributes with the latest data can have indexes on them, whereas the old revisions would stick around without indexes in a growing array.

4. Instead of storing old revisions of the customer data inside each Customer record, you could have a separate collection (archive) and store the Customer keys along with it (one record per revision). Using the key, it is possible to join them to the main Customer records. The Customer records themselves would only store the latest version of the data. The benefit is that you can have indexes on the attributes in both collections if desired.

What the best approach is depends on how much data you will store, what queries will commonly we run etc.

On a different note: you don't have to use 0..2 traversal if the number of hops is fixed. You can actually do two 1..1 OUTBOUND traversals to go via Proxy to Customer. Maybe that helps to build the desired result data structure? You can also use the 3rd traversal variable with the path to construct it differently.

**Comment by thierry-github** [comment]
tks, i need to think more about it.

one question more about edges collection. From a memory perspective, is it better to have one big collection to hold all property edges (i' my case) or it's better to split it into more small collections ? i think the overall memory foot print should remain nearly the same but as is going to be a very huge collection, i'm wondering what's the best approach.

**Comment by dothebart** [comment]
@thierry-github have a look at: https://docs.arangodb.com/3.0/Manual/Graphs/index.html#multiple-edge-collections-vs-filters-on-edge-document-attributes

**Comment by thierry-github** [comment]
thanks for the link
