### ISSUE TITLE
AQL bad optimization with LET

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#2079]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [*] 3.0
- [*] self-compiled devel branch (from yesterday)

On this operating system:
- [ ] Linux 
  - [*] Debian .deb

I'm issuing AQL via:
- [*] web interface with this browser: Chrome    running on this OS: Win10

Hi, I have two almost identical queries. I only assigned part of the query to LET variable which should not have impact on optimization, but index is not used and query takes much longer to finish. See two attached files with explain output.
[bad_no_index_used.txt](https://github.com/arangodb/arangodb/files/495507/bad_no_index_used.txt)
[ok_index_used.txt](https://github.com/arangodb/arangodb/files/495508/ok_index_used.txt)

**Comment by dothebart** [comment]
did you already update to 3.0.10 ?

**Comment by roman1720** [comment]
yes I tried it on 3.0.10 and devel branch, index is not applied on query with extra LET

**Comment by roman1720** [comment]
Btw I don't know if it helps, but I found out that with LET in this case

for m in macList
for o in vOui

index is applied

Indexes used:
 By   Type      Collection   Unique   Sparse   Selectivity   Fields       Ranges
 51   primary   vOui         true     false       100.00 %   [ `_key` ]   (m.`oui` == o.`_key`)


if I switch rows

for o in vOui
for m in macList

then not.

**Comment by jsteemann** [comment]
Yes, there was no optimization for cases like
```
FOR doc1 IN collection
  FOR doc2 IN non-collection-value
    FILTER condition-using-doc1-and-doc2
```
because the optimizer could not push the filter condition beyond the second for loop that introduced variable `doc2`. This would have led to the following (invalid) plan:
```
FOR doc1 IN collection
  FILTER condition-using-doc1-and-doc2
  FOR doc2 IN non-collection-value
```
With the fix introduced by commit a45322076a79141a822d0b6cc7be372552528aec, the optimizer can now permute the two FOR loops to
```
FOR doc2 IN non-collection-value
  FOR doc1 IN collection
    FILTER condition-using-doc1-and-doc2
```
which allows it to use the filter condition in the second FOR loop using an index.

In the end the fix allows the permutation of FOR loops that do not access collections with FOR loops that access collections. Previously, the optimizer only permuted FOR loops that accessed collections. With the additional permutations, the optimizer is able to find better execution plans and use indexes in more cases than before.

**Comment by roman1720** [comment]
Thanks for fix!

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
