### ISSUE TITLE
session cookie options

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#2085]
- [x] 2.8
### Foxx

For session cookies, is there any way to set the `secure` and/or `HttpOnly` flags?

**Comment by pekeler** [comment]
Also, when using sessions-jwt with a `jwtSecret`, is it a good idea to specify an additional secret in `controller.activateSessions()` or is the `jwtSecret` enough?

**Comment by pekeler** [comment]
And most importantly: how do I control the expiration of the session cookie?

**Comment by pekeler** [comment]
OK, so looking at the code I can see that sessions-jwt controls the expiration.

It also seems that secure and httpOnly are supported by Foxx BaseMiddleware all the way down to HttpResponse.cpp. It's Foxx Sessions' fault which is ignoring these params. Just add

```JavaScript
          secure: cfg.cookie.secure,
          httpOnly: cfg.cookie.httpOnly,
```

to https://github.com/arangodb/arangodb/blob/5c97465b6274b97a7a0f7ca243837f178cea1401/js/server/modules/org/arangodb/foxx/sessions.js#L92

and it'll work as expected.

I'm not sure how to submit a PR for this since Foxx Sessions is now considered legacy in 3.*. @pluma ?

**Comment by pluma** [comment]
The 2.8 Foxx API is frozen and only maintained in 3.0 for backwards-compatibility. Since this feature is missing in 2.8, the compatibility layer in 3.0 reflects that.

However this feature is currently also missing in the 3.0 API, so you could create a PR against that:

https://github.com/arangodb/arangodb/blob/devel/js/server/modules/%40arangodb/foxx/sessions/transports/cookie.js

The compatibility mode is only intended to be used to run legacy code written for 2.x and as a stepping stone while migrating to 3.0.

**Comment by pekeler** [comment]
Sorry, I'm not confident about 3.x yet, so I'm not able to prepare that PR soon.
