### ISSUE TITLE
Segfault on latest CentOS.. believe related to database.

### ISSUE THREAD

**Issue by brianrusso** [arangodb/arangodb#2087]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [X ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [X ] other: CentOS
- [ ] Windows, version: 
- [ ] MacOS, version:

Can reproduce with internal VM.
![arango](https://cloud.githubusercontent.com/assets/6276108/19124785/977d9e0e-8b02-11e6-905a-9b20aa374c4d.png)

**Comment by jsteemann** [comment]
@brianrusso : thanks for this bug report. Is the problem reproducible with every arangod start? Or did it happen just once and then went away?
Another interesting thing to know is whether the problem happened during WAL recovery, directly at server start or later while arangod was already serving requests. The screenshot does not fully reveal that.

If you could also install the debug info for arangod as gdb suggests in the screenshot that would be great. I am not sure how that works on CentOS, but hopefully gdb can then provide line numbers for the backtrace and hopefully some more internals when the SIGSEGV happens. Additionally, running `thread apply all bt` in gdb after the crash would be interesting so we can see what other threads are doing (this may or may not be a race).

If the problem is somehow reproducible, it would also be ideal to create a backup of the entire data directory and provide it to us so we can try to reproduce, analyze and fix the issue here. Obviously it cannot be posted here, but if you could upload it somewhere and send the access data to hackers@arangodb.com then this would be very helpful. Thanks in advance.

**Comment by brianrusso** [comment]
It happens at start up every time. I tried installing the debug info but it
didn't work. Maybe I have the wrong repo configured?

**Comment by dothebart** [comment]
hm, it seems we don't have any ready mabe debug rpm packages - its just debian ones :-( 
Does by any chance `bt full` give more output than `bt` alone? 

I will try to get an arangod with debug symbols built locally.

**Comment by dothebart** [comment]
http://arangodb.com/repositories/travisCI/arangod.gz is a gzip compressed 3.0.x arangod with debug symbols on board.

**Comment by brianrusso** [comment]
Where'd you get your jemalloc build from? I don't have that in CentOS 7 and can't find an RPM.

**Comment by brianrusso** [comment]
Where did you find a jemalloc2 lib for CentOS 7? I can only find it for Fedora but that brings in a slew of new library changes.

**Comment by dothebart** [comment]
I've built it in [that docker container](https://github.com/arangodb-helper/build-docker-containers/tree/master/distros/centos/7)

Its downloading the file like that:

    cd /etc/yum.repos.d; wget http://download.opensuse.org/repositories/home:/fceller2/CentOS_CentOS-6/home:fceller2.repo
    yum -y install arangodb-gcc54-5.4.0 arangodb-jemalloc-devel glibc-devel openssl-devel rpm-build

(which reminds me that we need to fix the jemalloc linking to be static)

**Comment by brianrusso** [comment]
![image](https://cloud.githubusercontent.com/assets/6276108/19156518/2b285dd0-8bb0-11e6-9c6c-9dc3ce927104.png)

**Comment by brianrusso** [comment]
Just gives illegal instruction now; using that jemalloc from the repo you linked; everything else as before.

**Comment by dothebart** [comment]
Ok, it seems that it compiled an arangod with processor optimisation you environment doesn't understand. I've re-created the binary without any optimizations. Can you re-download and re-try? 

Sorry for causing inconvenience.

**Comment by brianrusso** [comment]
![arango1](https://cloud.githubusercontent.com/assets/6276108/19165631/8795696a-8bd2-11e6-9665-448a2862456f.png)
![arango2](https://cloud.githubusercontent.com/assets/6276108/19165635/879da90e-8bd2-11e6-876a-1ba9ceb338c3.png)
![arango3](https://cloud.githubusercontent.com/assets/6276108/19165630/87942302-8bd2-11e6-8fbd-74ebaf0807e8.png)
![arango4](https://cloud.githubusercontent.com/assets/6276108/19165633/8797ca5c-8bd2-11e6-893f-73d66e14fd8b.png)
![arango5](https://cloud.githubusercontent.com/assets/6276108/19165632/8796573a-8bd2-11e6-854b-f02f16d39505.png)
![arango6](https://cloud.githubusercontent.com/assets/6276108/19165629/87920874-8bd2-11e6-8468-a326839f20c4.png)
![arango7](https://cloud.githubusercontent.com/assets/6276108/19165634/879da652-8bd2-11e6-8caf-66026f0fa8c8.png)
![arango8](https://cloud.githubusercontent.com/assets/6276108/19165636/879e8518-8bd2-11e6-834b-de21656634e7.png)

**Comment by brianrusso** [comment]
Let me know what else I can do to help.

**Comment by brianrusso** [comment]
Here's just what it looks like (that was the bt full).
![arango-simple](https://cloud.githubusercontent.com/assets/6276108/19165752/11a8662a-8bd3-11e6-9121-1aa3dddb8fb4.png)

**Comment by brianrusso** [comment]
Here's the log; probably easier than screenshots.
[arango.txt](https://github.com/arangodb/arangodb/files/514592/arango.txt)

**Comment by dothebart** [comment]
after some serious debugging and this not being reproducible on different systems with the same database directory we settled that the cause of this was not in the scope of arangodb but rather that the installation got messy along with an upgrade from centos 6 to 7.
