### ISSUE TITLE
Could not connect to endpoint 'http+tcp://8.31.3.58:8531', database: '_system', username: 'root' Error message: 'Could not connect to 'http+tcp://8.31.3.58:8531' 'connect() failed with #111 - Connection refused' 

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb#2094]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0.8
On this operating system:
- [x] Linux 
  - [x] SUSE   .rpm

I have build a arangodb cluster with one coordinator(8.31.3.58:8531) and one agency (8.31.3.56:8529) and the agency can work normally but the coordinator can not and has the problem:
Could not connect to endpoint 'http+tcp://8.31.3.58:8531', database: '_system', username: 'root'
Error message: 'Could not connect to 'http+tcp://8.31.3.58:8531' 'connect() failed with #111 - Connection refused'
Could anyone give me some suggestions with this problem?

**Comment by saliormoon** [comment]
I have solved the problem by myself. The cause is that I forget to update the endpoint from 127.0.0.1:8529 to 8.31.3.58:8531. And when I update the right endpoint, it can work well.Thanks.

**Comment by pruek** [comment]
I've the same error code 'connect() failed with #111 - Connection refused' after my system run normally for a few months. And I've check endpoint (it's not changed), and try to change to 8530/8531 (and restart arango3), but can not solve this problem.
Could anyone tell me why and how to solve this problem ?

**Comment by jsteemann** [comment]
What exactly happens if you restart arangodb3? Is the process running afterwards?
Are there are error messages in logs (syslog or arangod.log)?

**Comment by pruek** [comment]
arangodb3.service - LSB: arangodb
   Loaded: loaded (/etc/init.d/arangodb3; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-07-11 17:20:47 UTC;
32s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 22531 ExecStart=/etc/init.d/arangodb3 start (code=exited,
status=139)

Jul 11 17:20:45 server-01.localdomain systemd[1]: Starting LSB: arangodb...
Jul 11 17:20:45 server-01.localdomain arangodb3[22531]:  * Starting arango
database server arangod
Jul 11 17:20:47 server-01.localdomain arangodb3[22531]: Segmentation fault
(core dumped)
Jul 11 17:20:47 server-01.localdomain arangodb3[22531]:  * database version
check failed, maybe you need to run 'upgrade'?
Jul 11 17:20:47 server-01.localdomain systemd[1]: arangodb3.service:
Control process exited, code=exited status=139
Jul 11 17:20:47 server-01.localdomain systemd[1]: Failed to start LSB:
arangodb.
Jul 11 17:20:47 server-01.localdomain systemd[1]: arangodb3.service: Unit
entered failed state.
Jul 11 17:20:47 server-01.localdomain systemd[1]: arangodb3.service: Failed
with result 'exit-code'.
