### ISSUE TITLE
[BUG] mergeObjects does not effect the root document

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#21079]
Given the collection `C` and the document `{_id:'C/1',_key:'1',test:1,test2:2}`

If running

```AQL
UPDATE {_key:'1', test2:1} INTO Client OPTIONS {"mergeObjects":false} RETURN NEW
```

The field `test` will still be in the document.

Given the document `{_id:'C/2',_key:'2',test:{test:1, test2:2}}`

Running

```AQL
UPDATE {_key:'2', test:{test:2}} INTO Client OPTIONS {"mergeObjects":false} RETURN NEW
```

This will return `{_id:'C/2',_key:'2',test:{test:2}}`

So the sub documents are not merged but the root document.

I'm on arangodb 3.12 with the java driver 7.6. But I reproduced it in the web frontend.

**Comment by Simran-B** [comment]
This is the expected behavior. With `OPTIONS {"mergeObjects": false}`, the attributes you specify will be set to the specified values. Attributes you don't specify remain, regardless of `mergeObjects`. If you want to remove attributes selectively, set them to `null` in an `UPDATE` operation with `OPTIONS { keepNull: false }`:

```js
UPDATE { _key: "C", test2: null } IN Client OPTIONS { keepNull: false }
```

Or you can consider specifying all attributes of the document you want to keep and use a `REPLACE` operation, but be careful not to remove more attributes than desired - only the ones stated in the query plus immutable system attributes will remain.

**Comment by jsteemann** [comment]
Hi @konsultaner, the implemented behavior of `mergeObjects` is 
- for any attributes that are present in the overwrite value but not in the source document:
  - add all attributes to the document which are present in the overwrite value but not in the source document. A special case is when `keepNull=false` is removed, in which case the attributes which are `null` in the overwrite attribute value will be removed from the target document.
- for any attributes that are present in the overwrite value and also in the source document:
  - if `mergeObjects=false`, overwrite the value of the attribute in the source document with the overwrite attribute value.
  - if `mergeObjects=true`, overwrite the value of the attribute in the source document with the overwrite attribute value if the attribute value in the source document is not an object (i.e. merging not possible, so we are overwriting).
  - if `mergeObjects=true`, merge the value of attribute in the source document with the overwrite attribute value if they are both objects (merging possible).

The algorithm is not performed on the very top level (i.e. the source document and the overwrite value). Instead it is performed for every top-level attribute present in the overwrite value individually. When merging two attribute values objects, the merging is also performed recursively using the same algorithm.

I understand that this behavior may not always be the desired behavior, but the merging algorithm shouldn't be changed in an incompatible way to avoid incompatibility. In case a different merging algorithm is needed, there are multiple options:
- implement the custom merging in the client application (requires fetching the original document first, so may not work for large amounts and is subject to data races if there are other concurrent update operations).
- implement the custom merging as a new option in the database. This would mean another hard-coded merging algorithm, which may or may not be general enough to suit everyone's needs. Also requires support from all relevant drivers in order to be able to use it properly.
- implement the custom merging in the AQL query, using built-in AQL functions (example following)

```
FOR doc IN collection
  REPLACE doc WITH MERGE_RECURSIVE(@update) IN collection
```
Note that this query is not providing a different merge algorithm, but it may be adjusted to your needs. I currently can't tell what merge algorithm you have in mind.
