### ISSUE TITLE
AQL: can't assign the result of APPEND to an already assigned variable

### ISSUE THREAD

**Issue by cyrilleverrier** [arangodb/arangodb#2114]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.0

On this operating system:
- [ ] Linux 
  - [X] Ubuntu .deb

I'm issuing AQL via:
- [X] web interface with this browser: Opera 37    running on this OS: Ubuntu 16

The issue can be reproduced using this following AQL query in the AQL query editor (webUI):

```
LET range = APPEND([ 1, 2, 3 ], [ 5, 6, 9 ])
range = APPEND([ 1, 2, 3 ], [ 5, 6 ])
RETURN range


Query: syntax error, unexpected identifier near 'range = APPEND([ 1, 2, 3 ], [ 5,...' at position 2:1 (while parsing)

```

I would expect the result of APPEND to be reassignable to the already assigned variable `range`.

Please note that this one works:
```
LET range = APPEND([ 1, 2, 3 ], [ 5, 6, 9 ])
RETURN range

[
  [
    1,
    2,
    3,
    5,
    6,
    9
  ]
]
```

**Comment by jsteemann** [comment]
Assigning a value to a variable without `LET` will result in a parse error, as you have reported.
This is intentional. All variables in AQL are immutable once assigned.

Please note that in your example query there is no benefit of re-assigning a value to `range` because its original value is never used. However, sometimes there is actual need to modify existing variables. If this is necessary, you can simply assign the new value to another variable, e.g.
```
LET range1 = APPEND([ 1, 2, 3 ], [ 5, 6, 9 ])
LET range2 = APPEND([range1, [ 5, 6 ])
RETURN range2
```

**Comment by cyrilleverrier** [comment]
@jsteemann : thanks for your reply.
I didn't know that `variables in AQL are immutable once assigned`.

I implemented the solution that you referred in the comment. Sorry for having bothered you with this question :)

**Comment by jsteemann** [comment]
No worries.

**Comment by Simran-B** [comment]
It is actually not mentioned in the docs for LET. I'll add a note.

**Comment by Simran-B** [comment]
Done: https://github.com/arangodb/arangodb/commit/f748bab31e664d5e4a104b4232f5bf9139ded928
