### ISSUE TITLE
Arango 3.1 RC2 web interface - AQL parser error

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangodb#2117]
## my environment running ArangoDB
I'm using the latest ArangoDB 3.1 rc2

On this operating system Debian .deb

I want to report problem in AQL parser in web interface

```
for eox in vEox
return Merge({}, {desc: eox.desc, milestones: [], repl: eox.replace})
```

This AQL returns error 
```Query: syntax error, unexpected DESC keyword, expecting } near 'desc: eox.desc, milestones: [], ...' at position 2:19 (while parsing)```
and I think that this AQL should work, because I was able to insert documents (with properties desc & replace withour any problem) via ArangoJS

**Comment by DeShadow** [comment]
@Kurtas You can insert documents by arangojs with properties `desc` and `replace`, because these properties non in AQL query.

If you want to use fields named like keywords, you can do 
```
for eox in vEox
return Merge({}, {`desc`: eox.`desc`, `milestones`: [], repl: eox.`replace`})
```

**Comment by jsteemann** [comment]
This is not an error. `desc` and also `replace` are keywords in AQL (please refer to https://docs.arangodb.com/3.0/AQL/Fundamentals/Syntax.html for the full list of keywords). In order to use these keywords as attribute names or variable names, they must be enclosed in backticks as @DeShadow has suggested.

**Comment by Kurtas** [comment]
Ok guys, thanks
