### ISSUE TITLE
ArangoDB not responding for large collections

### ISSUE THREAD

**Issue by akki** [arangodb/arangodb#2126]
## My environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [x] Linux 
  - [x] Ubuntu (installed with `apt-get`)
## Issue

I am currently porting my data from MongoDB to ArangoDB as a multi-model db would be much beneficial for me as per my use case. So I copied all my documents in Mongo to Arango (as is) via a Python script iterating over the Mongo cursor and [inserting](http://python-driver-for-arangodb.readthedocs.io/en/master/classes.html#arango.collections.Collection.insert) it into Arango.
Then I tried accessing my collections via Arangosh and everything worked fine until I restarted the Arango service (via `sudo service arangodb3 restart`). After the restart Arangosh stopped responding to any query related to one of my collections (say `c1`).
All these queries lead to the shell hanging up - `db._query('RETURN count(FOR doc in c1 RETURN doc)')`, `db.c1.count()`, `db.c1.toArray()[0]`, `db.c1.any()`,  `db.c1.figures()`.
I also observed that  when I run any these commands the process associated to arango starts taking a lot of RAM memory. Everything works fine for other collections of the same database.
I have about 3GB used and 4GB free RAM before I issue that command (I saw using `free -lhm` on Ubuntu). I also scanned `c1` using `dfdb` - [results](https://gist.github.com/akki/0b806aecbaae937e1ead6f58a61d72c0).
Thanks to Manuel on Slack who helped me debug all this info.
### About `c1`

This is the largest collection of my database
It has about 2.6M documents
The average size of the documents of this collection is 5.1KB
The maximum size of the document of this collection is 910KB
### About my machine

Memory: 7.5 GiB
Processor: Intel® Core™ i5-5200U CPU @ 2.20GHz × 4
OS-type: 64-bit

My second largest collection with 2.15M collections, avg-size 0.3KB, max-size 10KB works perfectly fine.

Mongo handles both these collections fine so I thought of reporting this case.

**Comment by jsteemann** [comment]
I think this is due to the total size of the `c1` collection exceeding the available RAM.
If `c1` has 2.6M documents and each document is 5.1Kb big on average, then the documents will require about 12.6 GB storage space for the raw document data (2.6 * 1000 * 1000 * 5.1 * 1000 / 1024 / 1024). Some RAM must also be put aside for the primary index and other indexes for the documents.
Then `db._query('RETURN count(FOR doc in c1 RETURN doc)')` will temporarily materialize all documents in the collection server-side, which will take a lot of RAM. `db.c1.toArray()[0]` will also materialize the entire collection and ship it to the ArangoShell before the shell will discard all documents but the first one.

Overall the collection data plus the operations run on it seem to require much more RAM than the available 7.5 GB, which probably explains the operations getting much slower. My guess is that the system is swapping heavily while the operations are executing.

Can you try modifying the operation
```
db._query('RETURN count(FOR doc in c1 RETURN doc)')
```
to its lighter variant
```
db._query('RETURN count(c1)')
```
and try to omit the following expensive operation altogether as it will require a full materialization:
```
db.c1.toArray()[0]
```
If that does not help much, can you try monitoring RAM usage of ArangoDB and check if its hits the available RAM capacity while executing and start swapping?

**Comment by akki** [comment]
I ran `db._query('RETURN COUNT(c1)')` and got no response. There are the results of some monitoring commands on my machine (running Ubuntu).

```bash
:~$ free -lhm
             total       used       free     shared    buffers     cached
Mem:          7.5G       7.4G       142M       378M       419M       3.3G
Low:          7.5G       7.4G       142M
High:           0B         0B         0B
-/+ buffers/cache:       3.6G       3.9G
Swap:         9.3G       149M       9.2G

:~$ top

top - 08:29:11 up 13:55,  3 users,  load average: 0.57, 0.36, 0.92
Tasks: 240 total,   2 running, 238 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.4 us,  1.1 sy,  0.0 ni, 66.7 id, 28.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   7881416 total,  7739652 used,   141764 free,   424376 buffers
KiB Swap:  9764860 total,   153288 used,  9611572 free.  3951032 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                    
 2534 arangodb  20   0 11.571g 3.259g 2.957g S   4.5 43.4   2:05.29 arangodb [serve
```
Unfortunately, I don't know much about swapping but maybe you can figure out what is required from the above info. Let me know if there is anything else I can do to help.
BTW, the %MEM of Arango's process keeps increasing until it reaches around 60% after which my machine starts to slow down so I have to kill the process or stop the arangodb3 service.

FWIW, I had also tried `db._query('RETURN count(FOR doc in c1 RETURN 1)')` but got the same behaviour.

**Comment by jsteemann** [comment]
It looks like all the available RAM is used (which is normal on Linux because free RAM will be used for filesystem buffering). 
arangod uses 3.259 GB resident memory (that will mostly be for indexes and collection meta-data plus temporary result sets), and 11.571 GB virtual memory. The system spent a huge fraction of time waiting for I/O (28.7 %) at the point `top` was run. That means it was likely reading or writing data from/to disk. 

I suspect that the overall size of the collection is too big to keep it in memory. From the above calculations the collection should have a data size of 12.6 GB, which is more than the available RAM, so the OS will be forced to constantly unload parts of the collection data and reload other parts from disk.
I also suspect that this already happens during collection loading. When a collection is first accessed, it is loaded automatically. The load process will iterate once through all collection data and build the in-memory indexes for the collection. That will need to read the 12.6 GB of datafiles and while reading, insert every document into the in-memory indexes for the collection. The in-memory indexes will consume a RAM amount proportional to the number of documents in the collection. But overall, the more RAM the in-memory indexes consume, the less RAM will be available for buffering the collection datafiles, which will again increase paging and swapping activity and slow down the loading.

So maybe the 7.5 GB available RAM are just not enough for working with this particular dataset.
We are already working on reducing the RAM requirements for ArangoDB for future releases, but that requires fundamental changes to the core of ArangoDB so it will still take us some time.

Just to confirm how big the dataset actually is in ArangoDB: can you run an `du -hs` on ArangoDB's data directory? That will show the approximate total dataset size for all collections stored in ArangoDB. If that's far bigger than the available 7.5 GB RAM (minus some reserve RAM for the OS and other processes) and all data needs to be accessed by ArangoDB, then all operations, even reads, will require disk activity. Until there is an ArangoDB release with lifted in-memory requirements, this problem can be fixed by increasing the available RAM of the server or reducing the size of the dataset so more of it fits into RAM.

**Comment by akki** [comment]
Sorry for the late reply, I didn't realise that you had replied to this thread.

Yes, my data is 13GB in size hence much bigger than my machine's RAM and switching to a server with higher RAM did solve my problem.

But I would like to confirm as it is quite shocking to me that if my data size increases to 100GB, would I nee d a server with RAM higher than 100GB?
Also as you mentioned `We are already working on reducing the RAM requirements for ArangoDB for future releases`, is there anywhere I could track and help in the progress of these efforts.

Thank you very much for the help.

**Comment by Simran-B** [comment]
A pluggable storage engine is currently planned for the 3.2 release, which should reduce the amount of RAM required.

**Comment by akki** [comment]
@Simran-B Thanks for the response. Is there any page where I can track it's progress and anyway I could help.
I can also close this issue in favour of that.

**Comment by Simran-B** [comment]
There are no details yet, but if you are familiar with RocksDB, you may contact hackers (at) arangodb.com and ask if there's anything you can contribute.

**Comment by baslr** [comment]
@akki ArangoDB version 3.2 will feather a additional storage engine based on rocksdb. Alpha1 was just released. Personally I expect the final 3.2 version in roughly 2.5 month.

You can track the progress at https://github.com/arangodb/arangodb/commits/devel, https://github.com/arangodb/arangodb/commits/3.2 and also by compiling ArangoDB and look for the startup option `--server.storage-engine <string>                      storage engine type possible values: "mmfiles", "rocksdb" (default: "mmfiles")`

**Comment by akki** [comment]
@baslr Great job on the progress and thanks a lot for the link.
I am curious if RocksDB would be available/work for [Cluster (Processes)](https://docs.arangodb.com/3.1/Manual/Deployment/Distributed.html) also?

**Comment by baslr** [comment]
@akki yeah the ArangoDB database nodes can also use RocksDB as a storage engine.

**Comment by baslr** [comment]
@akki did you retried with ArangoDB 3.2 and rocksdb?

**Comment by dothebart** [comment]
Since ArangoDB 3.2 is readily available containing the discussed rocksdb engine I will close this issue now.

**Comment by akki** [comment]
@baslr Sorry, somehow I had missed your last comment. I didn't try it with the actual data but I had done some small tests with RocksDB and the results seemed satisfactory.
@dothebart Thanks for updating the ticket/issue.
