### ISSUE TITLE
There is a TypeError when using"Graph._create('GraphName'); " in arangosh.

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb#2128]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [x] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
### My problem is:

Graph._create('knows-graph');

JavaScript exception in file '/usr/share/arangodb3/js/common/modules/@arangodb/general-graph.js' at 534,12: TypeError: Cannot read property 'forEach' of undefined
!      sGEDs.forEach(
!           ^
stacktrace: TypeError: Cannot read property 'forEach' of undefined
    at /usr/share/arangodb3/js/common/modules/@arangodb/general-graph.js:534:12
    at Array.forEach (native)
    at Object._create (/usr/share/arangodb3/js/common/modules/@arangodb/general-graph.js:531:17)
    at <shell command>:1:7

**Comment by jsteemann** [comment]
AFAIK this error can only occur when there are documents in the `_graphs` collection that do not have an `edgeDefinitions` attribute at all or that have an `edgeDefinitions` attribute that is not an array.
Because in your case `edgeDefinitions` is undefined, the document hasn't had an `edgeDefinitions` attribute at all. 

This should not happen when graphs are managed via the `general-graph` module. Creating or modifying graphs via the `general-graph` module should always ensure that the `edgeDefinitions` attribute is an array.

So I guess you have either used the `_graphs` system collection to store your own documents (which have a different structure than the `general-graph` module expects) or that the documents in the collection have been modified manually. 

Whatever the reason, the problem can be fixed by ensuring that the `_graphs` system collection only contains graphs managed by the `general-graph` module and no user-defined documents at all. I suggest cleaning it by removing all documents from it that were not created by the `general-graph` module. As a consequence, all remaining documents in that collection should have the `edgeDefinitions` attribute and it should be an array. 
That should fix the problem and prevent it from happening in the future.

**Comment by saliormoon** [comment]
ok, thank you very much, jsteemann. When I create a graph, its structure will be registered in _graphs. But after I delete the collection of this graph, its graph structure still remains in the _graphs.

**Comment by jsteemann** [comment]
Graphs should be managed exclusively via the `general-graph` module, i.e. 
```js
require("@arangodb/general-graph")._drop("<graph-name-goes-here>");
```
This function also provides a means of dropping the graph's collections by adding a second parameter (`dropCollections`) and setting it to `true`:
```js
require("@arangodb/general-graph")._drop("<graph-name-goes-here>", true);
```

**Comment by jsteemann** [comment]
@Simran-B : not sure if this is already mentioned in the documentation, but it should be made clear there that graphs should only be managed via the `general-graph` module. Additionally it should be mentioned (if not already done) that user data should not be stored in system collections.

**Comment by saliormoon** [comment]
ok, thank you very much.

**Comment by dothebart** [comment]
done by 62b38028dc.
