### ISSUE TITLE
Cannot kill a long-run query.

### ISSUE THREAD

**Issue by jmshi123** [arangodb/arangodb#2129]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [Y] 3.0

On this operating system:
- [Y] Linux 
### this is an AQL-related issue:

[Y] I'm using graph features

I'm issuing AQL via:
- [Y] web interface with this browser:     running on this OS:
- [Y] arangosh

I am using ArangoDB for graph shortest path queries over a graph with 70 million vertices and 500 million edges. So sometimes there are queries running more than an hour without returning a result.

I want to kill such queries to release CPU and memory burden. But I cannot. I have tried to use web interface to kill the query in the "running queries" tab of "Queries" page, and it does not work. When I click yes to kill, just nothing happened.

I also tried to use arangosh to [kill the queries by id](https://docs.arangodb.com/3.0/Manual/Appendix/JavaScriptModules/Queries.html#kill), which also does not kill the long-run queries.

Is there any other way for me to kill such heavy queries? e.g., can I get the process id of such queries and kill them manually? Thanks!

**Comment by jsteemann** [comment]
Killing queries by id as you did is the only available way of telling the server to stop executing a particular query.
Fetching the process or thread id via `ps`, `top` or anything similar and killing it manually via `kill` will result in the entire server stopping or crashing.

There may be a few reasons if the server does not abort a long-running query:
- all server threads are busy so incoming requests (and also the "kill query with id x" request) are not processed. This reason can be ruled out if the server still responds to other requests, e.g. when it serves data for the the web interface etc.
- the server is busy waiting for I/O and heavily swapping or paging because it is running out of free RAM. If this is the case, you should see high `io wait` values in top for the server and also disk activity. In this case, killing a query may take a long time because many operations are waiting for the (slow) disk.
- the server will check for a kill request only at certain points in a query. Basically a kill request only sets a flag that the executing query thread must check. This check is only done at every x iterations to save CPU time. If the server is executing "expensive" operations (which may include disk activity) when the kill request is sent, it may take some time until it will re-check the flag and actually abort the query.
- some operations cannot be killed at all. For example, an AQL query may load collections if they are not already loaded. If the query is in the stage of loading collections, sending a kill request will not have effect until the query gets into the actual execution stage. The same is true if a query is waiting for locks.
- specific parts of AQL may not respond to a kill request. I am currently checking if SHORTEST_PATH is responsive to kill requests or not.

I'll post an update if I find something out.

**Comment by jsteemann** [comment]
I found that `SHORTEST_PATH` did not respond to kill requests. So when sending a kill request to a query that executed a shortest path operation, the killed flag was set, but only checked when the entire shortest path computation was finished.
Now the shortest path code will check periodically if the query was aborted in the meantime.

**Comment by jsteemann** [comment]
Fixed in 3.0 (3.0.11), 3.1 (3.1.1) and devel.

**Comment by dothebart** [comment]
3.0.12 is available for download via the regular upgrade channels - closing.
