### ISSUE TITLE
Arangosh - max packet size error

### ISSUE THREAD

**Issue by crs-** [arangodb/arangodb#2130]
Hello,

I've used the following query with arangosh:
`stmt = db._query("FOR vertex in MyCollection filter has(vertex, \"creationTime\") COLLECT AGGREGATE maxTime = max(vertex.creationTime) into lastVertex Limit 10 RETURN lastVertex")`

While  executing the statement I get the following error (independend of the server.max-package-size I specify):

2016-10-25T12:29:37Z [35798] WARNING Content-Length > max packet size found
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 100,7: ArangoError 2001: Content-Length > max packet size found
!      throw error;
!      ^
stacktrace: ArangoError: Content-Length > max packet size found
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:98:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:178:12)
    at ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:868:42)
    at <shell command>:1:11

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

**Comment by jsteemann** [comment]
Note that the above query will return all documents from the collection that have a "creationTime" attribute. The result may get very big, and it cannot be split because the documents are put into a horizontal array. The LIMIT 10 will have no effect, because the query will produce a single result (which is an array with all the documents that have a "creationTime" attribute).

Because the result is big and cannot be split, the ArangoShell refuses to load it.
By the way, a more efficient way to get the document with a max value is posted in the following Google Groups thread: https://groups.google.com/forum/#!topic/arangodb/n17WeWQsH2E

An alternative is to first query the max value and then return the documents for this value as a (hopefully small array):
```
LET maxValue = FIRST(FOR vertex in MyCollection 
  FILTER HAS(vertex, \"creationTime\") 
  COLLECT AGGREGATE maxTime = MAX(vertex.creationTime) 
  RETURN maxTime)
FOR doc IN MyCollection 
  FILTER doc.creationTime == maxValue
  LIMIT 0, 10
  RETURN doc
```
This will first query the maximum value of "creationTime" from all documents and then select at most 10 documents with that attribute value. Note that this will do two full collection scans if "creationTime" is not indexed. The latter collection scan can be avoided if "creationTime" is properly indexed.

Using the solution suggested in the Google Groups thread above will be more efficient however because it will only look at a single document provided a sorted index is present.

**Comment by crs-** [comment]
Ok thank you.
