### ISSUE TITLE
New String function to generate slugs

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#2151]
Since this use-case is pretty common for SEO these days and usually tightly connected with one or more attributes in a collection, it would be nice to have a new V8 function that can do this internally.

Reason behind this is that it can get really tricky to be done on the application code, because you always have to:
- retrieve similar slugs
- check if the value is unique
- prepend with something to make it unique
- atomically try to set it back to the database and hope nobody else already picked it up in the meantime

Another problem is that for very common names, the dataset can be very big to be retrieved on the application side (imagine firstname slug for "Stefan" in a multi million customer database of german names), and this is not even needed for the purpose, one just wants to set the next available slug based on the name, nickname or a combination of attributes.

Having this on the DB side would have the benefit that dataset does not have to travel around, unique indices can be used for the respective field, FULLTEXT indices would not be needed and performance would be way better.

As a signature, I would imagine this function would take:
1. "slug base" as a string / document attribute
2. separator ("_" or "-" for example)
3. random characters to apply (numbers or character set)
4. attribute in collection to check for uniqueness (maybe unique index mandatory?)

If you have other approach for this use-case with abstracting this logic from the application feel free to provide an alternative solution, maybe a `NEXT_UNIQUE` function instead?

Thank you!

**Comment by gamedev8** [comment]
Hello - not so sure this type of logic belongs directly in ArangoDB.

What if you just put the key in the URL? 

**For example**, the key in the following URL would be _27745041_
http://stackoverflow.com/questions/27745041/java-collections-over-arangodb

Now you would just fetch the question from arango using the key

`return document("questions/27745041")`

**Comment by razvanphp** [comment]
Hmm, indeed, but that's a little bit too late, we already have the slugs in place.

Plus, it has the benefit to have links like www.site.com/my-very-unique-slug without any number in it, SEO things, business decisions, no control over this.

I agree it's debatable if something so specific should be part of a database, but if you look at [existing string functions](https://docs.arangodb.com/3.0.10/AQL/Functions/String.html) you will understand this is exactly what makes arangodb great, because it's _different_.

**Comment by jsteemann** [comment]
I quickly hacked together a JS prototype, which could already be used to generate unique slug values.
It's a standalone server-side JS function at the moment.

I used the function `url_slug` from https://gist.github.com/sgmurphy/3095196 for transliterating accented characters and removing non-ASCII characters from the input value. This is far from complete, but it will work for most of the western European special characters. 
It can be replaced with any other function that mangles the input string into a normalized target format of choice.

Here is the one I used:
```js
// from: https://gist.github.com/sgmurphy/3095196
/**
 * Create a web friendly URL slug from a string.
 *
 * Requires XRegExp (http://xregexp.com) with unicode add-ons for UTF-8 support.
 *
 * Although supported, transliteration is discouraged because
 *     1) most web browsers support UTF-8 characters in URLs
 *     2) transliteration causes a loss of information
 *
 * @author Sean Murphy <sean@iamseanmurphy.com>
 * @copyright Copyright 2012 Sean Murphy. All rights reserved.
 * @license http://creativecommons.org/publicdomain/zero/1.0/
 *
 * @param string s
 * @param object opt
 * @return string
 */
function url_slug(s, opt) {
	s = String(s);
	opt = Object(opt);
	
	var defaults = {
		'delimiter': '-',
		'limit': undefined,
		'lowercase': true,
		'replacements': {},
		'transliterate': (typeof(XRegExp) === 'undefined') ? true : false
	};
	
	// Merge options
	for (var k in defaults) {
		if (!opt.hasOwnProperty(k)) {
			opt[k] = defaults[k];
		}
	}
	
	var char_map = {
		// Latin
		'À': 'A', 'Á': 'A', 'Â': 'A', 'Ã': 'A', 'Ä': 'A', 'Å': 'A', 'Æ': 'AE', 'Ç': 'C', 
		'È': 'E', 'É': 'E', 'Ê': 'E', 'Ë': 'E', 'Ì': 'I', 'Í': 'I', 'Î': 'I', 'Ï': 'I', 
		'Ð': 'D', 'Ñ': 'N', 'Ò': 'O', 'Ó': 'O', 'Ô': 'O', 'Õ': 'O', 'Ö': 'O', 'Ő': 'O', 
		'Ø': 'O', 'Ù': 'U', 'Ú': 'U', 'Û': 'U', 'Ü': 'U', 'Ű': 'U', 'Ý': 'Y', 'Þ': 'TH', 
		'ß': 'ss', 
		'à': 'a', 'á': 'a', 'â': 'a', 'ã': 'a', 'ä': 'a', 'å': 'a', 'æ': 'ae', 'ç': 'c', 
		'è': 'e', 'é': 'e', 'ê': 'e', 'ë': 'e', 'ì': 'i', 'í': 'i', 'î': 'i', 'ï': 'i', 
		'ð': 'd', 'ñ': 'n', 'ò': 'o', 'ó': 'o', 'ô': 'o', 'õ': 'o', 'ö': 'o', 'ő': 'o', 
		'ø': 'o', 'ù': 'u', 'ú': 'u', 'û': 'u', 'ü': 'u', 'ű': 'u', 'ý': 'y', 'þ': 'th', 
		'ÿ': 'y',

		// Latin symbols
		'©': '(c)',

		// Greek
		'Α': 'A', 'Β': 'B', 'Γ': 'G', 'Δ': 'D', 'Ε': 'E', 'Ζ': 'Z', 'Η': 'H', 'Θ': '8',
		'Ι': 'I', 'Κ': 'K', 'Λ': 'L', 'Μ': 'M', 'Ν': 'N', 'Ξ': '3', 'Ο': 'O', 'Π': 'P',
		'Ρ': 'R', 'Σ': 'S', 'Τ': 'T', 'Υ': 'Y', 'Φ': 'F', 'Χ': 'X', 'Ψ': 'PS', 'Ω': 'W',
		'Ά': 'A', 'Έ': 'E', 'Ί': 'I', 'Ό': 'O', 'Ύ': 'Y', 'Ή': 'H', 'Ώ': 'W', 'Ϊ': 'I',
		'Ϋ': 'Y',
		'α': 'a', 'β': 'b', 'γ': 'g', 'δ': 'd', 'ε': 'e', 'ζ': 'z', 'η': 'h', 'θ': '8',
		'ι': 'i', 'κ': 'k', 'λ': 'l', 'μ': 'm', 'ν': 'n', 'ξ': '3', 'ο': 'o', 'π': 'p',
		'ρ': 'r', 'σ': 's', 'τ': 't', 'υ': 'y', 'φ': 'f', 'χ': 'x', 'ψ': 'ps', 'ω': 'w',
		'ά': 'a', 'έ': 'e', 'ί': 'i', 'ό': 'o', 'ύ': 'y', 'ή': 'h', 'ώ': 'w', 'ς': 's',
		'ϊ': 'i', 'ΰ': 'y', 'ϋ': 'y', 'ΐ': 'i',

		// Turkish
		'Ş': 'S', 'İ': 'I', 'Ç': 'C', 'Ü': 'U', 'Ö': 'O', 'Ğ': 'G',
		'ş': 's', 'ı': 'i', 'ç': 'c', 'ü': 'u', 'ö': 'o', 'ğ': 'g', 

		// Russian
		'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'Yo', 'Ж': 'Zh',
		'З': 'Z', 'И': 'I', 'Й': 'J', 'К': 'K', 'Л': 'L', 'М': 'M', 'Н': 'N', 'О': 'O',
		'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U', 'Ф': 'F', 'Х': 'H', 'Ц': 'C',
		'Ч': 'Ch', 'Ш': 'Sh', 'Щ': 'Sh', 'Ъ': '', 'Ы': 'Y', 'Ь': '', 'Э': 'E', 'Ю': 'Yu',
		'Я': 'Ya',
		'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh',
		'з': 'z', 'и': 'i', 'й': 'j', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o',
		'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c',
		'ч': 'ch', 'ш': 'sh', 'щ': 'sh', 'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu',
		'я': 'ya',

		// Ukrainian
		'Є': 'Ye', 'І': 'I', 'Ї': 'Yi', 'Ґ': 'G',
		'є': 'ye', 'і': 'i', 'ї': 'yi', 'ґ': 'g',

		// Czech
		'Č': 'C', 'Ď': 'D', 'Ě': 'E', 'Ň': 'N', 'Ř': 'R', 'Š': 'S', 'Ť': 'T', 'Ů': 'U', 
		'Ž': 'Z', 
		'č': 'c', 'ď': 'd', 'ě': 'e', 'ň': 'n', 'ř': 'r', 'š': 's', 'ť': 't', 'ů': 'u',
		'ž': 'z', 

		// Polish
		'Ą': 'A', 'Ć': 'C', 'Ę': 'e', 'Ł': 'L', 'Ń': 'N', 'Ó': 'o', 'Ś': 'S', 'Ź': 'Z', 
		'Ż': 'Z', 
		'ą': 'a', 'ć': 'c', 'ę': 'e', 'ł': 'l', 'ń': 'n', 'ó': 'o', 'ś': 's', 'ź': 'z',
		'ż': 'z',

		// Latvian
		'Ā': 'A', 'Č': 'C', 'Ē': 'E', 'Ģ': 'G', 'Ī': 'i', 'Ķ': 'k', 'Ļ': 'L', 'Ņ': 'N', 
		'Š': 'S', 'Ū': 'u', 'Ž': 'Z', 
		'ā': 'a', 'č': 'c', 'ē': 'e', 'ģ': 'g', 'ī': 'i', 'ķ': 'k', 'ļ': 'l', 'ņ': 'n',
		'š': 's', 'ū': 'u', 'ž': 'z'
	};
	
	// Make custom replacements
	for (var k in opt.replacements) {
		s = s.replace(RegExp(k, 'g'), opt.replacements[k]);
	}
	
	// Transliterate characters to ASCII
	if (opt.transliterate) {
		for (var k in char_map) {
			s = s.replace(RegExp(k, 'g'), char_map[k]);
		}
	}
	
	// Replace non-alphanumeric characters with our delimiter
	var alnum = (typeof(XRegExp) === 'undefined') ? RegExp('[^a-z0-9]+', 'ig') : XRegExp('[^\\p{L}\\p{N}]+', 'ig');
	s = s.replace(alnum, opt.delimiter);
	
	// Remove duplicate delimiters
	s = s.replace(RegExp('[' + opt.delimiter + ']{2,}', 'g'), opt.delimiter);
	
	// Truncate slug to max. characters
	s = s.substring(0, opt.limit);
	
	// Remove delimiter from ends
	s = s.replace(RegExp('(^' + opt.delimiter + '|' + opt.delimiter + '$)', 'g'), '');
	
	return opt.lowercase ? s.toLowerCase() : s;
}
```
And then there is function `sluggify` that generates the slugs from the input by calling `url_slug` and that ensures the generated slugs are unique. 
It does so by inserting each generated slug into a dedicated collection, using the slug as the document key. If the insert fails, the function will generate a new slug value, using the random characters. If insertion succeeds, the slug hasn't been before. This is as simple as it can get, and there is no need for transactions or other dedicated atomic operations. And there is no need for a separate unique index and a special index attribute. 
Sure this is not the only way to do it, but it's simple and works for the standalone function. Note that when using the `_key` attribute for storing the slugs there are some restrictions for length (which the functions limits to 64 bytes plus unique appendix) and the characters used. But as long as only ASCII chars are stored and no punctuation, it should work.

Here it is:
```js
function sluggify(value, separator, randomChars, collectionName) {
  var c = require("@arangodb").db._collection(collectionName);

  if (c === null) {
    throw "slug target collection '" + collectionName + "' not found!";
  }

  // transliterate and remove non-ASCII chars from value
  // plus limit length of value to 64 bytes
  var base = url_slug(value, { delimiter: separator, limit: 64 });
  var slug = base;

  while (true) {
    try {
      c.insert({ _key: slug });
      return slug;
    } catch (err) {
      if (err.errorNum !== 1210) {
        // 1210 = unique constraint violated
        throw err;
      }
      // slug already exists, try adding some randomness
    }
    slug = base + separator;
    var n = Math.ceil(Math.random() * 6);
    for (var i = 0; i < n; ++i) {
      slug += randomChars[Math.floor(Math.random() * randomChars.length)];
    }
  }
}
```
In order for the function(s) to work, create a collection named "slugs". This collection is intended to contain the unique slug values:
```js
db._create("slugs");
```
Once the two functions are in scope and the collection exists, simply call the `sluggify` function with the input value, the delimiter character, the alphabet for random additions plus the slug collection name, e.g.
```
arangod> sluggify("ein mops kam in die küche", "-", "0123456789abcdef", "slugs");
ein-mops-kam-in-die-kuche
arangod> sluggify("ein mops kam in die küche", "-", "0123456789abcdef", "slugs");
ein-mops-kam-in-die-kuche-da3f
arangod> sluggify("Und stahl dem Koch ein Ei", "-", "0123456789abcdef", "slugs");
und-stahl-dem-koch-ein-ei
arangod> sluggify("Und stahl dem Koch ein Ei", "-", "0123456789abcdef", "slugs");
und-stahl-dem-koch-ein-ei-1bcf1
arangod> sluggify("der mötermeister klötert  mit\nder tröte!!", "-", "0123456789abcdef", "slugs");
der-motermeister-klotert-mit-der-trote
arangod> sluggify("der mötermeister klötert  mit\nder tröte!!", "-", "0123456789abcdef", "slugs");
der-motermeister-klotert-mit-der-trote-365d89
```
Sure the above is no final version (especially the transliteration seems to need some love), but it can be used as a starting point. The function will work from Foxx. It won't work as an AQL custom function though, because those are required not to modify any collection data (which the above function does).

**Comment by jsteemann** [comment]
I think this functionality is useful but will always be custom.
So the best place for it is either a custom AQL function or a custom JavaScript function in a (custom) Foxx route. Making it available as a JavaScript function and calling it from Foxx is probably the best way to do it, as AQL functions can transform data but not modify data in collections.
I am closing this issue here because it is better implemented in user-land custom code rather than in standard code shipped with ArangoDB.

**Comment by LaravelFreelancerNL** [comment]
I came across this issue while searching for a similar solution. I ended up going for a userland solution just because a more complete function was available (Str::slug in Laravel). 

However in AQL you could do something like this for a slug consisting of several attributes:

`FOR doc IN collection
    LET slug = LOWER(TRIM(CONCAT_SEPARATOR('-', doc.attributeX, doc.attributeY, doc.attributeZ)))
    RETURN (
        LET `search` = [
            "ä","â","á","à","ã",
            "ë","ê","è","é",
            "ï","í","ì","î",
            "ö","ó","ò","ô",
            "ü","ú","ù","û"
        ]
        LET `replace` = [
            "a","a","a","a","a",
            "e","e","e","e",
            "i","i","i","i",
            "oe","o","o","o",
            "u","u","u","u"
        ]
        RETURN REGEX_REPLACE(SUBSTITUTE(slug, `search`, `replace`), "[^a-zA-Z0-9]+", "-")
    )`
