### ISSUE TITLE
Update an array temporary variable inside AQL

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2157]
Dear Team,

  Is it possible to use temporary variable (simple or array) inside AQL. 

If there is a support, then I should be able to update this variable during an AQL query.

One use case is to add new element to an array variable if the element is not present in the array. This way the entire execution will be in pipe-lined manner and huge performance gain.

Right now, when I use the UNION(), UNIQUE(), DISTINCT(), it is having a performance cost. 

Regards,
Sajeev

**Comment by jsteemann** [comment]
Modifying an existing variable in an AQL query like this is not possible:
```
LET v = value1
LET v = value2
```
This will produce an error when the query is parsed.

However, it's possible to use a new variable which contains the updated value, e.g.
```
LET array1 = [ 1, 2, "foo", "bar" ] 
/* do something else ... */ 

LET array2 = APPEND(array1, [ 3, 4, 2, "foo" ], true)
```
Now `array2` contains the updated value. In the above example, `array2` will contain all values from `array1` plus the values `3` and `4`. The other values are not added again because of the third parameter that controls the uniqueness. There are also the AQL functions `PUSH`, `POP`, `REMOVE_VALUE`, `REMOVE_VALUES`, `REMOVE_NTH`, `SHIFT` and `UNSHIFT` which may be helpful when creating new arrays from existing values.

**Comment by sajeevpr** [comment]
Thanks @jsteemann .
I will try to use these functions. But unfortunate that using temporary variables are not supported.

**Comment by jsteemann** [comment]
Temporary variables are supported, at least if you assign the result of a computation to a new variable.
There is no such thing as updatable variables in AQL (the reason for this is that allowing them would make query optimization and distribution in the cluster much harder).

**Comment by jsteemann** [comment]
See also #2114

**Comment by sajeevpr** [comment]
Thank you @jsteemann

**Comment by baslr** [comment]
Hi @sajeevpr,

if your question was answered, feel free to close this issue.
