### ISSUE TITLE
AQL - Slice vs Limit return value - Inconsistent return

### ISSUE THREAD

**Issue by hgill** [arangodb/arangodb#2167]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [y ] 3.0

On this operating system:
  - [ y] docker - official docker library

### this is an AQL-related issue:
[ y] I'm using graph features

I'm issuing AQL via:
- Foxx and graphql

The AQL query in question is:
```
query=aql`
return slice((
     for v in 1..1 outbound ${root._id} first_child
     sort v._id asc
     return v),${slice[0]},${slice[1]-slice[0]})
`;
results=db._query(query).toArray()[0];   //unexpected behaviour - need to add [0] in end
```
Also, the same query run on web interface returns a single array, so .toArray() should work fine.
```
return slice(for v in 1..1 outbound "meta/1000" first_child
     sort v._id asc
     return v,5,25)
```
Against the below query, the return behaviour is different, wondering if it is a bug?

```
query=aql`
     for v in 1..1 outbound ${root._id} first_child
     sort v._id desc
     limit 10
     return v
`;
results=db._query(query).toArray();    //works as expected
```

**Comment by pluma** [comment]
This is actually neither related to Foxx nor to GraphQL.

In AQL the result is always an array, even if it is a single value (which can in turn also be an array).

By using `RETURN SLICE(...)` you're specifying a single return value, which is of course an array (which is what `SLICE` returns). By using `FOR ... RETURN ...` you're returning multiple values (one per iteration).

In this case I would strongly advise against using `SLICE` as you're working on actual query result sets, not arbitrary arrays, and `FOR` is likely more performant (also, slicing from a set of all results is probably much slower than only building up a limited result set in the first place).

You can find out more about query results in the documentation: https://docs.arangodb.com/3.0/AQL/Fundamentals/QueryResults.html

@dothebart Maybe we should add an example for what happens if a plain `RETURN` is used to make it more obvious that the result is always an array.

**Comment by Simran-B** [comment]
Extended the description of RETURN and subqueries:

https://github.com/arangodb/arangodb/commit/8b63f116e94a08f776616b2b45bbc96ae8ded940
