### ISSUE TITLE
APPEND function - internal error of ArangoDB

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2183]
I use latest version (ArangoDB 3.1.1)

I have collection `messages` and simplified version of query:
```
for msg in messages
return APPEND(msg.fromUser, msg.action.data.addUsers, msg.action.data.removeUsers)
```

But it produces error:
```
Query: Expecting type Array or Object (while executing) (exception location: /var/lib/jenkins/workspace/ArangoDB_Release/arangod/RestHandler/RestCursorHandler.cpp:131). Please report this error to arangodb.com
```

fromUser - string
msg.action - object, not required
msg.action.data.addUsers/removeUsers - array of strings.

**Comment by jsteemann** [comment]
Fixed in 3.1 (3.1.2) and devel.

**Comment by jsteemann** [comment]
The problem occurred when the first parameter to APPEND was a non-array.

**Comment by jsteemann** [comment]
Please note that the call syntax in the above query seems wrong. The third parameter for `APPEND` is expected to be a boolean if set.
I am not sure if in your documents `removeUsers` is a boolean, but from the name I guess it's not.

Here's the call signature from the docs the docs:
```
`APPEND(anyArray, values, unique) → newArray`

Add all elements of an array to another array. All values are added at the end of the
array (right side).

- **anyArray** (array): array with elements of arbitrary type
- **values** (array): array, whose elements shall be added to *anyArray*
- **unique** (bool, *optional*): if set to *true*, only those *values* will be added
  that are not already contained in *anyArray*. The default is *false*.
- returns **newArray** (array): the modified array
```

**Comment by DeShadow** [comment]
@jsteemann Yeah, you are right!
But the strange thing: `return APPEND(1,[2,3])` throws warning, not internal error:
```
Warnings:

[1542], 'invalid argument type in call to function 'APPEND()''

Result:

[
  null
]
```

You are right, my query was wrong, because I thought that APPEND accepted many arrays to join each other. :)

**Comment by DeShadow** [comment]
@jsteemann  Thanks for fix! :)

**Comment by jsteemann** [comment]
To add to the confusion: there are two implementations for `APPEND`: a C++-based one and the legacy v8-based implementation.
The two implementations had different behavior w.r.t. handling the first argument in case it was a non-array. That has been unified with the fix.

**Comment by DeShadow** [comment]
@jsteemann Thank you for explaining! :) As I can understand older version of ArangoDB worked with V8-functions. And they were rewritten with C++?

**Comment by Simran-B** [comment]
There are actually two implementations side-by-side of several AQL functions. C++ is preferred and usually faster, except when a part of a query has to run in V8 anyway, then it is faster to run JS code in V8 and avoid converting intermediate results back and forth between V8 and the native code.

Some functions are solely implemented in JS, as they are "fast enough" for most purposes, and because an implementation in C++ would probably be tricky and/or time consuming. Have a look here: https://github.com/arangodb/arangodb/blob/devel/arangod/Aql/FunctionDefinitions.cpp#L130

If you see `&Functions::` there for an AQL function, that means there's also a C++ implementation. The actual function code is here: https://github.com/arangodb/arangodb/blob/devel/arangod/Aql/Functions.cpp

**Comment by dothebart** [comment]
ArangoDB 3.1.2 is available for download.
