### ISSUE TITLE
Query time 0.000000 in log with too many open connections

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#2209]
I'm using ArangoDB 2.8.11, I also noticed this in the past, but it seems to be fixed after the server restarts, but somehow reappears.

```
2016-12-06T22:28:30 [51782] INFO "http-request-end","0x368f84dc0","10.107.141.88","GET","HTTP/1.1",200,0,3117,"/sorter-api-ch/products/1977042/scores",0.000000
2016-12-06T22:28:30 [51782] INFO "http-request-end","0x358e483c0","10.107.61.41","GET","HTTP/1.1",200,0,3105,"/sorter-api-edited/products/1799328/scores",0.000000
2016-12-06T22:28:30 [51782] INFO "http-request-end","0x36bc8a580","10.107.141.88","GET","HTTP/1.1",200,0,1706,"/sorter-api-ch/products/2188765/scores",0.000000
2016-12-06T22:28:30 [51782] INFO "http-request-end","0x3740d0940","10.107.141.88","GET","HTTP/1.1",200,0,163,"/sorter-api-ch/products/2053765/scores",0.000000
2016-12-06T22:28:30 [51782] INFO "http-request-end","0x358e483c0","10.107.61.41","GET","HTTP/1.1",200,0,159,"/sorter-api-edited/products/1799330/scores",0.000000
2016-12-06T22:28:30 [51782] INFO "http-request-end","0x358e483c0","10.107.61.41","GET","HTTP/1.1",200,0,159,"/sorter-api-edited/products/1799332/scores",0.000000
```

As a side effect, it seems that the web interface also does not show anything anymore in the first part of the graphs, here is the API response:
```
{"times":[1481060071.001472],"avgTotalTime":[0],"avgRequestTime":[0],"avgQueueTime":[0],"avgIoTime":[0],"bytesSentPerSecond":[0],"bytesReceivedPerSecond":[0],"asyncPerSecond":[0],"optionsPerSecond":[0],"putsPerSecond":[0],"headsPerSecond":[0],"postsPerSecond":[0],"getsPerSecond":[0],"deletesPerSecond":[0],"othersPerSecond":[0],"patchesPerSecond":[0],"systemTimePerSecond":[0.04199827773481849],"userTimePerSecond":[0.5379779386035236],"majorPageFaultsPerSecond":[0],"minorPageFaultsPerSecond":[3618.0516309546174],"totalTimeDistributionPercent":{"values":[0,0,0,0,0,0,0],"cuts":[0.01,0.05,0.1,0.2,0.5,1]},"requestTimeDistributionPercent":{"values":[0,0,0,0,0,0,0],"cuts":[0.01,0.05,0.1,0.2,0.5,1]},"queueTimeDistributionPercent":{"values":[0,0,0,0,0,0,0],"cuts":[0.01,0.05,0.1,0.2,0.5,1]},"bytesSentDistributionPercent":{"values":[0,0,0,0,0,0],"cuts":[250,1000,2000,5000,10000]},"bytesReceivedDistributionPercent":{"values":[0,0,0,0,0,0],"cuts":[250,1000,2000,5000,10000]},"numberOfThreadsCurrent":40,"numberOfThreadsPercentChange":0,"virtualSizeCurrent":29724635136,"virtualSizePercentChange":0.00031455431224050476,"residentSizeCurrent":25894342656,"residentSizePercent":0.3834003641716429,"asyncPerSecondCurrent":0,"asyncPerSecondPercentChange":0,"syncPerSecondCurrent":0,"syncPerSecondPercentChange":0,"clientConnectionsCurrent":1000,"clientConnectionsPercentChange":0,"physicalMemory":67538649088,"nextStart":1481060071.001472,"waitFor":6.969300031661987,"numberOfThreads15M":40,"numberOfThreads15MPercentChange":0,"virtualSize15M":29374102907.685394,"virtualSize15MPercentChange":0.0002356930559135715,"asyncPerSecond15M":0,"asyncPerSecond15MPercentChange":0,"syncPerSecond15M":0,"syncPerSecond15MPercentChange":0,"clientConnections15M":1000,"clientConnections15MPercentChange":0}
```

The only strange this that happens with the server during this time is the high number of ESTABLISHED connections (around 2000), which we are still investigating, seems to be cause by some VPN connection or a bad client not closing the connections, not really sure if related.

If you need a stack trace when this happens, let me know, I saved it.

Thank you!

**Comment by jsteemann** [comment]
AFAIR when an HTTP request comes in, it will lease a statistics object from an internal freelist.
When the response is sent back, the statistics object will be put into another queue for results aggregation. This queue is processed asynchronously. Statistics objects that have been processed will be put into the freelist again.
There is a fixed number of statistics objects around. In 2.8 and later versions, the number of objects is 1,000. That means if there are more than 1,000 simultaneous requests, then some requests will not gather statistics. Additionally, there is always some gap between when a request is finished and the statistics results aggregation. In this period, the statistics object is also unusable for further requests. That means if there are many short-lived requests and results aggregation does not catch up, then no statistics will be gathered for some requests, too.
This could be fixed by increasing the internal queue size [here](https://github.com/arangodb/arangodb/blob/devel/arangod/Statistics/statistics.cpp#L41).

It would be interesting to know if statistics "come back" after request peaks, or if statistics are permanently gone until a server restart. Do you know anything about this?

**Comment by razvanphp** [comment]
Actually I never figured out why there are so many ESTABLISHED connections fiddling around, most probably it's the VPN filtering or closing some connections and arango didn't know about it, so it never got back to "normal". Actually those are not "real" connections, just open for a very long time.

Would it be possible to increase the queue to the number of possible open connections limit on the kernel? or would it use too much memory?

1000 simultaneous requests is pretty much anyway in real usage, so it's a good limit, don't know how to improve here, at least now we know why it happens.

Thank you again!

**Comment by fceller** [comment]
@razvanphp it is possible, that they VPN does not properly propagate the "close" from the client. One possibility is to set the TCP keep alive (this is different from HTTP).

The instructions and kernel parameter can be found here:

http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/addsupport.html

**Comment by dothebart** [comment]
Closing this question as answered.
