### ISSUE TITLE
Can not access req.body.key, req.body[key] 

### ISSUE THREAD

**Issue by AntoBrajkovic** [arangodb/arangodb#2215]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

On this operating system:
- [x] Linux 
  - [x] Ubuntu 14.04 .deb

Using foxx to write a simple back end, but can not get the values from the req.body.object.
I'm really sorry if I missed something obvious.

I'm making a JSON post to (sudo code):
```javascript
router.post("/myRoute", function(req, res) {
Object.keys(req.body)//does not work, I get ["length"]
for (let k in keys) keys.push(k)//does not work, I get the methods of the object
});
```

**Comment by jsteemann** [comment]
I think `req.body` is a `Buffer` object if no structure is defined for the incoming data. Thus `Object.keys(req.body)` will only return `["length"]`.
Requiring the request body to be an object (by attaching `.body(joi.object())` to the route definition) will validate the incoming request data and also turn `req.body` into a parsed structure:
```js
router.post("/myRoute", function(req, res) {
  console.log(Object.keys(req.body));
}).body(joi.object());
```
Then issuing an HTTP POST request will make the incoming request body being parsed and useful:
```
> curl -X POST http://127.0.0.1:8529/tupsi/myRoute --dump - --data '{"aha":123,"foo":"bar"}'; 
...
2016-12-12T07:31:38Z [2970] INFO [ "aha", "foo" ]
```

Note that instead of `joi.object()` any other joi types can be used, e.g.
```js
.body(joi.object({
  name: joi.string().required(),
  type: joi.any().required(),
  version: joi.string().optional()
}).required();
```

**Comment by AntoBrajkovic** [comment]
Thank you, solved the problem

**Comment by pluma** [comment]
I've added a sentence to the documentation that clarifies what `req.body` is initialized to. I hope that avoids problems like this in the future.
