### ISSUE TITLE
Skiplist index: Very slow query if value doesn't exist.

### ISSUE THREAD

**Issue by smith64fx** [arangodb/arangodb#2221]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: MaxOSX
- [ ] arangosh
- [ ] this Driver:

can somebody explain the long query time?

I have a created a skiplist index for topic.labels.de.valueLower (Lowercase version of "value")
When I filter for a value that actually exists, I get the result very fast.

Example:
```
FOR t in topic
  FILTER t.labels.de.valueLower LIKE ‚%thailand%'
  RETURN t
```
0.3s, almost Instant (Returns 1 result)

But when I filter for a value that does not exists, the query runs very long...
```
FOR t in topic
  FILTER t.labels.de.valueLower LIKE '%asdfsfdsdds%'
  RETURN t
```
500s for the second query (No results of course, but why it takes so long?)

Thank you in advance!

**Comment by jsteemann** [comment]
I am not sure why the second query is slower than the first. However, neither of the two queries will use the skiplist index. If you run explain on the two queries, it should show that:
```
db._explain("FOR t in topic "FILTER t.labels.de.valueLower LIKE '%thailand%' RETURN t");
db._explain("FOR t in topic FILTER t.labels.de.valueLower LIKE '%asdfsfdsdds%' RETURN t");
```
Both queries in your example are incomplete (there is no *RETURN* statement in them, so they will fail with a parse error). Maybe there is something else in the original (full) queries that causes the difference?

**Comment by Simran-B** [comment]
Can you share the data that is in your topic collection? It would be interesting to see what labels there are (especially how many characters valueLower contains). If you really just want to test if a certain phrase is contained in the attribute, you should use `CONTAINS(t.labels.de.valueLower, 'thailand')` instead. LIKE is implemented using regular expressions, which is slower than a specific function like CONTAINS().

**Comment by smith64fx** [comment]
Hi @jsteemann 
Thanks for your fast response.

I tried your command and got this:
![image](https://cloud.githubusercontent.com/assets/3246782/21148253/eebdf0b6-c157-11e6-9f94-8129f40bc880.png)

In fact, the index seems not to be used.

Here are the index settings for the "topic" collection
![image](https://cloud.githubusercontent.com/assets/3246782/21148222/d8631396-c157-11e6-931d-d92b9971c159.png)

Is there anything else necessary to tell ArangoDB to use the index?
It's really strange, because the query for %Thailand% is very fast though the index is officially not enabled.

**Comment by smith64fx** [comment]
@Simran-B 
Thank you for this hint. 

Here is an example dataset:
```
{
  "aliases": {
    "de": [
      {
        "language": "de",
        "value": "Königreich Thailand"
      },
      {
        "language": "de",
        "value": "Ratcha Anachak Thai"
      }
    ],
    "en": [
      {
        "language": "en",
        "value": "Kingdom of Thailand"
      },
      {
        "language": "en",
        "value": "th"
      }
    ]
  },
  "descriptions": {
    "de": {
      "language": "de",
      "value": "Staat in Südostasien"
    },
    "en": {
      "language": "en",
      "value": "country in Asia"
    }
  },
  "id": "Q869",
  "labels": {
    "de": {
      "language": "de",
      "value": "Thailand",
      "valueLower": "thailand"
    },
    "en": {
      "language": "en",
      "value": "Thailand",
      "valueLower": "thailand"
    }
  },
  "sitelinks": {
    "dewiki": {
      "site": "dewiki",
      "title": "Thailand",
      "badges": []
    },
    "dewikiquote": {
      "site": "dewikiquote",
      "title": "Thailand",
      "badges": []
    },
    "enwiki": {
      "site": "enwiki",
      "title": "Thailand",
      "badges": []
    },
    "enwikiquote": {
      "site": "enwikiquote",
      "title": "Thailand",
      "badges": []
    }
  },
  "type": "item"
}
```
I have about 43 million documents of this type in the database originating from the Wikidata JSON Dump.

So I also tried with CONTAINS and for the "thailand" query it seems faster than the regex.
Unfortunately, when I query for "adfsadsadf" it runs again very long.

The explain in arangosh showed me this
![image](https://cloud.githubusercontent.com/assets/3246782/21161212/ee5b3c02-c187-11e6-812c-79deb6885c0d.png)

What I don't understand is: Why is ArangoDB not using the index I created?


Thank you very much for your help! ArangoDB is the best DB I've ever used 👍

**Comment by Simran-B** [comment]
I'll try to explain it in a very simplified (and thus not very accurate) way. Imagine an index data structure looking somewhat like the following:

```
A
  Af
    Afghanistan
  Al
    Albania
    Algeria
  Am
    American Samoa
  An
    Andorra
    Angola
    Anguilla
    Antarctica
    Antigua And Barbuda
  Ar
    Argentina
    Armenia
    Aruba
  Au
    Australia
    Austria
  Az
    Azerbaijan
B
  Ba
    Bahamas
    Bahrain
    Bangladesh
    Barbados
```

When you start looking up an entry in the index (let's say we are trying to find **Austria**), you need to go to the sublist under the right first letter (**A**). Using a hash-based type of index would us allow to jump directly to some entry, but it is only possible if it's an exact match, Hash("Austria") == Hash("Austria"). A skiplist type of index is more like walking over the first level of entries (A, B, C, ...) until the right entry point is found (*A*). Then, the entries on the second level under A are being iterated over until a match is found (*Au*). Then again, we loop over the entries under Au until a match is found (*Austria*).

If we looped over the flat list of countries, it would had taken 14 comparisons until *Austria* is found. By using some smart data structure, it becomes possible to skip some of the entries that we know are not relevant (all countries under Af, Al, Am, An and Ar). To find *Austria*, we only need 9 comparisons (the first 7 only against the first (two) letters of the search phrase).

Skiplist indexes do not actually group entries by letters like that, but what they do is to allow skipping over blocks of non-matching entries to spare us a lot of unnecessary comparisons. Now, the problem with `LIKE '%austria%'` and `CONTAINS('austria')` is that you can't take the first letter and look up the index, because the search phrase is supposed to be **somewhere** in the string, but not necessarily at the beginning. You might want to find *"Republic of Austria"* as well, in which *A* / *Austria* is not what the text starts with. Since we can not use the index, we have to iterate over the entirety of entries and test every string (and that is not just a simple == check, cause the search phrase can be at any position in the string).

There are probably other types of indexes, which would allow to accelerate contains-style lookups, but we don't have such in ArangoDB and it is non-trivial to do (unless there's no limitation of memory). What you could do is to use a full-text index instead and do per-word prefix-style searches (`prefix:austria` would match *Republic of Austria*, but not the fictional entry *Maustria*). Alternatively, there's also a way to do prefix-style searches (full entry starting with the search phrase as opposed to per-word) while utilizing a skiplist index: https://docs.arangodb.com/3.1/cookbook/UseCases/PopulatingAnAutocompleteTextbox.html


I'm not sure why your queries takes much longer if you're searching a non-existing entry however. That would only be expected if there was a LIMIT, so that the search stops after X matches without further testing against the remaining records.

**Comment by jsteemann** [comment]
I have tried to reproduce this with a local collection of 10,000,000 artificial test values.
Here's my test code:
```js
var query = `FOR t in topic FILTER t.labels.de.valueLower LIKE @value RETURN t`; 
var time = require("internal").time;
["%x%", "%test1000%", "%test10000%", "%test100000%", "%TEST%", "%asdfsfdsdds%", "%Thailand%", "%this is a very long string and matching will take longer%"].forEach(function(value) { 
  var s = time(); 
  var res = db._query(query, { value }); 
  var t = time() - s; 
  print("value:", value, "results:", res.toArray().length, "time:", t) 
});
```
It prints the following results:
```
value: %x% results: 0 time: 16.054481029510498
value: %test1000% results: 1111 time: 16.676566123962402
value: %test10000% results: 111 time: 16.22467803955078
value: %test100000% results: 11 time: 16.41826105117798
value: %TEST% results: 0 time: 15.913997888565063
value: %asdfsfdsdds% results: 0 time: 16.2606418132782
value: %Thailand% results: 0 time: 16.471983194351196
value: %this is a very long string and matching will take longer% results: 0 time: 20.114672899246216
```
That means I am not seeing any notable differences for queries that return results and queries that don't. 
However, the performance of LIKE also depends on the length of the pattern, as can be seen in the last line of the results.

By the way, here are the results for CONTAINS:
```
value: x results: 0 time: 8.853091955184937
value: test1000 results: 1111 time: 9.361598014831543
value: test10000 results: 111 time: 9.266539096832275
value: test100000 results: 11 time: 9.283586025238037
value: TEST results: 0 time: 8.787339210510254
value: asdfsfdsdds results: 0 time: 8.561698913574219
value: Thailand results: 0 time: 8.594917058944702
value: this is a very long string and matching will take longer results: 0 time: 8.514348983764648
```
As @Simran-B pointed out, it is faster because it is not regular expression-based.

**Comment by jsteemann** [comment]
If the queries on your end are reproducibly slower non-matches than for matches, this probably has another cause. Maybe you can try my test code above and check the results. It would surprise me if non-matches for LIKE are reproducibly slower once the collection is loaded and it fits in RAM.

**Comment by smith64fx** [comment]
@Simran-B 
Thank you for this easy-to-understand explanation. This would be a good example in the index documentation.

@jsteemann 
Also thank you for this nice test setup. I made some tests with the database using your code.

I also used a LIMIT to fasten up the things a little bit.
```
var query = `FOR t in topic FILTER t.labels.de.valueLower LIKE @value LIMIT 1 RETURN t`; 
```

These are the results with %ABC%
```
value: %thailand% results: 1 time: 0.1612100601196289
value: %dragonball% results: 1 time: 54.34961795806885
value: %michael jackson% results: 1 time: 3.6182448863983154
value: %notexisting% --> Took too long, aprox > 500s
```

With ABC%
```
value: thailand% results: 1 time: 0.12615394592285156
value: dragonball% results: 1 time: 38.397444009780884
value: michael jackson% results: 1 time: 2.6388731002807617
value: %notexisting% --> Took too long, aprox > 500s
```

With CONTAINS(ABC)
```
value: thailand results: 1 time: 0.015486001968383789
value: dragonball results: 1 time: 4.192897081375122
value: michael jackson results: 1 time: 0.27257394790649414
```

I really wonder, why "dragonball" is very slow compared to Michael Jackson which runs very fast.
I tried with LIMIT 10 and it took 2.563s overall.
One of the result is:
```
{ ...
"valueLower": "20th century masters: the millennium collection: the best of michael jackson"
... }

So "Michael Jackson" is not at the beginning of the valueLower string, but it searches very fast anyway.

**Comment by smith64fx** [comment]
@Simran-B 
I'm also trying to use your example here:
https://docs.arangodb.com/3.1/cookbook/UseCases/PopulatingAnAutocompleteTextbox.html

Looks very interesting and it's actually using the skiplist index!

**Comment by jsteemann** [comment]
I think the "LIMIT 1" addition makes it an unfair comparison.
This will end the query as soon as a single match is found. How fast the query is then depends on in which document the match is found. If the match is in the first document that's checked, the query will return fast. If the match is found at some later stage (e.g. in the 40,000,000th document) then the query will need to check 40,000,0000 documents and take some time.

**Comment by smith64fx** [comment]
@jsteemann I updated the query results.
The "LIMIT 1" caused the unfair comparison. Now everything seems normal. Sorry for that 😅

So for the search of strings inside of text (e.g. "this is michael jackson live at Seattle"), it's better to use a full-text-index?

If I use the full-text-index do I still need the skiplist index? 
What about the memory consumption of the full-text-index? 
The skiplist index takes about 3GB right now.

Thanks a lot for clarifying things @jsteemann and @Simran-B !

**Comment by jsteemann** [comment]
If you need substring matching, then the fulltext index won't help. It supports word and prefix matches only. If you need to search for fragments like `ael` or `ack` (to find "michael jackson"), then the fulltext index will not return the document. 
However, the skiplist index will not return the document either because it only supports exact and prefix matches for the entire value. 

In case you want to search for arbitrary substrings then no index type will work.

If you want to search for words or word prefixes, then the fulltext index can do it, and there is no need for the skiplist index. The skiplist index is good for finding exact matches of the entire search value or prefixes of the search value (e.g. `mich` or `michael j` if the value is `michael jackson live at Seattle`). The skiplist index does not support queries such as "find `mich` somewhere in string `this is michael jackson live at Seatlle`". That can only be achieved by a comparison function and using a full collection scan.

**Comment by smith64fx** [comment]
Hmm ok, so a full-text-index would only search for full words but not substrings.

Isn't it possible to make something like this?
"Start at the second character of the word".
```
FILTER t.labels.de.valueLower >= '**ailand' && t.labels.de.valueLower < '**ailane'
```

Will it be possible in the future to create an index for substrings? Is there not a theoretical solution for this? (Even if it consumes a lot of RAM) Google is also doing it and they also boil with water :-) (OK, it's an ocean of water)
This would be really nice so ArangoDB will also be perfect for data mining.

What we like to create is something that goes into the direction of a search engine, and we like to do it with ArangoDB.

**Comment by smith64fx** [comment]
@Simran-B @jsteemann This issue can be closed. Thank you for the answers!

**Comment by akki** [comment]
Using `CONTAINS` over `LIKE` is a really [good suggestion](https://github.com/arangodb/arangodb/issues/2221#issuecomment-266778503). I think it is worth documenting it so that everyone can leverage it.
