### ISSUE TITLE
Foxx: JWT token iat key

### ISSUE THREAD

**Issue by Heruabollo** [arangodb/arangodb#2249]
The iat (issued at) generated by the jwtStorage is of type NumericDate, and it's specified in the JWT RFC that "A JSON numeric value representing the number of seconds" and not milliseconds :) !

**Comment by jsteemann** [comment]
@pluma: can you have a look at this?

**Comment by pluma** [comment]
Okay, that is correct and the PR is a good start.

However this is a breaking change because it would break existing JWTs in a surprising way (they would probably not time out correctly as existing milliseconds values would be read as seconds values instead).

@fceller Can you make a decision about this? My recommendation would be to ship this in a minor release and document the changed behaviour. The old logic is definitely non-compliant with the specification.

**Comment by fceller** [comment]
@pluma yes, do not change this in 3.1. Change it in the upcoming 3.2.
