### ISSUE TITLE
Question: Fastest way how to insert data into DB

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangodb#2253]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.1

On this operating system:
- [x] Linux 
  - [x] Debian .deb

Hello, 

I want implement snapshot of DB. We have stored JSON documents which represent data what is necessary for recovering DB in particular time, so I'm looking for the fastest solution how to insert data into the database.

I thought that FOXX should be faster than ArangoJS driver, because Foxx lives inside DB, so there will be eliminated requests to HTTP API.

I wrote simple test, 2 000 devices who have 20 routes each. See implementation using ArangoJS. This test took 19s
```javascript
Promise.map(listOfDev, dev => {
    return storeDev(arDb, dev.devName)
    .then(sDev => {
      return Promise.map(dev.route, r => storeRoute(arDb, sDev._id, r));
    });
});

function storeRoute(db, devId, name) {
  return db.query(`for r in vRoute filter r.vDevId == @devId && r.name == @name return r`, {name, devId})
  .then(cursor => cursor.all())
  .then(results => {
    switch (results.length) {
      case 0:
        return db.collection('vRoute').save({vDevId: devId, name});
      default:
        return results[0];
    }
  });
}

function storeDev(db, name) {
  return db.query(`for d in vDev filter d.name == @name return d`, {name})
  .then(cursor => cursor.all())
  .then(results => {
    switch (results.length) {
      case 0:
        return db.collection('vDev').save({name}).then(r => r);
      default:
        return results[0];
    }
  });
}
```
Then I wrote same test using FOXX, this test took 394s - it's because FOXX is sync
```javascript
function storeDev(dev){
  const d = vDevItems.byExample({name: dev.devName}).toArray();
  switch(d.length) {
    case 0:
     return vDevItems.insert({name: dev.devName});
    default:
     return d[0];
  }
}

function storeRoute(vDevId, name){
  const r = vRouteItems.byExample({vDevId, name}).toArray();
  switch(r.length) {
    case 0:
     return vRouteItems.insert({vDevId, name});
    default:
     return r[0];
  }
}

router.get(function (req, res) {
  vRouteItems.truncate();
  vDevItems.truncate();
  const vLogItems = db.vLog.all().toArray();
  const start = Date.now();
  vLogItems.forEach(dev => {
    const d = storeDev(dev);
    dev.route.forEach(r => storeRoute(d._id, r));
  })
  res.send([{time: Date.now() - start}]);
}, 'list')
```

Then I tried to use FOXX Queues (200 workes), only insertion jobs to queues took 6.8s and all tasks was completed after 321s! (_jobs.modified - _jobs.created)
```javascript
router.get(function (req, res) {
  vRouteItems.truncate();
  vDevItems.truncate();
  const vLogItems = db.vLog.all().toArray();
  const start = Date.now();

  vLogItems.forEach(dev => q.push(
    {mount: '/test', name: 'saveDev'},
    dev
  ))
  res.send([{time: Date.now() - start}]);
}, 'list')

/***** saveDev.js script *****/
'use strict'
const argv = module.context.argv;

const vDevItems = module.context.collection('vDev');
const vRouteItems = module.context.collection('vRoute');

function storeDev(dev){
  const d = vDevItems.byExample({name: dev.devName}).toArray();
  switch(d.length) {
    case 0:
     return vDevItems.insert({name: dev.devName});
    default:
     return d[0];
  }
}

function storeRoute(vDevId, name){
  const r = vRouteItems.byExample({vDevId, name}).toArray();
  switch(r.length) {
    case 0:
     return vRouteItems.insert({vDevId, name});
    default:
     return r[0];
  }
}

const d = argv[0];
const dev = storeDev(d);
d.route.forEach(r => storeRoute(d._id, r));

```

**Comment by jsteemann** [comment]
I saw that when using the JS driver, the collections were named `vDev` and `vRoute`, and for the Foxx version they are named `vDevItems` or `vRouteItems`. This is not a problem, but I was wondering whether the collections have identical index definitions.

`vDev`/`vDevItems` should have an index on `name`, `vRoute`/`vRouteItems` should have an index on `[vDevId, name]`. If indexes are missing, the lookup operations will be unnecessarily slow. 

For example, when I run the inserts in Foxx without indexes, it takes 265 seconds. With indexes, it takes only 10 seconds. So probably the different insertion times are due to missing indexes in one case.

Additionally, is any of these collections created with `waitForSync` === `true`? If yes, this will make insert operations slower than when setting it to `false`.

Finally, the approach you've taken to ensure uniqueness is more expensive than necessary. For each item you're about to insert the code is performing an `all()` or `toArray()` query. If the normal case is that the item is not present yet (so insert will normally succeed), then it will be better to create a unique index and try the insert. Only if it fails a document lookup needs to be done.

I have created the unique indexes and changed the relevant code section as follows:
```js
function storeDev(dev){
  try {
    // first try insert...
    return vDevItems.insert({name: dev.devName});
  } catch (err) {
    // insert failed. now return the first document matching the search pattern
    return vDevItems.firstExample({name: dev.devName});
  }
}

function storeRoute(vDevId, name){
  try {
    // first try insert...
    return vRouteItems.insert({vDevId, name});
  } catch (err) {
    // insert failed. now return the first document matching the search pattern
    return vRouteItems.firstExample({vDevId, name});
  }
}
```
This change cut down the runtime to less than a second in Foxx.
The commands to create the unique indexes in ArangoShell were:
```js
db.vDevItems.ensureIndex({ type: "hash", fields: ["name"], unique: true });
db.vRouteItems.ensureIndex({ type: "hash", fields: ["vDevId", "name"], unique: true });
```

**Comment by Kurtas** [comment]
Firstly let me clarify setup. Yes, JS driver vs FOXX use different collections, it's only for testing purposes (comparing results). Each of collections had set ```waitForSync === false``` and also there wasn't any index. I thought that index optimization isn't needed for testing purposes.

But I just tested your suggested solution (unique indexes) and now both have similiar times.
- JS driver (async) 9529.924ms
- JS driver (sync Promise.mapSeries)  20933.033ms
- Foxx (no queue) 9121ms
- Foxx (using queue 200 workers) 
  - Fistr insert into queue 8121ms all jobs done 1020ms
  - Second insert into queue 10239ms all jobs done 1020ms
  - Third insert into queue 13179ms all jobs done 1020ms (how ```_jobs``` collection grow then insertion is slower)

Now I can see that FOXX can be little bit faster than JS driver, but it isn't still too big difference and also it depends on good DB design. Do you plan async in FOXX?

**Comment by jsteemann** [comment]
By using Foxx you may also save a lot of HTTP traffic. This can be beneficial if the network is slow or client application and database are on different hosts.
For example, if a Foxx route can insert all documents at once, it will only require one HTTP request from the client application. Compare this to issuing 2,000 times 20 HTTP requests for the individual inserts (probably even more, because at least in the old code each insert was actually a series of check-and-insert-only-if-not-already-exists operations).

And getting the indexes right will definitely help. Not only will the lookups be faster, but the index uniqueness will also save you from data races that the non-unique-index code will be suffering from. Without the unique indexes, two parallel client threads could at the same time detect that an entry was not yet present and both try to insert it (and succeed). By using a unique index only one thread will succeed. And by catching the error and turning the insert into a lookup as in my example the results will always be correct provided that documents aren't deleted from the collections in between.

Finally, regarding async operations in Foxx: at the moment they are not supported, and I myself don't if they are on the roadmap and for which version. I'll leave this up for others to answer.
