### ISSUE TITLE
Uploading Foxx services should be consistent among 3 methods

### ISSUE THREAD

**Issue by jperez110** [arangodb/arangodb#2274]
I am running arangodb version 3.1.8 via docker container from https://hub.docker.com/r/arangodb/arangodb/. We have the need to dynamically and programmatically add Foxx services so I'm using the HTTP API. I created a simple hello-world Foxx service and packaged it into a service1.zip. Using Web UI I was able to add service from the zip and query it with no problems. 
Next, when I would try with HTTP API via 

**curl --dump - -X PUT http://172.17.0.3:8529/_db/jperez/_admin/foxx/install --data '{"appInfo":"/foxx_services/service1.zip","mount":"/helloworld"}'**

I would get this error
**Put response: {"error":true,"code":500,"errorNum":4,"errorMessage":"unable to open zip file /foxx_services/service1.zip: internal error"}**

I discovered that problem was because my service1.zip contained my index.js and manifest.json in top level versus within a directory/folder. I repackaged the service1.zip so my  index.js and manifest.json resides within a services1 directory/folder and that solved the problem.

My concern is it worked within web UI and since we have 3 (web UI, foxx-manager, and HTTP API) ways to manage our Foxx services the 3 ways should behave the same and be consistent.

**Comment by jperez110** [comment]
Sorry, forgot to also mentioned when I succeeded in adding service via HTTP API it does not show up from Web UI even though its working.

**Comment by pluma** [comment]
The issue you're running into seems unrelated to *which* API you're using and instead *how* you're using it. The web UI simply uploads the file to the server and then invokes the same underlying method with the zip file's absolute file system path as you have done.

I'm guessing your docker container has a folder in its file system root called `foxx_services` and that folder contains the zip file?

The error message you're seeing indicates that the problem is caused by ArangoDB trying to extract zip file, not by the Foxx manager trying to find the manifest. Are you sure nothing changed between the attempts other than the contents of the zip file? Maybe the first zip file did not have the read permission set or was somehow corrupted?

Can you maybe check the ArangoDB logs and see if there's a related error?

**Comment by pluma** [comment]
For the record: foxx-manager uses the old HTTP API (`/_admin/foxx`). The old HTTP API, the Web UI's API (`/_admin/aardvark`) and the new (3.2) Foxx HTTP API (`/_api/foxx`) do the same thing internally when passed an absolute path. The only difference is that the Web UI and foxx-manager first use the upload API (which returns the file path they can then pass to their respective HTTP APIs).

The current problem aside, if you intend to manage Foxx from the CLI I would recommend looking into the new Foxx HTTP API which is experimentally available in 3.1 and will become officially part of the HTTP API in 3.2 (unlike the old API which is undocumented and only exists for backwards-compatibility with the foxx-manager CLI). You can find the swagger documentation by opening the services list in the web UI and activating the option "show system services". The service should appear as mounted at `/_api/foxx`.

**Comment by pluma** [comment]
@jperez110 Are you still able to reproduce this problem? Can you clarify whether my assumptions in the first comment are correct?

**Comment by jperez110** [comment]
Sorry, I've moved on to a different project. Please close this ticket. Thanks
