### ISSUE TITLE
Import data into ArangoDB.

### ISSUE THREAD

**Issue by new94** [arangodb/arangodb#2280]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1.8

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

How can i import edges from csv into ArangoDB? Or it's possible only from json?

**Comment by jsteemann** [comment]
You can use the arangoimp binary, which is shipped with ArangoDB.
Its manual is here: https://docs.arangodb.com/3.1/Manual/Administration/Arangoimp.html

You can invoke it as follows to make it import JSON data into a not-yet existing collection named "edges":
```
arangoimp --file data.json --type json --collection edges --create-collection true --create-collection-type edge
```
Use as follows to import CSV data into an existing collection named "edges":
```
arangoimp --file data.csv --type csv --collection edges
```

**Comment by new94** [comment]
@jsteemann Thanks! How should look csv for edges? Example:
_from _to
"id1" "id2" ?

**Comment by jsteemann** [comment]
For CSV the values in a line should be comma-separated, otherwise you will need to adjust the value for `--separator` or use `tsv` for `--type`.
Edges should consist of collection name plus document key, e.g. `users/foo` or `cars/bmw` because edges may refer to vertices in different collections. If all the edges in the import file should use the same collections, you can also make arangoimp auto-prefix them by using `--from-collection-prefix` and `--to-collection-prefix`.
In general, running `arangoimp --help` should show all the available options in case I missed some.

**Comment by new94** [comment]
@jsteemann Thanks!

**Comment by davidk08** [comment]
I am facing the problem that when i try to convert a csv file to json that it only imports the header row from the csv table into one json row as the final JSON-file in the arangoDB web interface. I am using the following command: 

 --file FC_ACTUAL_SALES.csv --type csv --collection myFoxxCollection -create-collection 

Any idea how to solve this issue @jsteemann

**Comment by dothebart** [comment]
please post at least the first two lines of the file, else we won't be able to help you with this.

**Comment by davidk08** [comment]
Planned output in the web interface:
SALES_VOLUMES: 205,8
NET_SALES: 770,61376
CM1: 428,21268
...
ENTRY_TS: 07-SEP-11 07.36.47.000000000 AM

Actual output in the web interface:
SALES_VOLUMES;NET_SALES;CM1;PRODUCT_MAIN_GROUP;REGION;SBU;SALES_TYPE;DATA_SOURCE;PERIOD;PERIOD_YEAR;PERIOD_HALF_YEAR;PERIOD_QUARTER;PERIOD_MONTH;CURRENCY;USERID;ENTRY_TS: 0;0;0;Oettinger Kellerbier;North America;Oettinger;3rd_party;BW B;201102;2011;1;1;02;eur;system;07-SEP-11 07.10.06.000000000 AM

As you can see, it imports all the headers from the csv header line into one object instead of only importing one header row per object.

**Comment by dothebart** [comment]
you probably need to specify 
`  --separator <string>                   field separator, used for csv and tsv (default: "")`
if you're using a semicolon instead of a coma (alas Coma separated values)
