### ISSUE TITLE
ArangoDB3 update fails on Ubuntu 16.04 because of the Expired GPG key

### ISSUE THREAD

**Issue by luav** [arangodb/arangodb#2284]
A few months ago I installed ArangoDB3 and now have had minor issues with software updates on Ubuntu:
```
$ sudo apt-get update
...
Reading package lists... Done
W: https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04/Release.gpg: Signature by key 4497DA50FBD0158CCFD1996CEE611E131C42E360 uses weak digest algorithm (SHA1)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1484090025
W: https://deb.packager.io/gh/opf/openproject-ce/dists/xenial/Release.gpg: Signature by key 6257DF9972462F57A20FFB2AB6D583CCBD33EEB8 uses weak digest algorithm (SHA1)
W: Failed to fetch https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1484090025
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

I'm aware that the new version is ArangoDB is 3.1 `https://www.arangodb.com/repositories/arangodb31/xUbuntu_16.04  arangodb3 3.1.8`, but:
1. Why do you have a distinct repository for the same major version, why users should manually update the reposinory for the non-major release?
2. Why the GPG Key is experied in just few months, why not to use some stronger digest algorithm and produce a long-term key?

Ideally, a life DBMS should not cause update issues using the official [Ubuntu] repository.

**Comment by dothebart** [comment]
we changed the build infrastructure with arangodb 3.1 - as we already told you a while back. 
The old infrastructure was based on the opensuse build system, which wouldn't produce "strong" signed files in first place. 
The new build infrastructure is completely inhouse where we control the cryptographic signing, thus can address these issues in first place. 
Since the new infrastructure leans on the cmake system producing the packages, it can't be ported to older versions. 

Please see issue #2031 for more details.

**Comment by luav** [comment]
Thank you for the clarification.
