### ISSUE TITLE
Using AQL bind parameters for graph traversal direction

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#2332]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.1

On this operating system:
- [X] Linux 
  - [X] Ubuntu .deb

### this is an AQL-related issue:
[X] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser: Firefox     running on this OS: Linux Mint 18.1

The AQL query in question is:

This is a feature request to be able to use bind parameters for graph traversal direction, e.g. for the following query:

    FOR y IN 1..2 @direction 'Collection/12345' GRAPH myGraph RETURN y

...where `@direction` is `INBOUND`, `OUTBOUND`, or `ANY`.

As it is, Arango just gives an error:
`Query: syntax error, unexpected bind parameter near '@direction'`

**Comment by dothebart** [comment]
This will most probably be difficult to implement due to the BISON parser not being able to distinguish between a graph query and regular queries anymore - the [INBOUND|OUTBOUND|ANDY] is an anchor for it.

If, it will most probably require to specially mark that bind parameter, as we do with collections - i.e. using a tripple-@. Due to the difficult nature it will probably done in the near future. 

Due to the above parser anchor issue its most probably not even easily possible to improve the error message.

**Comment by dothebart** [comment]
I will add a note to https://docs.arangodb.com/3.1/AQL/Graphs/Traversals.html that one can't use bind parameters for the direction.

**Comment by ropeladder** [comment]
Thanks for the response. A specialty mark would be great.

I don't really know how the parser works at all, but some possible other suggestions (if these are bad ideas please don't feel like you need to provide lengthy explanations of why they won't work):

-parse the bind params beforehand and substitute any params that have the string value of [INBOUND|OUTBOUND|ANY] directly into the AQL

-maybe it is possible to identify graph traversals as any FOR statements with the pattern FOR [var] IN [array] [INBOUND|OUTBOUND|ANY|param], since there is no situation (that I'm aware of) where you would use a bind parameter directly after a standard FOR loop (e.g. FOR x IN 1..100 @parameter).

**Comment by dothebart** [comment]
Closing as `wont't fix` since we didn't find a way to make this work with bison.
