### ISSUE TITLE
Deleting document with just the id

### ISSUE THREAD

**Issue by Pkoiralap** [arangodb/arangodb#2340]
Say there are many nodes in my graph. A node 'X' may be pointing to many other nodes. I wish to delete every node(documents from the collection) that X points to.
The REMOVE AQL command desires a collection. But if I have a globally unique id (_id = collection/doc_key) why should I need a collection in order to delete the document ? Is there a way to delete a document without the need of collection ??

**Comment by baslr** [comment]
@Pkoiralap you can write a transaction. The input is a list with all ids to delete and of course all affected collections.

```
some pseudocode

for id in ids
  [collection, key] = id.split('/')
  db._query('remove key in collection')
```

Read more about transactions https://docs.arangodb.com/3.1/Manual/Transactions/

I don't know the why but the doc says `Each REMOVE operation is restricted to a single collection, and the collection name must not be dynamic.`

**Comment by Pkoiralap** [comment]
The documentation part is confusing me. Why do I even need a collection if I have an id ? I am using **arangojs** for the database operations. And yes I can delete a document by simply using the `Collection.remove()` method. But that should be able to be done from the query as well, isn't it ?

**Comment by jsteemann** [comment]
The problem is that `REMOVE` in AQL works on a single collection.
Its syntax is:
`REMOVE key IN collection`
Now when an _id is specified instead of the key, then it would be possible to omit the collection name entirely. However, the `key` part in `REMOVE` can be an arbitrary expression, and `REMOVE` can also be invoked in a loop. If we then omit the collection name, we could end up with a query as follows:
`FOR i IN 1..3 REMOVE CONCAT('test', i, '/abc')` 
When executed, this would remove the documents `test1/abc`, `test2/abc`, `test3/abc`, from three different collections. When the query is parsed and initialized, the collections it will use would be unknown (at least in the general case when the key expression is more complex or includes runtime values).

While this is absolutely fine from the user perspective, the `REMOVE` command does not support it at the moment. It requires the collection name to be known in advance, while the query is parsed. This is why specifying the collection name is mandatory.

**Comment by dothebart** [comment]
https://docs.arangodb.com/3.2/AQL/Operations/Remove.html states this clearly now.
