### ISSUE TITLE
Java program going to waiting stage on cluster

### ISSUE THREAD

**Issue by ahr12** [arangodb/arangodb#2341]
I installed arangodb-3.1.11 using source code on ubuntu 16.04. and I am using Arangodb tool for the cluster (4 node cluster). 
My code going to waiting stage when one node goes to down and code start again when that node add on the cluster.
Why is it not working on remaining nodes?
why  Cluster is very slow as compare to a single node

**Comment by neunhoef** [comment]
We need a bit more information about what you are doing. If you, for example, have collections that are not replicated, then everything has to stop as long as one server holding such data is down. Only if you configure the `replicationFactor` to be more than 1, the system can fail over and service continues if one machine is down. So:

What collections are you using, what is your replicationFactor? What operations are you trying?

**Comment by ahr12** [comment]
Hello Sir,
I try to create the graph of some data using java code. and I run my code on the master coordinator. How can I configure the replicationFactor? 
And also I compare the running time on single node and cluster. cluster takes almost 2x times more as compare to the single node. Can you tell me how actually cluster work?

**Comment by neunhoef** [comment]
The `replicationFactor` is an optional parameter when you create a collection.

As to your observation with the performance. Some operations in a cluster naturally have a higher latency than on a single server, simply because they involve network hops, which can be several orders of magnitude slower than certain operations on a single server. This is to be expected and will in general be true for any distributed system. For example, on a gigabit ethernet, a network ping time is typically 300us (microseconds), whereas a full document write operation on a single server takes currently around 100us.

I cannot hope to explain here in any detail how an ArangoDB cluster works. Suffice to say that it is a complex distributed system without a single point of failure. Your client talks to processes called "coordinators" which know about the cluster topology and organise the execution of your query across the cluster. To this end, network communications with the "dbservers" happen, which are the processes that actually hold the data in a distributed, potentially replicated and thus fault tolerant way. There are complex supervision procedures to fail over should any part of the system fail.

Therefore, what you can expect from a cluster is fault tolerance (provided you configure data replication), more capacity than a single server (because you use more hardware resources), and higher throughput, at the cost of a certain increase in latency. I hope these explanations help.

**Comment by mpv1989** [comment]
The Java code for creating a collection with a replication factor:

`arangoDB.db().createCollection("myCollection",new CollectionCreateOptions().replicationFactor(2));`

**Comment by ahr12** [comment]
Hello Sir,
I create a collection with  replication factor using following line - 
arangoDriver.createCollection(edge1,new CollectionOptions().setReplicationFactor(2));
and I am try to use this collection as a edge collection 

// We start with one edge definition:
		EdgeDefinitionEntity edgeDefHasWritten = new EdgeDefinitionEntity();
		 
		// Define the edge collection...
		edgeDefHasWritten.setCollection(edge1);
		List<String> from = new ArrayList<String>();
		from.add("label");
		edgeDefHasWritten.setFrom(from);
		 
		// ... and ends.
		List<String> to = new ArrayList<String>();
		to.add("category");
		edgeDefHasWritten.setTo(to);
		edgeDefinitions.add(edgeDefHasWritten);

GraphEntity mgraph = arangoDriver.createGraph(graphname, edgeDefinitions, orphanCollections, true);

but i am getting the error
com.arangodb.ArangoException: [1218] labeledge cannot be used as relation. It is not an edge collection
com.arangodb.ArangoException: [1924] graph not found

**Comment by mpv1989** [comment]
Hello,
you have to set the type `CollectionType.EDGE` when creating the collection:

    arangoDriver.createCollection(edge1,new CollectionOptions().type(CollectionType.EDGE).setReplicationFactor(2));

**Comment by ahr12** [comment]
Hello,
I am using 3.1.3 arangodb java driver.and i am getting this- 
The method type(CollectionType) is undefined for the type CollectionOptions
I create my whole code base on java driver 3.1.3 so I can not change the java driver version .

**Comment by mpv1989** [comment]
This works for the old API (driver 3.1.x)

    arangoDriver.createCollection(edge1,new CollectionOptions().setType(CollectionType.EDGE).setReplicationFactor(2));

**Comment by ahr12** [comment]
Thanks. everything working fine now
