### ISSUE TITLE
Executing a certain number queries in web interface crashes Google Chrome

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#2352]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

### this is a web interface-related issue:
I'm using the web interface with this browser:  **Google Chrome**   running on this OS: **Mint Linux**

### repro steps ###
1) Log in to the web interface
2) execute any query (e.g "return 1")
3) then execute another query  (e.g "return 2")
4) keep executing queries until your browser crashes
...

The following problem occurs: [Screenshot?] 

It seems a web worker (new thread) is spawned each time you execute a query. Once I get up to 55  then all of my Web Interface browser tabs crash.
![c](https://cloud.githubusercontent.com/assets/1688049/23589720/24db0f16-01a0-11e7-964f-e308c5cb5c1d.png)

Pressing "Remove all results" doesn't help
Pressing "X" on the query result doesn't help

**Comment by hkernbach** [comment]
Many thanks for the detection. The main reason for that issue was the outdated version of ace editor. Updated now to version: 1.2.6. Memory cleanup looks much better now. Also small optimisations were made to the query editor view. 

Depending on your output results count and length, it is not totally impossible to not run into trouble. But removing results with "Remove all results" or "X" will clean memory now as expected.

This is fixed in 3.1 and devel branch. So it will be included in 3.1.16+ and 3.2.+

**Comment by dothebart** [comment]
3.1.16 is now available for Download - closing.
