### ISSUE TITLE
arangodb cluster read speed problems with authentication mode

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#2387]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [1 ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [1 ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ 1] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [1 ] authentication is enabled?
- [1 ] using the cluster?
- [1 ] _system database?

These are the steps to reproduce:
1) Install arangodb3.1.15 with the dcos 1.8.8
2) add a collection about 111k size, and install a service designed for testing download speed.
3) when i used the default seting which doesn't enable arangodb-jwt-secret, the maximum download speed is proportional to the coordinator number. And the download speed with just one client is equal to the arangodb standalone mode. It's great.
4) However, when I enable the "arangodb-jwt-secret" and do the same experiment, the maximum download get a half discount. Also it's never relative to the coordinator number.  I would be thankful if 
you talent will solve it soon! Thanks!

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by m0ppers** [comment]
Can you give us some hard numbers on this? It seems rather strange because the coordinators won't talk to each other. So to me it seems surprising that the number of coordinators should play any role in this issue.

Also the jwt authentication should not influence any download speed issues. How are you accessing arangodb? Is it through the DC/OS frontend? Please note that there are several components from DC/OS involved before it is even making it to arangodb.

Can you give us some more details on your setup (especially how you are accessing your foxx application?)

Also can you put up an example which is accessing ArangoDB from within the DC/OS cluster without any Mesos DNS etc. So something which would access the coordinator IP and port directly and give us some numbers?

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing lots of improvements to the clustering.
Closing this ticket since feedback has been missing.
