### ISSUE TITLE
Allow more characters in collection name

### ISSUE THREAD

**Issue by ghost** [arangodb/arangodb#243]
It would be great if you could allow more characters in the collection name
My suggestion is to at least support the POSIX Portable Filename Character Set
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_276

Related to issue #238

**Comment by CoDEmanX** [comment]
I'd actually like to revive the discussion. JavaScript allows the dollar sign `$` as [initial character in variable names][1] (aside from all kind of Unicode letters...), there's a [test tool][2] by the way.

ArangoDB requires the collection name to start with a letter, no other character is supported in this position. On the other hand, dashes `-` and underscores `_` are supported from the 2nd character on (dashes are illegal in JS, because they can't be told apart from subtraction operations). An odd, but legal name in Arango is `d-_-b` (smiley with headphones).

`#` and `@` are not allowed in either environment (in MongoDB they are apparently), although these characters have no special meaning (unlike `.`, `&` etc. in many programming languages).

I ran into the following problem: a customer's data comes in multiple databases with one table each, named after the contained record types or projects they were created for. One of the names was **"3D-Objects"**. I can't import it to a collection with this name to ArangoDB. But I can't prefix it with an underscore either (in JS, I would go for *_3D_Objects* or *_3dObjects*). My workaround was to prefix it with **"A_"** to keep it at the top when sorted alphabetically.

In another recent data source, some column names are called `_type` and `_version`. Because it's possible that `type` and `version` also exist, and I'd like to import the data straight without changing attribute names to something like `a_type` or `x--version`, underscore support would be of tremendous benefit.

Apart from backward compatibility, would speak anything against the dollar sign as prefix for system collections and attributes to free the underscore for users?

When sorted, `$key` would even come before `_key` and `KEY` (in contrast, `_key` comes after `KEY` because `_` has a numeric value of 95, which is between the upper and lower case character ranges).

Psychologically, I would argue that `$` looks more "dangerous" (less common) than an `_`, and seems thus predestined for system stuff.

Another solution could be to either use double underscores for system collections/variables or to allow them for user stuff (I would prefer the former, similar to Python naming conventions). But this can be very confusing, because it's hard to tell `_` and `__` apart plus the reasons mentioned by @jsteemann.

[1]: http://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names
[2]: https://mothereff.in/js-variables

**Comment by CoDEmanX** [comment]
+ Another Pro for `$`: looks like `S` as in **s**ystem
- Contra: some HTTP requests would use a mix of `_` and `$`, e.g.<br>`_db/$system/_api/collection/$jobs`, but end-users don't do much CRUD in system DB/collections

**Comment by jsteemann** [comment]
We could probably allow the characters `$`, `#` and `@` in collection names, but I would have to validate this first. The `@` will have the problem that it needs URL-escaping, and collection names are used pretty often in ArangoDB URLs. Using `@` in collection names and putting it into URLs (unescaped) will thus potentially cause some new client-side issues, but inside the server this should be relatively easy (to be confirmed).

I like the idea of using the `$` prefix for system collections instead of the underscore. The main problem with this is that it wouldn't be downwards-compatible if we renamed them all. 

Regarding numbers as the first collection name character: when allowing this, this would disable the feature of accessing a collections by its *id*. At least it would not allow the code to look at a given collection name string and figure out whether it's an id (all numeric) or a name. 
This could be kept somewhat working by making the collection lookup code first look for a collection *name* equal to the user-specified value, and if not found, check if the specified value was all numeric and additionally look for a collection with that *id*. And when creating a new collection, all names would be disallowed that are already used as collection ids, because then all-numeric names wouldn't be unambigious. But this sounds complicated and error-prone, especially as collection ids are auto-generated and you'll never know which will be the next one used. Creating collections with all-numeric names might therefore behave non-deterministically, which is not desired.
So we should either not allow it or disable looking up collections by id.

Regarding attribute names, user-defined attributes can already start with underscores (since ArangoDB 2.2.2.), but some attributes names are reserved (`_key`, `_id`, `_rev`, `_from` and `_to` at the moment - there may be more in the future but the list has been pretty stable for the last years).

**Comment by CoDEmanX** [comment]
In repect of Arango 3.0, I'd like to re-open this issue. It's quite a jump from 2.x, so changing the prefix from `_` to `$` for system-related fields and collections seems ok-ish in terms of backward compatibility.

> it would not allow the code to look at a given collection name string and figure out whether it's an id (all numeric) or a name

Don't you mean `_key` (all numeric)? Document keys are actually strings, and contain arbitrary characters, but automatically assigned keys use digit characters only so far. The most reliable way to distinguish keys from ids (`collectionName/documentKey`) is to check for the slash. I'm against digits as first character of a collection name though. Most programming languages don't allow variable names starting with a digit.

**Comment by jsteemann** [comment]
Collections can be accessed by name or by id. If we allow arbitrary characters in collection names (e.g. digits as first character), then we can't tell collection ids and collection names apart.

**Comment by CoDEmanX** [comment]
I see, makes sense. Never tried to access a collection via its ID, didn't even know you could.

So collection names should not be allowed to start with a digit for ideological as well as practical reasons. But what about the prefix change? It wouldn't affect the code to distinguish between collections names and collection IDs. It would affect aardvark and several other stock Foxx apps as well as a few customer apps and I guess also all Arango drivers. Furthermore, many AQL queries would require a change if they access internal fields (_key, _id, _to, _from, _rev). On the plus side, it's simple to change in affected code, the underscore would be freed up as escape character and URL path segments would be clearly distinguishable from system collection names and system field names in the HTTP API.
