### ISSUE TITLE
Misleading _getConnectingEdges documentation

### ISSUE THREAD

**Issue by jvnn** [arangodb/arangodb#2485]
I just spent quite some time trying to figure out why graph._getConnectingEdges doesn't work. Initially I was even having headaches with an "is not a function" error, because in the documentation the function is called "_connectingEdges". But the real problem is this:
```
  _getConnectingEdges (vertexExample1, vertexExample2, options) {
    options = options || {};
    // TODO
    return [];
  }
```

Please update the [documentation](https://docs.arangodb.com/3.1/Manual/Graphs/GeneralGraphs/Management.html) to reflect the fact that the function is not yet implemented.

**Comment by jvnn** [comment]
Managed to waste another 15 minutes due to this issue (had already forgotten about it). Would still appreciate a short note "not yet implemented" in the docs. :)

**Comment by harrigan** [comment]
Ugh, same here. Now the method contains a big chunk of commented-out code 👎

**Comment by Simran-B** [comment]
@graetzer Doesn't seem to be related to the multithreaded import commit, but you added the code there: https://github.com/arangodb/arangodb/commit/2f2d07ab9ac83953b12ffa136b4976e51f808428#diff-9de27fae767eff5586ca4de20eaa8722

Is it working?

One thing: I think `${optionsVertex1.maxDepth || 1}` should be changed to `${optionsVertex1.maxDepth || optionsVertex1.minDepth || 1}` because that is the AQL behavior AFAIK.

**Comment by Simran-B** [comment]
See https://github.com/arangodb/arangodb/issues/7395#issuecomment-443838448
