### ISSUE TITLE
Can't create database on NTFS storage

### ISSUE THREAD

**Issue by Cauterite** [arangodb/arangodb#2507]
ArangoDB version:
- [X] 3.1.21

On this operating system:
- [X] Linux 
  - [X] Debian .deb (x64)

When I create the symlink `/var/lib/arangodb3 => /mnt/my-ntfs-drive/db`, arango can't seem to create all of its database files and logs this error:

    ERROR cannot create datafile '/var/lib/arangodb3/journals/logfile-11.db': Operation not permitted

The entire NTFS drive has `777` permissions, as does the symlink itself. I think it's using the "NTFS-3G" driver. The drive has >100GB of free space.

If I instead make the symlink to ext4 storage instead, like `/var/lib/arangodb3 => /var/db`, it seems to work fine.

I honestly don't know enough about Linux to understand what the problem could be. I also can't seem to find a better way to specify the database directory than using a symlink, since the `/var/lib/arangodb3` path seems to be hard-coded.

I can't have the database in the root partition because the OS is running off a small/slow flash drive. I can't mount the entire NTFS partition at `/var/lib/arangodb3` since it's used for other purposes as well.

Any workaround suggestions would be greatly appreciated. Thanks.

**Comment by dothebart** [comment]
you can use 
```
[database]
directory = 
```
as documented in:
https://docs.arangodb.com/3.1/Manual/Administration/Configuration/GeneralArangod.html#directory

in /etc/arangodb3/arangod.conf
to configure the location of the database files. 

ArangoDB uses certain operation system calls to work with memory mapped files. Therefore the filesystem needs to support certain operations. 
We don't have any experiences with running ArangoDB on linux with mounted NTFS drives and I would not recommend that by any means for a production setup.

I would rather recommend to use a native windows environment with arangodb if you need to work with NTFS, otherwise we recommend to use the linux EXT4 filesystem.

**Comment by Cauterite** [comment]
Thanks, this is very helpful,

I guess I didn't think the `arangod.conf` option worked because it still creates the `/var/lib/arangodb3` folder, but doesn't use it. I'm using that now option instead of the symlink :+1:

It still fails with the same error, but you're probably right about the cause; the docs for NTFS-3G do mention a number of issues with memory-mapped files. I'll play around with its options, otherwise I'll try your other suggestions.

So I think we're done with this issue; thanks again for your assistance.
