### ISSUE TITLE
Feature Request - Change method for redirecting users to latest ArangoDB documentation

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2773]
This is a feature request for something that would be really great to resolve and trips me up a lot with the online ArangoDB documentation.

When you go to a page like https://docs.arangodb.com/3.0/Manual/Foxx/Context.html there is a link that says "This documentation is outdated. Please see the most recent version here: [Latest Manual](https://docs.arangodb.com/latest/Manual/)"

The problem is that the URL provided for 'Latest Manual' goes to the generic landing page of https://docs.arangodb.com/latest/Manual/ which means you lose the context of where you are.

If you click on the 'Latest Manual' link you then realise you lost your location, click the back button, and then manually update the URL of the page from /3.0/ to /3.1/ or /latest/

Would it be possible to have the 'Latest Manual' URL point to the same document location as the currently displayed page, but just replace the version number with /latest/?

So rather than have:
"This documentation is outdated. Please see the most recent version here: [Latest Manual](https://docs.arangodb.com/latest/Manual/)"
...you would have...
"This documentation is outdated. Please see the most recent version here: [Latest Manual](https://docs.arangodb.com/latest/Manual/Foxx/Context.html)"
...if you were on the page...
https://docs.arangodb.com/3.0/Manual/Foxx/Context.html

It could probably be done programmatically and not require someone to go through updating links.

Would be much appreciated.

The next challenge is to update your robots.txt file to remove linking of old documentation versions from google, and have your /latest/ url path linked to by Google so that you can autodirect to the current version.

**Comment by Simran-B** [comment]
We replaced Gitbook with Jekyll as site generator and the latest version is now always at `/stable`. In case of page renames there is the `redirect_from` plugin to forward users to the correct page, but there some issues with that, see https://github.com/arangodb/docs/issues/95

The pages set canonical URLs heuristically, which isn't perfect but hopefully better than before.

The version switcher allows you to switch between versions of the same page as long as that page exists in the other version too. Otherwise that version it is grayed out in the dropdown. To forward users to the corresponding new page in case of a move/rename/split, we would need to set that up manually, but don't have enough resources for such a small gain in usability.

The _Latest Manual_ link was generated on the client-side in the old system. This feature was not ported to the new system, so you only get _Try latest_ which points to `/docs/stable`.
