### ISSUE TITLE
init.d startup script does not honor directory param in arangod.conf

### ISSUE THREAD

**Issue by Arcticus** [arangodb/arangodb#2822]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

- Stopped arangodb3.service
- Created alternative db location folder
- Rsync'ed /var/lib/arangodb3 to alternative db folder
- Renames /var/lib/arangodb3 to /var/lib/arangodb3_old
- Updated /etc/arangodb3/arangod.conf "directory" database param to point at alternative db folder
- Update /etc/arangodb3/arango-dfdb.conf "directory" database param to point at alternative db folder
 - Started arangodb3.service

Startup fails as it is still looking for the /var/lib/arangodb3 folder.

How to correct:
- Modify /etc/init.d/arangodb3 to reflect new alternative db folder:
`( cd /var/lib/arangodb3 && chown -R arangodb:arangodb . && chmod 700 . ) || exit 1`

Expected that /etc/init.d/arangodb3 should honor the arangod.conf "directory" param.

**Comment by dothebart** [comment]
hm, there are several `directory` options for `/etc/arangodb3/arangod.conf` so without parsing the configuration there is no good way to reliably extract that option from the shellscript. 

Since this chown is mainly there to stop the novice user from running `arangod` from the root account, and voiding their directory permissions for subsequent starts, I think that somebody starting such configuration stunts should be able to detect and fix these issues himself. 

Thus closing as `won't fix`
