### ISSUE TITLE
confusing information about arangodb-Coordinator

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#2831]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
  - [x] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE .rpm
  - [x] RedHat .rpm
   - [ ] Fedora .rpm

In the DCOS admin UI, there are many logs flushing in the output logs.

Is it a import information warning me to do something to make it right? And How can I make it ?
Thanks!
![image](https://user-images.githubusercontent.com/25783698/28356646-6690af9a-6c9b-11e7-9475-3fb33b37241e.png)
![image](https://user-images.githubusercontent.com/25783698/28356789-ddef8f16-6c9b-11e7-829e-2dc741c46e71.png)
![image](https://user-images.githubusercontent.com/25783698/28356859-0d7e4e20-6c9c-11e7-9d7a-754ef4cdea14.png)

**Comment by dothebart** [comment]
Hi, 
sorry for the late reply. 
These are two coordinator hosts trying to talk to each other to synchronize their foxx application deployment state. 

Since this was 3.1, and that area was completely reworked with ArangoDB 3.2 I don't think this issue is relevant anymore. 

If you still have similar issues in DC/OS, please open a new ticket; I will close this one now.
