### ISSUE TITLE
DBServer crashing automatically post upgrade to 3.2

### ISSUE THREAD

**Issue by krjain** [arangodb/arangodb#2920]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
3.2

Mode:
Cluster

Storage-Engine:
mmfiles

On this operating system:
Linux 

authentication is enabled

Problem Description:
After upgrade to 3.2, The dbservers are going down in every few hours.
I do not see anything in the logs either. 
The cluster is described below in details

**Cluster details:**
4 machine: server1,server2,server3,server4

**Commands to start servers:**

**agency:** server1, server3,server4
numactl --interleave=all /usr/sbin/arangod --pid-file /var/run/arangodb3/arangoagency.pid --gid arangodb --configuration /etc/arangodb3/agency.conf &

**primary:** server1, server2
numactl --interleave=all /usr/sbin/arangod --gid arangodb --pid-file /var/run/arangodb3/arangoprimary.pid --configuration /etc/arangodb3/primary.conf &

**coordinator:** server2,server3,server4
numactl --interleave=all /usr/sbin/arangod --gid arangodb -pid-file /var/run/arangodb3/arangocoord.pid --configuration /etc/arangodb3/coordinator.conf &

**primary.conf:**
[server]
endpoint = tcp://0.0.0.0:8529
authentication = true
statistics = true
uid = arangodb
jwt-secret = somesecret

[query]
slow-threshold = 0.5

[database]
directory = /test/arangodb/primary

[cluster]
my-role = PRIMARY
my-address = tcp://server1:8529
agency-endpoint = tcp://server1:12001
agency-endpoint = tcp://server3:12001
agency-endpoint = tcp://server4:12001

[javascript]
startup-directory = usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /test/arangodb/log/primary/primary.log

**agency.conf:**
[server]
endpoint = tcp://0.0.0.0:12001
authentication = true
statistics = true
uid = arangodb
jwt-secret = somesecret

[query]
slow-threshold = 0.5

[database]
directory = /test/arangodb/agency

[agency]
my-address = tcp://server1:12001
activate = true
size = 3
supervision = true

[javascript]
startup-directory = usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /test/arangodb/log/agency/agency.log

**coordinator.conf:** 
[server]
endpoint = tcp://0.0.0.0:8532
authentication = true
statistics = true
uid = arangodb
jwt-secret = somesecret

[query]
slow-threshold = 0.5

[database]
directory = /test/arangodb/coordinator

[cluster]
my-role = COORDINATOR
my-address = tcp://server3:8532
agency-endpoint = tcp://server1:12001
agency-endpoint = tcp://server3:12001
agency-endpoint = tcp://server4:12001

[javascript]
startup-directory = usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /test/arangodb/log/coordinator/coordinator.log

**Comment by jsteemann** [comment]
Is it possible to enable coredumps on the dbservers and install debug symbols? 
This would help us gather more information in case a server goes down.
Apart from that, is there anything relevant in the syslog(s) for the time that servers went down (e.g. invocation of OOM killer)? 
Am I correct in understanding that this affects the dbservers in the cluster but not the coordinator or agency servers?

**Comment by krjain** [comment]
enabling coredumps on dbserver.

OOM killer logs:
I see the following lines in OOM Killer
Scheduler[71160] trap invalid opcode ip:1b2a949 sp:7fa0279f8af8 error:0 in arangod (deleted)[400000+22be000]
Scheduler[4710] trap invalid opcode ip:1b2a949 sp:7ffb216fa198 error:0 in arangod[400000+22be000]
V8GarbageCollec[98959] trap invalid opcode ip:1b2a949 sp:7f9f1a9fc728 error:0 in arangod[400000+22be000]
V8GarbageCollec[12317] trap invalid opcode ip:1b2a949 sp:7fc3651fc728 error:0 in arangod[400000+22be000]

This problem does not happen for coordinators and agencies. Only Primary is killed.

**Comment by jsteemann** [comment]
May the primaries be running out of memory? 
I mean, does the syslog indicate anything about the OOM killer having picked arangod processes as its victims, or are the above lines the only information in the logs concerning arangod?

**Comment by krjain** [comment]
This is the only arango related messages we see for OOM Killer.

Another point to be noted is, primary goes down immediately after we see:
V8GarbageCollec[12317] trap invalid opcode ip:1b2a949 sp:7fc3651fc728 error:0 in arangod[400000+22be000]

There are no other processes running on this box apart from another arangodb agency.

**Comment by jsteemann** [comment]
Is this actually an OOM killer-related message?
I am sure the OOM killer logs different messages depending on which Linux is used, but when I recently had to do with it, it logged a lot of extra information about the process to be killed into the syslog.
In the above message, I do not see any indication about the OOM killer. 
It rather looks like the above message is not related to the OOM killer at all, but that the kernel has trapped an application that tried to execute an instruction that the CPU or VM was not able to execute.
Are you running the dbservers on virtual machines or in cloud infrastructure? What CPUs are reported in /proc/cpuinfo? It would also be good to have a look at the coredumps (or backtraces) if any are available. Thanks!

**Comment by krjain** [comment]
We are running them on physical server (92GB, 64core, x64). 

It seems like a V8 issue. Please have a look at:
https://github.com/nodejs/node/issues/3898

The service seems to fail because of V8.  

This was not happening in versions prior to 3.2.

I have enabled coredump. I will share the logs once the server fails again. Also, the DBserver is failing in high load only.

**Comment by jsteemann** [comment]
As far as I can see the "illegal instructions" are produced by V8.
Whenever V8 runs out of memory, it will calls its own out-of-memory handler, which will log some information to stdout/stderr and then call V8's `OS::Abort()`function. This will simply call `__builtin_trap`, which according to the GCC manual is a platform-dependent way to exit the program abnormally:

> This function causes the program to exit abnormally. GCC implements this function by using a target-dependent mechanism (such as intentionally executing an illegal instruction) or by calling abort. The mechanism used may vary from release to release so you should not rely on any particular implementation. 

On my local Linux `__builtin_trap` will cause an illegal instruction error which will be loged to the syslog. Chances are that this is the exact same behavior as you have seen.

There is no proper way to fix this because the error happens in V8 when it runs out of memory and it is a non-recoverable error. A potential workaround however is to increase the minimum number of V8 contexts by adjusting the value in startup option `--javascript.v8-contexts-minimum`.

In ArangoDB versions older than 3.2, there was only one configuration option to control the number of V8 contexts for JavaScript execution: this variable `--javascript.v8-contexts` controlled the fixed number of V8 contexts that would be created at server start. While the server was running, no more V8 contexts would be created. So context creation did not happen at runtime and could not fail because of OOM. Still V8 could run out of memory, but not during context creation. The default value for the number of contexts to create was `0`, which meant that the value was dynamically set to the number of scheduler threads, which itself would default to the number of available cores. So potentially the number of contexts was rather high. Potentially these contexts used a lot of memory, and as they were created at server start, there was no way to reduce that memory usage if the contexts were actually unused or only partially used.
Because of that we changed the behavior in 3.2: the number of V8 contexts is now dynamic so it can vary at server runtime. The number of contexts started will now float between `--javascript.v8-contexts-minimum` and `--javascript.v8-contexts`. So by default the server will start with only few contexts and will dynamically create new contexts if needed. If contexts are unneeded, the server will dispose them eventually. This can lead to V8 context creation at runtime, something we did not have in 3.1. If this context creation triggers an OOM error in V8, then this will terminate the server process. To prevent this from happening, it is possible to set `--javascript.v8-contexts-minimum` and `--javascript.v8-contexts` to the same fixed value. 
This will not entirely keep V8 from running out of memory, but it eliminate the possibility that it fails during V8 context creation.
Can you try that out? If the servers have 64 cores, then you may want to try `--javascript.v8-contexts-minimum 64 --javascript.v8-contexts 64` to mimic the 3.1 default behavior.

**Comment by jsteemann** [comment]
3.2.1 will contain a fix that will attempt to log a FATAL error into the arangod logfile in case V8 runs out of memory. In case V8 runs out of memory there is not much that can be done about it, and it will terminate the entire process. But at least there should be something in the logs indicating what the problem was. Apart from that, the process should be exited with SIGABRT rather than SIGILL as it shouldn't go into the `__builtin_trap` anymore.

Anyway it would be helpful if you could also check whether adjusting `--javascript.v8-contexts-minimum` (as suggested above) also mitigates the problem. Thanks!

**Comment by krjain** [comment]
I have restarted the cluster with the suggested config.
Will update if it works well this time.

**Comment by jsteemann** [comment]
Thanks!

**Comment by krjain** [comment]
Hi Jan,
Seems like the workaround suggested is working just fine.
I have used  --javascript.v8-contexts-minimum 64 --javascript.v8-contexts 64 while starting arango instances. My cluster looks healthy.

Thanks for your help.

**Comment by fceller** [comment]
@krjain now that it is running could you check the resident size and virtual size of the arangod process and post them here? Thanks a lot

**Comment by dothebart** [comment]
Ok, I think we can close this as resolved then.
