### ISSUE TITLE
[3.2] [RocksDB] Slow response when use LIMIT

### ISSUE THREAD

**Issue by amurchick** [arangodb/arangodb#2948]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.0

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Debian .deb

I'm issuing AQL via:
- [x] arangosh

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is: `FOR d IN onem LIMIT 999970, 10 RETURN d`

The issue can be reproduced using this dataset: `FOR uid IN 1..1000000 INSERT {uid} IN onem`

These are the steps to reproduce:
1) Create collection with 1 millions documents: "FOR uid IN 1..1000000 INSERT {uid} IN onem"
2) Make queries:
```
127.0.0.1:8529@test> console.time('query'); db._query("FOR d IN onem LIMIT 70, 10 RETURN d"); console.timeEnd('query') 
2017-08-04T05:24:00Z [3281] INFO query: 2ms                

127.0.0.1:8529@test> console.time('query'); db._query("FOR d IN onem LIMIT 999970, 10 RETURN d"); console.timeEnd('query')                                                                                                                    
2017-08-04T05:24:09Z [3281] INFO query: 208ms              
```

Whats wrong: The larger `offset` in `LIMIT`the more slow response.

**Comment by jsteemann** [comment]
> Whats wrong: The larger offset in LIMIT the more slow response.

I honestly do not have any idea how to fix this.
The RocksDB storage engine in ArangoDB intentionally does not keep any indexes or documents in RAM except for caching purposes. That means a collection scan like `FOR doc IN collection LIMIT offset, x` will actually have to go through the documents one by one and skip them until the offset value specified in `offset` has been reached.
That means it has a complexity of `O(offset)`.

I am not saying that the skipping code cannot be optimized, I am just unsure how to solve the problem in general given the algorithmic complexity of the operation.

**Comment by pocketwalker** [comment]
any progress on this issue? "LIMIT 5000" is slow enough...

**Comment by jsteemann** [comment]
@pocketwalker : can you elaborate on "LIMIT 5000 is slow enough"?
The original issue was about using a high offset, e.g. "LIMIT x, y" (where x is a high number). A high offset requires a lot of scanning of data in the collection, so the execution time will be proportional to the value of x. This is somewhat unavoidable, and I would be surprised if other databases do behave much different here.
Or is your question more about a query that doesn't use an offset at all? I am asking because "LIMIT 5000" is effectively "LIMIT 0, 5000", i.e. a query with an offset of 0, so it may be a completely different thing.
Anyway, more information is needed to give you a sound answer.
Apart from that, this issue was opened for ArangoDB version 3.2, and the currently released version is now 3.4.5. There may have been other improvements since 3.2 that could have led to better execution times, but I cannot answer this more specifically as I don't know your exact use case, query, indexing etc.

**Comment by pocketwalker** [comment]
@jsteemann Thanks. In arangodb, I create a big graph with collections(nodes & edges) and run my queries on it. and I created primary and hash index on all collections. 
My question here is that, what's the best practice if I want to get 5000 nodes/edges from billions, like blablabla LIMIT 5000 quickly?

**Comment by jsteemann** [comment]
@pocketwalker : the key thing in a query that uses `LIMIT 5000` will not be the performance of the skipping (as `LIMIT 5000` will perform absolutely no skipping) but if the query can make use of any indexes (and which).
Without any knowledge about the actual query and the setup that is all I can say right now.

**Comment by pocketwalker** [comment]
@jsteemann could you take a look at this issue, [?](https://github.com/arangodb/arangodb/issues/9040) I put the query and also explain() into it.

**Comment by TimNZ** [comment]
This issue should be closed, @jsteemann explained it perfectly.

@pocketwalker:
If you don't use indexes smartly, your queries will get slower if a full scan is required, which always has to start at Document zero in the collection - all LIMIT does is skip processing X first documents, which it first has to scan regardless.

**Comment by dothebart** [comment]
since the referenced issue has been marked as solved, closing this as solved too.
