### ISSUE TITLE
Collection _key autoincrement value increases on error

### ISSUE THREAD

**Issue by sandrokeil** [arangodb/arangodb#2968]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [ x Linux 
  - [x] docker - official docker library

## Problem

Assuem I have a collection with these options:

```php
            [
                'keyOptions' => [
                    'allowUserKeys' => false,
                    'type' => 'autoincrement',
                    'increment' => 1,
                    'offset' => 1,
                ],
            ]
```

If an error occurs, the auto increment value increases nevertheless. So gaps can be occurred in the sequence, even If I use the transaction feature. Is there a way to prevent gaps in the auto increment value?

**Comment by jsteemann** [comment]
The auto-increment values are increased and handed out on each insert attempt. 
Even if an insert fails, the auto-increment value is never rolled back.
While in theory it would be possible to roll them back on error, this would require serializing all insert operations on a collection or holding an exclusive lock on the global auto-increment value for the entire insert operation, but both options would not be good for parallelism.
At the moment I don't see a way of making the value roll back on error.

**Comment by sandrokeil** [comment]
Alright, maybe a hint in the docs would be good.

**Comment by jsteemann** [comment]
Ok, let's add a hint to the documentation then.

**Comment by jsteemann** [comment]
Adjusted the docs accordingly.

**Comment by Simran-B** [comment]
Even if rolled back, gaps would still occur if you deleted documents.

For what purpose would you need gap-less, auto-incrementing numbers? Maybe there's another solution to your problem.

**Comment by jsteemann** [comment]
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).

**Comment by AhmadMansour** [comment]
Hello all,
I wonder if this issue has been resolved. We really need the auto-incremented value to be rolled back on error. This kind of gap-less identity is necessary for reliability of financial transactions.
Thanks.

**Comment by jsteemann** [comment]
@AhmadMansour: no, this issue hasn't been addressed.
The auto-increment value is still increased on every insert **attempt**, not only on successful insert. As mentioned above in 2017, the issue would be hard to fix, as it would require waiting for insert operations to fully succeed before increasing the auto-increment value. This would limit concurrency to 1 for insert operations on a particular collection, at least for some of the necessary steps. This is an unwanted side-effect.

Since the issue was originally reported, the docs reflect that current behavior:
https://www.arangodb.com/docs/3.8/http/collection.html#key-generator
