### ISSUE TITLE
Unused variable seems to be executed

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#3050]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
- [ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
```
FOR package IN packages
  FILTER !IS_NULL(package.Architecture)
  LET isGithub = LIKE(package["Vcs-Git"], "github")
  FOR architecture IN SPLIT(package.Architecture, ' ')
    COLLECT arch = architecture INTO g
    RETURN {
      architecture: arch,
      packages: g[*].package.Package,
      packagesCount: LENGTH(g[*].package.Package)
    }
```
It seems that `isGithub` is executed (tested by copying and pasting the variable multiple times and seeing that the execution time of the query increases) despite it is not used. Arango usually ignores unused variables (and it is also not included in the execution plan) however it seems like it is not the case when `COLLECT` (or custom imported function) is used.

The issue can be reproduced using this dataset: [Debian packages](https://github.com/arangodb/example-datasets/tree/master/DebianDependencyGraph)

**Comment by jsteemann** [comment]
Yes, the `isGithub` variable and its associated expression `LIKE(package["Vcs-Git"], "github")` will not be removed from the query if `COLLECT...INTO` is used.
The reason is that all variables in the scoped will be captured in the COLLECT result variable (`g` in the above query). And as `g` is accessed later in the query, it may be unsafe (in terms of changing query results) to remove some input variables for it from the query.

In order to keep just specific variables in the COLLECT result variable, you can use `KEEP`, e.g.
```
COLLECT arch = architecture INTO g KEEP package
```
This will then also optimize away the variable `isGithub`.

**Comment by gurisko** [comment]
Thank you @jsteemann!
