### ISSUE TITLE
Web UI redirects to database selection form instead of logon form

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#3064]
When the server goes down, the Web UI shows the disconnect message:

> You have been disconnected from the server

When the server comes back online and the UI reconnects, it throws you back to the database selection form, but only "database" is listed as database (placeholder in the template?).

Instead, it should redirect to the logon form (except if there's no authentication I guess, in that case the database selection form would be correct, but it needs to list the actual databases).

![image](https://user-images.githubusercontent.com/7819991/29416029-28c8ddc8-8365-11e7-997f-fda7bf9802e6.png)

Windows 10, Chrome 60.0.3112.90,
3.2 branch (custom build) at cbe004d35296bc4cd104cfc0b28a611feb8f8610

**Comment by hkernbach** [comment]
I think this is related to https://github.com/arangodb/arangodb/issues/2835 and should be fixed. You are using a custom build, that means all UI related stuff is not newly built because we are not pushing those files. So you could either wait and test the next bugfix release or build all front-end files.

Under path: `js/apps/system/_admin/aardvark/APP` run `grunt deploy` (you need grunt + grunt-cli + all node packages - run "npm install" in the same folder)

**Comment by hkernbach** [comment]
Closing this issue now. Should be fixed. Please reopen if not.

**Comment by Simran-B** [comment]
Redirects to login page at 066e91e1ed7555381f63f99b593da8a49072f124 ✔️
