### ISSUE TITLE
AQL: Sparse index not applied (non-sparse yes)

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#3334]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [*] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [*] Single-Server

Storage-Engine:
- [*] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [*] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [*] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

Running query with non-sparse hash index => index is applied. Running same query with sparse hash index => index is not applied. See attached screenshot with explain
![sparse_index_bug](https://user-images.githubusercontent.com/13378043/30922310-0c69bb5c-a3a9-11e7-9572-584323333eb0.png)

**Comment by jsteemann** [comment]
I think this is "intentional".
The sparse index does not contain the documents for which the indexed attribute ("hash" in this case) is `null` or not present at all.
 So if the join condition "i.hash == c.vId" used the sparse index, it would exclude all documents for which the "hash" attribute is either not present or has a value of `null`. That would mean if such documents exist, the result of the join would be different than if the sparse index would not be used at all.
And because an index should not change the result of a query (apart from potentially different sort order if not explicitly specified in the query), the sparse index is not used for the join condition. The non-sparse index contains all documents, regardless of the value of the "hash" attribute, so it can always be used for any join operation.

**Comment by roman1720** [comment]
What we had was non-sparse index with unique options. But problem was with documents which didn't had that property. So there was unique constraint violation. I thought sparse index would solve this, but obviously not. Is there any solution for that? Unique index on property which can be missing in documents? Thanks for your help Jan

**Comment by jsteemann** [comment]
You are right, a non-sparse unique index will not work here as it will trigger a "unique constraint violation" should more than one document lack the indexed attribute. Only a sparse index will allow this.
However, the sparse index cannot be used safely for all queries.
At the moment I do not see a good way for achieving uniqueness on an optional attribute with an index AND using the same index for general purpose queries.

**Comment by roman1720** [comment]
OK, we will do workaround to have property always present on document with unique non-sparse index. Thank you!
