### ISSUE TITLE
export database name with dump for easier restore

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#3504]
I'm finally upgrading from ArangoDB 3.1 to 3.2 and from mmfiles to rocksdb.
Update was a charm, but one obstacle could have been avoided, talking of "sensible defaults":

During export with `arangoexport`, the database *name* is not exported along with the structure, only the collections are written out.
So later during restore, you have to specify the database name explicitly; if you forget to do that, *all* collections are added to the *_system* database, which is 99.99% never what you want.

Either, the `--server.database` parameter should be *required*, or the original database name should be taken as default (from the dump).
Then, you could still restore into a different database, which is a valid use case, too, but would not risk polluting the `_system` database when forgetting this option.

This is all the more important since there currently *is no easy way* to delete *all* or an array of collections of a database with AQL or over the arangosh.

**Comment by jsteemann** [comment]
Arangoexport will not return the name of the database, but arangodump does (in the "dump.json" file it generates). However, it is only informational as of now.
I think it would make sense to have a mode in arangorestore that compares the name of the (source) database in "dump.json" with the name of the target database, and bail out if they do not match. That should be optional however, because it is a valid use case to restore data into a different database.

You are right, there is no (easy) way to drop collections from within AQL. In fact, this is not possible at all. It is however easy from the ArangoShell, as it allows execution of JavaScript commands such as:
```js
[ "foo", "bar", "baz"].forEach(function(name) { db._drop(name); });
```

**Comment by jsteemann** [comment]
Should be addressed by this PR: https://github.com/arangodb/arangodb/pull/4215

**Comment by maxkernbach** [comment]
Hi,

version 3.3.3 is released. It includes the added option `--force-same-database` for arangorestore.

With this option set to `true`, it is possible to make any arangorestore attempt fail if the specified target database does not match the database name specified in the source dump's "dump.json" file. It can thus be used to prevent restoring data into the "wrong" database.

The option is set to `false` by default to ensure backwards-compatibility.

Please note that `arangodump` saves the name of the (source) database in the "dump.json" file, while `arangoexport` will not return the name of the database. Therefore this option is only useful when using `arangodump`.
