### ISSUE TITLE
Array sort function

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#3518]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

On this operating system:
- [x] Debian .deb

### this is an AQL-related suggestion:
It would be useful to have an array sort function.

For example I'm in a case where I would like to group on all the values from an array that do not appear in a reference array (array difference). But documentation for `minus()` says "the order of the result array is undefined and should not be relied on."

I guess this would work if `minus()` result could be sorted afterwards.

Example code :
```
LET ref_array = ["a", "b", "c"]
LET docs = ([
    { k: ["a","b","d","e"] },
    { k: ["a","b","c","e","d"] },
    { k: ["a","b","d","e"] },
    { k: ["a","b","e","d"] },
    { k: ["a","b","d","e","f"] }
])
FOR d IN docs
    COLLECT dif = MINUS(d.k, ref_array)
    WITH COUNT INTO nb
    RETURN { dif, nb }
```

Result :
```
[
  { "dif" : [ "d", "e" ], "nb" : 2 },
  { "dif" : [ "e", "d" ], "nb" : 2 },
  { "dif" : [ "f", "e", "d" ], "nb" : 1 }
]
```

Desired result :
```
[
  { "dif" : [ "d", "e" ], "nb" : 4 },
  { "dif" : [ "d", "e", "f" ], "nb" : 1 }
]
```

Thanks,
Mathias

**Comment by jsteemann** [comment]
There is an internal helper function `SORTED_UNIQUE` that is currently undocumented. AQL uses it for some internal sorts, but I think it is also called from user queries.
It's not a pure sort function, but also produces uniqueness of the result array, but it should help in your case.
If you change the following line of your query from
```
    COLLECT dif = MINUS(d.k, ref_array)
```
to
```
    COLLECT dif = SORTED_UNIQUE(MINUS(d.k, ref_array))
```
then it should work.
However, the function is currently undocumented and not official part of AQL. We may properly document and expose it in a future release, but I cannot tell yet when there will be time for this.

**Comment by Simran-B** [comment]
I added MINUS() to issue #3467 although it's not helping here - the original element order is not sorted, no matter what MINUS() or other array functions might do to the element order.

You can use the high-level SORT operation on arrays however:

```js
FOR d IN docs
    COLLECT dif = (FOR elem IN MINUS(d.k, ref_array) SORT elem RETURN elem)
    WITH COUNT INTO nb
    RETURN { dif, nb }
```

`REMOVE_VALUES(d.k, ref_array)` would work as well by the way.

The high-level operation is pretty powerful, you can `SORT elem ASC` or `DESC`, by multiple values, or even based on some other calculated values. It also respects the sorting rules of the specified server language. And if you already use a sub-query, you could apply filters, limit etc. if useful. You could get rid of the array function call altogether even:

```js
FOR d IN docs
    COLLECT dif = (
      FOR elem IN d.k
        FILTER elem NOT IN ref_array
        SORT elem
        RETURN elem
    )
    WITH COUNT INTO nb
    RETURN { dif, nb }
```

A function call to sort like `SORTED(d.k)` would be fast to type for a simple sort like you want it, but the function would be less versatile - unless we added a bunch of comparator options? Here some random ideas: 

    SORTED(d.k, { order: "DESC", language: "sv-SE", natural: true, keepNull: false })

The ability to sort according to the rules of a given language independent of the server language might be useful for some use cases. Natural sorting could sort numbers in text based on their value instead of plain lexicographic. Null values could optionally be dropped, see #3496 - but `REMOVE_VALUE(d.k, null)` could also do that.

**Comment by matcho** [comment]
Thanks for the information about SORTED_UNIQUE and the use of SORT in a more general way, I'll do that !

**Comment by jsteemann** [comment]
Note that our devel branch (to become 3.4) now "officially" provides SORTED and SORTED_UNIQUE.
Introduced by this commit: https://github.com/arangodb/arangodb/commit/7018d003cce31bf2cbfd037e9e92b8ae92a50e16

**Comment by maxkernbach** [comment]
This feature is implemented by the [**SORTED()**](https://docs.arangodb.com/3.4/AQL/Functions/Array.html#sorted) and [**SORTED_UNIQUE()**](https://docs.arangodb.com/3.4/AQL/Functions/Array.html#sortedunique) functions in 3.4.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
