### ISSUE TITLE
Sort by numeric value of autoincrement _key

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#3539]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Storage-Engine:
- [x] rocksdb

On this operating system:
  - [x] Ubuntu .deb

### this is an AQL-related issue:
I'm using a collection created with
```
db._create("mycollection", {
  keyOptions: {
    type: "autoincrement",
    offset: 0,
    increment: 1
  }
});
```

I'd like to obtain easily the _n_ latest docs, and paginate back. As those docs do not (by default) have a date, I intended to use `SORT doc._key DESC` along with `LIMIT offset, n`.
With a manually created index on `_key`, this is very efficient.

But. The fact is `_key` is always a string, and not a number, even though autoincrement feature guarantees it contains a number. Thus the sort is alphabetical and the result I get is not what I expect.

It's possible to sort on `TO_NUMBER(doc._key)` but the index is not used and the performance is poor.

Adding a new autoincrement integer field to each doc could solve the problem (although it's not very elegant) but it doesn't seem to be possible.

Thanks a lot for any clue about how to achieve this.

Greetings,
Mathias

**Comment by DeShadow** [comment]
@matcho You have two ways.

**1. Set autoincrement offset**
I had problem like you. But I solved it very simply: I set offset to 1e12 (10^12).
That's why my first key is '1000000000000'. I'm sure that I will never have more than 10^12 documents.
And I can simply sort all my documents by key in alphabetical order without problems.

**2. Transactions and separated collection**
The second approach is to have separate collection with mapping `collection -> lastKey`. And you can on every insert in collection use:
```
LET newKey = FIRST(UPDATE @collectionName with { key: OLD.key + 1 } in keys RETURN OLD.key)
INSERT MERGE(@doc, { _key: newKey }) in @@collectionName
```

But to my mind this approach is not elegant and simply like previous one.

**Comment by matcho** [comment]
@DeShadow 

Indeed approach 1 will indeed do the trick.

Theoretically it's not totally satisfying because who knows how many docs there will be one day, but in real life this is a very good solution.

Many thanks

**Comment by DeShadow** [comment]
@matcho I understand that it's not universal. But in real life it's working :) 

Also you can read this article for fun from ArangoDB team :)
https://www.arangodb.com/2017/09/sorting-number-strings-numerically/

**Comment by brunoaduarte** [comment]
> @matcho I understand that it's not universal. But in real life it's working :)
> 
> Also you can read this article for fun from ArangoDB team :) https://www.arangodb.com/2017/09/sorting-number-strings-numerically/

Are there examples on how to implement this method in AQL?

Something like

`RETURN "+ 9998982860" < ", 10004642043"`
