### ISSUE TITLE
Slow query in temporary variable

### ISSUE THREAD

**Issue by isogram** [arangodb/arangodb#3614]
My Environment:
- ArangoDB v3.2.3 CE
- Docker
- Single Server

Hi there, I've some issue with my arangodb query.
There are `products`, `variants`, `offers`, `categoriesVertexCollection` collections here.
- `products` collections has 414,613 doc(s),
- `variants` has 414,984 doc(s)
- `offers` has 414,978 doc(s)
- `categoriesVertexCollection` has 3,360 doc(s) .

CASE : I want to search over temporary variable and got very slow query, why?. Please see the query below.

```
FOR product IN products 
  LET variantsList = (
    LET imgBase = "http://thestatic.url/pk"
    FOR variant IN variants
      LET off = (
        FOR offer IN offers
          FILTER offer.variantId == variant._key
          RETURN {
            id: offer._key,
            vplPrice: offer. vplPrice,
            vplSuggestedPrice: offer.vplSuggestedPrice,
            normalPrice: offer.normalPrice,
            specialPrice: offer.specialPrice,
            specialPriceStartDate: offer.specialPriceStartDate,
            specialPriceEndDate: offer.specialPriceEndDate,
            offerInfo: offer.offerInfo,
            offerStatus: offer.offerStatus
        }
      )
      LET price = (
        LET now = DATE_ISO8601(DATE_NOW())
        FOR o IN off
            LET p = now >= o.specialPriceStartDate && now <= o.specialPriceEndDate ? o.specialPrice : o.normalPrice
            SORT p ASC
            RETURN p
      )
      LET searchName = CONCAT(product.name, " " ,variant.name)
      FILTER variant.productId == product._key
      LET sortingScore = (
        LET mid    = LIKE(searchName, "%gadget hard case 3d%", true) == true ? 1 : 0
        LET after = LIKE(searchName, "%gadget hard case 3d", true) == true ? 2 : 0
        LET before  = LIKE(searchName, "gadget hard case 3d%", true) == true ? 3 : 0
        LET sku = LIKE(variant.skuNo, "gadget hard case 3d", true) == true && variant.skuNo != null ? 4 : 0
        return before + after + mid + sku
      )
      SORT FIRST(sortingScore) DESC, variant._key ASC
      RETURN {
        id: variant._key,
        name: variant.name,
        searchName: searchName,
        skuNo: variant.skuNo,
        status: variant.status,
        images: (for img in TO_ARRAY(variant.images) return {default: img.default, order: img.order, variety: (for varietyImg in img.variety return {type: varietyImg.type, size: varietyImg.size, url: CONCAT(imgBase, SUBSTITUTE(varietyImg.url, imgBase, "") )})}),
        price: FIRST(price) == null ? [] : price
    }
  )

  // THIS FILTER MAKES QUERY SO SLOW. WHY?
  FILTER LIKE(variantsList[*].searchName, '%gadget hard case 3d%', true)

  LIMIT 0, 10 RETURN 
  {
    id: product._key,
    name: product.name,
    model: product.model,
    additionalTitle: product.additionalTitle,
    status: product.status,
    registerNoTypeId: product.registerNoTypeId,
    registerNoTypeName: product.registerNoTypeName,
    exemptionTypeId: product.exemptionTypeId,
    exemptionTypeName: product.exemptionTypeName,
    categoryId: product.categoryId,
    brandId: product.brandId,
    description: product.description,
    inTheBox: product.inTheBox,
    keyFeatures: product.keyFeatures,
    searchTerms: product.searchTerms,
    intendedUse: product.intendedUse,
    targetAudience: product.targetAudience,
    realLength: product.realLength,
    realWidth: product.realWidth,
    realHeight: product.realHeight,
    realWeight: product.realWeight,

    brandOldId: FIRST( FOR brand IN brands FILTER TO_STRING(product.brandId) == brand._key RETURN brand.oldId ), 
    brandName: FIRST( FOR brand IN brands FILTER TO_STRING(product.brandId) == brand._key RETURN brand.name ), 
    categoryOldId: FIRST( FOR cat IN categoriesVertexCollection FILTER TO_STRING(product.categoryId) == cat._key RETURN cat.oldId ), 
    categoryName: FIRST( FOR cat IN categoriesVertexCollection FILTER TO_STRING(product.categoryId) == cat._key RETURN cat.name ),
    categoryStructure: REVERSE( FOR v, e, p IN 0..3 INBOUND CONCAT("categoriesVertexCollection/", product.categoryId) GRAPH "categories" RETURN { id: v._key, oldId: v.oldId, name: v.name, currentLevel: v.currentLevel }),

    variants : variantsList,

    creator: product.creator,
    createdAt: product.createdAt,
    editor: product.editor,
    modifiedAt: product.modifiedAt,
    step: product.step
}
```

Any recommendations for this case? Should I add new attribute for the concatenate string there?

**Comment by jsteemann** [comment]
It looks to me that the relevant parts of the query are the following:
```
FOR product IN products 
  LET variantsList = (
    FOR variant IN variants
      LET off = (
        FOR offer IN offers
          FILTER offer.variantId == variant._key
          RETURN ...
       )
       FILTER variant.productId == product._key
      SORT ...
      RETURN {
        searchName: searchName,
    }
  )

  // THIS FILTER MAKES QUERY SO SLOW. WHY?
  FILTER LIKE(variantsList[*].searchName, '%gadget hard case 3d%', true)
  LIMIT 0, 10
  RETURN ...
```
That means the query will always build up all variants per product, and then look up all offers for all variants. After having build all variants and offers for a product, it will concatenate all search names for the variants and search for "gadget hard case 3d" in them. If any variant contains the search string, the entire variants list will pass. If no variant satisfies the search condition, the variants will be discarded.
The query will do so for all products until 10 matches have been found.

I see a few potential optimizations:
* if the filter on the searchName can be pulled inside the FOR loop that builds up all the variants for a product, then it would only let those variants pass that satisfy the search condition. This would mean a lot less variants would come out of `variantsList` and intermediate results would be much smaller. It would also mean, and that is where it will change the query result, that per product only the matching variants would be returned. This may or may not be ok for the use case. But overall it should mean less processing of temporary results that will be discarded later on.
* regardless of whether the filter can be applied earlier, offers for all variants are always built, regardless of whether the variants are relevant later on. The same is true for images and other calculations. It could save a bit of processing time if offers and images and all other related information could be built only for those variants/products that have passed the search filter condition.
* a big problem of this query is that it will potentially look at all products and all their variants, at least if there are no 10 matches in total. In the worst case that means a scan over 414,613 products, plus additional 414,xxx lookups for the variants plus extra 414,xxx lookups for the offers. If somehow the query could be restricted to a subset of the products (e.g. by searching for a specific product category only) it would benefit a lot, because that could greatly reduce the processing time.

**Comment by dothebart** [comment]
@isogram did @jsteemann answer your question? can we mark this question as solved?

**Comment by isogram** [comment]
sure @dothebart  . i've solved this problem. thank you for the support 👍
