### ISSUE TITLE
Linux colours don't work in the Windows terminal

### ISSUE THREAD

**Issue by ForsakenHarmony** [arangodb/arangodb#3741]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Windows, version: 10

### 
The shell is pretty much unusable, because it's getting spammed with
```
  [0m{[0m[0m [0m
    [1m"_key"[0m : [1m"example8"[0m[0m, [0m
    [1m"_id"[0m : [1m"places/example8"[0m[0m, [0m
    [1m"_rev"[0m : [1m"_V7F2vyG--_"[0m[0m, [0m
    [1m"zipcode"[0m : [1m8[0m
  [0m}[0m[0m, [0m
```

**Comment by sleto-it** [comment]
Hi @ForsakenHarmony,

Thanks for opening this ticket. If you start arangosh with the option `--console.colors=false` things should improve. However, I believe there are still other cases we would like to optimize/fix (e.g. the tutorial)

We will investigate more

Thanks,

**Comment by jsteemann** [comment]
It seems like terminal color support has changed in Windows 10 after it was originally added.
Now one needs to enable a flag explicitly in order to make the Windows command prompt interpret the escape sequences:
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
```cpp
  hStdout = GetStdHandle(STD_OUTPUT_HANDLE);
  GetConsoleMode(hStdout, &handleMode);
  handleMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
  SetConsoleMode(hStdout, handleMode);
```
And we are currently not setting this flag, so color sequences produce garbled output.

**Comment by Simran-B** [comment]
BTW: Windows 10 supports [24-bit colors](https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/) and received an [overhaul of the terminal color palette](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/) (only new installations however). Maybe that flag is required since one of these updates?

We might want to test a PR on both, old and new Windows 10 installations. And as command lines, we could test cmd, cygwin terminal and WSL bash. You can ping me to do that.

**Comment by ForsakenHarmony** [comment]
WSL just doesn't display the colours, but also not the code, shows the password, doesn't display the prompt, but you can input stuff

Cygwin same as above but does display the colours, had problems with it only taking input once before, but doesn't seem to be the case now

**Comment by jsteemann** [comment]
An attempt to fix this issue is made in PR #3753.
However, this PR needs manual testing on Windows still.

**Comment by Simran-B** [comment]
I pushed a small fix and can confirm that the PR fixes the problem on an up-to-date Windows 10.

Without virtual terminal processing:

![image](https://user-images.githubusercontent.com/7819991/33465381-e1896460-d647-11e7-8243-274191c0e500.png)

And enabled:

![image](https://user-images.githubusercontent.com/7819991/33465453-406c4132-d648-11e7-81b6-4054a519d083.png)

Also works in my Cygwin terminal.

@jsteemann Do you want me to test this on something like Windows 7 as well?

**Comment by jsteemann** [comment]
Thanks.
Yes, if you could check Windows 7 as well, it would be great.
I think it is ok if no colors are used on Windows 7 as long as it works on Windows 10. However, in Windows 7 arangosh should not display any escape sequences as it potentially did before.

**Comment by Simran-B** [comment]
No colors, but no garbage either under Windows 7:

![arangosh](https://user-images.githubusercontent.com/7819991/33488186-29d74076-d6b0-11e7-85f4-760ced93fa63.png)

LGTM

**Comment by Simran-B** [comment]
On a different note:

Cmd and Powershell are apparently unable to display Unicode. Should we do something about that?

![image](https://user-images.githubusercontent.com/7819991/33488862-64262b3c-d6b2-11e7-9f8b-cbb21ba5f2de.png)

(Powershell, Cmd, Ubuntu bash when quitting arangosh)

**Comment by sleto-it** [comment]
@Simran-B please open a new ticket for that other problem

We are going to close this one as soon as 3.2.10 is out. I also did some tests with 3.2.10 and it seems all is working fine from color point of view

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this ticket. Version 3.2.10 has been released yesterday

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,
