### ISSUE TITLE
Cluster/Foxx: update service configuration/dependencies not propagated

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#3848]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2
- [x] self-compiled devel branch

Mode:
- [x] Cluster

### Foxx

When updating the configuration or dependencies of a foxx service within a cluster setup, the information is not propagated to all coordinators. This can easily lead to an inconsistent state.

**Comment by pluma** [comment]
A minor correction because the issue sounds scarier than it is: this is a bug in the self-healing logic to recover from a loss of connectivity during the reconfiguration (i.e. changes to config, deps or devmode) of a service in a distributed cluster with multiple coordinators while the service is not running in development mode.

As long as all coordinators can communicate with each other during a reconfiguration, everything behaves normally. Additionally the inconsistent state will be corrected if anything causes a reload of the affected services (e.g. cycling devmode).

**Comment by pluma** [comment]
I'm closing this. Looks like the problem has been solved. The reconfigure triggers a self-heal and the self-heal checks the `_rev`, which should catch all changes to the service definition.
