### ISSUE TITLE
Foxx queues stuck in 'progress' status

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3858]
Running 3.2.7, single-server on Ubuntu 16.04.
May be a regression of #3166.

We've noticed that jobs were stuck in 'progress' status (and so the queues stop processing any new job). Manually deleting those jobs resumed the normal operation of the queues, but they got stuck later again (so it is recurring although hard to reproduce).

This started to happen just after we migrated from 3.2.5 to 3.2.7, so we're pretty confident that this bug got (re?)introduced by either 3.2.6 or 3.2.7.

**Comment by dothebart** [comment]
Hi Thomas, 
you should definitely upgrade to 3.2.8. 
I will tell @mpv1989 to have a look at this again.

**Comment by jsteemann** [comment]
@ThomasWeiss : I guess this is a problem after restarting an arangod instance. After a restart jobs that were in state "progress" (i.e. executing) when the server was shut down, were not properly reset to state "pending". This is especially a problem when these jobs were recurring, because it would mean they would not be restarted after a server restart when the server was shut down while a recurring job was being executed.
Release 3.2.9 has a fix for this.

**Comment by ThomasWeiss** [comment]
@jsteemann Yep I think that's our case, but apparently not only after a restart, also when we update/replace the Foxx service that was consuming the queues.

**Comment by sleto-it** [comment]
Hi, version 3.2.9 has been released. I am closing this issue now. If the problem persists please let us know.

Many thanks,
