### ISSUE TITLE
I can't understand where the problem is, how does ArangoDB run the transaction in the end?

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#3971]
This is My Code.
```
public void testTransaction() {
		ArangoDBUtils dbUtils = new ArangoDBUtils();
		String action = "function(id){ var db = require('@arangodb').db; db.id.save({_key:'key5', 'name':'zhangsan'}); }";
		try {
			TransactionOptions transactionOptions = new TransactionOptions();
			transactionOptions.params("C1");
			transactionOptions.writeCollections("C1");
			dbUtils.transaction(dbName, action, TransactionOptions.class, transactionOptions);
		} catch (ArangoDBException e) {
			e.printStackTrace();
		}
		dbUtils.shutdown();
	}
```
this is utils 
```
	public <T> T transaction(String dbName, String action, Class<T> type, TransactionOptions options) 
        {
		return arangoDB.db(dbName).transaction(action, type, options);
	}
```
error
`Response: 400, Error: 17 - Cannot read property 'save' of undefined`

**Comment by Simran-B** [comment]
Hi @CengSin,

in order to support you, we need a few more details about your environment. What version of ArangoDB are you using, under which operating system, and what is your driver (Java something)?

[According to the docs](https://docs.arangodb.com/3.2/Manual/Transactions/Passing.html), parameters are passed to the JavaScript transaction code as **object**.  In JavaScript, it would be something like:

```js
db._executeTransaction({
  collections: { 
    write: 'C1'
  },
  action: function (params) {
    var db = require('@arangodb').db;
    var doc = { _key: 'key5', name: 'zhangsan' };
    db[params['coll']].save(doc);
  },
  params: { 
    coll: "C1"
  }
});
```

In your code, you seem to be passing a string of the collection name. One possible problem might be, that the `[]` square bracket notation is needed on the db object, and the other could be, that you need to use a parameters object and get the value of the correct attribute. `id` in your action represents all parameters, not only the string `"C1"`.
