### ISSUE TITLE
Unexpected query performance impact

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3984]
Running 3.2.9, single-server on Ubuntu 16.04.

On a database where the `shares` collection (docs) has ~4M docs and the `follows` collection (edges) has ~600k docs, with a hash index on `publications[*].id` in the `shares` collection.

The following query:
```
WITH users 
FOR s IN shares FILTER 'hasPublished/5548899456' IN s.publications[*].id 
LET user = DOCUMENT(users, s.targetKey) 
LET follows = FIRST(FOR f IN follows FILTER f._from == CONCAT('users/', s.targetKey) && f._to == 'users/88764109' RETURN f)
RETURN { share: s, follows: follows, user: user }
```
takes around 5 minutes to complete (consistently), but if we don't aggregate `follows` in the end result like that:
```
WITH users 
FOR s IN shares FILTER 'hasPublished/5548899456' IN s.publications[*].id 
LET user = DOCUMENT(users, s.targetKey) 
LET follows = FIRST(FOR f IN follows FILTER f._from == CONCAT('users/', s.targetKey) && f._to == 'users/88764109' RETURN f)
RETURN { share: s, follows: null, user: user }
```
then the query returns in 160ms.

**Comment by ThomasWeiss** [comment]
Sure, here's the first query:
```
Query string:
 WITH users 
 FOR s IN shares FILTER 'hasPublished/5548899456' IN s.publications[*].id 
 LET user = DOCUMENT(users, s.targetKey) 
 LET follows = FIRST(FOR f IN follows FILTER f._from == CONCAT('users/', s.targetKey) && f._to == 
 'users/88764109' RETURN f)
 RETURN { share: s, follows: follows, user: user }

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 15   IndexNode            4     - FOR s IN shares   /* hash index scan */
  5   CalculationNode      4       - LET user = DOCUMENT(users   /* all collection documents */, s.`targetKey`)   /* simple expression */   /* collections used: s : shares */
 11   SubqueryNode         4       - LET #5 = ...   /* subquery */
  6   SingletonNode        1         * ROOT
 16   IndexNode            4           - FOR f IN follows   /* edge index scan */
 17   CalculationNode      4             - LET #10 = (f.`_from` == CONCAT("users/", s.`targetKey`))   /* simple expression */   /* collections used: f : follows, s : shares */
  9   FilterNode           4             - FILTER #10
 10   ReturnNode           4             - RETURN f
 13   CalculationNode      4       - LET #12 = { "share" : s, "follows" : FIRST(#5), "user" : user }   /* simple expression */   /* collections used: s : shares */
 14   ReturnNode           4       - RETURN #12

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields                     Ranges
 15   hash   shares       false    false        20.75 %   [ `publications[*].id` ]   ("hasPublished/5548899456" in s.`publications`[*].`id`)
 16   edge   follows      false    false        24.52 %   [ `_to` ]                  (f.`_to` == "users/88764109")

Optimization rules applied:
 Id   RuleName
  1   remove-unnecessary-calculations
  2   use-indexes
  3   remove-filter-covered-by-index
  4   remove-unnecessary-calculations-2
```

and here's the second:
```
Query string:
 WITH users 
 FOR s IN shares FILTER 'hasPublished/5548899456' IN s.publications[*].id 
 LET user = DOCUMENT(users, s.targetKey) 
 LET follows = FIRST(FOR f IN follows FILTER f._from == CONCAT('users/', s.targetKey) && f._to == 
 'users/88764109' RETURN f)
 RETURN { share: s, follows: null, user: user }

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 15   IndexNode            4     - FOR s IN shares   /* hash index scan */
  5   CalculationNode      4       - LET user = DOCUMENT(users   /* all collection documents */, s.`targetKey`)   /* simple expression */   /* collections used: s : shares */
 13   CalculationNode      4       - LET #12 = { "share" : s, "follows" : null, "user" : user }   /* simple expression */   /* collections used: s : shares */
 14   ReturnNode           4       - RETURN #12

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields                     Ranges
 15   hash   shares       false    false        20.76 %   [ `publications[*].id` ]   ("hasPublished/5548899456" in s.`publications`[*].`id`)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-unnecessary-calculations
  3   use-indexes
  4   remove-filter-covered-by-index
  5   remove-unnecessary-calculations-2
```

Looks like the optimizer is smart enough to completely remove the fetch from the `follows` collection, so I guess the question becomes, why is this fetch taking so much time?

**Comment by jsteemann** [comment]
Yes, in the first query the optimizer will remove the unreferenced variable `follows`, because that removal should be free of side effects.
Regarding execution times: from the optimizer estimates it looks like the average selectivity for both indexes is around 20 to 25 %. So the outer loop will on average find around 4 to 5 documents in average, and then the subquery will be executed for each of these and find around 4 to 5 documents as well on each invocation. That shouldn't take too long unless the distribution of values in the index is very unbalanced/skewed.

How long does the subquery `LET follows = FIRST(FOR f IN follows FILTER f._from == CONCAT('users/', s.targetKey) && f._to == 'users/88764109' RETURN f)` take in isolation, when using a few of the existing user keys?
```
FOR s IN [{ targetKey: "123456" }, { targetKey: "985843" } ] /* should be some proper user keys here */
  LET follows = FIRST(
    FOR f IN follows 
      FILTER f._from == CONCAT('users/', s.targetKey) && f._to == 'users/88764109' 
      RETURN f
  )
  RETURN follows
```
And does its execution time vary greatly depending on which user keys are fed into it? That would mean some users have many more followers than others.

A few options that may help, but to which extent is currently unclear to me:
* the subquery only needs to return a single edge on each invocation. This is indicated by the usage of `FIRST`. It may help slightly to put in an additional `LIMIT 1` into the subquery (between the subquery's FILTER and RETURN statements). But this should help more when the subquery is invoked a lot of times.
- if the edge is index not that selective, it may help to create an extra index on the `follows` collection on the combination of the `_from` and `_to` attributes. Note that this may also be a unique index if there can only be a single connection between two given users. That additinal index should help to reduce the amount of work needed to be done in the subquery, and should also lead to the subquery's FILTER to be optimized away.

**Comment by ThomasWeiss** [comment]
Hi @jsteemann 

1. I've tested
```
FOR s IN [{ targetKey: "123456" }, { targetKey: "985843" } ] /* should be some proper user keys here */
  LET follows = FIRST(
    FOR f IN follows 
      FILTER f._from == CONCAT('users/', s.targetKey) && f._to == 'users/88764109' 
      RETURN f
  )
  RETURN follows
```
(with real user keys) and it returns in around 60ms. I've tested with many different user keys and got the same results.

2. That said, it is confirmed that some users have way more followers than others (it varies from tens to thousands - user `88764109` as in the query above has 5722 followers).

3. Adding `LIMIT 1` did help as the query mentioned above went from 5 minutes to 90 seconds.

4. I would guess that the selectivity of an edge index is naturally limited, as all the keys start with the same string (the collection name)?

5. So you would suggest to create a hash index on `[_from,_to]`? I thought that's what the edge index was doing already.

**Comment by jsteemann** [comment]
I then guess that the query will be much slower when there are many matches in `shares` and many in `followers` at the same time, at least compared to when there are only a few shares and not many followers.
Adding a LIMIT clause to the subquery will do no harm, and in the best case it can speed up the query, so I recommend adding it. In the future, the query optimizer should do this automatically in simple cases like this, so I will add an internal note for that too.

The index selectivity is not so much affected by a common prefix string (the collection name), but only by the uniqueness of the indexes values. So it all index entries share the same collection name, it won't matter if still all _from values are distinct. The problem here seems to be that for some cases there are many index entries with the same `_from` value (up to a few thousands if I understood correctly). Locating the first index entry for a given `_from` value will be quite quick, but scanning all index entries may take a while for a few thousand. The edge index here will help to locate the first entry, but as there is an additional filter on `_to`, it may well happen that most of the items found are discarded later because of the non-matching `_to` value. This is work that can be avoided.
Creating the additional combined index on `_from` and `_to` will "fix" this, as it will help to directly locate an edge that will be used later. When combined with a "LIMIT 1", the subquery only needs to do a single index lookup per invocation, whereas with an index on either `_from` or `_to` it will need to do an index lookup to find the start of the matches and then scan and filter.
The edge index that is there by default is both on `_from` and `_to`, but each attribute is indexed separately and not in combination. That's why creating the extra index may make sense. 
Creating it as a unique index may also help lookup performance, as it can turn the lookup from a range scan into a point lookup.

**Comment by ThomasWeiss** [comment]
I've created the unique hash index on `[_from,_to]` and it brought the most expensive query (from the slow query history) from ~5600 to ~15 seconds. I leave it to you to decide if you want to close this issue; the problem we had is solved, but you might still be interested in finding out why the request took such a long time initially.

**Comment by dothebart** [comment]
Hi, 
meanwhile ArangoDB 3.7.2 is availabe for download:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
Closing this Issue.
