### ISSUE TITLE
Using the AQL traversal

### ISSUE THREAD

**Issue by feitianstyle** [arangodb/arangodb#4103]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] RedHat .rpm

I want to use AQL to traverse a graph,I start from a vertex, I don't know how many layers of relationships, I want to go through the end,I want this traversal not to be influenced by direction,Is there any way to do it?Thank you for coming to help me.

**Comment by dothebart** [comment]
Hi, 
please have a look at https://docs.arangodb.com/3.2/AQL/Graphs/Traversals.html#working-with-named-graphs

Please note that this is an issue tracker. 
If you read the documentation, and didn't understand something, this is the right place to ask for clarification so the documentation can be improved. 

Else please ask in the community slack.

**Comment by Simran-B** [comment]
Following edges in both, inbound and outbound direction, can be achieved with `ANY`. Unlimited traversal depth is not directly supported, but you can use an arbitrary high number for the maximum depth.

**Comment by feitianstyle** [comment]
Thank you for your answer!@Simran-B

**Comment by maxkernbach** [comment]
Hello,

do you have any further questions or can we close this issue?

**Comment by Himan000** [comment]
Hi @dothebart ,
How do we traveral graph with some inbound while some with outbound? For example, I want to find Kobe Bryant's daughter's grandpa's  height, while the predicate are:
1. Kobe Bryant daughter XXX
2. Joe Bryant granddaughter XXX
3. Joe Bryant height 2.07m
I don't want to use ANY bound because it will collect whole sub-graph to filter what we need.
I found aql's function is limited. And It's not as convenient to traval graph as other language such as GraphQL...Do you have a plan to improve traveral function or import other good graph language?

**Comment by dothebart** [comment]
please don't comment on closed tickets if your topic isn't related.

 Have a look at our training material: 
https://www.arangodb.com/arangodb-training-center/graphs/
to get a headstart on graphs in ArangoDB.
