### ISSUE TITLE
Incorrect fullCount when subquery uses a limit

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#4271]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is HTTP API related issue

```bash
curl -X POST --data-binary @- --dump - http://localhost:8529/_api/cursor <<EOF
{
  "query": "LET data = [{_key: '42', name: 'arangojs'}] LET test = [{name: 'arangojs', value: 123}, {name: 'arangojs', value: 456}] FOR rec IN data LET value = FIRST(FOR t IN test FILTER t.name == rec.name LIMIT 1 RETURN t.value) RETURN {value, name: rec.name}",
  "count": true,
  "options": { "fullCount": true }
}
EOF
```
This will return
```json
{
   "result":[
      {
         "value":123,
         "name":"arangojs"
      }
   ],
   "hasMore":false,
   "count":1,
   "cached":false,
   "extra":{
      "stats":{
         "writesExecuted":0,
         "writesIgnored":0,
         "scannedFull":0,
         "scannedIndex":0,
         "filtered":0,
         "httpRequests":0,
         "fullCount":2,
         "executionTime":3.924369812011719e-4
      },
      "warnings":[

      ]
   },
   "error":false,
   "code":201
}
```

Please notice incorrect value for `fullCount` in the result.

**Comment by Simran-B** [comment]
From the [docs](https://docs.arangodb.com/3.3/HTTP/AqlQueryCursor/AccessingCursors.html):

> The _fullCount_ attribute will contain the number of documents in the result **before the last LIMIT in the query was applied**.
> [...]
> Note that the _fullCount_ attribute will only be present in the result if the query has a LIMIT clause and the LIMIT clause is actually used in the query.

The last, or rather only limit in the query, is in the subquery:

    FOR t IN test ... LIMIT 1 RETURN ...

Thus, "before the last limit" is whatever the FOR loop iterates over, which is the `test` variable. It has two elements. The FILTER condition does not reduce the amount.

The documentation does not mention subqueries, so I'm not 100% sure that *any* LIMIT may be considered as last LIMIT as long as it is actually used and not optimized away. But following the current definition in the docs, `fullCount` seems correct.

**Comment by gurisko** [comment]
I can see that it complies with the documentation now.

However the next question arises - what would normally be expected from feature such as `fullCount`? Wasn't the intention to help for example with pagination over the data?

**Comment by Simran-B** [comment]
What you are interested in seems to be this:

> - **count**: indicates whether the number of documents in the result set should be returned in the "count" attribute of the result. Calculating the "count" attribute might have a performance impact for some queries in the future so this option is turned off by default, and "count" is only returned when requested.

**fullCount** is defined differently:

> It can be used to count the number of documents that match certain filter criteria, but only return a subset of them, in one go. It is thus similar to MySQL's SQL_CALC_FOUND_ROWS hint.

From the [MySQL docs]():

> A SELECT statement may include a LIMIT clause to restrict the number of rows the server returns to the client. In some cases, it is desirable to know how many rows the statement would have returned without the LIMIT, but without running the statement again.
> [...]
> SQL_CALC_FOUND_ROWS and FOUND_ROWS() can be useful in situations when you want to restrict the number of rows that a query returns, but also determine the number of rows in the full result set without running the query again.

I think **fullCount** equals *SQL_CALC_FOUND_ROWS* and **count** roughly corresponds to *FOUND_ROWS()*:

> An example is a Web script that presents a paged display containing links to the pages that show other sections of a search result. Using FOUND_ROWS() enables you to determine how many other pages are needed for the rest of the result.

**Comment by gurisko** [comment]
I am fully aware of differences in between `count` and `fullCount`. I have a query that normally returns `m` results. I want to know only first `n` results (`n < m`) while I need to find out what is `m`. So I use `LIMIT n` and I set `fullCount` to `true`.

Despite `fullCount` being implemented as described in the documentation I would still argue that it returns unexpected results for every-day programmers when used with subqueries.

**Comment by Simran-B** [comment]
Is the `LIMIT n` in the global scope? In that case, fullCount should return the expected result.

If the LIMIT is applied in some subquery, and there is no LIMIT in the global scope, then fullCount can be unexpected indeed. If you add a LIMIT with an arbitrary high count so that it doesn't actually cap the result set, but is present as node in the execution plan, then fullCount is returned as 1:

```js
LET data = [{_key: '42', name: 'arangojs'}]
LET test = [{name: 'arangojs', value: 123}, {name: 'arangojs', value: 456}]
FOR rec IN data
  LET value = FIRST(FOR t IN test FILTER t.name == rec.name LIMIT 1 RETURN t.value)
  LIMIT 9999999999
  RETURN {value, name: rec.name}
```

@jsteemann If we were to restrict fullCount to the top scope, would that break it for other queries?

**Comment by jsteemann** [comment]
@gurisko: Just saw this issue...
`fullCount` was originally implemented to return the count value of the LIMIT clause used last in the query. It did not make any difference if that limit was used in a subquery or not. 
In the original query posted in this issue, there is just one LIMIT in the subquery, so the `fullCount` result will refer to the number of documents returned by that subquery if it were executed without the LIMIT.
It will not refer to the number of documents returned by anything else, because there isn't even another LIMIT present in the query.

That may or may not be intuitive (likely depends on the point of view).

Below is a patch (for 3.2) that would change the current behavior so that `fullCount` would have no effect in subqueries. With this patch it would only be used for the last LIMIT on outer, non-subquery level. All that would be missing then is to make `fullCount` return the value of `count` in case `fullCount` is requested but there is not even a LIMIT present on the outer, non-subquery level as in your original query.
Then `fullCount` would be equal to `count` for queries that do not have a LIMIT on the outer, non-subquery level. And for queries that do have a LIMIT on the outer, non-subquery level `fullCount` would contain the number of documents returned if there would be no LIMIT clause.

```
diff --git a/arangod/Aql/ExecutionPlan.cpp b/arangod/Aql/ExecutionPlan.cpp
index 9da910695f..b7282c8614 100644
--- a/arangod/Aql/ExecutionPlan.cpp
+++ b/arangod/Aql/ExecutionPlan.cpp
@@ -185,6 +185,7 @@ ExecutionPlan::ExecutionPlan(Ast* ast)
       _root(nullptr),
       _varUsageComputed(false),
       _isResponsibleForInitialize(true),
+      _nestingLevel(0),
       _nextId(0),
       _ast(ast),
       _lastLimitNode(nullptr),
@@ -885,7 +886,9 @@ ExecutionNode* ExecutionPlan::fromNodeLet(ExecutionNode* previous,
 
   if (expression->type == NODE_TYPE_SUBQUERY) {
     // operand is a subquery...
+    ++_nestingLevel;
     auto subquery = fromNode(expression);
+    --_nestingLevel;
 
     if (subquery == nullptr) {
       THROW_ARANGO_EXCEPTION(TRI_ERROR_OUT_OF_MEMORY);
@@ -1267,7 +1270,11 @@ ExecutionNode* ExecutionPlan::fromNodeLimit(ExecutionNode* previous,
                                        static_cast<size_t>(offsetValue),
                                        static_cast<size_t>(countValue)));
 
-  _lastLimitNode = en;
+  if (_nestingLevel == 0) {
+    // a LIMIT node will only be used to determine the fullCount value
+    // if the LIMIT node is not inside a subquery
+    _lastLimitNode = en;
+  }
 
   return addDependency(previous, en);
 }
diff --git a/arangod/Aql/ExecutionPlan.h b/arangod/Aql/ExecutionPlan.h
index 8bde3c5d21..b52ab94007 100644
--- a/arangod/Aql/ExecutionPlan.h
+++ b/arangod/Aql/ExecutionPlan.h
@@ -314,6 +314,9 @@ class ExecutionPlan {
 
   bool _isResponsibleForInitialize;
 
+  /// @brief current nesting level while building the plan
+  int _nestingLevel;
+
   /// @brief auto-increment sequence for node ids
   size_t _nextId;
 
diff --git a/js/common/modules/@arangodb/aql/explainer.js b/js/common/modules/@arangodb/aql/explainer.js
index 131c119169..6c63ec5688 100644
--- a/js/common/modules/@arangodb/aql/explainer.js
+++ b/js/common/modules/@arangodb/aql/explainer.js
@@ -1100,7 +1100,7 @@ function processQuery (query, explain) {
             return variableName(node.inVariable) + ' ' + keyword(node.ascending ? 'ASC' : 'DESC');
           }).join(', ');
       case 'LimitNode':
-        return keyword('LIMIT') + ' ' + value(JSON.stringify(node.offset)) + ', ' + value(JSON.stringify(node.limit));
+        return keyword('LIMIT') + ' ' + value(JSON.stringify(node.offset)) + ', ' + value(JSON.stringify(node.limit)) + (node.fullCount ? '  ' + annotation('/* fullCount */') : '');
       case 'ReturnNode':
         return keyword('RETURN') + ' ' + variableName(node.inVariable);
       case 'SubqueryNode':
```
This would change the behavior of `fullCount` quite a bit, so I am a bit reluctant to do this in the middle of a stable release. I really wouldn't want to roll out such changes with a bugfix release, because users may need to take preparations and adjust queries/client code beforehand.

@gurisko @Simran-B : what about introducing such change in the next branch, i.e. 3.4, and documenting it properly, so everyone can check before upgrading from 3.3 to 3.4 (which requires manual intervention anyway)?

**Comment by gurisko** [comment]
@jsteemann I like the idea to change the behavior for release 3.4. Until then we will use a workaround

**Comment by Simran-B** [comment]
@jsteemann 3.4 sounds good. Still wondering though, if there are reasonable use cases which require the old behavior.

**Comment by gurisko** [comment]
I just tested 3.4.technical preview and I noticed that this hasn't been addressed there yet. Are you still considering to add this into 3.4? Thanks!

**Comment by jsteemann** [comment]
@gurisko : yes, it is still on my list for 3.4. But you are right, it is not yet included there.
I can update this issue when it has landed.

**Comment by jsteemann** [comment]
There is now a PR for 3.4 with the changes:
https://github.com/arangodb/arangodb/pull/5285

**Comment by jsteemann** [comment]
The PR has been merged into devel.

**Comment by gurisko** [comment]
@jsteemann Thank you!

**Comment by vinaypyati** [comment]
Hi @gurisko,

version 3.4.0-RC1 has been released, which contains the fix for this issue.
I will be closing this issue for now. Please comment, if needed, and we will reopen it.

Thanks again for reporting this issue.

Best,
