### ISSUE TITLE
DC2DC on the issue:Can solve the problem of fragmentation?

### ISSUE THREAD

**Issue by Mokwing** [arangodb/arangodb#4292]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [✔ ] 3.3

Mode:
- [✔ ] Cluster

Storage-Engine:
- [✔ ] rocksdb

On this operating system:
- [✔ ] Linux 
  - [✔ ] RedHat .rpm

hi,
    Today, I started the cluster encountered a shard error, start the log display   👇:
![image](https://user-images.githubusercontent.com/34149942/34870665-c4c1ad70-f7c5-11e7-8f93-30535f11b1be.png)
   
   I saw the document DC2DC, would like to ask if this can solve the problem of segmentation error?

**Comment by dothebart** [comment]
Hi, 
it seems you've got collection names by number in your agency, which they shouldn't be. 
DC2DC means having two disjunct datacenters, so you can fail over to the second datacenter if the first datacenter drops into a sinkhole or burns.

**Comment by moxiaoyu100** [comment]
hi,
Thank you for your reply. That question now, how do I solve the problem of shards?

**Comment by sleto-it** [comment]
Hi @Mokwing,

Thanks for opening this ticket and sorry for late reply.  One question: how did you create those collections 10118, 10122, etc?

Arangosh typically throws an error if the collection name does not start with a letter, and the ArangoDB Web UI also does not allow you to create them because a field validation is done at UI level

Have you used a specific driver? Was this server upgraded from an older version (just wondering)?

I am trying to reproduce your issue

FYI, naming conventions for collections are documented in the following page:
https://docs.arangodb.com/3.3/Manual/DataModeling/NamingConventions/CollectionNames.html

Thanks!

**Comment by dothebart** [comment]
Please use ArangoDB via the Kubernetes Operator for DC/OS. 
ArangoDB 3.7 is available for download:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
