### ISSUE TITLE
Bad index selection for AQL queries (and false selectivity?) on rocksdb

### ISSUE THREAD

**Issue by lewisdiamond** [arangodb/arangodb#4331]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] docker - official docker library
  - [ ] other:

I'm issuing AQL via:
- [x] web interface with this browser: chromium   running on this OS: linux

When filtering over multiple indices, arangodb uses only one of them.
```
Query string:
 for o in observations
     filter o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000 and o.seenEpoch < 
 DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000 and o.apMac == 'xx:xx:xx:xx:xx:xx'
     sort o.clientMac, o.seenTime desc
     return o

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  9   IndexNode         1436062     - FOR o IN observations   /* hash index scan */
 10   CalculationNode   1436062       - LET #1 = ((o.`seenEpoch` > 1514178000) && (o.`seenEpoch` < 1514264400))   /* simple expression */   /* collections used: o : observations */
  4   FilterNode        1436062       - FILTER #1
  5   CalculationNode   1436062       - LET #3 = o.`clientMac`   /* attribute expression */   /* collections used: o : observations */
  6   CalculationNode   1436062       - LET #5 = o.`seenTime`   /* attribute expression */   /* collections used: o : observations */
  7   SortNode          1436062       - SORT #3 ASC, #5 DESC
  8   ReturnNode        1436062       - RETURN o

Indexes used:
 By   Type   Collection     Unique   Sparse   Selectivity   Fields        Ranges
  9   hash   observations   false    false         0.00 %   [ `apMac` ]   (o.`apMac` == "xx:xx:xx:xx:xx:xx")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
```

```
Query string:
 for o in observations
     filter o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000 and o.seenEpoch < 
 DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000
     sort o.clientMac, o.seenEpoch desc
     return o

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  9   IndexNode         4978351     - FOR o IN observations   /* skiplist index scan */
  5   CalculationNode   4978351       - LET #3 = o.`clientMac`   /* attribute expression */   /* collections used: o : observations */
  6   CalculationNode   4978351       - LET #5 = o.`seenEpoch`   /* attribute expression */   /* collections used: o : observations */
  7   SortNode          4978351       - SORT #3 ASC, #5 DESC
  8   ReturnNode        4978351       - RETURN o

Indexes used:
 By   Type       Collection     Unique   Sparse   Selectivity   Fields            Ranges
  9   skiplist   observations   false    false        97.33 %   [ `seenEpoch` ]   ((o.`seenEpoch` > 1514178000) && (o.`seenEpoch` < 1514264400))

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
```

Also why does apMac index have 0% selectivity?

**Comment by dothebart** [comment]
Can you try to move the calculation of the timestamps outside of the loop? 
as the explain suggests, the calculation nodes are invoked on each iteration, thus probably no indices can be used...

**Comment by lewisdiamond** [comment]
@dothebart I tried removing it completely but it doesn't change anything. See the 2nd `explain`, the calculation is there and it still properly uses the index.

**Comment by dothebart** [comment]
I meant moving them out, assigning them to a variable, so the optimizer can work more freely inside the loops.

**Comment by lewisdiamond** [comment]
@dothebart 
What I mean is I removed any logic. I precomputed the datestamp and did something like 
```
for x in y
   filter x.seenEpoch < 1516285706
   ...
```
And it doesn't change anything.

**Comment by sdrsdr** [comment]
What I see strange is once you got `  9   hash   observations   false    false  `  and then `9   skiplist   observations   false    false`

**Comment by sdrsdr** [comment]
I'm new to arango but can you try to add two filter lines and post the result?

**Comment by lewisdiamond** [comment]
```
Query string:
 for o in observations
     filter o.seenEpoch > 1514264400
     return o

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  6   IndexNode       18668818     - FOR o IN observations   /* skiplist index scan */
  5   ReturnNode      18668818       - RETURN o

Indexes used:
 By   Type       Collection     Unique   Sparse   Selectivity   Fields            Ranges
  6   skiplist   observations   false    false        97.33 %   [ `seenEpoch` ]   (o.`seenEpoch` > 1514264400)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```
```
Query string:
 for o in observations
     filter o.seenEpoch > 1514264400 and o.apMac == 'e0:55:3d:f3:b6:76'
     return o

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  6   IndexNode         1436062     - FOR o IN observations   /* hash index scan */
  7   CalculationNode   1436062       - LET #1 = (o.`seenEpoch` > 1514264400)   /* simple expression */   /* collections used: o : observations */
  4   FilterNode        1436062       - FILTER #1
  5   ReturnNode        1436062       - RETURN o

Indexes used:
 By   Type   Collection     Unique   Sparse   Selectivity   Fields        Ranges
  6   hash   observations   false    false         0.00 %   [ `apMac` ]   (o.`apMac` == "e0:55:3d:f3:b6:76")

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
```
```
Query string:
 for o in observations
     filter o.seenEpoch > 1514264400 
     filter o.apMac == 'e0:55:3d:f3:b6:76'
     return o

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  8   IndexNode         1436062     - FOR o IN observations   /* hash index scan */
  3   CalculationNode   1436062       - LET #1 = (o.`seenEpoch` > 1514264400)   /* simple expression */   /* collections used: o : observations */
  4   FilterNode        1436062       - FILTER #1
  7   ReturnNode        1436062       - RETURN o

Indexes used:
 By   Type   Collection     Unique   Sparse   Selectivity   Fields        Ranges
  8   hash   observations   false    false         0.00 %   [ `apMac` ]   (o.`apMac` == "e0:55:3d:f3:b6:76")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
```

**Comment by sdrsdr** [comment]
sounds reasonable to me .. the hash index should have the best performance of all. You can create index with the two fields apMac  and seenEpoch  in it if you want your query to be maximum efficient but lose some speed when adding data, or you could diverse your data more and use graph traversal so you can use multiple indexes at each step of the traversal ... just my 2c

**Comment by lewisdiamond** [comment]
Do you mean that only 1 index can be used for a query?
`Indexes used` -> `Index used`?

**Comment by sdrsdr** [comment]
I'm not really sure. But multiple index usage is quite sub optimal. Create multifield index and test how this impact your 'insert' and 'for' speeds

**Comment by lewisdiamond** [comment]
But you can't do a multifield index for skip-list + hash.

**Comment by sdrsdr** [comment]
I'm not sure hash is best solution for your case in the first place. You have too many documents with the same hash. If it were just few documents per mac then hash shines. When there  are hash collisions the hash index can resolve to list this is ok for few records but after that it's bad database design :-(

**Comment by jsteemann** [comment]
Sorry, I am a bit late to the game, but I think I can shed some light on this.

@dothebart @lewisdiamon: first of all, moving the filter conditions `o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000` and `o.seenEpoch < 
 DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000` into separate variables is not necessary. The optimizer will simply calculate the timestamp value once at the start of the query and insert the computed values. That also means precomputing the timestamps in this case is not necessary.
Example:
```
Query string:
 for o IN observations FILTER o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000 and 
 o.seenEpoch <  DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000 RETURN o

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      0     - FOR o IN observations   /* full collection scan */
  3   CalculationNode              0       - LET #1 = ((o.`seenEpoch` > 1514178000) && (o.`seenEpoch` < 1514264400))   /* simple expression */   /* collections used: o : observations */
  4   FilterNode                   0       - FILTER #1
  5   ReturnNode                   0       - RETURN o
```
However, keep in mind that ArangoDB does not support indexed on function values. For example, no index would be used for a condition such as `DATE_TIMESTAMP(o.seenEpoch) > ....`. But in the original query there is no function called on the indexed values, but the indexed values are compared to some value that is calculated by a function. This is supported. Apart from that the optimizer will only  call that function once and use function result because the funciton is marked as deterministic and the function input parameters are constants.

Now coming back to the actual questions regarding indexes:
There are a few things to consider for this query. The filter conditions are:
- `o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000`
- `o.seenEpoch < DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000`
- `o.apMac == 'xx:xx:xx:xx:xx:xx'`
And there is a sort condition later:
- `sort o.clientMac, o.seenTime desc`

The query optimizer is cost-based, meaning it will make try to come up with the query execution plan that has the least estimated cost. The costs here will be more or less determined by how many documents to scan, and by how many documents to sort.
The ideal solution would be to use an index that supports both the filter conditions and the sort criteria, but that is not possible, as the filter conditions and the sort use different attributes. Apart from that, the optimizer will not use any index for sorting here, because the sort orders are `ASC` and `DESC`, but indexes in ArangoDB are either sorted ascending or descending, but not mixed.

About which index to use for filtering, the optimizer could pick a sorted index on `seenEpoch`, or an index on `apMac` or a combined (sorted) index on `apMac` and `seenEpoch`.
The optimizer will use an index (hash or skiplist) on just `apMac` in case no other suitable index is found.
Such index can be created by `db.observations.ensureIndex({ type: "hash", fields: ["apMac"] });` for example:
```
Query string:
 for o IN observations FILTER o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000 and 
 o.seenEpoch <  DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000 and o.apMac == 'xx:xx:xx:xx:xx:xx' RETURN o

Execution plan:
 Id   NodeType           Est.   Comment
  1   SingletonNode         1   * ROOT
  6   IndexNode         99999     - FOR o IN observations   /* hash index scan */
  7   CalculationNode   99999       - LET #1 = ((o.`seenEpoch` > 1514178000) && (o.`seenEpoch` < 1514264400))   /* simple expression */   /* collections used: o : observations */
  4   FilterNode        99999       - FILTER #1
  5   ReturnNode        99999       - RETURN o

Indexes used:
 By   Type   Collection     Unique   Sparse   Selectivity   Fields        Ranges
  6   hash   observations   false    false         0.00 %   [ `apMac` ]   (o.`apMac` == "xx:xx:xx:xx:xx:xx")
```

Now, let's add an index on `seenEpoch` as well: `db.observations.ensureIndex({ type: "skiplist", fields: ["seenEpoch"] });`. The optimizer should now prefer this index over the other:
```
Query string:
 for o IN observations FILTER o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000 and 
 o.seenEpoch <  DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000 and o.apMac == 'xx:xx:xx:xx:xx:xx' RETURN o

Execution plan:
 Id   NodeType           Est.   Comment
  1   SingletonNode         1   * ROOT
  6   IndexNode         13333     - FOR o IN observations   /* skiplist index scan */
  7   CalculationNode   13333       - LET #1 = (o.`apMac` == "xx:xx:xx:xx:xx:xx")   /* simple expression */   /* collections used: o : observations */
  4   FilterNode        13333       - FILTER #1
  5   ReturnNode        13333       - RETURN o

Indexes used:
 By   Type       Collection     Unique   Sparse   Selectivity   Fields            Ranges
  6   skiplist   observations   false    false        99.99 %   [ `seenEpoch` ]   ((o.`seenEpoch` > 1514178000) && (o.`seenEpoch` < 1514264400))
```
In reality it will also depend on the index selectivity and on how many documents there are in the collection. The optimizer will either pick the index `apMac` or `seenEpoch`, depending on which index it thinks will return less documents for the corresponding filter condition(s) supported by the index.

The best index here however is not an index on just `apMac` or just `seenEpoch`, but a combined index on both. This should be a sorted index, because we want to support the range scan on `seenEpoch`. And the `apMac` attribute must be the first attribute in the index: `db.observations.ensureIndex({ type: "skiplist", fields: ["apMac", "seenEpoch"] });`

With that index, the execution plan reduces to just an index scan, and all post-filtering becomes unnecessary:
```
Query string:
 for o IN observations FILTER o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000 and 
 o.seenEpoch <  DATE_TIMESTAMP('2017-12-26T05:00:00Z')/1000 and o.apMac == 'xx:xx:xx:xx:xx:xx' RETURN o

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode        666     - FOR o IN observations   /* skiplist index scan */
  5   ReturnNode       666       - RETURN o

Indexes used:
 By   Type       Collection     Unique   Sparse   Selectivity   Fields                     Ranges
  6   skiplist   observations   false    false       100.00 %   [ `apMac`, `seenEpoch` ]   ((o.`apMac` == "xx:xx:xx:xx:xx:xx") && (o.`seenEpoch` > 1514178000) && (o.`seenEpoch` < 1514264400))
```
In the original query there was also a SORT clause. This will remain there (I didn't use it here for brevity) because the sorting was requested for different attributes than in the filter condition, and because the sorting uses a mix of ascending and descending orders, which is unsupported by indexes in ArangoDB.
So the goal here is to use the index to do all the filtering, and have it reduce the number of documents to sort later on as much as possible. Sorting a few documents will not be expensive, but sorting many will be. The post-sorting here could be avoided if the sort would be on the attributes used for the index that was used for filtering, i.e. `apMac` (can also be omitted in the sort because it is compared to a constant value) and `seenEpoch`. Using any other sort criteria will require a post-index-sort to be used by the optimizer.

Now finally answering the question on how many indexes are used:
A query can use more than one index, but for each `FOR` loop in an AQL query the optimizer will use at most one index if the filter conditions are combined with logical `and`. The optimizer will try to pick the index that promises to reduce work (filtering, sorting) by the greatest amount. If there are multiple candidate indexes, they will all be looked at, but the one with the least expected cost will be chosen. Therefore it often makes sense to use combined indexes. In my examples above I created 3 indexes, but in the end I will only need the one I created last for this query. The other ones will not be used for the query in question (but of course they may be used for other queries).

Why does ArangoDB not use multiple indexes on different attributes for this query?
The main reason is because it is not clear if that would be better in all cases.
Let's assume there is one index on just `seenEpoch`, and one index on just `apMac`. But the query filters on both attributes. So with two indexes, the query processor would need to query results from both indexes and merge them. It must only return documents that are present in both indexes (because of logical `and` used in this query). But the two indexes do return documents in different orders: the one index is sorted by `seenEpoch` values, and the other is sorted by `apMac` values. To check that a document is present in both indexes, the query processor would need to keep all these results in memory for the intersection, or at least it would need to keep the smaller index query result in memory and then iterate over the other index query result to check if each document is contained in both indexes. This is not necessarily faster than using a combined index, and it will have extra space requirements for at least one temporary index result to keep somewhere.

In case there filter conditions combined with logical `or`, the optimizer may pick more than one index even for the same `FOR` loop. For example, the following query could use two different indexes:
```
 for o IN observations FILTER o.seenEpoch > DATE_TIMESTAMP('2017-12-25T05:00:00Z')/1000 or o.apMac == "xx:xx:xx:xx:xx:xx" return o
```

Then there was a question on the index selectivity for the index on `apMac`. That question I cannot answer without any further info on what data is contained in that attribute. An index selectivity of 0.0% may for example occur for indexes that are created on attributes that are not present in any of the documents, or for which all documents have the same index attribute value, or for which there are very few distinct values in the index. I have no clue about the data distribution of the `apMac` attribute in your dataset, so I can just give these general pointers.

**Comment by sdrsdr** [comment]
epic answer! should be put in the official documentation somehow :-)

**Comment by lewisdiamond** [comment]
@jsteemann Idk if I ran into a bug, but I had a skiplist defined with `seenEpoch,apMac`, which wasn't being used. I removed it and recreated it with `apMac,seenEpoch` and now it's being used. Does the order matter?

**Comment by jsteemann** [comment]
Yes, the order does matter.
For example, if the attributes order in the index is `seenEpoch`, `apMac`, then the index cannot be used for range querying on `seenEpoch` **and** an equality lookup on `apMac` at the same time. It can then only be used for range queries on `seenEpoch`, or for equality lookups on `seenEpoch` and `apMac`, or on equality lookups on `seenEpoch` and range queries on `apMac`.
The query above requires the index to be present on attributs `apMac` and `seenEpoch` in this order, because then it will support equality lookups on `apMac` **and** range queries on `seenEpoch`.

**Comment by lewisdiamond** [comment]
Thanks
