### ISSUE TITLE
Error: Signature verification failed! should return 403 instead of 500

### ISSUE THREAD

**Issue by solisoft** [arangodb/arangodb#4494]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [X] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### Foxx

When loading a Foxx service with wrong JWT token, it raise a 500 error instead of a 403
By example : 
`Service "/auth" encountered error 500 while handling GET http://localhost:8529/_db/cms_bw/auth/whoami via Error: Signature verification failed!`

**Comment by jsteemann** [comment]
I think it should rather be HTTP 403 (Forbidden).

**Comment by solisoft** [comment]
Oh yes you are right ! 403 will be more helpful  indeed !

**Comment by pluma** [comment]
Status 500 generally indicates an uncaught exception. As I understand this issue is about using `crypto.decodeJwt` in your own Foxx service to handle application level client authentication. In this case you should handle the exception and react accordingly (e.g. by sending your own 403 response).

The API in question doesn't know anything about Foxx or responses and requests. We could use an `ArangoError` here but we don't for any of the related APIs and even so it wouldn't be clear this should use a 403 HTTP code given there's no way to tell how the API was used or for what purpose.
