### ISSUE TITLE
authentication of APIs of dbserver and agency is failed

### ISSUE THREAD

**Issue by 3rduncle** [arangodb/arangodb#4552]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: centos
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an API auth issue:
my arangodb started with  ```authentication = true```. 
some APIs on coordinator such like ```/_api/document/{document-handle}``` are authenticated successfully.
another APIs on agengcy/dbaserver(404 on coordinator) such like ```/_api/agency/config```|```/_api/replication/logger-follow``` are always return 401(unauthorized).
Is this a bug?

**Comment by maxkernbach** [comment]
Hi @3rduncle,

sorry for the late reply. You mentioned using `authentication = true`. Did you use the the `ArangoDB starter` or another procedure to start the cluster? What is your current version (3.2.x)?

`curl http://$SERVER:$PORT/_api/agency/config` can only be executed using `$SERVER:$PORT` of your agency. Using `$SERVER:$PORT` of a dbserver or coordinator will result in `{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/_api/agency/config'"}`.

`/_api/replication/logger-follow` is not supported on a coordinator in a cluster, which is mentioned in the [documentation](https://docs.arangodb.com/3.2/HTTP/Replications/ReplicationLogger.html#return-replication-logger-state). It is used for a master/slave replication.

> Note: this method is not supported on a coordinator in a cluster.

**Comment by dothebart** [comment]
**NOTE** this is one of the `don't try this at home` parts and not officially supported. End users should talk to ArangoDB via the Coordinator. 

In order to talk to the backend components you need to work with JW-Tokens. Auth basic is not supported.
You can use [`jwtgen`](https://www.npmjs.com/package/jwtgen) to generate the proper token, or [use the openssl commandline tool](https://gist.github.com/cheapRoc/5cbe11e9a8831c9e73f55121d4eddacf):

    jwtgen -a HS256 -s openSesame -c server_id=hans -c iss=arangodb

The [startLocalCluster.sh](https://github.com/arangodb/arangodb/blob/devel/scripts/startLocalCluster.sh) which we use for internal development also demonstartes this. 

at least in current devel arangosh learned to talk to the backend components.

**Comment by OmarAyo** [comment]
Hi @3rduncle,

Just sending a quick follow-up, were the previous messages useful for you?

Best,

**Comment by maxkernbach** [comment]
Hi @3rduncle, 

i am closing this issue as solved for now since we have not received any feedback for a few months.
Please feel free to comment and reopen in case you have further questions.
