### ISSUE TITLE
_api/replication/logger-follow always returns 204 no content

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#4692]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
  - [x] Debian .deb

### issue description

Hi. All apologies in advance if this is a beginner mistake…
I noticed the issue trying to use **arangochair**, at first.

No matter what I do, I always get `204 no content` when calling
 * `_api/replication/logger-follow`
 * `_db/mydatabase/_api/replication/logger-follow`

Example response headers (using cURL) :
```
< HTTP/1.1 204 No Content
< X-Content-Type-Options: nosniff
< X-Arango-Replication-Frompresent: false
< X-Arango-Replication-Checkmore: false
< X-Arango-Replication-Lastincluded: 0
< X-Arango-Replication-Active: true
< X-Arango-Replication-Lasttick: 6256271647
< Server: ArangoDB
< Connection: Keep-Alive
< Content-Type: application/x-arango-dump; charset=utf-8
< Content-Length: 0
```

But, `_api/replication/logger-state` returns valid content and says that the replication log is active.
```
{
  "state":
  {
    "running": true,
    "lastLogTick": "6256267278",
    "lastUncommittedLogTick": "6256267278",
    "totalEvents":6256267278,
    "time": "2018-02-27T16:04:00Z"
  },
  "server":
  {
    "version": "3.3.3",
    "serverId": "221779840837043"
  },
  "clients": []
}
```
When looking at files under `/var/lib/arangodb3/engine-rocksdb/journals`, one can see their size and last access date change, as expected.
Also, `lastLogTick` returned grows regularly, as expected.

Authentication is good since I get a 401 response if login/password do not match.

Any idea what I did wrong ?

Many thanks,
Mathias

**Comment by jsteemann** [comment]
The logger state is global meaning that it will show all operations which happen(ed) in all databases altogether.
However, the logger-follow API is database-specific, so it may not show activity in a specific database even though in other databases there may be ongoing activity.
Are you sure that the `logger-follow` request is issued for a database in which there is definitely ongoing activity? Additionally, `logger-follow` has a `from` URL parameter which can be passed to restrict the tailing to some specific period (it's the lower bound of the range). Can you append a `logger-follow` parameter with a value of `1` to the URL to see if that returns something? It maybe expects some value.

**Comment by matcho** [comment]
Thanks for your quick answer.

Indeed, adding `?from=1` to `logger-follow` does the trick (note: `?from=0` does not) and I get some content. But very little content (see below).

At first I called `/_db/mydb/_api/replication/logger-follow?from=1` and got a `204: no content` response. Then I added a new document in a collection in this database, called the same URL again and got a `200` response with the expected content.

Great. But this database has been existing from a long time (months) and I only get the changes of the… day ? Last hours ? I read somewhere that the replication log is somehow garbage-collected; is there a way to make it a little more persistent, at least a week or a month ? Maybe I misconfigured something unwantedly ?

By the way [here might not be the place to discuss this but] the current version of **arangochair** on GitHub does not work anymore; authentication is not supported (although it is in some forks) and receiving an event leads to errors. Is there any plan to go on developing this software ? IMHO it adds a great value to ArangoDB.

Thanks

**Comment by jsteemann** [comment]
The logger-follow API will only return the latest changes which are still contained in the write-ahead logs (WAL files). If an operation is moved from the WAL to some other place (MMFiles datafiles or RocksDB sst files), then it will not be returned by the `logger-follow` API anymore. This is meant to be used for WAL tailing only.
It is actually not that easy to get all changes in order from a specific point in time for arbitrary ranges, because everything the operations that are stored outside of the WAL are ordered by collection id and key value, and also existing values may be updated in-place eventually by compaction (to reduce space requirements for persistent storage).

**Comment by matcho** [comment]
OK got it, thank you.

**Comment by AntoineAA** [comment]
Hi,
Is that mean a pending replication can not be restarted few days later ?
Thanks

**Comment by jsteemann** [comment]
Well, `/_api/replication/logger-follow` tails the WAL. The WAL will not be kept around forever. It will only contain the latest changes, but the changes will eventually be merged into the main data storage.

In order to restart the replication a few days after it was turned off, the WAL alone will not be sufficient.
In this case, the ArangoDB replication has some mode to do an incremental resynchronization, that will sync the differences between master and slave. But that is not the purpose of this specific API endpoint.

**Comment by AntoineAA** [comment]
Ok,
Thank you!
