### ISSUE TITLE
Client generated _key field very bad insert performance

### ISSUE THREAD

**Issue by ppiccolo** [arangodb/arangodb#4800]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ x] 3.3

Mode:
- [ x] Single-Server

Storage-Engine:
- [ x] rocksdb

On this operating system:
- [ x] Linux 
  - [ x] docker - official docker library

### this is an AQL-related issue:
[ x] I'm using graph features

I'm issuing AQL via:
- [ x ] this Driver: py-arango

The AQL query in question is:

```
FOR item in source_collection
    LIMIT 1000
    INSERT 
    {
        task_id: item.task_id,
        ts_created: item.ts_created,
        ref_id: item.ref_id,
        ts_item: item.ts_item,
        doc_id: item.doc_id,
        with_autogenerated_key: true
        //_key: item.key
    }
    IN dest_collection OPTIONS {ignoreErrors: true}
    REMOVE item._key INTO source_collection
```
**Time:** `200 msec`

```
FOR item in source_collection
    LIMIT 1000
    INSERT 
    {
        task_id: item.task_id,
        ts_created: item.ts_created,
        ref_id: item.ref_id,
        ts_item: item.ts_item,
        doc_id: item.doc_id,
        with_autogenerated_key: false,
        _key: item.key
    }
    IN dest_collection OPTIONS {ignoreErrors: true}
    REMOVE item._key INTO source_collection
```
**Time:** `5000 msec` :(

Any suggestion ?

Thanks in advance.

**Comment by goedderz** [comment]
Hi @ppiccolo,

I tried to reproduce your problem on v3.3.4, but without success: The performance is roughly the same.

Are you using 3.3.4? If not, does the problem persist there? If it persists, can you provide a minimal example with which you are able to reproduce the problem?

Kind regards,

Tobias

**Comment by ppiccolo** [comment]
Hi @goedderz ,

I'm using 3.3.3 and digging a little bit more, the problem appear if the _key is already present in the destination collection, and `OPTIONS {ignoreErrors: true}` take effect.

**Comment by goedderz** [comment]
Hi @ppiccolo,

I tried to reproduce your problem again. However, I cannot see any difference in performance regardless if the `_key`s already exist or not, neither in v3.3.3 nor in v3.3.4.

Can you please

* Test if you get the same difference in performance when executing the query via the webinterface, rather than via pyArango
* If not, please create an issue in https://github.com/tariqdaouda/pyArango/issues instead and cross-link this issue
* Otherwise, please try upgrading to 3.3.4 if possible and check if the problem still persists

Kind regards,

Tobias

**Comment by ppiccolo** [comment]
Thank You for your time the problem seem to be related to a disk IO ... this instance was deployed on server with a SAS 7.200K RAID1 :(
