### ISSUE TITLE
Starting arangosh and giving a wrong password drops to a v8 shell

### ISSUE THREAD

**Issue by aoighost** [arangodb/arangodb#4826]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x ] 3.3

Mode:
- [ x] Single-Server

Storage-Engine:
- [x ] mmfiles

On this operating system:
- [ x] Windows, version: 10

Starting arangosh and giving a wrong password drops to a v8 shell. This could cause security issues. Proper behavior would be to kill the process if n number of wrong password attempts happens.

**Comment by jsteemann** [comment]
@aoighost : can you elaborate why it could cause security issues to have access to a V8 shell that has no access to server-side data?
A v8 shell will allow the user to execute arbitrary JavaScript code, but probably that is not worse than being able to invoke the ArangoShell or invoking any other shell (e.g. bash) commands.
Or am I missing something?

**Comment by dothebart** [comment]
Closing as solved.

**Comment by aoighost** [comment]
Sorry it took a while to respond, I didn't see a notification email.

Arbitrary js is the primary problem here. Just because it's "just another shell" doesn't mean this isn't a problem. JS would allow a user to potentially do other things depending on the situation. Just dropping to another shell could cause issues if for example arango is running on a different set of privileges than the user in question (possible privilege escalation). This alone might not be much of a threat, but chained with other issues can become a big problem,

**Comment by dothebart** [comment]
Hi, 
you probably don't understand the situation properly. 
Arangosh talks to ArangoD via tcp / HTTP(s). If the user isn't able to authenticate to arangod via these calls, he won't be able to invoke  APIs on the database. Your claim is like declaring curl a security risk because of you can send http requests. 

The arangosh runs as the user you're currently logged in as. Unless you stop the user from invoking perl or python (which you probably will find on any *nix system nowadays) arangosh doesn't offer any additional thread to the security.

**Comment by aoighost** [comment]
Alright, I wasn't aware of how arangosh operates on that level. That makes sense then. Regardless, it shouldn't drop to v8 shell on login fail, it should pskill, it's still a bug, just thankfully not a security bug like I first thought it was.

**Comment by dothebart** [comment]
you can still make it establish a connection afterwards. Its intended to be usefull without an active server connection.
