### ISSUE TITLE
Is there a possibility to start ArangoDB Replication Slave in read-only mode ?

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#4864]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ v] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [v ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ v] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [v ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Greetings,

  Is there a possibility to start ArangoDB Replication Slave in read-only mode ?
  I.e. that all users will be able to view-only the contents of Slave replicated DBs, and (possibly) only root user could have read-wrie access at slave.
  Something similar to setting on "read_only" parameter in /etc/my.cnf file of MySQL configuration ?

Best regards and looking forward your assistance,
Avi

**Comment by jsteemann** [comment]
At the moment, there are a few replication modes, and I am not sure to which one you are referring to here:
- the replication that can be turned on for individual databases on a slave server (available since ArangoDB 2.0)
- the replication that can be turned on for a complete slave instance (available since ArangoDB 3.3)
- two servers (leader/follower) with replication in an active failover setup

The latter modes (active failover setup) will automatically reject all writes on followers already, so it is made sure writes are only executed on the leader, and then replicated. This is built-in, and nothing needs to be configured to have it behave like this. Effectively, the followers in this setup will also reject reads. We have some plans (however without any ETA) to optionally allow reads from the followers, so that the followers can be used for read-scaling.

In the former two modes a slave cannot be told at the moment to reject any writes. It may be the case that we'll introduce some API for setting a server to read-only mode in the course of the read-scaling changes for active failover, but that is yet unclear.

**Comment by jsteemann** [comment]
@avive99 : that is true. But as you mentioned, the functionality is likely to be extended in the future.

**Comment by dothebart** [comment]
If you use the meanwhile implemented Active Failover mode, followers will be only available once they become leader:

https://www.arangodb.com/docs/stable/tutorials-starter.html#starting-a-resilient-single-server-pair

ArangoDB 3.7 is available for download:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
