### ISSUE TITLE
batch endpoint fails when chunked encoding is used

### ISSUE THREAD

**Issue by ijcd** [arangodb/arangodb#4886]
It's common for many http clients to fall back to chunked encoding. Indeed, the HTTP spec requires that servers be able to handle it. Arango seems not to. Wireshark reports that the data parses fine. Arango complains.

This works fine if the `--header 'Transfer-Encoding: chunked'` is not passed to curl:

```
% cat test.sh                                                                                                                                                                               
#!/bin/bash

curl -v --basic --user "root:" -X POST --header 'Transfer-Encoding: chunked' --header 'Content-Type: multipart/form-data; boundary=SomeBoundaryValue' --data-binary @test.data --dump - http://localhost:8529/_api/batch
```

Be sure to use CRLF line endings:
```
% cat test.data                                                                                                                                                                              (master●●●)
--SomeBoundaryValue
Content-Type: application/x-arango-batchpart
Content-Id: myId1

GET /_api/version HTTP/1.1

--SomeBoundaryValue
Content-Type: application/x-arango-batchpart
Content-Id: myId2

DELETE /_api/collection/products HTTP/1.1

--SomeBoundaryValue
Content-Type: application/x-arango-batchpart
Content-Id: someId

POST /_api/collection/products HTTP/1.1

{"name": "products" }

--SomeBoundaryValue
Content-Type: application/x-arango-batchpart
Content-Id: nextId

GET /_api/collection/products/figures HTTP/1.1

--SomeBoundaryValue
Content-Type: application/x-arango-batchpart
Content-Id: otherId

DELETE /_api/collection/products HTTP/1.1
--SomeBoundaryValue--
```

```
% ./test.sh                                                                                                                                                                                  (master●●●)
*   Trying ::1...
* Connected to localhost (::1) port 8529 (#0)
* Server auth using Basic with user 'root'
> POST /_api/batch HTTP/1.1
> Host: localhost:8529
> Authorization: Basic cm9vdDo=
> User-Agent: curl/7.43.0
> Accept: */*
> Transfer-Encoding: chunked
> Content-Type: multipart/form-data; boundary=SomeBoundaryValue
>
> 2bd
* upload completely sent off: 708 out of 701 bytes
< HTTP/1.1 400 Bad Request
HTTP/1.1 400 Bad Request
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< Server: ArangoDB
Server: ArangoDB
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Content-Length: 92
Content-Length: 92
```

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version: 10.11

**Comment by jsteemann** [comment]
I can confirm that ArangoDB 3.x do not handle chunked encoding at all.
In order to make use of ArangoDB, please make sure the HTTP clients in use are not using chunked transfer encoding.

**Comment by dothebart** [comment]
Though the HTTP/1.1 API requires servers to implement chunked transfer encoding, we decided against doing so. 
To understand our reasons you have to look at the use cases chunked transfer encoding was made for and which implications it puts on the server. 
Chunked transfer encoding in post documents is usually here for if the client creates a post document on the fly while talking to the server where it doesn't know the total length of the content. This may be usefull if you want to handle transparent compression of large files (you expect your connection to be slow, or being CPU-bound while compressing for longer times), or i.e. if you want to stream a video that is filmed while you are uploading it

While talking to an arangodb server you usually will send JSON documents, which are known by the time you send them. 

Since the documents need to be valid the server needs to parse them. It can either do so by collecting all of your post chunks. Since it won't know the size it needs, it has to re-allocate and copy them until the final chunk has arived. The other solution could be a "streaming enabled"-json parser. This would need to be able to handle json elements crossing chunk boundaries which makes things overly complex and prevents using certain optimisations. 

Since we don't want neither, we don't support chunked encoding.

**Comment by ijcd** [comment]
Understood, but these assumptions break down for bulk calls, for example.
The included requests being generated can be streamed. The client I was
using assumed chunking would be fine so it took awhile to hunt down.

--Ian
