### ISSUE TITLE
Need to set and persist vars in Foxx service

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#5369]
At the top of a Foxx service source file it possible to use `const` to create identifiers that can be used within the routes in the service.  It is also possible to declare vars but the usefulness is very limited.

It would be useful to create a 'setter' route that could be used to 'hot update' variables that would be available to the entire service. The idea here is not to create a 'state' within the service but rather to update the values available by any endpoint that is utilized within the service.

Some examples? Maybe I declare a debug flag or use the same LIMIT value at multiple points in the service. I don't want to reload the service or touch the front end to make a configuration change. If ArangoDB / Foxx is the entire backend solution and the frontend is static - submitting settings changes via a Foxx endpoint could improve the viability of this simple app configuration.  

Of course the current app configuration could be persisted as a document stored in a collection.  But it would be awkward to retrieve that document each time the service API is called.

**Comment by pluma** [comment]
This isn't technically possible because Foxx runs in multiple threads in parallel and even global variables only exist in one thread at a time. This also sounds like exactly the kind of problem Foxx configuration is supposed to solve.

There are currently no plans to provide an API for services to modify their own configuration though, as that could lead to difficult bugs.
