### ISSUE TITLE
What are the big challenges in porting to mobile (Android & IOS)?

### ISSUE THREAD

**Issue by wis** [arangodb/arangodb#5389]
Hi team, another great piece of German engineering 😄👍 

seems like you're not porting to mobile anytime soon https://github.com/arangodb/arangodb/issues/2090

my (still theoretical) use case is using Arango for a mostly offline, client-side only storage application across Desktop/s and mobile device/s with replication and consistency.
    first of all, would it work in theory? (replication and consistency across devices, while most of the time not all devices are unavailable, turned off or out of range (for Bluetooth/WiFi access point p2p communication for replication)).

it's great that it's cross-platform while written in c++, makes it much easier to port, than OrientDB for example (written in Java).

so, is it persistence and/or usage of not available on mobile-OS APIs?

**Comment by dothebart** [comment]
Hi, 
while currently arangodb can be crosscompiled/native built on  linux/ARM, it currently won't run. 
Debugging and maintaining an ARM port is cumbersome due to LOOOOONG compile time turnarounds and low resources that make debugging a real work for patient people. (even more patient then waiting for also not fast MSVC for maintaining the windows port of ArangoDB).
If somebody would be willing to spend all that time and fix i.e. the issues with the boost lockfree queue on ARM (next to other problems inside of ArangoDB) you would probably have a running arangodb on ARM. 

While this could then be suitable for use on ARMv7 ++ architectures, ArangoDB is optimized for performance, not for sparse resource usage and saving battery cycles. This could ultimatively become that contrary, that you maybe even couldn't maintain this from the same code base. 

So while ArangoDB may be suiteable to be used as storage backend for mobile apps, doing so offline on the device is probably not going to be an option any time soon, unless you want to spend significant amounts of time changing that, or find somebody you can pay to do so. In the end ArangoDB is Open Source to enable that.

**Comment by dothebart** [comment]
Closing as answered.
