### ISSUE TITLE
Insert query slow loading collections

### ISSUE THREAD

**Issue by njdart** [arangodb/arangodb#5696]
I have been running some load tests against an ArangoDB instance (Arangodb-docker 3.3.10) and have found that it becomes very unresponsive after a while under load. Arango reports
```
2018-06-27T09:43:36Z [1] WARNING {queries} slow query:'...', bind vars: {...}, took: 36.696373 s, loading took: 33.893819 s
```

I was supplying approx 100 queries/second (query shown below) on a single server configuration, using the example run command found on the docker hub page. After stopping the test and leaving arango to settle, it returns to normal.

Is this expected behaviour? Is there any configuration I need to run Arango in a more production/scalable setting (short or using it in a cluster)

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

```
# arangod --version
3.3.10

architecture: 64bit
arm: false
asan: false
asm-crc32: true
assertions: false
boost-version: 1.62.0
build-date: 2018-06-05 19:03:35
build-repository: tags/v3.3.10-0-g902a980389
compiler: gcc [6.3.0 20170516]
cplusplus: 201103
debug: false
endianness: little
failure-tests: false
fd-client-event-handler: poll
fd-setsize: 1024
full-version-string: ArangoDB 3.3.10 [linux] 64bit, using jemalloc, build tags/v3.3.10-0-g902a980389, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0f  25 May 2017
icu-version: 58.1
jemalloc: true
maintainer-mode: false
openssl-version: OpenSSL 1.1.0f  25 May 2017
platform: linux
reactor-type: epoll
rocksdb-version: 5.6.0
server-version: 3.3.10
sizeof int: 4
sizeof void*: 8
sse42: false
unaligned-access: true
v8-version: 5.7.492.77
vpack-version: 0.1.30
zlib-version: 1.2.11
```

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Host: Arch linux `Linux ARCHY 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux`. Also tried on OSX with worse results

### this is an AQL-related issue:
- [x] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver:
https://github.com/arangodb/go-driver @ 76f2dacf4181c3624a801371c5aecc09ece82e25

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

```
Query string:
 LET entity = (INSERT @entity IN entities RETURN NEW)[0]
 INSERT {
     _from: CONCAT("entities/", @fromKey),
     _to: entity._id,
     _type: [@sourceType, @type]
 } IN edges
 RETURN entity

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  6   SubqueryNode         1     - LET #1 = ...   /* subquery */
  2   SingletonNode        1       * ROOT
  3   CalculationNode      1         - LET #5 = { "downlink" : 100, "uplink" : 2062 }   /* json expression */   /* const assignment */
  4   InsertNode           1         - INSERT #5 IN entities
  5   ReturnNode           1         - RETURN $NEW
  7   CalculationNode      1     - LET entity = #1[0]   /* simple expression */
  8   CalculationNode      1     - LET #7 = { "_from" : "entities/vepc", "_to" : entity.`_id`, "_type" : [ "VirtualisedEvolvedPacketCore", "Usage" ] }   /* simple expression */
  9   InsertNode           0     - INSERT #7 IN edges
 10   ReturnNode           0     - RETURN entity

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   remove-data-modification-out-variables

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
```
BindVars:
```
{
    "entity": {
        "downlink": 100,
        "uplink": 2062
    },
    "fromKey":"vepc",
    "sourceType":"VirtualisedEvolvedPacketCore",
    "type": "Usage"
}
```

![2018-06-27-10 18 23-screenshot](https://user-images.githubusercontent.com/1180858/41968488-89013e68-79fc-11e8-8e2d-2b0fdbad4685.png)

*This dump was taken after the instance had settled back down*
[debugDump.zip](https://github.com/arangodb/arangodb/files/2141036/debugDump.zip)

The issue can be reproduced using this dataset:
[arangodb3.tar.gz](https://github.com/arangodb/arangodb/files/2141067/arangodb3.tar.gz)
The volume has been modified to remove some sensative information, the `edges` and `entities` collections are the notable ones here.

```
tar -xvf arangodb3.tar.gz
docker run --rm --name arango -p 8529:8529 -e ARANGO_ROOT_PASSWORD=arango-root -v `pwd`/arangodb3:/var/lib/arangodb3 arangodb:3.3.10
```

**Comment by jsteemann** [comment]
As the storage engine is MMFiles and the loading time of the collection is by far the most time-consuming part of the query execution, it seems that the query was run when the collection was not loaded. For example, if you had shut down the server and restarted it and then ran the query, the query will load the collection first.

The MMFiles storage engine will implicitly load a collection upon first usage (e.g. when used in an AQL query). Loading a collection in MMFiles is not instantaneous, because it requires a scan over the datafiles of the collection to build up the in-memory indexes for the collection.
Follow-up queries on already loaded collections do not require this step of course.

The RocksDB storage engine does persist all its index entries, so this step is not necessary and loading a collection there is a no-op.

Another potential cause is that the MMFiles engine uses collection-level locks. So if there is any other thread that has acquired the lock on one of the involved collections, the query will have to wait until it can acquire the lock itself. If your application code reads/writes the collection in parallel, this may happen, especially if you have long-running read queries and such. Finally it could be one of ArangoDB's internal threads processing data of the collection and having to acquire the collection lock for a while. Though this should operate on the data in small chunks and not acquire the locks for so long.

The RocksDB engine has document-level locks, so the collection lock can be ruled out as a factor here.

It may be sensible to run the same test using the RocksDB storage engine, as this will rule out collection loading and collection-level locks. Apart from that, the RocksDB storage engine should be somewhat slower than the MMFiles engine, but should scale better on a single server with concurrent accesses.

**Comment by maxkernbach** [comment]
Hi @njdart,

has the previous message been helpful?
Did you have a chance to test loading involved collections before executing the AQL query or try the RocksDB storage engine?

**Comment by njdart** [comment]
@maxkernbach 

I'm hoping to have some time this evening to debug this further, including bumping the version of the go driver i'm using, and switching from MMFiles to RocksDB. I'll report my findings back.

@jsteemann's message was useful, but I have some questions.

> it seems that the query was run when the collection was not loaded

The queries were being run in rapid succession as soon as the previous one had returned, so I would assume they would still be loaded. How/when does MMFiles decide to unload the collection? And how long would you expect it to take to load two collections edges and node of approximately 48k and 24k each? To me 45 seconds seems very long.

 > Loading a collection in MMFiles is not instantaneous, because it requires a scan over the datafiles of the collection to build up the in-memory indexes for the collection.

Watching memory usage whilst this was going on, there was very little change over time. I couldn't see any evidence of loading the records into memory and then unloading them after. Although I wasn't particularly looking for it. I will check this when I get some time

> Another potential cause is that the MMFiles engine uses collection-level locks. So if there is any other thread that has acquired the lock on one of the involved collections, the query will have to wait until it can acquire the lock itself

Using go, with heavy use of go-routines, this is possibly a cause. Is there any way of seeing if this is the case? 

> If your application code reads/writes the collection in parallel, this may happen

How would you expect a service to make use of Arangodb with parallelisation? Is there any documentation/advice for supporting this kind of behaviour?

**Comment by maxkernbach** [comment]
@njdart 

A collection unload does not occur on its own. Either the collection unload has to be invoked (e.g _arangosh_: `db.collection.unload();`) or for example a server restart happens.
It is difficult to estimate the loading time of edge collections since it is quite hardware dependent.

Avoiding collection locks using MMFiles is not possible when multiple write operations access the same collection at the same time. There is no best practice to prevent it.

It would be helpful if you can share your findings of using RocksDB instead of MMFiles to figure out if collection locks are a possible cause.

**Comment by vinaypyati** [comment]
Hi @njdart,

Sending a quick follow up. Did you have a chance to try out the RocksDB storage engine and collect some findings? 
Thanks.

**Comment by maxkernbach** [comment]
Hi @njdart,

we haven't heard from you recently, I am closing this issue for now.
Please feel free to send an update with your RocksDB findings and reopen this issue.
