### ISSUE TITLE
Distinct count on edges collection is really slow

### ISSUE THREAD

**Issue by ohardy** [arangodb/arangodb#5747]
Hi,

Version: 3.3.9
RocksDB
In cluster

This query is used to count distinct edges take ~= 2s

```
LET id = 'sample/86177031'

FOR edge IN data
  FILTER edge._from == id
  COLLECT to = edge._to
  COLLECT WITH COUNT INTO count
  RETURN count
```

The same query without distinct take ~= 33ms:
```
LET id = 'sample/86177031'

FOR edge IN data
  FILTER edge._from == id
  COLLECT WITH COUNT INTO count

  RETURN count
```

Any solution to speed up that ?

It's private data so I can't share more details on public issue.

**Comment by jsteemann** [comment]
Is this is a cluster installation or a single server, using the MMFiles storage engine or RocksDB? 
Which version of ArangoDB are you using?

**Comment by ohardy** [comment]
Sorry to have forgotten that, I updated my initial message

**Comment by jsteemann** [comment]
Ok, let me have a look.

**Comment by jsteemann** [comment]
The non-distinct query
```
LET id = 'sample/86177031'

FOR edge IN data
  FILTER edge._from == id
  COLLECT WITH COUNT INTO count

  RETURN count
```
is optimized a lot by the AQL query optimizer.
It will count the matching edges on each shard only, and return the number of edges from each shard to the coordinator. So each shard returns just one numeric value. The coordinator will then only sum up these numbers. The execution plan for this query shows it:
```
Execution plan:
 Id   NodeType        Site       Est.   Comment
  1   SingletonNode   DBS           1   * ROOT
  8   IndexNode       DBS          10     - FOR edge IN data   /* edge index scan, scan only */
 13   CollectNode     DBS           1       - COLLECT  WITH COUNT INTO #5   /* count */
 11   RemoteNode      COOR          1       - REMOTE
 12   GatherNode      COOR          1       - GATHER 
  6   CollectNode     COOR          1       - COLLECT AGGREGATE count = SUM(#5)   /* sorted */
  7   ReturnNode      COOR          1       - RETURN count

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  8   edge   data         false    false            n/a   [ `_from` ]   (edge.`_from` == "sample/86177031")
```

The execution plan for the distinct query is not so trivial, as this query actually needs to ship the different _to values from all shards to a central place (the coordinator), where a final "make distinct" round needs to be done. The reason is that different shards can produce the same _to values, so there needs to be one further round of aggregation on the coordinator. In order to do this, all shards will need to send their different _to values. In comparison to the simple query (which only sent a single numeric value), the shards will now send as many records as there are distinct _to values. This is of course more expensive.
Here is the execution plan for this query:
```
Execution plan:
 Id   NodeType          Site       Est.   Comment
  1   SingletonNode     DBS           1   * ROOT
 11   IndexNode         DBS          10     - FOR edge IN data   /* edge index scan, projections: `_to` */
  6   CalculationNode   DBS          10       - LET #6 = edge.`_to`   /* attribute expression */   /* collections used: edge : data */
 16   CollectNode       DBS           8       - COLLECT #10 = #6   /* hash */
 14   RemoteNode        COOR          8       - REMOTE
 15   GatherNode        COOR          8       - GATHER 
  7   CollectNode       COOR          8       - COLLECT to = #10   /* hash */
 10   SortNode          COOR          8       - SORT to ASC
  8   CollectNode       COOR          1       - COLLECT  WITH COUNT INTO count   /* count */
  9   ReturnNode        COOR          1       - RETURN count

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
 11   edge   data         false    false            n/a   [ `_from` ]   (edge.`_from` == "sample/86177031")
```
There are only minor ways to speed this up, e.g. by removing the extra unnecessary `SORT`. Note that the `SORT` is only there because `COLLECT` guarantees sorted output. It can be removed by putting an extra `SORT null` clause between the two `COLLECT` statements in the query. However, I doubt that this will help much.

The query could also be simplified to just
```
LET id = 'sample/86177031'
RETURN COUNT(FOR edge IN data FILTER edge._from == id RETURN DISTINCT edge._to)
```
But again, this will not help much, as here the shards still need to send all their distinct _to values to the coordinator for a final "make them unique" aggregation.
As long as the shards need to send (lots of?) data to the coordinator, the distinct query will be much more expensive than the simple non-distinct, counting-only query. And there is not much that can be done about it just by changing the query somehow.

**Comment by OmarAyo** [comment]
Hi @ohardy,

Did you have the chance to read what jsteemann reported above ? Could you please send us a status update 

Best

**Comment by OmarAyo** [comment]
Hi @ohardy 

Since we have not heard back from you in a while, I am closing this issue for now.
In case the problem persists, please provide further details and we would be glad to investigate it.

Best,
