### ISSUE TITLE
Batch request handling incompatible with .NET's default ContentType format

### ISSUE THREAD

**Issue by FilipFilipov** [arangodb/arangodb#5827]
When posting to the `/_api/batch` endpoint you must provide a header like this `Content-Type: multipart/form-data; boundary=SomeBoundaryValue`

However, if the boundary is in quotes like this `boundary="SomeBoundaryValue"` you get a `400 Bad Request` with the message `invalid multipart message received`. I found this out because .NET's `MultipartFormDataContent` class (which is the canonical way to build these kinds of requests through the `HttpClient`) automatically adds quotes to the boundary value if it doesn't already have them.

So in the interest of not confusing any other .NET developers, I propose that arangodb trim any quotes from the boundary before using it.

**Comment by dothebart** [comment]
we should also lookup what the HTTP RFC says about this.

**Comment by FilipFilipov** [comment]
Another thing in regards to the format. Each part of the body is meant to be a standard http message, right? Well in order to parse that .NET requires the `Content-Type` header to be `application/http; msgtype=response` and not `application/x-arango-batchpart`

Similarly the `Content Type` for the request parts defaults to `application/http; msgtype=request` when using the built-in libraries. I'm not sure if that's a Microsoft standard or an HTTP one.

**Comment by maxkernbach** [comment]
Hi @FilipFilipov, 

version 3.3.13, which includes a fix for the boundary, has been released yesterday.
The `boundary` field can include quote marks now (see [5860](https://github.com/arangodb/arangodb/pull/5860/files)).

However the `Content Type` for both header and request parts won't be changed since `application/x-arango-batchpart` is part of the existing ArangoDB API.
