### ISSUE TITLE
Difference between queries using HTTP API and AQL when key is url encoded

### ISSUE THREAD

**Issue by omerzohar** [arangodb/arangodb#5885]
## My Environment

* __ArangoDB Version__:      e.g. 3.3.10 
Settings vanilla using docker image

When making a request to a table when the key contains '%' of a urlencode string (_key == 'www.moshe.com%2Fbbb' , using direct AQL thru the console will properly find the document, but using HTTP API will give a 404

## Steps to reproduce

AQL (Works perfectly):
FOR doc IN Url
  FILTER doc._key == 'www.moshe.com%2Fbbb'
  RETURN doc

Result:
[
  {
    "_key": "www.moshe.com%2Fbbb",
    "_id": "Url/www.moshe.com%2Fbbb",
    "_rev": "_XHxz80K--_"
  }
]

Using HTTP API:

curl -vv --header Content-Type: --compressed --user "root:<REMOVED>" --header "Connection: keep-alive" --user-agent "python-requests/2.19.1" --data-binary "{<REMOVED>}" --request PUT http://127.0.0.1:8529/_db/labdbTest/_api/document/Url/www.moshe.com%2Fbbb?collection=Url&waitForSync=False 

*Note about the CURL: the curl was created from a pcap capture between the client and DB and seems ok, so the problem is not on the client side, but with how the server parses the request

**Comment by maxkernbach** [comment]
Hi @omerzohar,

thanks for reporting this issue and providing a detailed description. 

In order to use curl with '**%**' included in the document key, '**%**' has to be escaped to '**%25**', which is the two-digit hexadecimal of its byte value. Therefore you have to use your curl command with `www.moshe.com%252Fbbb` instead of `www.moshe.com%2Fbbb`.

Any other special character can be encoded the same way ([see HTML codes table - Hex column](https://www.ascii.cl/htmlcodes.htm)).

**Comment by maxkernbach** [comment]
@omerzohar

Has the previous suggestion solved your problem?

**Comment by dothebart** [comment]
As explained by @maxkernbach a double escape is required since the `/` has 3 meanings here: 
- separator in the HTTP Uri
- separator <collection/key> (in document IDs)
- string inside the document ID.

Closing this as solved with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) .
