### ISSUE TITLE
ArangoDB hangs under the load

### ISSUE THREAD

**Issue by blokhinnv** [arangodb/arangodb#6230]
## My Environment

* __ArangoDB Version__:        3.3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Serverw
* __Configuration__:               Intel Xeon X5650 x2, 32GB RAM
* __Infrastructure__:               own
* __Operating System__:        Windows 10

__Problem__:
Currently I'm maintaing a cycle which consist of four steps:
1. Collection information as csv
2. Import them to temporary collections via `arangoimp`
3. Merge them with main collection using AQL request with UPSERT

I have two 'main' collections - one is 'document collection' with 4 million documents, another one is 'edge collection' with 45 million documents. 
The problem is I have to restart the system regurarly, because ArangoDB stops working. For example, I've been waiting for the AQL query to finish for 3 hours, while trying to import collection via `arangoimp` and now ArangoDB doesn't response. 'Doesn't response' means that I can't use web interface (I see only empty white window), Arango Shell doesn't work as well, etc. 

Can I somehow find out why this happens? 

__Expected result__:

**Comment by jsteemann** [comment]
Can you post the exact AQL query here, plus the exact indexes that are present for the collection(s)?
As I have no idea what the query looks like, my first guess is either that it does not use any index or builds up huge (intermediate) result sets.

From the details above, it seems you are on ArangoDB 3.3.4. The current version of ArangoDB is 3.3.14 and may help improve things (though this is still unclear, because we don't know yet what the exact problem is). However, later versions of ArangoDB contain some nice "explain" and "debug" functionality in the web UI, making it rather easy to export your exact query, the index setup and some example data into a JSON file. By providing this file it is a lot easier for us to debug the issue than guessing.

**Comment by jsteemann** [comment]
Here's a screenshot from the functionality from 3.3.14:
![image](https://user-images.githubusercontent.com/1423118/44484684-b8081f00-a64e-11e8-9b63-e3bc61930f70.png)

**Comment by blokhinnv** [comment]
The AQL query is
```
FOR edge IN @@temp_edges_collection
	UPSERT { _key:edge._key } 
	INSERT { _from: edge._from, _to: edge._to, coccurrence: edge.coccurrence, _key:edge._key } 
	UPDATE { coccurrence: OLD.coccurrence + edge.coccurrence } 
	IN myedges
```
where @temp_edges_collection is the collection in which ive just imported about 5 million edges, and `myedges` in the collection with 45 million edges.
Both collections have the standart indexes, I haven't created my own.
![image](https://user-images.githubusercontent.com/36994200/44488868-88631200-a662-11e8-9920-ad7e1ab3e53b.png)

**Comment by blokhinnv** [comment]
I've managed to upgrade the version, here's the debugDump
[debugDump.zip](https://github.com/arangodb/arangodb/files/2311915/debugDump.zip)
Not sure, if it is importand or not, but I call this query from `python-arango` driver.

**Comment by blokhinnv** [comment]
Thank you, I will try.
But actually the problem is not the query's duration, but the fact that the whole database occasionally  stops working, while I expect it to work slower but at least to respond somehow. 
Could that be the result of the 'subquery overhead' that you mentioned?

**Comment by jsteemann** [comment]
It's probably not the subquery overhead that is causing it to stop responding timely, but the sheer amount of writes done by these queries.

I guess the server will be blocked on I/O then. If you run `top` or some other tools that shows disk utilization while the queries are running, you should see a lot of I/O activity, and probably the whole system is blocked by that. But that's just a guess of course.

Please take into account that when updating a document in ArangoDB the whole document plus all index entries will need to be written to disk with the RocksDB engine. And as RocksDB is an LSM storage, there will always be some write amplification, which makes each logical key/value modification trigger multiple disk writes.

If the amount of disk writes are the actual problem, then it's probably an option to process the input in smaller chunks and pause a while in between to allow for some recovery in between.

**Comment by blokhinnv** [comment]
I've tried what you suggested, and the results are sad. I decided to try it firsly with the temp collection with 1 million edges instead of 5 million.
I'm attaching the screenshots, your query took about 4.5h (both parts) and it was still in progress, so I interrupted it. I started the query with `UPSERT` just after it and it took 12mins to finish.
![v0](https://user-images.githubusercontent.com/36994200/44541469-b3a53a00-a712-11e8-9f36-6ff65b19ec1b.png)
![part1_exec](https://user-images.githubusercontent.com/36994200/44541477-bdc73880-a712-11e8-9296-a5f9a4c6fcfc.png)
![part2_exec](https://user-images.githubusercontent.com/36994200/44541480-bf90fc00-a712-11e8-97ff-706e85010132.png)

**Comment by jsteemann** [comment]
Did you run the UPSERT query on a fresh "myedges" collection? 
Asking because if you ran the UPSERT query after running the queries I put together, the state of "myedges" was already modified, so the UPSERT query may do less/other work.

Back to the UPSERT query then...
Is there a way to run this query for smaller chunks of data, e.g. for chunks for 100k documents?
For example invoking the below query until `edges_temp_col` is empty:
```
FOR edge IN edges_temp_col 
LIMIT 100000 
UPSERT { _key:edge._key }  INSERT { _from: edge._from, _to: edge._to, coccurrence: edge.coccurrence, _key:edge._key }  UPDATE { coccurrence: OLD.coccurrence + edge.coccurrence }  IN myedges 
REMOVE edge IN edges_temp_col
```
If you invoke that in a loop and let the process sleep for a little while in-between, it may be better than running it all in one big query. But that is just guesswork right now. Can you check if it helps?

**Comment by blokhinnv** [comment]
Here's the strange thing. It worked pretty well 7 hours ago, but now there's a problem. For 23 chunks the query executes about 1-1.5 minutes, but the next one takes 47 mins atm and hasn't finished yet.  
The task manager shows 31% RAM usage, but 0% disk usage.
Why could this happen? 
![image](https://user-images.githubusercontent.com/36994200/44568797-f30a6f80-a780-11e8-879b-78aab050b24d.png)
![image](https://user-images.githubusercontent.com/36994200/44568819-04ec1280-a781-11e8-8a8f-bbfbcd5be677.png)

**Comment by jsteemann** [comment]
There are several potential reasons for this, but I can't tell if they apply or not:
- the edges may have completely different sizes, like one batch with only small edges and one batch with huge edges. Not sure if this is the case.
- the UPSERT query obviously is data-dependent. For each edge in `temp_edges_collection` there will either be an INSERT or an UPDATE performed, depending on whether the edge already exists in `myedges`. It's a least possible that for some batches the majority of cases will trigger the INSERT and in some batches it will mainly be UPDATE. UPDATE is definitely slower than INSERT because it has to do more work, though it shouldn't be orders of magnitude.
These are obviously data-dependent potential reasons for one batch being slower than another.
The main I would have suspected is that writing data into RocksDB is waiting for the disk (then you should see massive disk I/O) or that RocksDB's compaction is ongoing and taking a lot of CPU (then you should see high CPU activity).

**Comment by blokhinnv** [comment]
For now everything works OK, so I'm closing the issue.
Thank you for all your help!
