### ISSUE TITLE
Documentation - Arangorestore data integrity

### ISSUE THREAD

**Issue by alejom99** [arangodb/arangodb#6370]
The documentation says:

> Please note that arangorestore must not be used to create several similar database instances in one installation.

> This means if you have an arangodump output of database a, and you create a second database b on the same instance of ArangoDB, and restore the dump of a into b - data integrity can not be guaranteed.

Can you explain why this is the case? Isn't arangodb built to support multiple databases in the same instance regardless of what the data looks like?

**Comment by sleto-it** [comment]
hi @alejom99 thanks for opening this ticket

which version are you using? the recent doc (devel branch) was changed to mention when that limitation was solved 

please could you check this page https://docs.arangodb.com/devel/Manual/Programs/Arangorestore/Examples.html

yes, you can have multiple databases - the limitation was due to a bug, which was then solved in 3.3

let me know if this helps,

many thanks,

**Comment by alejom99** [comment]
hi @sleto-it , thanks for your response. The 3.3 documentation shows that wording. See screenshot. So, does this mean that the bug fix is included in any 3.3.X version? Or any specific version of 3.3.X?

Thanks

![image](https://user-images.githubusercontent.com/4347903/45038680-53be6580-b027-11e8-917c-4a3e6c623266.png)

**Comment by Simran-B** [comment]
Here's the 3.3 file: https://github.com/arangodb/arangodb/blob/3.3/Documentation/Books/Manual/Administration/Arangorestore.md

Devel: https://github.com/arangodb/arangodb/blob/devel/Documentation/Books/Manual/Programs/Arangorestore/Examples.md

> Please note that in versions older than 3.3, Arangorestore must not be used to create several similar database instances in one installation.

It does not specify a version, but if it was fixed in a bugfix release, then the exact version should be added to 3.3 and devel documentation.

**Comment by sleto-it** [comment]
since it says "This limitation was solved starting from ArangoDB version 3.3" I believe and if I remember correctly it means from 3.3.0 (the first GA)

Though to avoid confusion in the future we can and should always add also the patch number as well

Tagging as bug, as the 3.3 doc is outdated as it does not include that the limitation was solved

@alejom99 to reply your question:

yes, arangodb supports different databases (regardless of their content)
in some old versions, though, there was a bug that was occurring when restoring the same database (the very same, with a different name) on the same server. this bug was linked with collection _ids_ - this is the reason why we added that warning in the documentation

than the bug was fixed and we updated the devel documentation, but not the 3.3 documentation

I hope the above clarifies

If you are using latest 3.3. version or higher you should not be affected by this issue

I hope the above answers. Please let us know if you are seeing any specific issues

many thanks,
