### ISSUE TITLE
Cannot access API of Foxx Service due to Auth Problem

### ISSUE THREAD

**Issue by lanluu** [arangodb/arangodb#6438]
ArangoDb 3.4 RC 1 - Windows
After uploading Foxx Service, the API/Swagger is not accessible.

![image](https://user-images.githubusercontent.com/3998945/45289579-cfb82200-b4ed-11e8-902c-75de5d6e7a8c.png)

**Comment by Simran-B** [comment]
@vinaypyati @lservini Can you check this in latest RC?

**Comment by vinaypyati** [comment]
Hi @lanluu,

Did you have a chance to test if this issue also occurs in [3.4.0 RC2](https://www.arangodb.com/download-technical-preview/) ? I tried reproducing this issue on 3.4.0 RC1 and unfortunately, it is not reproducible. API of Foxx services are accessible.  Can you please confirm the following so that we can reproduce on our side too?
- Are you using Single Server? 
- How are you creating a service? Is it via the `Store`, `Upload` or `New` UI?

Thanks!

**Comment by vinaypyati** [comment]
Hi @lanluu,

We haven't received feedback from you for a while, I am closing this issue for now.

Please consider testing this issue on 3.4.0 RC3. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). If it does not resolve your problem, please feel free to reopen the issue by adding a new comment.

Thanks!
