### ISSUE TITLE
FULLTEXT subquery with dynamic collection name no longer works as of 3.4.0-rc.1

### ISSUE THREAD

**Issue by FilipFilipov** [arangodb/arangodb#6445]
## My Environment

* __ArangoDB Version__:        3.4.0-rc.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               query.cache-mode demand
* __Infrastructure__:               own
* __Operating System__:        Windows 10 
* __Used Package__:              official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query__:
```
FOR obj IN objects
UPDATE obj._key WITH {
    merged_props: FIRST(
        FOR row IN FULLTEXT(obj.type, 'id', obj.id, 1)
        RETURN KEEP(row, REMOVE_VALUE(ATTRIBUTES(row, true), 'id', 1)
    )
} IN objects
```

__AQL explain__:
`collection or view not found:  (while optimizing plan)`

__Dataset__:
Basically there's one master table "objects" where each document has an id string and a bunch of generic properties including a type. Each type has its type-specific properties in another collection with the same name as its type with a 1-to-1 relation through the id property (the database is mirroring an SQL schema). The query is meant to iterate through the objects collection and merge the properties from the other collections into a "merged_props" document property all at once using a `FULLTEXT` subquery with a dynamic collection name.

## Steps to reproduce

1. Create collections `objects` and `test`.
2. Add a fulltext index to `test` on the `id` field.
3. Insert a document in `objects` with properties `{ id: '1', type: 'test' }`.
4. Insert a document in `test` with properties `{ id: '1', prop: 'value' }`.
5. Run the AQL query above.

__Problem__:
This query used to work in 3.4.milestone0, but doesn't any more, failing in the optimization stage. I suspect #5529 has something to do with it, but that's just a guess.

__Expected result__:
Collection `objects` should contain a single document with properties 
```
{ 
  id: '1',
  type: 'test',
  merged_props: { prop: 'value' }
}
```

**Comment by jsteemann** [comment]
This is an intentional change (i.e. a "feature"), as accessing collections dynamically via functions has caused many internal issues in AQL. This was completely changed in the 3.4 code, and is also a documented, downwards-incompatible change.

Please refer to the list of incompatible changes in 3.4 for more details:
https://github.com/arangodb/arangodb/blob/3.4/Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md#aql

**Comment by Simran-B** [comment]
Your query tries to use the `type` attribute as dynamic collection name: `FULLTEXT(obj.type, ...)`
This is indeed no longer supported. However, I don't see why you used `FULLTEXT()` in the first place.

With a document `{ _key: '1', type: 'test' }` in *objects* and a document `{ _key: '1', prop: 'value' }` in *test*, you can do this without `FULLTEXT()` and without secondary indexes:

```js
FOR obj IN objects
    LET doc = DOCUMENT(obj.type, obj._key)
    LET merged_props = KEEP(doc, ATTRIBUTES(doc, true))
    UPDATE obj._key WITH {merged_props} IN objects
```

If you can't use the `id` attributes as document keys, then this isn't possible because it would require a FOR loop to filter by the `id` attribute, but the collection you iterate over can't be dynamic. You could still try a graph model in that case, which allows edges between vertices of arbitrary collections.

**Comment by FilipFilipov** [comment]
That does seem to work, but will the DOCUMENT function still be allowed to use dynamic collection names in the future?

**Comment by Simran-B** [comment]
Yes, it will continue to support this for the foreseeable future.

**Comment by dothebart** [comment]
With the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this as solved.
