### ISSUE TITLE
Cluster: jobs moved to coordinator

### ISSUE THREAD

**Issue by timeau** [arangodb/arangodb#6616]
## My Environment

* __ArangoDB Version__:        3.4rc1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Configuration__:              3 physical hosts, each have DBS and agent. Coordinator runs on first of them 
* __Infrastructure__:               own
* __Operating System__:        CentOS 7
* __Used Package__:              RedHat .rpm

## Component, Query & Data

__AQL query (if applicable)__:
```
WITH pmfull,pmlinks,pmcfull
for doc in pmfull 
    filter (doc.PMID > 1) AND (doc.PMID < 1000)
    for v,e,p IN OUTBOUND doc pmlinks
        FILTER "0019-9567" IN v.JOURNAL[*]
        return {"pmid":doc.PMID,"pmcid":v.PMCID,"pm":doc.AUTH,"pmc":v.JOURNAL}
```

__Dataset__:

I have an ArangoDb cluster (version 3.4rc1) and three collections: "pmfull" (document, 29 million docs), pmcfull (document, 5 million docs) and "pmlinks" (edges, 4.5 million). Last collection stores links between first two document collections.

__Replication Factor & Number of Shards (Cluster only)__:
_Replication factor_: 1
_Number of Shards_:64

__Problem__:
Only first part of query runs on DBS. Everything else moved to coordinator which significantly impact performance. I could be wrong, but don't see any reason why links lookup and further search in the "pmclinks" database could not be done on DBS. Total execution time is 1.294 s, which is unreasonable. Please, help/advise. 

```
Query String:
 WITH pmfull,pmlinks,pmcfull
 for doc in pmfull 
     filter (doc.PMID > 1) AND (doc.PMID < 1000)
     for v,e,p IN OUTBOUND doc pmlinks
         FILTER "0019-9567" IN v.JOURNAL[*]
         return {"pmid":doc.PMID,"pmcid":v.PMCID,"pm":doc.AUTH,"pmc":v.JOURNAL}
 

Execution plan:
 Id   NodeType          Site  Calls   Items   Runtime [s]   Comment
  1   SingletonNode     DBS      64      64       0.00010   * ROOT
 10   IndexNode         DBS     128     998       0.01158     - FOR doc IN pmfull   /* hash index scan, 64 shard(s) */
 13   RemoteNode        COOR    256     998       0.11862       - REMOTE
 14   GatherNode        COOR    193     998       0.00031       - GATHER 
  5   TraversalNode     COOR      1      95       0.61978       - FOR v  /* vertex */ IN 1..1  /* min..maxPathDepth */ OUTBOUND doc /* startnode */  pmlinks
  6   CalculationNode   COOR    129      95       0.00011       - LET #10 = ("0019-9567" in v.`JOURNAL`[*])   /* simple expression */
  7   FilterNode        COOR    129       6       0.00003       - FILTER #10
  8   CalculationNode   COOR    129       6       0.00002       - LET #12 = { "pmid" : doc.`PMID`, "pmcid" : v.`PMCID`, "pm" : doc.`AUTH`, "pmc" : v.`JOURNAL` }   /* simple expression */   /* collections used: doc : pmfull */
  9   ReturnNode        COOR    129       6       0.00000       - RETURN #12

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
 10   hash   pmfull       false    false        99.99 %   [ `PMID` ]    ((doc.`PMID` > 1) && (doc.`PMID` < 1000))
  5   edge   pmlinks      false    false            n/a   [ `_from` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections   Options                                   Filter conditions
  5   1..1                         pmlinks            uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   optimize-traversals
  8   remove-unnecessary-calculations-2
  9   scatter-in-cluster
 10   remove-unnecessary-remote-scatter

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0         1093         89         0.80293

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00001
 parsing                    0.00016
 optimizing ast             0.00002
 loading collections        0.00000
 instantiating plan         0.00007
 optimizing plan            0.00055
 executing                  0.77859
 finalizing                 0.02351


```

**Comment by mchacki** [comment]
Hi @timeau,

this behavior is intended, a traversal node can not be optimized to a database server.
Reason:
It is not guaranteed that all edges and neighboring vertices are stored on the very same database server, hence we need to do network communication, and this is coordinated on the coordinator.
So there is not much we can do in the community version.

The only idea that has potential to help is to reverse the search of the traversal.
Right now you search pmfull to pmcfull, resulting in almost 1000 traversals to be executed in this case (998 input vertices).
If you could reverse the search pmcfull (backwards) to pmfull this may result in less traversals to be executed (i do not know because i do not know the details of your dataset)

So the query would look like this:

    WITH pmfull,pmlinks,pmcfull
    FOR v IN pmcfull
      FILTER "0019-9567" IN v.JOURNAL[*]
      FOR doc,e,p IN OUTBOUND v pmlinks
        FILTER (doc.PMID > 1) AND (doc.PMID < 1000)
        RETURN {"pmid":doc.PMID,"pmcid":v.PMCID,"pm":doc.AUTH,"pmc":v.JOURNAL}

However we have a feature called smart-graphs in the enterprise variant as described here: https://www.arangodb.com/why-arangodb/arangodb-enterprise/arangodb-enterprise-smart-graphs/
This will (with clever and enforced sharding) ensure that the above non-guaranteed condition is hold  to a certain extend, and the traversal can take advantage of this situation => i expect a much better performance there.
NOTE: Still the Traversal will be located on the Coordinator, but much more computation will be done locally.

If you need any further help/introduction to SmartGraphs please let us know.

**Comment by timeau** [comment]
Hi @mchacki!
Thank you for explanation. Reverse search is not an option since traversals should be combined with full-text search, but contains an error (#6618 ). So my example here was pretty artificial, just to demonstrate the question.
Anyway, thank you very much for looking into this, I appreciate it.
