### ISSUE TITLE
Implement graph consistency in ArangoDB java driver.

### ISSUE THREAD

**Issue by Dashia18** [arangodb/arangodb#6687]
## My Environment

* __Deployment Mode__:       Single Server
* __Arango DB__:      version : 3.2.5
* __Arango java driver__:  version : 4.6.1

## Component, Query & Data
__Affected feature__:
AQL query using web interface  & with java driver

__AQL query (if applicable)__:
REMOVE vertex IN collection

## Steps to reproduce

1.  Create 3 vertices 
2.  Create 2 edges connected those 3 vertices 
3.  Delete vertex with 2 edges

__Problem__:
In the result we have 2 vertices and 2 edges, which have _from/_to values point to nowhere. It can leads  to errors and graph inconsistency

__Expected result__:
In the result we have 2 vertices and 0 edges, because edge cannot point to not existed vertex.

## Comment
In this case the edges don't deleted automatically by AQL when vertices are deleted, I checked this.
The documentation confirms this: https://docs.arangodb.com/devel/AQL/Examples/RemoveVertex.html

However javascript driver support data consistency as they say here: https://docs.arangodb.com/devel/Manual/Graphs/GeneralGraphs/Management.html#remove-a-vertex
I think that as documentation says for javascript driver deleting of vertex should removes associated edges (ingoing and outgoing). Because as a result of vertex removing, edges  are appeared which points to nowhere.

When graph consistency will be implemented in ArangoDB java driver and edges will be deleted automatically by AQL when vertices are deleted?

Is it planned?

**Comment by dothebart** [comment]
Hi, 
doesn't https://docs.arangodb.com/3.4/Drivers/Java/Reference/Graph/Vertices.html#arangovertexcollectiondeletevertex do this? With ArangoDB 3.4 the backendimplementation on the database side was rewritten in C++ with some issues fixed; Can you try this?

**Comment by MrPieces** [comment]
Hi Dashia,

in addition to what @dothebart wrote:

PLease note that you have to create a so called "named graph" to have the ability to automatically delete edges, if a vertice gets deleted. 

Please find general information about namedgraphs in our ArangoDB docs https://docs.arangodb.com/devel/Manual/Graphs/#named-graphs
and for Java in the Java Driver Reference http://arangodb.github.io/arangodb-java-driver/javadoc-4_3/index.html

Hope this helps,

Jan

**Comment by Dashia18** [comment]
Hi, 

@dothebart and @MrPieces thank you for the answers!

@dothebart how can I try version 3.4? I try to find it in https://hub.docker.com/_/arangodb/ but the latest version is 3.3.16. 

Did you make any issues about deleting vertex associated to edges in v.3.4?

@MrPieces as I see in documentation (http://arangodb.github.io/arangodb-java-driver/javadoc-4_3/index.html) it says that only a vertex can be deleted . With "Named graph" it can be used traversals/short path, java script or Restfull graph interface. But I need to remove vertex with associated edges by java driver (AQL queries). I cannot find a solution.

Thank you in advance!

**Comment by dothebart** [comment]
Hi, 
please have a look at: https://www.arangodb.com/download-technical-preview/docker-preview/

**Comment by Simran-B** [comment]
AQL does not support the automatic removal of edges when connected vertices get deleted, mainly because it would be a major performance issue (edges can point to vertices in arbitrary collections).

Related: https://github.com/arangodb/arangodb/issues/1529, https://github.com/arangodb/arangodb/issues/1575,
https://stackoverflow.com/questions/35074545/safe-removal-of-vertexes-in-arangodb-using-ids

**Comment by Dashia18** [comment]
Thank you!

@dothebart As a result nothing is changed in v 3.4 . I checked and edges is left when I removed a vertex.

@Simran-B Do you know if this will be planned once? Or it is principal decision to not implement this?

**Comment by MrPieces** [comment]
@Simran-B the SO question is from 2016, so maybe outdated.

@Dashia18 To automatically delete an edge when a vertex gets deleted, you have to use
a) named graphs
AND b) the graphAPI in the java driver https://docs.arangodb.com/3.4/Drivers/Java/Reference/Graph/#graph-api

If you are sure that you setup everything correctly and the edge still doesn't get deleted, please let us know

**Comment by Simran-B** [comment]
The SO post is indeed old, and the question uses the obsolete GRAPH_EDGES() function, but the answer looks up-to-date (using AQL traversal).

It might be more feasible to support it in AQL using the RocksDB storage engine with document-level locks, but cluster would still be a challenge I guess. Back then in 2016/17 when I asked our developers, there was only MMFiles engine with its collection-level locks.

@mchacki @ifcologne Anything planned or decided in this regard?

**Comment by epluribusunix** [comment]
I see that there is some kind of solution for this using NamedGraph, etc., but is there a time when a dangling edge is ever useful?  And if you plan on changing the _from/_to field mid-transaction (for instance), then why not just re-create the edge using the original values?

If broken edges are so dangerous, why risk breaking graph traversal queries at all?  It seems like it's similar to littering your code with NULL pointers and hoping that no one references that variable.

Performance issue or not, I see this as a MAJOR issue.  Currently, I cannot chance broken edges and have to write custom clean-up code, which I am SURE is less performant than something native.

**Comment by Dashia18** [comment]
@MrPieces thank you very much!

I checked it on version 3.4 and when I remove vertex all associated vertex are removed too.

**Comment by MrPieces** [comment]
@Dashia18 thank you for staying with us :) Sorry, that our docs/java docs are not clear enough about the topic.

@epluribusunix you are absolutely right that dangling edges are basically of no use. This is why we have the concept of "namedgraphs" in ArangoDB. But "namedgraphs" do come with some overhead in terms of write performance because additional writes have to be made for a consistent graph definition. That is why we also have the concept of "anonymousgraphs". If you combine both concepts, you have the advantage of less write overhead and graph consistency at the same time.

Hope that explanation helps for now. Will ask my more experienced teammates to write a quick tutorial about the topic

**Comment by MrPieces** [comment]
@epluribusunix does this answer your questions? https://docs.arangodb.com/3.2/Manual/Graphs/#named-graphs Please see the part "JavaScript General Graph implementation, as you may use it in Foxx Services"

**Comment by epluribusunix** [comment]
@MrPieces - yes!  I'm not sure how I missed this, especially since I was looking for it specifically.  The docs definitely feel a bit jumbled sometimes, but I don't have a suggestion on how they could be better (or differently) organized.  It just seems that I have to really dig around to find information on functionality available within Foxx.

Thank you, again.  I'll pay more attention next time!  RTFM

**Comment by dothebart** [comment]
Ok, @Dashia18 @epluribusunix I think we can close this issue then?

**Comment by Dashia18** [comment]
@dothebart yes, I think it can be closed. You helped me to find the solution. Thank you all!
