### ISSUE TITLE
Query causes ArangoDB to Crash

### ISSUE THREAD

**Issue by peterfraedrich** [arangodb/arangodb#7233]
## My Environment

* __ArangoDB Version__:        3.3.19-1
* __Storage Engine__:            both
* __Deployment Mode__:       single-server
* __Deployment Strategy__:   systemd
* __Configuration__:               defaults
* __Infrastructure__:              own
* __Operating System__:       Ubuntu 18.04 LTS
* __Used Package__:              .deb package

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
```
for item in builtin_cpu
    FILTER
        item.timestamp in RANGE(
            DATE_SUBTRACT(DATE_NOW(), 30, "day"),
            DATE_NOW()
    )
    RETURN item
```

__AQL explain (if applicable)__:
```
Query string:
 for item in builtin_cpu
     FILTER
         item.timestamp in RANGE(
             DATE_SUBTRACT(DATE_NOW(), 30, "day"),
             DATE_NOW()
     )
     RETURN item

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR item IN builtin_cpu   /* persistent index scan */
  5   ReturnNode         1       - RETURN item

Indexes used:
 By   Type         Collection    Unique   Sparse   Selectivity   Fields            Ranges
  6   persistent   builtin_cpu   false    false       100.00 %   [ `timestamp` ]   (item.`timestamp` in RANGE(DATE_SUBTRACT(DATE_NOW(), 30, "day"), DATE_NOW()))

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

__Dataset__:
collection of objects similar to below
```JSON
{
  "timestamp": 1541457014,
  "host_id": "18724d56-7c8a-51f3-fe7f-6c2d0e903c31",
  "hostname": "budgie",
  "ip": "10.0.0.49",
  "data": {
    "cpu_info_model": "2",
    "cpu_info_mhz": 3515.619,
    "cpu_info_cache": 2048,
    "cpu_info_cores": 3,
    "cpu_pct": [
      30.85,
      32.97,
      29.47
    ],
    "cpu_pct_avg": 31.09,
    "cpu_user": 5842.7,
    "cpu_system": 7945.94,
    "cpu_idle": 108489.19,
    "cpu_nice": 60.78,
    "cpu_iowait": 895.48,
    "cpu_irq": 0,
    "cpu_softirq": 252.93,
    "cpu_steal": 0,
    "cpu_guest": 0,
    "cpu_guestnice": 0,
    "cpu_stolen": 0
  }
}
```

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. start new arangoDB instance
2. load sample data into database/collection
3. run query
4. db crash

__Problem__:
database crashes when running query

__Expected result__:
a query result

**Comment by jsteemann** [comment]
The reason for this is the following part of the query:
```
FILTER ... IN RANGE(
             DATE_SUBTRACT(DATE_NOW(), 30, "day"),
             DATE_NOW()
     )
```
The `RANGE` AQL function creates all integer numbers between its two input parameters (https://docs.arangodb.com/3.3/AQL/Functions/Numeric.html#range).

The two input parameters are (dates vary of course):
* `"2018-10-07T07:42:45.473Z"` (produced by `DATE_SUBTRACT(DATE_NOW(), 30, "day")`)
* `1541490184330` (produced by `DATE_NOW()`)

So effectively this will try to create all integers between that string value (which is converted to `0` because it is not a number) and the other numeric values. So approx. 1.5 billion integers will be created in memory for this query, so it will eventually run the server out of memory.

What will probably work a lot better is to use `>=` and `<=` operators for filtering, i.e.
```
FILTER 
  item.timestamp >= DATE_TIMESTAMP(DATE_SUBTRACT(DATE_NOW(), 30, "day")) &&
  item.timestamp <= DATE_NOW()
```
Note that I also converted the lower bound value for the filter into a numeric value again, because the timestamps in your data seem to be integers and not strings.
