### ISSUE TITLE
SORT statement on indexed field slows down query - bad optimization plan

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#7262]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query 1 (fast)__:
```
FOR v IN votes
    FILTER v.missing > null
    FILTER v.missing.image_id != null
    RETURN DATE_ISO8601(v.date)
```

__AQL explain 1__:
```
Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  9   IndexNode         4535008     - FOR v IN votes   /* hash index scan, projections: `date`, `missing` */
  5   CalculationNode   4535008       - LET #3 = (v.`missing`.`image_id` != null)   /* simple expression */   /* collections used: v : votes */
  6   FilterNode        4535008       - FILTER #3
  7   CalculationNode   4535008       - LET #5 = DATE_ISO8601(v.`date`)   /* v8 expression */   /* collections used: v : votes */
  8   ReturnNode        4535008       - RETURN #5

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields          Ranges
  9   hash   votes        false    true         52.19 %   [ `missing` ]   (v.`missing` > null)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   reduce-extraction-to-projection
```

__AQL query 2 (slow)__:
```
FOR v IN votes
    FILTER v.missing > null
    FILTER v.missing.image_id != null
    SORT v.date DESC
    RETURN DATE_ISO8601(v.date)
```

__AQL explain 2__:
```
Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
 11   IndexNode         9070034     - FOR v IN votes   /* reverse hash index scan, projections: `date`, `missing` */
  3   CalculationNode   9070034       - LET #1 = (v.`missing` > null)   /* simple expression */   /* collections used: v : votes */
  4   FilterNode        9070034       - FILTER #1
  5   CalculationNode   9070034       - LET #3 = (v.`missing`.`image_id` != null)   /* simple expression */   /* collections used: v : votes */
  6   FilterNode        9070034       - FILTER #3
  9   CalculationNode   9070034       - LET #7 = DATE_ISO8601(v.`date`)   /* v8 expression */   /* collections used: v : votes */
 10   ReturnNode        9070034       - RETURN #7

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields       Ranges
 11   hash   votes        false    false        43.85 %   [ `date` ]   *

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   use-index-for-sort
  7   remove-unnecessary-calculations-2
  8   reduce-extraction-to-projection
```

__Dataset__:
`votes` collection has around 9 million documents.

Indexes:
 * hash on `missing`, sparse (selectivity 52.19%)
 * hash on `missing` (selectivity 0.00%)
 * hash on `date` (selectivity 43.78%)
 * skiplist on `date` (selectivity 44.05%)

## Steps to reproduce

1. Run both queries

__Problem__:
Query 1 completes in 15ms. Query 2 completes in 145s. Index on `date` in query 2 has a lower selectivity than index on `missing` used in query 1.

I use the `> null` trick because `filter x != null` or `filter x` do not use any index (why ?). Using `!= null`, the query completes in 6s without the SORT statement, and is still very slow with it.

In both cases only 245 documents are returned (which is expected).

__Expected result__:
As SORT is after FILTER, I would expect FILTER in query2 to behave as FILTER in query1, and then only 245 documents would have to be sorted.

My indexes might not be the smartest for this query, but anyway I would not expect SORT to add complexity to query2.

Thanks,
Mathias

**Comment by danielhlarkin** [comment]
Hi @matcho, thanks for reporting this. Unfortunately, it's a known limitation for our current index and query optimizer implementations. Currently, when a query deals with ranges over _two different fields_, we can only use indices to sort or filter on one at a time. We cannot handle both with indices, neither with two separate indices nor with a combined index. (Note that as long as we are just dealing with a range over a single field, we can of course use an index for both filtering and sorting, but your issue relates to having ranges over multiple fields instead.) Furthermore, the query optimizer uses a cost estimation which takes selectivity into account, but for a range query it will do some further computation instead of just comparing the selectivity estimates directly. Moreover the selectivity estimate should be relatively accurate over the full collection, but may not be particularly relevant for particular ranges (e.g. if 80% of the collection has unique values for the indexed field, but the other 20% all have the same value). So it isn't always very clear from the reported selectivity estimates exactly why a given index is used. At the present time, we do not have a query mechanism to force the use of one index over the other, but we may add one in the future.

**Comment by Simran-B** [comment]
FYI, in 3.4 the following patterns are recognized just like `x > null` and can make use of a (sparse) hash (RockDB only) or skiplist index:
- `x != null`
- `NOT IS_NULL(x)`

**Comment by matcho** [comment]
Hi @danielhlarkin Thank you for this very clear explanation ! No problem then, I guess we can close this.
