### ISSUE TITLE
Missing `_from` and `_to` in WAL removal events

### ISSUE THREAD

**Issue by garryyao** [arangodb/arangodb#7315]
Hi folks, I’m building foxx service that look at the *removal events* from Write Ahead Logs, while it works very well for most of the case, I didn’t manage to find a way to tell from deletion log what’s there for `_from` and `_to`:
https://docs.arangodb.com/devel/HTTP/Replications/WALAccess.html#remove-document-2302

```
{
  "cuid": "hE0E3D7BE511D/119",
  "data": {
    "_key": "194",
    "_rev": "_XUJIbS---_"
  },
  "db": "_system",
  "tick": "397",
  "tid": "0",
  "type": 2302
}
```
Is there any way to tell which vertexes this edge were connected to, before the removal?

## My Environment

* __ArangoDB Version__:        3.3.14
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        MacOS
* __Used Package__:              Docker - official Docker library

**Comment by jsteemann** [comment]
Hi @garryyao, keeping the removal records lean is the intended behavior. 
We are intentionally not returning the full documents that are removed to save processing time and network bandwidth. 
Furthermore, the underlying WAL (that we scan for returning the list of changes) we also do not store the full data of the documents to be removed, because that would make WAL entries a lot bigger and increase memory & persistent storage space requirements (at least for the time the removes need to stay around in the WAL).

I don't think there is a sensible way to figure out the `_from` and `_to` values anyhow when WAL tailing, because the documents are effectively gone at that point and cannot be queried anymore.
The only sensible way to retrieve `_from` and `_to` (or any other values) of deleted documents will be to store the extra document data in the WAL as well. But as noted above, we are intentionally not doing this, because for the internal operations we are using the WAL for, it would just mean overhead.

**Comment by garryyao** [comment]
Hi thanks for the reply, I understand you'd keep a minimal overhead for WAL and not storing more does make sense, but I'd rather consider `_from` and `_to` on edge collection are critical keys in analogy to those foreign keys in a SQL database. We're looking for those keys because we'd like to under **how this edge removal will affect other vertexes** in the system, and take action from there.

For above reason may I please wish you store `_from`/`_to` as part of WAL data?

**Comment by graetzer** [comment]
We are not going to change the on-disk format of the WAL; I would suggest you find another solution to track deletions. 
Perhaps your application can keep its own deletion log in Kafka ?
