### ISSUE TITLE
arangorestore very slow converting from mmfiles to rocksdb

### ISSUE THREAD

**Issue by odinhaus** [arangodb/arangodb#7407]
## My Environment

* __ArangoDB Version__:        3.3.14
* __Storage Engine__:            MMFiles restoring to RocksDb
* __Deployment Mode__:      Single Server

I'm trying to convert an existing database from MMFiles to RocksDB on 3.3.14.  The database was dumped using arangodump tool.

Initially received timeout error, so included the --server.request-timeout 65000 value to make it not timeout.

arangorestore has been running for almost 4 hours now, and arangod.exe is consuming over 4 Gb of RAM, and there are still several large collections left to be imported.

Is this normal?  When converting from/to MMFiles the restore would only take a couple minutes.

Will it always be this slow when using RocksDb, or is it a one-time thing?

**Comment by odinhaus** [comment]
FYI - the restore finished after 4.5 hours

**Comment by Simran-B** [comment]
Good to hear that it finished eventually.

How much data was it, as in dump size on disk and number of documents? Are there any secondary indexes?

**Comment by jsteemann** [comment]
@odinhaus: it sounds similar to the issue reported here: https://github.com/arangodb/arangodb/issues/6379#issuecomment-423275700
The slowness in restoring with RocksDB is caused if the dump contains many document updates. When restoring such dump, there will always be an attempt to insert the document first, and if that fails (e.g. because of unique constraint violation), the existing document will be replaced with the new one from the dump.
With MMFiles, that insert-if-failed-replace procedure is not expensive at all, but with the RocksDB engine this will trigger a rollback internally, which is very expensive. We fixed this for 3.4RC3 when issue 6379 was reported first.
It hasn't been addressed in 3.3 AFAIK, as the fix for 3.4 used a new feature exclusive to 3.4.

**Comment by jsteemann** [comment]
Potential fix contained in this PR: https://github.com/arangodb/arangodb/pull/7438
I am confident the PR will fix the problem at hand, but I am not 100% sure as I have no indication yet that the dump contains the same keys a lot of times. However, the PR will not make things worse for the restore.

**Comment by odinhaus** [comment]
> Good to hear that it finished eventually.
> 
> How much data was it, as in dump size on disk and number of documents? Are there any secondary indexes?

I'm not really sure how to answer this?  There are 75 collections in dump.  Most of the .json files are pretty small (KB size), some are in the 10s to 100s of MB in size, and one is just over 1 Gb in size.

**Comment by odinhaus** [comment]
Not sure what a secondary index is?  The collections all have several custom indexes, if that’s what you mean.

Sent from my iPhone

On Nov 22, 2018, at 2:57 AM, Jan <notifications@github.com<mailto:notifications@github.com>> wrote:


@odinhaus<https://github.com/odinhaus>: it sounds similar to the issue reported here: #6379 (comment)<https://github.com/arangodb/arangodb/issues/6379#issuecomment-423275700>
The slowness in restoring with RocksDB is caused if the dump contains many document updates. When restoring such dump, there will always be an attempt to insert the document first, and if that fails (e.g. because of unique constraint violation), the existing document will be replaced with the new one from the dump.
With MMFiles, that insert-if-failed-replace procedure is not expensive at all, but with the RocksDB engine this will trigger a rollback internally, which is very expensive. We fixed this for 3.4RC3 when issue 6379 was reported first.
It hasn't been addressed in 3.3 AFAIK, as the fix for 3.4 used a new feature exclusive to 3.4.

**Comment by odinhaus** [comment]
Here is an example collection that takes a very long time to restore, which does not contain any protected data.  It's simply an edge collection.
[Edge_e4a297a0f76119a442c2595ac040673e.data.zip](https://github.com/arangodb/arangodb/files/2625814/Edge_e4a297a0f76119a442c2595ac040673e.data.zip)

**Comment by jsteemann** [comment]
Yes, "secondary indexes" are the user-defined (custom) indexes.
The collection you posted has lots of them. 

The secondary indexes will obviously slow down the restore operation a bit (because data needs to be inserted into all secondary indexes - the more indexes there are, the slower this will get).
However, I suspect that the actual problem the restore was suffering from in your case were not the secondary indexes, but that the dump contains lots of updates for the same keys, which in 3.3 is not ideal because the restore operation will try to insert first, and fall back to a replace operation in case the key already exists. However, the failing insert operation will internally trigger a rollback which is very expensive.
The PR I mentioned above should fix this in 3.3.20.

**Comment by odinhaus** [comment]
Ok, I will try 3.4 when it is in GA state

**Comment by maxkernbach** [comment]
Hi @odinhaus,

3.3.20, which contains a potential fix for the slow MMFiles to RocksDB conversion, has been released. Could you please give it a try?

**Comment by odinhaus** [comment]
Yes, i will soon.  I have found an issue/discrepancy in how queries are processed between Rocks and MMFiles databases that I need resolution to before I will run the conversion.  I am logging a new issue for it.

**Comment by maxkernbach** [comment]
Hi @odinhaus, 

did you already have a chance to test it?
FYI: version 3.3.21 is out by now.

**Comment by maxkernbach** [comment]
Hi @odinhaus,

I am closing this issue for now since we have not heard back from you in a while.
In case the conversion speed is not improved using 3.3.21+, please feel free to comment and we will reopen.

**Comment by odinhaus** [comment]
Thanks max!  No i have not tested it yet.

Sent from my iPhone

On Jan 22, 2019, at 8:23 AM, maxkernbach <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @odinhaus<https://github.com/odinhaus>,

I am closing this issue for now since we have not heard back from you in a while.
In case the conversion speed is not improved using 3.3.21+, please feel free to comment and we will reopen.
