### ISSUE TITLE
[Question] ArangoSearch "==" same as phrase() when "text_en" analyzer used?

### ISSUE THREAD

**Issue by dvstans** [arangodb/arangodb#7488]
I'm unsure whether the two following ArangoSearch queries should be equivalent (where the "something" field has been indexed using the "text_en" analyzer):

1) for i in myview search analyzer( i.field == "something", "text_en") return i

2) for i in myview search analyzer( phrase( i.field, "something"), "text_en" ) return i

In my testing, I've found cases where these two return the same result, but then I've also found cases where they do not. In the cases where they differ, the first form fails to return a match, but the second does. More specifically, the second form using "phrase" always returns what I expect, but the first form occasionally does not (depending on the value of "something"). If these are supposed to be equivalent, I can work up a test case.

**Comment by KVS85** [comment]
Hello @dvstans. Can you please provide your data where results are supposed to be equal?

Generally, `i.field == "something"` will give you only exact match results while `PHRASE(i.field, "something"), "text_en")` will match all fields where stemmed (according to `text_en` analyzer) `* something *`  was present.

**Comment by dvstans** [comment]
@KVS85 Given a document where 'field' contains: "some words: apple red bike letter." running the two queries with "red" as the value results in a match to this document for both; however, if I run the queries with "apple" as the value, only query #2 (using phrase function) matches the document.

This behavior is independent of which indexed field I use and also word order in the field. I thought perhaps my index was corrupt, but after rebuilding it this behavior persisted. I have seen this selectivity with different words as well - not just "apple". :)

**Comment by KVS85** [comment]
@dvstans Thank you for clarification. Now I see that everything works as expected here.

Actually, in `FOR i IN myview SEARCH ANALYZER( i.field == "something", "text_en") RETURN i` the `ANALYZER` function will not be applied to ` i.field == "something"` comparison. That is because comparison itself doesn't use `ANALYZER` context. In case of `PHRASE` analyzer context applies (or can be chosen as the last parameter of this function).

Therefore, since "text_en" analyzer use stemming, these queries are not identical for different words. For "apple" stemmed value is "appl" while for "red" it's still "red".

In order to make these queries similar (for a single word), you can use the following approach:
1. `FOR i IN myview SEARCH i.field == TOKENS("something", "text_en")[0] RETURN i`
2. `FOR i IN myview SEARCH PHRASE(i.field, "something", "text_en") RETURN i`

The `TOKENS` function with analyzer name as the second parameter will show you how input is processed and what actually is being searched.

Please notice also that possibility of search on indexed data using specific analyzer depends on whether this data was indexed with it. By default, only "identity" analyzer is applied.

**Comment by Simran-B** [comment]
@KVS85 Do you think your explanation is needed/useful for the documentation?
