### ISSUE TITLE
Transactions spanning multiple requests

### ISSUE THREAD

**Issue by neunhoef** [arangodb/arangodb#7630]
This is a feature request. It would be nice if ArangoDB could have an API to start, commit and abort a transaction from the client side. It should then be possible to execute reading and writing operations between start and commit in the context of the created transactions.

**Comment by neunhoef** [comment]
This has already been asked here previously: https://github.com/arangodb/arangodb/issues/3794

**Comment by Simran-B** [comment]
Other requests about transactions:
- https://github.com/arangodb/arangodb/issues/471 - Transaction handles
- https://github.com/arangodb/arangodb/issues/2019 - Distributed transactions

**Comment by thestarmaker** [comment]
This would be very useful to have as the current AQL behaviour seems a bit limiting. I have a use-case where clients request needs to update a collection transactionally by adding couple new entries and deleting few old entries in the same collection. 

AQL manual states:
>Only a single <INSERT/REMOVE/UPDATE, etc> statement per collection is allowed per AQL query, and it cannot be followed by read or write operations that access the same collection, by traversal operations, or AQL functions that can read documents 

If I get this right, I can not specify the adds and removes as part of the same AQL request and have to do two calls. If the serverside code invoking the DB fails in-between two calls there is no way to know that something has happened partially.

Is there a way to achieve this in AQL without explicit clien-side transactions?

**Comment by Simran-B** [comment]
@thestarmaker You can read multiple documents from a collection, temporarily store them in a variable with `LET`, use that information to calculate something and delete one or multiple documents from the collection. This does not violate the the rule you cited because the read occurs before the removal operation. First deleting documents and then reading documents is not allowed in a single AQL query, nor combinations of INSERT / REMOVE / UPDATE. You can use server-side JavaScript transactions, so not AQL, but also not client-side.

**Comment by thestarmaker** [comment]
@Simran-B thanks for replying, it's the INSERT and REMOVE conflict that I am having. The the bottom line is that the parent request reaching the serverside only states what the current model should look like, hence it is responsibility of the serverside to figure out what edges to delete and what to add. This causes the conflict of INSERT and REMOVE. Since INSERT and REMOVE on the same collection is not allowed within the same AQL query this is impossibly easily guarantee transactionality in this use-case.

Example: Story references few Topics via TopicReference edge. When client decides to change the Topics referenced he/she just posts the Story to the serverside enumerating the list of Topics that should be there (so there is no explicit add theese, remove those, just objective statement what should be there). This become responsibility of serverside to figure out which topics are no longer referenced, and what topics have been freshly added. Doing this update transactionally is impossible due to INSERT and REMOVE conflict.

**Comment by graetzer** [comment]
https://www.arangodb.com/docs/stable/http/transaction-stream-transaction.html
