### ISSUE TITLE
Haskell driver

### ISSUE THREAD

**Issue by janat08** [arangodb/arangodb#7778]
I see no Haskell driver.

**Comment by maxkernbach** [comment]
Hi @janat08,

currently there is no Haskell driver available for ArangoDB.

A list of all official and community drivers can be found in the [Drivers Documentation](https://docs.arangodb.com/3.4/Drivers/index.html).

**Comment by janat08** [comment]
Can it be made?

**Comment by dothebart** [comment]
Since ArangoDB mainly uses HTTP to communicate, it should not be to complicated to implement for s.b. familliar with Haskell. If there are tools to generate stubs from OpenAPI/Swagger, it should get you started. 

However, we don't have any haskell expertise in house. So, if you want to take the task, its going to happen ;-) - else not any time soon.

 Feel free to join us in Slack, and start a discussion in #driverdev  if you need more pointers into which directions to move.

**Comment by vinaypyati** [comment]
Hi @janat08,

Hope the above comments answer your question. I am going ahead and closing this issue. Feel free to reopen the issue for further questions or discussions. 

Thanks!
