### ISSUE TITLE
Arango cluster aspects

### ISSUE THREAD

**Issue by stelios6** [arangodb/arangodb#8060]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:    ArangoDB Starter
* __Infrastructure__:                own 
* __Operating System__:         Windows 2019
* __Total RAM in your machine__:       32Gb.
* __Disks in use__:                  SSD
* __Used Package__:               other -->

We have some questions in relation to how the Arango cluster works since we are confused.

First we have installed the standalone version of Arango and we had 10GB of data in 10 different collections.

Then we wanted to get experiment with Arango cluster and we have followed the instructions and have setup 3 different machines/nodes.

The cluster started successfully with 3 agents, 3 coordinators and 3 db servers.

Our questions:

1.  When we go to the dbserver folder where the data are saved in the rockdb we found out that on machine 1 the size was 1GB, on machine 2 the size was 700MB and on machine 3 the size was 8GB. Question:  The data are not distributed evenly to all machines? Is there an option to have the full data set stored in each machine?

2. We have stopped machine 2 and the cluster was working ok. Question: Have we lost any data since machine 2 is down?

3. We have stopped machine 2 and machine 1 and the cluster could not work. So the question is. Is there an option to continue to work with machine 3 until machine 1 and machine 3 are up and running? of course that could make sense if the entire data set are stored in each machine.

4. We have tried to setup a cluster of 4 Nodes and we could not. It needs to be an odd number. What is the reason behind it? If we setup a cluster with 5 nodes and 2 or 3 of them are down for some reason, will the cluster continue to work with the rest 2 nodes even temporarily? What is the minimum number of nodes that the cluster is needed to be operational?

We would appreciate the answers above to understand the dynamics of Arango cluster and how reliable will be in a real environment.

**Comment by OmarAyo** [comment]
Hi @stelios6 

Thanks for using ArangoDB, please see answers below:

 **A1** I think that your collections are _not_ sharded . In order to distribute the data evenly, you need to have some number of shards that is according to the UI hintbox equal to  `DBservers squared`. Please note, the number of shards has to be set at the time of collections creation. A full data set is stored in each DBserver when the ReplicationFactor equals the amount of DBservers. If you plan to store the complete data set on each node, you might also want to consider using an Active Failover deployment (see [here](https://docs.arangodb.com/3.4/Manual/Architecture/DeploymentModes/ActiveFailover/)).

**A2** It depends on the value they you have set for the ReplicationFactor (RF). If RF is 1, all data can be lost if e.g. the disk fails on one of the DBServers. If the node goes down, but comes back up with all it's data, it should be okay. That's why we always recommend RF>=2 for data safety. So if we have 3 servers and 3 shards, and one disk fails, we lose the shard that was on that disk. We lose 1 shard that contains 1/3 of the collection - we still have two other shards that contain the same 1/3 collection. If you had 3 shards with RF2, then there would be a backup on one of the other servers. If we have RF=2 though and node crashes, there is no data loss - we have each shard on 2 nodes, one leader and one follower. When the leader or follower shard is lost, there is still the same shard on another dbserver. Also, once there is only 1 shard available (since 1 is lost), the cluster distributes this shard to another node again so RF=2 is restored

**A3** The ArangoDB Cluster is based on a specific consensus algorithm called "RAFT". Typical consensus algorithms make progress when any majority of their servers is available. An ArangoDB Cluster consists of a number of ArangoDB instances which talk to each other over the network. Inside the ArangoDB Cluster there are 3 distinct roles:
- Agents
- Coordinators
- DBservers 

The most important part of the Cluster is the Agency (one or multiple Agents form the Agency). In your case you stopped 2 (out of 3) nodes, therefore the Cluster cannot survive with only 1 node (that is carrying only 1 agent). So the only solution is to bring up again at least 1 node to have again an up and running Cluster. See *A4* for more examples 

**A4** The odd number is only referring to the number of Agents (that form the Agency) and this is because the consensus protocol (RAFT algorithm), basically so you can't end up with a tie. Any odd number can be written as `n = 2*k + 1`, which means that you can distinguish between a strict majority of `>= k+1` and a minority of `<= k`. With an even number `n = 2*k` you can get a k-k tie. May you share the command used to start the 4th node ?

Regarding the example about having a Cluster made of 5 nodes. There could be multiple scenarios, for e.g.:
1) 5 nodes made of: 5 Agents 5 DBservers 5 Coordinators
2) 5 nodes mad of: 3 Agents 5DBservers 5 Coordinator

The general rule is that a cluster can survive with `n = k + 1` for cluster that were initially configured with `n = 2k + 1` where `n` is the number of nodes *that are carrying Agents*. So in the first case the the cluster is up and running with 2 nodes down and in the second case you should ensure that at least 2 nodes that are carrying agents are still up and running  

I invite you to have a look at the following links:
- https://docs.arangodb.com/3.4/Manual/Administration/Cluster/
- https://docs.arangodb.com/3.4/Manual/Architecture/SingleInstanceVsCluster.html
- https://docs.arangodb.com/3.4/Manual/Architecture/DeploymentModes/Cluster/Architecture.html

Best,

**Comment by stelios6** [comment]
Hello Omar,

Thanks a lot for the reply. This is very helpful for us to understand better how the clustering works. We really appreciate it since this info is not clear after reading the user manual of Arango.

1. This is clear. We will try to create shards for our collections
2. ok this is understood as well. So basically if we have 3 shards with 3 machines then even if we lose 2 machines we will still have the full data set but the cluster will not work.
3. ok understood
4. ok this is clear as well

If we have any further questions we will post them here.

**Comment by OmarAyo** [comment]
Hi @stelios6 

Regarding point **2**:

No, but if you change "3 shards" with "RF3" and 3 machines, then yes and your statement will look like:
>  if we have RF3 with 3 machines then even if we lose 2 machines we will still have the full data set but the cluster will not work.

RF controls redundancy and thus robustness to failure. In other words, if you have RFk, you can withstand up to k-1 failures without data loss. Shard count just controls load balancing, essentially.

Best,

**Comment by stelios6** [comment]
thxs Omar for the explanation.

We are trying to add two more nodes to the cluster with the following command 

arangodb.exe --starter.data-dir=./dbcluster --starter.address=192.168.1.2 --cluster.start-agent true --starter.join 215.123.123.123 (this is not the real ip) 

but we get the following error. 
Cannot start because of error from master component=arangodb

I have seen a similar error in another post but I have not manage to apply the solution. So basically how we add two new nodes to the existing cluster? we have 3 agents, 3 coordinators and 3 dbservers and we want to have 5-5-5. of course the idea is to create 5 shards as well.

Btw is there another way to have replication with 3 machines and even if we loose the 2 machines to have arango work and not loose the data? It is costly to have 5 machines and be able to loose 2 machines in order for the cluster to work.

**Comment by stelios6** [comment]
Omar in relation to the above, up to now we have manage to setup a 3 machine cluster with internal ip addresses. We have tried to setup a cluster using external (public) ip addresses and the cluster can not start. The communication(PING,TELNET) between the machines (vms) work fine.

We have used the command --starter.address ipaddress and --cluster.advertised-endpoint tcp://x.x.x.x:8528 without any luck. Is there a trick behind it?

**Comment by stelios6** [comment]
any news on the above?

**Comment by OmarAyo** [comment]
Hi @stelios6,

You should be able to set up a 3 node cluster using the following commands:
```
arangodb --starter.data-dir=<path-to-your-datadir-node1> --starter.join IP1:portA,IP2:portA,IP3:portA --starter.port portA


arangodb --starter.data-dir=<path-to-your-datadir-node2> --starter.join IP1:portA,IP2:portA,IP3:portA  --starter.port portB


arangodb --starter.data-dir=<path-to-your-datadir-node3> --starter.join IP1:portA,IP2:portA,IP3:portA  --starter.port portC
```
Please make sure that the ports are at least separated by the value +10 from each one (e.g. portA=5500, portB=5510, portC=5520).

I will send another message regarding:
- how to add more nodes to an already existing ArangoDB Cluster
- and how to manage the agency size 

Best,

**Comment by stelios6** [comment]
Hi Omar,

Thanks for the info. Are you assuming that the above will run on the same machine? Basically I have three vms in different geographic location with 3 external IP addresses. Should I specify the --starter.address=PublicAddress  as well?

**Comment by OmarAyo** [comment]
Hi @stelios6,

The option `--starter.address` will use the address under which this server is reachable from the outside.
You should be able to set up a Cluster using 3 diffrent machines even if not specifying that option. 

Since you are using the Starter, that is an ArangoDB tool, you may need to have a look at the following page:
- https://docs.arangodb.com/3.4/Manual/Programs/Starter/Options.html

Best,

**Comment by stelios6** [comment]
Thx Omar. I have read this page and have tried numerous combinations without any luck. If i do not specify the --starter.address=publicaddress then then other nodes can not communicate with each other.

If I use your commands above shall I put the IP1,IP2 and IP3 as 192.168.1.2 etc or publicaddresses?

**Comment by OmarAyo** [comment]
Okay, I will discuss internally about the `--starter.address`option and get back to you

Regarding IP1,IP2,IP3  they are referring to your machine IP so you should pass your all three IPs machines. 

Let's suppose you have the following IPs:
- machineA: 192.168.1.1
- machineB: 192.168.1.2
- machineC: 192.168.1.3

then your command should look like:
```
arangodb --starter.data-dir=<path-to-your-datadir-node1> --starter.join 192.168.1.1:portA,192.168.1.2:portA,192.168.1.3:portA --starter.port portA --starter.address=publicaddress

arangodb --starter.data-dir=<path-to-your-datadir-node2> --starter.join 192.168.1.1:portA,192.168.1.2:portA,192.168.1.3:portA  --starter.port portB --starter.address=publicaddress

arangodb --starter.data-dir=<path-to-your-datadir-node3> --starter.join 192.168.1.1:portA,192.168.1.2:portA,192.168.1.3:portA  --starter.port portC --starter.address=publicaddress
```

Best,

**Comment by stelios6** [comment]
I will try it but the above command will not work since the --starter.join will try to find the ip 192.168.1.1 but this the internal ip address of another machine somewhere else. What I have tried is --starter.join publicaddress. At a point it worked but it lasted for few seconds and couldn't manage to replicate it.

**Comment by OmarAyo** [comment]
Hi @stelios6 

I would like to focus on the fact that you would like to set up a 3 node cluster, where each node is in different geolocation, _this is not what the cluster is supposed to be used as_. The cluster setup usually should be in the same network. I fear that your approach will fail even if the servers find each other.

Using PublicAddresses will allow the Starter to detect the other nodes (that are on different networks), but you will not have a stable cluster in the time as well as you will not have query performance in an acceptable timeframe

ArangoDB offers a deployment called Datacenter2Datacenter (DC2DC) - you can have a look here:
- https://docs.arangodb.com/3.4/Manual/Deployment/DC2DC/
- https://docs.arangodb.com/3.4/Manual/Administration/DC2DC/

With a DC2DC you will have basically 2 Clusters that can be in different geolocation. The first Cluster will be the LeaderDC and the second Cluster will be the ReplicaDC (the replication among the cluster is asynchronous)  - **Please note, this feature is only available in the Enterprise Edition**

Another thing to keep in mind is regarding _shards_ - it's not possible to store data in shards in different geo location, this is not supported as well. You can only define the number of shards and the cluster will do all the rest. 

So two important points to keep in mind:
- the cluster is intended to have short pings
- the cluster doesn't support to define where your shards are going to live

I hope this helps,

Best,

**Comment by stelios6** [comment]
Thanks a lot Omar for the info. Yes this definitely helps.

Of course having two clusters (of at least 3 machines each) into two different geolocations is very expensive. Is there another less expensive solution like with other software solutions? For example we have a single Arango instance in one location and a replication of the data in another location for redundancy purposes? The replication can be asynchronous as well.

**Comment by stelios6** [comment]
Any options for the above enquiry?

**Comment by OmarAyo** [comment]
Hi @stelios6 

In your example, seems that you are referring to a Master-Slave deployment and unfortunatelly, this deployment is not meant to be deployed over different networks and in different geolocation. We cannot ensure performance and stability. You may be able to set up this deployment, but probably it will crash after some time and this is not what you want thought.

The only deployment that is meant to be deployed over different geolocation is, as already mentioned, the DC2DC (Datacenter to Datacenter). You can opt for using VMs instead of phisical machines, it could be probably a cheaper solution 

Let me know if any other clarification is required from our side 

Best,

**Comment by stelios6** [comment]
ok thx Omar. I will close the ticket for now.
