### ISSUE TITLE
Return query ID quickly

### ISSUE THREAD

**Issue by rogierschouten** [arangodb/arangodb#8127]
When I start a query, I would like to know its ID as soon as possible, to be able to kill it if needed.

```javascript
        const cursor = await db.query(query); // this takes long, should return instantly while query is being started
        const id = cursor.queryId; // THIS IS WHAT I WOULD LIKE TO HAVE
        const records = await cursor.all(); // if this takes long, I can kill the query
```

However, one snag is that getting the cursor already takes long, I suspect the query is executed entirely before I get the cursor back.   How about returning a cursor object immediately and delaying getting the first record from the cursor until the query has run?

Note that this may be a temporary workaround for #6146 .

**Comment by maxkernbach** [comment]
Hi @rogierschouten,

Sorry for the late reply.

As reported in #6146 the (server-side) query timeout parameter `maxRuntime` is implemented.

In addition, a `cursor.kill` method has been added for arangojs.

From the [Changelog](https://github.com/arangodb/arangojs/blob/v6.12.0/CHANGELOG.md#6120---2019-10-16):

> * Added cursor.kill method
> 
> Cursors that have not yet been fully depleted can now be killed using the cursor.kill method. Note that this method has no effect if the cursor is already depleted.

An example of this method can be found in the [documentation](https://github.com/arangodb/arangojs/blob/v6.12.0/docs/Drivers/JS/Reference/Cursor.md#cursorkill). This method will always work when one batch is fetched and there is more than one result batch in total. However, in case that the batch size is smaller than the result set this method will no-op because there is nothing to kill.

In case the batch size is smaller then the result set and you would like to kill the cursor with this method, the only solution would be to set a lower batch size for your AQL query.

**Comment by maxkernbach** [comment]
Hi @rogierschouten,

Did you have a chance to read my previous message?
Was it helpful?

**Comment by rogierschouten** [comment]
Hi @maxkernbach, maybe I don't understand you properly but I think your answer does not solve the issue.  Because as long as I don't get the cursor back, I cannot call cursor.kill.  And it already takes  long to get the cursor back.  Is there anything changed in this respect?

The maxRuntime parameter is certainly a welcome feature by the way, but it is for a different purpose.

**Comment by dothebart** [comment]
Hi, 
there are several ways to this. 
- You may use [streaming cursors](https://www.arangodb.com/docs/stable/http/aql-query-cursor-accessing-cursors.html) by setting `stream` to `true` - however this has implications on longer accessing the collections. 
- However, you should rather use [`explain`](https://www.arangodb.com/docs/stable/aql/execution-and-performance-explaining-queries.html) to inspect what the query is actually doing, to find out why its that slow. 
- if that doesn't already ring a bell, use [`profile`](https://www.arangodb.com/docs/stable/aql/execution-and-performance-explaining-queries.html#profiling-queries) to see where its actually taking long. 

Closing with the availablitiy of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/).
