### ISSUE TITLE
Make SSE4.2 optional for ArangoDB 3.4

### ISSUE THREAD

**Issue by kt215** [arangodb/arangodb#8135]
According to this issue https://github.com/arangodb/arangodb/issues/7705 ArangoDB 3.4 REQUIRES the CPU to support SEE4.2

This prevents ArangoDB 3.4+ from running on older hardware.

Can you please make this configurable (without recompilation) so SSE4.2 can be made optional instead?

**Comment by dothebart** [comment]
Hi, 
the machine in the other bug seemed to not have the CPUID feature supported, which was introduced with pentium 90. So most probably this was done to hide systems vulnearable to meltdown/spectre. 
If the cpu is detecteable, (at least on linux) the binaries should detect these, and turn off the optimizations. 

Since SSE 4.2 was introduced a decade ago, please share some insights which exact cpu you intend to run arangodb on - if this detection doesn't work. 
However, since databases are about performance, I'm sorry to say that we won't provide unoptimized versions for elderly hardware. Please note that all the source and the build instructions are out there, so you're free to compile your own binaries matching the features of your Architecture.

**Comment by kt215** [comment]
I have an old test server (Ubuntu Linux 16.04) with a CPU `Quad-Core AMD Opteron Processor 2378` that does not support SSE 4.2
```
the binaries should detect these, and turn off the optimizations
```
Your documentation on the download page says

```
The processor(s) must support the SSE 4.2 instruction set (Intel Nehalem or better, AMD Bulldozer or better, etc.).
```
I did not try to upgrade to 3.4 yet, because the linked issue says **REQUIRES** and your documentation says **MUST**. Do you mean that I can try to upgrade and the binaries will automatically turn off SSE 4.2 optimization, and the server with work anyway? :-)

**Comment by dothebart** [comment]
Maybe try downloading the tarball first, and try whether the arangosh in it does work, and then the arangod with `--server.rest-server false` and a different database directory.

**Comment by kt215** [comment]
I couldn't get the tarball to work (`--server.rest-server false` not recognized).

I installed on a VM without previous ArangoDB installation using `apt-get` on Ubuntu 18.04.2, got this error:
```
Setting up arangodb3 (3.4.2.1-1) ...
Illegal instruction (core dumped)
Illegal instruction (core dumped)
FATAL ERROR: EXIT_CODE_RESOLVING_FAILED for code 132 - could not resolve exit code 132
dpkg: error processing package arangodb3 (--configure):
 installed arangodb3 package post-installation script subprocess returned error exit status 132
```
Is this related to no SSE 4.2 support?

**Comment by dothebart** [comment]
Yes, most probably. 
However, as previously mentioned, the source is availabe, and you may be easily possible to create your own packages, or replace the binaries from packages you installed. 
Please have an understand that we can't build packages for any possible targets, and that we define the ~10 years old nehalem architecture as least common denominator for our efforts to provide ready made community packages. 
Since a workaround is available for you (compile your own), I will close this as I already proposed in advance: won't fix.

You should be able to get working binaries by checking out the corrosponding git-tag (i.e. `v3.4.2`) and invoke `./scripts/build-deb.sh` for your purposes.

If you need more help, let me know.
