### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by DONXAKer** [arangodb/arangodb#8163]
Version: 3.3.22
Storage: RocksDB
Deployment Mode: Active Failover(3 db server and 3 agents)
Deployment Strategy: Manual Start
Operating System: Ubuntu 16.04
Total RAM in your machine: 32Gb

After upgrade from 3.3.17 to 3.3.22 arangod become fall down with out of memory. In graph we see this:
![image](https://user-images.githubusercontent.com/5461979/52790450-a2ad0400-3077-11e9-99d3-26b43aa42e21.png)

Params:
```
systemctl show --property DefaultTasksMax
DefaultTasksMax=18446744073709551615

fs.file-max = 65535
vm.swappiness = 1
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5
vm.max_map_count = 2048000
cat /sys/kernel/mm/transparent_hugepage/enabled
always madvise [never]
cat /sys/kernel/mm/transparent_hugepage/defrag
always madvise [never]
cat /proc/sys/vm/overcommit_memory
2
cat /proc/sys/vm/overcommit_ratio
87
echo $GLIBCXX_FORCE_NEW
1
```

**Comment by jsteemann** [comment]
@DONXAKer : can you set `vm.overcommit_memory` from `2` to a value of `0` or `1`?
We found that an overcommit_memory setting of 2 does not play nice with the memory allocator we use (jemalloc).
We adjusted our docs a while ago regarding this:
https://docs.arangodb.com/3.3/Manual/Administration/Configuration/OperatingSystem.html#over-commit-memory

Additionally, if that does not help too much, there is also a new option for limiting the total size of all RocksDB write buffers which can be set to some sensible value: `--rocksdb.total-write-buffer-size`.
That option has been introduced between 3.3.17 an 3.3.22, so in order to keep things downwards-compatible with the 3.3 line, it has a value of 0, which means _unbounded_. It can be sensible to cap the total write buffer size to some amount of memory. 
The docs for this option are here: https://docs.arangodb.com/3.3/Manual/Administration/Configuration/RocksDB.html#write-buffers

**Comment by DONXAKer** [comment]
@jsteemann  For accept first parameter id need restart arangod proc? Whitch value better 0 or 1 for arango?

**Comment by DONXAKer** [comment]
@jsteemann For example how many we can set up for rocksdb.total-write-buffer-size. Is there some recommendation?

**Comment by jsteemann** [comment]
For `vm.overcommit_memory` the Linux kernel default is 0, so just using that should be ok.
For `--rocksdb.total-write-buffer-size` a good setting depends a bit on the workload. The more writes there are in relation to reads, the bigger this value can be set.

**Comment by DONXAKer** [comment]
Thanks. After setting vm.overcommit_memory 0 memory leak stopped. Now it's good. Why after upgrade from 3.3.17 to 3.3.22 this problems start with value 2?

**Comment by jsteemann** [comment]
I think the problems didn't start after the upgrade.
The problem with `vm.overcommit_memory=2` was always there, even in previous versions.
