### ISSUE TITLE
How to use incremental variable?

### ISSUE THREAD

**Issue by Maxmaxmaximus3** [arangodb/arangodb#8175]
```
LET q = 0

FOR user IN Users
  UPDATE user WITH {
    order: q++
  } IN Users
```

i have error: AQL: syntax error, unexpected } near '} IN Order' at position 1:76 (while parsing)

or this:

```
LET q = 0

FOR user IN Users
  UPDATE user WITH {
    order: (q = q + 1)
  } IN Users
```

or this:

```
LET q = 0

FOR user IN Users
  q = q + 1

  UPDATE user WITH {
    order: q
  } IN Users
```

or this:

```
FOR user, index IN Users
  UPDATE user WITH {
    order: index
  } IN Users
```

???

**Comment by Simran-B** [comment]
This is a documented limitation of AQL:

> Variables are immutable in AQL, which means they can not be re-assigned

https://docs.arangodb.com/3.4/AQL/Operations/Let.html

What you could do however would be something like this:

```
LET keys = (FOR u IN Users RETURN u._key)
FOR i IN 0..LENGTH(keys)-1
    UPDATE keys[i] WITH { order: i } IN Users
```

**Comment by Maxmaxmaximus3** [comment]
@Simran-B Do not you think that such a basic operation should be present in the syntax?

**Comment by Simran-B** [comment]
AQL is not a programming language but a query language. It is kept side-effect free on purpose, because it allows for much more optimizations. In many cases, enumerating should not be done on the server-side at all (#5359) or there are other possibilities such as using a different key generator. Your particular example would benefit from mutable variables but adding support for this would mean to allow it also in other places and it's likely to result in a performance hit or increased memory usage, at least for some queries.
