### ISSUE TITLE
Collect on _id returns null

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#8196]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               -
* __Infrastructure__:               own
* __Operating System__:        Debian 8
* __Total RAM in your machine__:        8GB
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__AQL query__:
```
LET vCollectId = FIRST(FOR m IN vCollect SORT m.tsStart DESC LIMIT 1 RETURN m._id)
FOR c IN vCounters
    FILTER c.vCollectId != vCollectId
    COLLECT id = c._id, key = c._key WITH COUNT INTO cnt
    FILTER cnt > 1
    RETURN {id, key, cnt, vCollectId}
```

__Dataset__:
I have arangodump of both collections in question. However, arangorestore fails to restore them. I can forward these to you.

__Problem__:
The query in question returns
```
[
  {
    "id": null,
    "key": null,
    "cnt": 112,
    "vCollectId": "vCollect/623599194"
  }
]
```
We have no more information about how the database got into the state. We tried to test the issue on different versions of the database. However, upgrading failed and corrupted our data. And as mentioned above, arangorestore fails to restore data.

vCounters collection was not reported as corrupted at the time of testing.
The query below did not return any data:
```
FOR c IN vCounters
  FILTER c._id == null
  RETURN c
```

**Comment by jsteemann** [comment]
@gurisko : the first thing I would like to check is why arangorestore fails to restore the data. For this it would help if you could somehow forward the data to us, e.g. by sending it via email to `hackers@arangodb.com` and mentioning this Github issue.

That should at least shed some light on the restore problem. I cannot predict right now if that will also help figure out any issues with the COLLECT.

It may actually help to get the binary database files to investigate this issue, because that will allow an investigation on the binary level (arangodump will create a JSON representation of the data, so it is already transforming the original database state). I will be happy with both the dump or the binary files for further investigation, and leave it up to you to determine if you can share any of them and which one is more convenient to share.
Thanks!

**Comment by gurisko** [comment]
@jsteemann I sent you our JSON dump. I will keep trying to reproduce the issue, but for now, I have no clue what triggered it.

**Comment by dothebart** [comment]
Since 3.3 is EOLed now closing this as outdated. 

[ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available now.
