### ISSUE TITLE
AQL:cluster internal HTTP connection broken

### ISSUE THREAD

**Issue by ZicolasJac** [arangodb/arangodb#8217]
## My Environment

* __ArangoDB Version__:     3.3.16
* __Storage Engine__:            RocksDB
* __Deployment Mode__:      Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:         cluster setup details
* __Infrastructure__:         own 
* __Operating System__:        redhat7.2
* __Total RAM in your machine__:       600G
* __Disks in use__:        800G
* __Used Package__:           RedHat .rpm

## Component, Query & Data

__Affected feature__: AQL query using web interface

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:800G

__Replication Factor & Number of Shards (Cluster only)__:
1&1

__Problem__:
AQL:cluster internal HTTP connection broken

**Comment by ZicolasJac** [comment]
Do you have any help?I'm really looking forward to having an expert to help solve this problem

**Comment by dothebart** [comment]
Hi, 
this usually happenes if one of the backends fail to communicate, due to overload, memory shortage, resource shortage, etc. 

Please note that you should use the latest version of a release series available - which is 3.3.22 for you. 
Above this 3.4 contains many improvements of resource usage in the cluster, 

Please note that we changed the kernel memory settings recommendations, see https://stackoverflow.com/questions/40401515/methods-to-decrease-memory-consumption-in-arangodb for details.

You also should have a look [at explain](https://docs.arangodb.com/3.4/AQL/ExecutionAndPerformance/ExplainingQueries.html), to find out how many Coordinator <-> DBServer hops you have.

**Comment by maxkernbach** [comment]
Hi @ZicolasJac,

could you please share a status update on this issue?
Does this problem still persist? Did the latest reply help you?

**Comment by maxkernbach** [comment]
@ZicolasJac 

I am closing this issue for now since we have not heard back from you in a while.
In case you are still facing this problem, please reply and we will reopen it.
