### ISSUE TITLE
Arangodb Failover mode is not working as expected

### ISSUE THREAD

**Issue by RohanKumbhar1** [arangodb/arangodb#8389]
Hi Team,

I'm using arangodb version as mentioned below
`ArangoDB 3.3.12 [linux] 64bit, using jemalloc, build tags/v3.3.12-0-g225095d, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2g  1 Mar 2016`

And running arangodb starter.mode=failover with 3 nodes instances.
But when i starting arangodb  with this mode , it keeps on accumulating WAL logs on Leader node in path journals/archive folder which is almost 10X times the actual data size.

Also when the leader stopped and follower which becomes leader doesnt contains any data :(

Could you please provide the fix for this?

Thanks,
Rohan

**Comment by Simran-B** [comment]
What storage engine do you have in use?

**Comment by RohanKumbhar1** [comment]
> What storage engine do you have in use?

Its rocksdb

**Comment by RohanKumbhar1** [comment]
Hi Team,

Is there any update on this? 
Could you please respond on this?

Thanks,
ROhan

**Comment by maxkernbach** [comment]
Hi @RohanKumbhar1,

first of all sorry for the late reply. How are things going, does the problem still persist? Is it reproducible in your environment?

If that is the case, could you please share the following information so that we can investigate this issue?

- missing information from the info table, e.g. OS, Used Package etc. 
- the exact starter (`arangodb`) commands on each node to start the Active Failover instance
- log files of dbserver + agent + coordinator from each node (located in the starter directory specified with `--starter.data-dir`)

**Comment by maxkernbach** [comment]
@RohanKumbhar1 

I am closing this issue since we have not heard back from you in a while.
In case you are still facing this problem, please share the requested information and we would be glad to look into it.

Please note that with 3.3.12 you are using a quite old version. The latest version available of the 3.3.x series is 3.3.23 and includes many improvements + fixes.
