### ISSUE TITLE
Add within_bounds function to AQL

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#846]
I do a lot of work with maps and would like to propose a new geo function for AQL so I can easily gather vertices within the current map bounds. 

Basically being able to use the information that comes back from Leaflet's [map.getBounds](http://leafletjs.com/reference.html#map-getbounds) when querying Arango would be amazing. Google maps has [something similar](https://developers.google.com/maps/documentation/javascript/reference#LatLngBounds).
Maybe a signature like this:

```
WITHIN_BOUNDS(collection, {sw: {lat: 45.41, lng: -75.71}, ne: {lat: 45.42, lng: -75.69}})
```

**Comment by yiqing** [comment]
i come from @sleepycat 's blog , an using the php client lib .
find that 'lat' or 'lng' need a double value , but in php the value will be trancated when it is too long. so want to know if these two values can be a type of String !

**Comment by jsteemann** [comment]
@yiqing : on the server side, `lat` and `lng` need to be doubles.
Where exactly is the value truncated in PHP? Could you provide an example that shows it?

**Comment by yiqing** [comment]
@jsteemann sorry for my late replying 
in php
~~~php
  $storeGeoCollection = $collectionHandler->get($collectionId);

        $cityDoc = new Document();
        $cityDoc->name = 'Ottawa';
        $cityDoc->lat = 45.4215296;
        $cityDoc->lng =  -75.69719309999999;

        $documentHandler = $arangodb->getDocumentHandler() ;
        $documentHandler->save($storeGeoCollection->getId(),$cityDoc);

~~~ 
and the value -75.69719309999999 saved in db is become :-75.6971931.
don't know where the truncating occurring , db or php? .  (i use the official php client driver)

**Comment by jsteemann** [comment]
@yiqing : truncation may indeed occur.

When I try the above snippet and execute it in PHP, it is PHP that actually truncates the floating-point value. Here's an example:
```php
<?php

$cityDoc = new StdClass();
$cityDoc->name = 'Ottawa';
$cityDoc->lat = 45.4215296;
$cityDoc->lng =  -75.69719309999999;

var_dump($cityDoc);
```
Executing this script produces:
```
class stdClass#1 (3) {
  public $name =>
  string(6) "Ottawa"
  public $lat =>
  double(45.4215296)
  public $lng =>
  double(-75.6971931)
}
```
with the floating-point value being truncated for display reasons already.

When the PHP driver sends the value to the db, it will use PHP's `json_encode()` to serialize the value before sending. Serializing the object with `json_encode()` produces the same truncated result:
```php
<?php

$cityDoc = new StdClass();
$cityDoc->name = 'Ottawa';
$cityDoc->lat = 45.4215296;
$cityDoc->lng =  -75.69719309999999;

echo json_encode($cityDoc) . PHP_EOL;
```

```
{"name":"Ottawa","lat":45.4215296,"lng":-75.6971931}
```

The result may vary with the PHP version. Mine was 5.5.12-2ubuntu4.1.

Increasing PHP's `precision` configuration setting from the default value of `14` to something higher will increase the precision when displaying and serializing floating-point values in PHP:
```php
<?php

ini_set("precision", 25); // more precision

$cityDoc = new StdClass();
$cityDoc->name = 'Ottawa';
$cityDoc->lat = 45.4215296;
$cityDoc->lng =  -75.69719309999999;

var_dump($cityDoc);
```
Result:
```
class stdClass#1 (3) {
  public $name =>
  string(6) "Ottawa"
  public $lat =>
  double(45.42152959999999950468919)
  public $lng =>
  double(-75.69719309999999268256943)
}
```
So now the value won't get truncated on the PHP side, but it is still inaccurate and not the value put into the script. This is because the floating-point representation that PHP uses cannot safely represent all possible values.

Actually this is by design. An IEEE754 binary double precision floating-point value can represent a huge range of values with only 8 bytes. The drawback is that it cannot store every possible value in a lossless format, but has to use approximations for some, which leads to value truncation and other seemingly odd behavior, e.g.:
```php
<?php

$a = 0.1;
$b = 0.2;
$c = 0.3;

var_dump($a, $b, $c);
var_dump(($a + $b) === $c);
```
The expected result of the script would be `0.1`, `0.2`, `0.3` for the first three values, and the `true` for the comparison. The comparison result however is `false`, so `0.1 + 0.2 !== 0.3`, regardless of what you set `precision` to. This is again due to IEEE754 values representing some values only approximately.

So the result is that you cannot rely on IEEE754 floating-point values to represent every value exactly.
