### ISSUE TITLE
AQL Graph traversal returns null in array 

### ISSUE THREAD

**Issue by RHSman** [arangodb/arangodb#8488]
## My Environment

* __ArangoDB Version__:        3.2.10
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start in Docker 
* __Configuration__:               
* __Infrastructure__:               AWS | Mac
* __Operating System__:        MacOS 10.13.4 
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:               Docker - official Docker library

## Component, Query & Data

__Affected feature__: AQL, Graph

__AQL query (if applicable)__:
FOR vertex, edge IN 0..2 OUTBOUND "skills/APPLICATION_HIERARCHY" skill_skill return edge

__AQL explain (if applicable)__:
With no values present:

Query string:
 FOR vertex, edge IN 0..2 OUTBOUND "skills/APPLICATION_HIERARCHY" skill_skill return edge

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  2   TraversalNode      1     - FOR vertex  /* vertex */, edge  /* edge */ IN 0..2  /* min..maxPathDepth */ OUTBOUND 'skills/APPLICATION_HIERARCHY' /* startnode */  skill_skill
  3   ReturnNode         1     - RETURN edge

Indexes used:
 By   Type   Collection    Unique   Sparse   Selectivity   Fields               Ranges
  2   edge   skill_skill   false    false       100.00 %   [ `_from`, `_to` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections   Options                                   Filter conditions
  2   0..2                         skill_skill        uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 none

With data:

Query string:
 FOR vertex, edge IN 0..2 OUTBOUND "skills/MM" graph 'skills_hierarchy' return edge

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  2   TraversalNode      1     - FOR vertex  /* vertex */, edge  /* edge */ IN 0..2  /* min..maxPathDepth */ OUTBOUND 'skills/MM' /* startnode */  GRAPH 'skills_hierarchy'
  3   ReturnNode         1     - RETURN edge

Indexes used:
 By   Type   Collection    Unique   Sparse   Selectivity   Fields               Ranges
  2   edge   skill_skill   false    false        61.70 %   [ `_from`, `_to` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections   Options                                   Filter conditions
  2   0..2    skills               skill_skill        uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 none

__Dataset__:
https://gist.github.com/RHSman/07ed64ded3c4d7a02d955668224767e4

https://gist.github.com/RHSman/a922c49c4ddece024e518ba3fe33abf3

__Size of your Dataset on disk__:
Little

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Create 1 document collection (skills), create edge collection (skill_skill)
2. Create graph (skills_hierarchy) 
3. run AQL: FOR vertex, edge IN 0..1 OUTBOUND "skills/MM" graph 'skills_hierarchy' return edge._to
4. currently if running depth greater than 1 it will just run and run

Output:
[
  null,
  "skill_skill/13670969",
  "skill_skill/13671707",
  "skill_skill/13671407",
  "skill_skill/13671239",
  "skill_skill/13671155",
  "skill_skill/13671017",
  "skill_skill/13671005",
  "skill_skill/13670987"
]

__Problem__:
inserts a null value into an array which then seems to break the logging system and lengths of arrays are not correct and its unreliable

__Expected result__: AQL result should not return null results

**Comment by Simran-B** [comment]
Looks like the intended behavior to me... Let me explain:

In a minimal graph `A --y--> B --z--> C`, you may traverse from `A` in outbound direction with a variable depth of min=1 and max=2. If you return the emitted vertex, then the output would be `B` and `C`: The traversal starts at `A`, follows the edge to `B` and emits it, continues to `C` and emits it. If you return the emitted edge instead, then you would get `y` and `z`.

If you want to return the vertices including the start vertex `A`, then you can set the min depth=0, so that it gets emitted as first vertex. The result would then be `A`, `B` and `C`. If you return the edges instead however, what you get is `null`, `y` and `z`. The reason should be obvious: no edge leading to the start vertex `A` is followed which could be returned. While there might be edges connected to `A` in your graph, but they are not traversed if `A` is the starting point. Returning a random edge would make no sense. Because there is no value, a `null` value is given.

If all you want to do is to return the traversed edges, then use a minimal depth of 1, not 0:

```js
FOR vertex, edge IN 1..1 OUTBOUND "skills/MM" graph 'skills_hierarchy'
  RETURN edge._to
```

**Comment by RHSman** [comment]
ok, so what about SHORTEST path returning a null entry? That really doesn't make any sense
`FOR vertex, edge IN INBOUND SHORTEST_PATH 'skills/MM-PUR' TO 'skills/SCOPE_ITEM' GRAPH 'skills_hierarchy' return edge`

`[
  null,
  {
    "_key": "13714256",
    "_id": "skill_skill/13714256",
    "_from": "skills/2R7.KP.7",
    "_to": "skills/MM-PUR",
    "_rev": "_YX6uQTy---",
    "type": "app_scope"
  },
  {
    "_key": "13713352",
    "_id": "skill_skill/13713352",
    "_from": "skills/2R7",
    "_to": "skills/2R7.KP.7",
    "_rev": "_YX6uPvK---",
    "type": "child"
  },
  {
    "_key": "13713185",
    "_id": "skill_skill/13713185",
    "_from": "skills/SCOPE_ITEM",
    "_to": "skills/2R7",
    "_rev": "_YX6uPny---",
    "type": "child"
  }
]`

**Comment by goedderz** [comment]
Note that a path with `n` vertices has `n-1` edges. The shortest path query returns all vertices along the path, each together with its incoming edge on the path. But the start vertex does not have such an edge; it is always null.

So say you execute the query `FOR v, e IN OUTBOUND SHORTEST_PATH s TO t GRAPH 'G' RETURN {v, e}`, and the path returned is `A --y--> B --z--> C`. Then this would return `[ {v: A, e: null}, {v: B, e: y}, {v: C, e: z} ]`.

So the reason here is the same as in the traversal.

**Comment by RHSman** [comment]
Hmm, Ok.
It makes sense I suppose but isn't very intuitive to me. Thanks for the explanation.
