### ISSUE TITLE
Add import function to arangosh

### ISSUE THREAD

**Issue by minnownoir** [arangodb/arangodb#862]
As a developer, I would like to be able to create, drop, and load collections from the same tool.  

Right now, I can create and drop collections from arangosh but can only load from arangoimp.  That means while debugging applications, where I'm dropping, creating and loading collections often, I have to drop in arangosh, then either create in arangosh or pass in the --create-collection on arangoimp, and then use arangoimp to load the data.  It would be nice if there were a db._loadCollection("myDb", "myCollection", "myFile.dat", "csv") method on arangosh.

Note:  Adding a parameter to overwrite existing collections (e.g., --overwrite) to arangoimp would be nice, as well, since sometimes developers will want to script loading changing/overlapping datasets into ArangoDB for analysis without having to use arangosh to drop the existing data before using arangoimp to load the refreshed data.

**Comment by ixxie** [comment]
This goes somewhat beyond the scope of this issue, but I will post it here since its still relevant.

While I am by no means an ArangoDB expert, I have been involved in doing data science and devops for a NLP microservice deployed with an ArangoDB container in the last 6 months. My experience led me to view the status quo as:

1. ArangoDB provides various interfaces through:
  a. REST API;
  b. Javascript bindings;
  c. shell tools and programs (arangodump, arangoinspect, etc);
  d. the web GUI;
  d. other language bindings / integrations.
2. These disparate APIs expose different functionality.
3. Devops and application scripting therefore has to be done using multiple languages/interfaces.
4. The closest thing to a unified comprehensive API is found in the `@arangodb` Javascript module.
5. The most reasonable way to deploy any serious JS based tooling is using a Foxx microservice, since it includes an easy way to import other node modules, proper deployment patterns, etc. It is also the most cross-interface friendly - `routers` can be used to expose a REST API and `foxx-cli` can be used to expose a CLI (with `foxx run`).

If this is correct then the intuitive course of action to me would to lean into Foxx as the main API framework and:
1. Articulate a canonical ArangoDB API that covers the functionality needed for fundamental database maintenance and use.
2. Extend the Javascript API implementation to cover the full API, allowing Foxx microservices to be building blocks for ArangoDB devops infrastructure.
3. Have the foxx-cli bundled with ArangoDB - at least in some production ready Docker image - and include templates for devops tasks.
4. Clarify, document and extend support for deployment models for these scripts (e.g. through `/docker-entrypoint-initdb.d`) 
5. Document the API by cross-referencing* endpoint and language to allow the user access to:
  a. a complete reference for each API language, listing all the endpoints
  b. an abstract description of each endpoint with a table showing the language specific syntaxes for calling it
6. Document a database development & maintanance lifecycle example to illustrate workflows

* this should be achievable with minimal duplicated effort by scripted building of the language specific sections from code or configuration files describing the endpoints in a scripting-friendly way.

I am still trying to figure this stuff out, so I am sure the above is not 100% clear, but hopefully will be of use.

**Comment by dothebart** [comment]
as discussed on slack, https://github.com/deusdat/arangomigo covers parts of the required things here, but is not completely whats desired.

3.4 and later versions of the docker container will contain foxx cli.

**Comment by Simran-B** [comment]
The originally issue is long solved and I don't see how the recent posts are related to this ticket.
Created a new one here: #7504
