### ISSUE TITLE
How to delete a attribute in document with AQL?

### ISSUE THREAD

**Issue by wjx-git** [arangodb/arangodb#8843]
a document like this:
{
    "is_encode": "1",
    "parse_session": "20180916",
    "update_time": "2018-10-14 10:43:52",
    "data_source": "seekerhr0910",
    "resume_status_code": "1",
}
How to delete "data_source" attribute with AQL

**Comment by Simran-B** [comment]
To remove an attribute (not necessarily at the top-level), you can use the following approach:

    UPDATE doc WITH { data_source: null } IN coll OPTIONS { keepNull: false }

This overwrites the `data_source` with an explicit `null`, which is then removed because of the query option `keepNull: false`. For a nested attribute you would do `WITH { nested: { data_source: null } }` likewise. Note that only those attributes are removed, which you set to null in the query. A stored attribute with a `null` value will be kept despite the query option, e.g.
`UPDATE doc WITH { data_source: null } IN coll` followed by
`UPDATE doc WITH { } IN coll OPTIONS { keepNull: false }` will not remove the attribute, but keep it as
`{ "data_source": null }` because the attribute isn't set to null in the query with `keepNull: false`.

To remove a top-level attribute, you can also do:

    REPLACE doc WITH UNSET(doc, "data_source") IN coll

- https://docs.arangodb.com/3.4/AQL/Operations/Update.html#setting-query-options
- https://docs.arangodb.com/3.4/AQL/Functions/Document.html#unset
