### ISSUE TITLE
 FATAL {config} Collection import not found although collection exits

### ISSUE THREAD

**Issue by zopyx** [arangodb/arangodb#9009]
ArangoDB 3.4.5
RocksDB
Single Server
Manual Start
Fedora 26
Installed using Fedora packages

I have this database `ugent` and a collection `import`:

```
ajung@dev ~/src/arangodb (devel) $ arangosh --server.password XXXX --server.database ugent 

                                       _     
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__  
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \ 
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/                 

arangosh (ArangoDB 3.4.5 [linux] 64bit, using jemalloc, build tags/v3.4.5-0-g648fbb8191, VPack 0.1.33, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0j  20 Nov 2018)
Copyright (c) ArangoDB GmbH

Command-line history will be persisted when the shell is exited.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.4.5 [SINGLE, server], database: 'ugent', username: 'root'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@ugent> db
[object ArangoDatabase "ugent"]

127.0.0.1:8529@ugent> db._collection('import')
[ArangoCollection 395, "import" (type document, status loaded)]

```

Trying to export the collection:

```
arangoexport --server.password XXXX --server.database ugent --collection import
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.4.5, database: 'ugent', username: 'root'
# Exporting collection 'import'...
2019-05-15T16:27:32Z [7900] FATAL {config} Collection import not found.

```

`arangodump` on the same collection works

**Comment by maxkernbach** [comment]
Hi @zopyx,

I was not able to reproduce this issue yet.

Since `arangodump` works, would it be possible to share the dump output directory, which includes the collection `import`? Does this problem persist when you restore the dump, that is obtained by `arangodump`, with `arangorestore`?

You can send us a message to hackers@arangodb.com (this ML is not public) and attach the dump in that email. This way we can try to reproduce and find the root cause. Please reference the number of this issue in your email.

**Comment by OmarAyo** [comment]
Hi @zopyx 

Closing this issue for now since we have not heard back from you in a while.
In case the problem persists, please respond to the latest comments and we will reopen.
