### ISSUE TITLE
Cannot search by _id in ArangoDB Web UI, but search by _key is OK

### ISSUE THREAD

**Issue by sonyarianto** [arangodb/arangodb#9148]
## My Environment

* __ArangoDB Version__:       3.4.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               normal
* __Infrastructure__:               Own
* __Operating System__:        CentOS 7
* __Total RAM in your machine__:        24Gb
* __Disks in use__:        HDD (3TB)
* __Used Package__:              SUSE or RedHat .rpm

## Component, Query & Data

__Affected feature__:
ArangoDB Web UI

## Steps to reproduce

1. I go to Web UI, I have a collection, when I search by _key data not found, but if I search by _id the data found. 
2. For me this is strange, since _key is seperate data and why not show up when search by _key 
3. Is this intended behaviour?

__Expected result__:
User able search by _key inside a FOR that use a particular collection.

**Comment by OmarAyo** [comment]
Hi @sonyarianto 

I've done a quick test and I was probably found what you are doing wrong:

- created a collection `c1`
- populated the collection with 1000 doc

At this moment I executed the following query filtering by the `._key` field:
`FOR d IN c1 FILTER d._key == 'sony42' RETURN d`
and I got the following expected result:
```
[ 
  { 
    "_key" : "sony42", 
    "_id" : "sony/sony42", 
    "_rev" : "_YuyVUpu---", 
    "value" : 42 
  } 
]
```
Then I filterd on `._id` field:
`FOR d IN c1 FILTER d._id == 'sony42' RETURN d`
And as you reported no result was returnd

This is because the `._id` field contains also the collection prefix that you are "probably" not passing in your query. See below-edited query: 
`FOR d IN c1 FILTER d._id == 'c1/sony42' RETURN d`

This query will now return the expected result

Please edit your query by citing the collection name when filtering by the `._id` field

Best,

**Comment by sonyarianto** [comment]
Hi @OmarAyo 
Thanks for the reply. Ahaaaa, now I know the problem. I treat the _key as integer. Like below AQL.

```
FOR ss IN some_sexy_collection
FILTER ss._key == 1
RETURN ss
```
Above return nothing. But when I change to this
```
FOR ss IN story_sources
FILTER ss._key == '1'
RETURN ss
```
It return what I am expected.

Hmmmm, at least I learn something new today.

Thank you and have a good day.

**Comment by OmarAyo** [comment]
Hi @sonyarianto  

You are welcome, I am going to close this ticket now 

Best,

**Comment by sonyarianto** [comment]
@OmarAyo and also in ArangoDB Web UI I use _key == 1, it should be _key == "1"
