### ISSUE TITLE
Thrift support

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#917]
I think it would be quite interesting to have the option to serve responses as [thrift](http://thrift.apache.org/) over http.

This isn't something that I feel is very important, but would be nice to have.

**Comment by jsteemann** [comment]
An update on this issue: we'll probably not have a separate interface for Thrift I/O.

This is because we would need to unpack incoming Thrift data anyway to get it into our internal format. And to ship it to clients we would need to convert it from our internal format. 
We'll likely switch to a different format that we can use for efficient serialization and unserialization as well as (indexed) storage. Thrift, MessagePack and all the others are very good for serialization and unserialization, but are not ideal for working with schema-free data and quickly navigating inside.

The format we require needs to be compatible to JSON in the sense of that it must be able to handle all valid JSON data and that we can also use it for processing incoming JSON, *and* it must not require a schema for data. We looked around a bit for such format, and could not find one that is really helps us.

**Comment by CoDEmanX** [comment]
... therefore you created your own - no need to be modest! See [VelocyPack](https://github.com/arangodb/velocypack/blob/master/README.md) :+1:

**Comment by jsteemann** [comment]
@CoDEmanX : yes, but it's not yet fully integrated into ArangoDB. Once that's done, I will likely become unmodest.
