### ISSUE TITLE
Error on 3.5.0-rc.3 arangod.exe auto-upgrade-start with 3.4.x database folder

### ISSUE THREAD

**Issue by x3cion** [arangodb/arangodb#9307]
## My Environment

* __ArangoDB Version__:        3.5.0-rc.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Manual Start 
* __Configuration__:               No changes
* __Infrastructure__:               
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Windows win64 zip Package

## Component, Query & Data

__Affected feature__:
Upgrade

__Size of your Dataset on disk__: 42Gb

## Steps to reproduce

1. Start `.\arangod.exe --database.auto-upgrade true`

__Problem__:
A error message is shown, although the upgrade was successful and the process ends:
```
2019-06-21T13:45:30Z [7536] ERROR [fae2c] {rocksdb} RocksDB encountered a background error during a compaction operation; The database will be put in read-only mode, and subsequent write errors are likely
```
I don't know whether the exit of the process is intentional, but since the upgrade did run well, maybe there should be no ERROR message. A normal start (`.\arangod.exe`) after the upgrade ran well and let me insert documents (no errors and no read-only mode in the new process).

__Expected result__:
No error message.

**Comment by maxkernbach** [comment]
Hi @x3cion,

the exit of the `arangod` process with option `--database.auto-upgrade true` is intentional once the database upgrade has finished. Afterwards the same `arangod` command without option `--database.auto-upgrade true` has to be executed to startup the server again.

However it is not expected that the stated error message occurs during the upgrade. I was not able to reproduce this error when performing a 3.4.6-1 -> 3.5.0-rc.3 upgrade on a database directory with some sample data.

- Do you have a backup of your 3.4.x database directory, that can be used to reproduce this error?
- Which 3.4.x version did you use when performing the upgrade?
- Since performing the upgrade, did you see any errors in the log?

**Comment by maxkernbach** [comment]
Hi @x3cion,

Since we have not heard back from you in a while, I am closing this issue for now.
If this issue persists, please reply to my latest comment and we will reopen it.
