### ISSUE TITLE
[Idea] ArangoDB for Wikidata

### ISSUE THREAD

**Issue by MorganeAlinai** [arangodb/arangodb#9310]
Wikidata has some scalling issues with its triplestore. The database is enormous and this type of engine does not support scalling so well. Could changing to a mixed model like ArangoDB be a key to resolve this issue ?

I opened the discussion here since it is not really what GitHub is meant for...

[Wouldn't a mix database system that handle both JSON documents and graph functions, like ArangoDB, provide a better scalability to enormous knowledge graphs like Wikidata than a classical quadstore?](https://www.quora.com/Wouldnt-a-mix-database-system-that-handle-both-JSON-documents-and-graph-functions-like-ArangoDB-provide-a-better-scalability-to-enormous-knowledge-graphs-like-Wikidata-than-a-classical-quadstore)

**Comment by dothebart** [comment]
Hi, 
The relation of [ArangoDB and Tripplestores have been discussed on stackoverflow](https://stackoverflow.com/questions/34015945/sparql-interface-for-arangodb) with the conclusion that there can be no direct automated translation - A conversion of the datamodel is required. 

@smyth64 has been discussing this in 
 https://github.com/arangodb/arangodb/issues/1913#issuecomment-447632284 resulting in https://github.com/smyth64/arangodb-wikidata-importer. This could already be a good starting point for an eventual data model conversion.

The question to ask would probably be which queries to use this in, and how to best work with it.

A good starting point would probably be [the ArangoDB Graph course](https://www.arangodb.com/arangodb-graph-course/).

Another topic covered in the linked article is search. Since now [ArangoSearch](https://www.arangodb.com/why-arangodb/full-text-search-engine-arangosearch/) is available - a good question could be how it could be included here.

**Comment by maxkernbach** [comment]
Hi @MorganeAlinai,

has dothebart's comment been helpful?
Do you have any further questions?

**Comment by maxkernbach** [comment]
@MorganeAlinai 

I am closing this issue as solved for now.
If you have any further questions, please comment and we will reopen.
