### ISSUE TITLE
Error Query: not found in Web Interface

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#9346]
## My Environment

* __ArangoDB Version__: 3.3.20  
* __Storage Engine__: RocksDB           
* __Deployment Mode__: Cluster       
* __Deployment Strategy__: Kubernetes  
* __Infrastructure__: Google Cloud              

While using the Arangodb Web Interface, at least 3 of 4 attempts I get the same error **Query: not found**.
But, it doesn't occur while using a python client.
![Screenshot_20190627_141415](https://user-images.githubusercontent.com/16288600/60251631-83a46580-98e6-11e9-8481-2a6deb787fb8.png)

Thanks,
Dilip Vamsi.

**Comment by dothebart** [comment]
can you <F12> and show whats going on on the network layer?

**Comment by jsteemann** [comment]
This may have to do with the load-balancer used by Kubernetes installations.
It may route queries to random coordinators, but AQL queries can only be accessed from the specific coordinator that they were started on.
Older versions of ArangoDB just failed when this happened, but newer versions of ArangoDB are expected to work in this setup, as load-balancing support was added at some point during the 3.3 series. 3.3.21 should actually include all the required fixes, so that when some request for a query is sent to a server that it wasn't started on it should redirect it to the proper coordinator.
Can you try at least version 3.3.21 (newer versions are available as well)?

**Comment by dilipvamsi** [comment]
Thanks @jsteemann ,
I will update to 3.4.2 version and will let you know if the error still occurs after adding/removing coordinators.

**Comment by dilipvamsi** [comment]
Hi @dothebart,
As said by @jsteemann, the query is unable to redirect to the proper coordinator. I'm getting a **404 (Not Found)**.
I think then the error should be changed from `Query: not Found` to `Unable to Reach Server`.

**Comment by maxkernbach** [comment]
Hi @dilipvamsi,

did you already have a chance to upgrade your deployment?
Does the query error persist after the upgrade?

**Comment by dilipvamsi** [comment]
Hi @maxkernbach ,
I have upgraded and I didn't find any error as of now.
Thanks,
Dilip Vamsi.

**Comment by maxkernbach** [comment]
Thanks for your reply, I am closing this issue for now.
In case this error reoccurs, please comment and we will reopen.
