### ISSUE TITLE
setTimeout inside foxx router gives 204

### ISSUE THREAD

**Issue by ashutosh-akss** [arangodb/arangodb#9609]
## My Environment

"arangodb engine: "^3.0.0"

```
router
  .get("/api", function(req, res) {
      setTimeout(() => {
        res.send("Hello from Arango);
      }, 3000);
  })
  .queryParam("url", joi.string().required(), "url to fetch")
  .response(joi.object().required(), "Entry stored in the collection.")
  .summary("Retrieve an api response")
  .description('Retrieves an entry from the "api" collection by url.');
```

above function in foxx service gives 204 no content but works file when setTimeout is removed, how to get this working, my purpose is to introduce controlled delays in response

**Comment by caracal7** [comment]
V8 doesn’t have event loop and setInterval/setTimeout functions. You cannot use this functions inside “V8 isolate” like FOXX service.
Simplest way to solve your problem is use simple node/express server but not FOXX

**Comment by pluma** [comment]
@caracal7 is correct. ArangoDB is synchronous, so there's no way to introduce a delay without actively waiting (which ties up an entire v8 context, preventing ArnagoDB from doing anything else with it, which is a bad idea).

The `setTimeout` function only exists because some node dependencies have caused problems in the past if it wasn't defined, even if they didn't actually need it to work.

I'm closing this as answered.
