### ISSUE TITLE
search an attribute value inside document attributes

### ISSUE THREAD

**Issue by antokara** [arangodb/arangodb#974]
I am sorry in case this is solved with the current functions/operators available, perhaps I have missed something.

So the issue is that I have a Document with a number of attributes,
one of them is of type document (not list). I need to search inside this attribute
which is called "modules" for one that has the "name" attribute with value "my module 1".

Is that possible with AQL? To match a document's value without knowing in which sub attribute this value is located? (basically perform a "find by module name", in this example)

...
"someAttr":"someValue",
"modules": {
    "module1": {
      "name": "my module 1",
      "type": "basic"
    },
    "module2": {
      "name": "my module 2",
      "type" : "basic"
    },
  },
...

I know that I cannot use FOR or POSITION since this is not a list.
MATCHES does not work either since I don't know the exact attribute "path".

Only possible solution appears to be a combination of TO_LIST  nad POSITION but even that is not optimal...

Please ask for more clarification if required.
Thank you.

**Comment by jsteemann** [comment]
Looking at this issue again, since 2.6 there is a relatively simple solution for the problem:

The `TO_LIST()` function can be used here, as it will turn a document (or an attribute) into an array that can then be traversed easily:
For example, given this attribute value:
```json
{ 
  "modules" : { 
    "module1" : { 
      "name" : "module-1" 
    }, 
    "module2" : { 
      "name" : "module-2" 
    } 
  } 
}
```
`TO_LIST(doc.modules)` will turn this into:
```json
[ 
  { 
    "name" : "module-1" 
  }, 
  { 
    "name" : "module-2" 
  } 
]
```
We can then use the `[*]` operator to iterate over it, and even combine it with an inline filter:
```
TO_LIST(doc.modules)[* FILTER CURRENT.name == 'my module 1']
```
That will return all the matches, e.g.:
```json
[ 
  { 
    "name" : "my module 1" 
  } 
]
```
and retrieving just the first one using `[0]` will return it. As no 'my module 1` value may not be present at all, an additional filter filtering for non-null results is necessary.

Full query:
```
FOR doc IN collection
  LET matches = (TO_LIST(doc.modules)[* FILTER CURRENT.name == 'my module 1'])[0] 
  FILTER matches != null 
  RETURN matches
```

**Comment by CoDEmanX** [comment]
Will an array index `modules[*]` index the (sub-)attribute values `module-1` and `module-2` in 2.8? That would be quite handy. On the other hand, a [fulltext index in v2.6+)](https://docs.arangodb.com/IndexHandling/Fulltext.html) should actually do just that, but only for the first nesting level.

**Comment by jsteemann** [comment]
@CoDEmanX : no, the array index won't help here, as it will only work on array values. It will ignore all non-array values and thus ignore the `modules` for the above data, as `modules` is an object.
