### ISSUE TITLE
3.5.0: Error: unknown flag: --database.auto-upgrade

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#9784]
## My Environment

* __ArangoDB Version__:        3.4.6 / 3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Nothing special
* __Infrastructure__:               My laptop
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        10Gb in VM, 32GB total
* __Disks in use__:        SSD
* __Used Package__:             tar

## Component, Query & Data

__Affected feature__:
startup / upgrade

__AQL query (if applicable)__:
n/a

__AQL explain (if applicable)__:
n/a

__Dataset__:
n/a

__Size of your Dataset on disk__:
n/a

__Replication Factor & Number of Shards (Cluster only)__:
n/a

## Steps to reproduce

1. Have data created in 3.4.6
2. Start 3.5.0 using that data and observe the error logs:
```
~/arango$ /home/<username>/arango/3.5.0/bin/arangodb --starter.mode single --starter.data-dir ~/arango/data
*snip*
    2019-08-21T23:23:01Z [29273] ERROR [24e3c] {startup} It seems like you have upgraded the ArangoDB binary.
    2019-08-21T23:23:01Z [29273] ERROR [8bcec] {startup} If this is what you wanted to do, please restart with the
    2019-08-21T23:23:01Z [29273] ERROR [b0360] {startup}   --database.auto-upgrade true
    2019-08-21T23:23:01Z [29273] ERROR [13414] {startup} option to upgrade the data in the database directory.
*snip*
    2019-08-21T23:23:01Z [29273] ERROR [1c156] Database '_system' needs upgrade. Please start the server with --database.auto-upgrade
*snip*
```

3. Follow the instructions in the logs:
```
~/arango$ /home/<username>arango/3.5.0/bin/arangodb --starter.mode single --starter.data-dir ~/arango/data --database.auto-upgrade true
Error: unknown flag: --database.auto-upgrade
```
Note that omitting `true` at the end of the command line has no effect. The logs appear to be inconsistent re whether that's required.

__Problem__:
The logs specify an apparently non-existing flag to use to upgrade data from 3.4.6 -> 3.5.0.

__Expected result__:
The data is upgraded to 3.5.0.

**Comment by jsteemann** [comment]
Sorry for the confusion, the option actually exists, but in `arangod`.

The problem here is that there are two executables, `arangodb` and `arangod`.
`arangod` is the server process, which can be manually started or started by the `arangodb` executable, which we call the ArangoDB "starter". This is the executable that you are invoking. 
 
The starter is useful to start a bunch of servers in different modes easily, but it has slightly different command-line options than `arangod`. This is a source of confusion, unfortunately.

The starter can pass arbitrary options to arangod using the `--all` option, as described here:
https://www.arangodb.com/docs/stable/programs-starter-options.html#other-database-options

So in this case the option to pass to the starter would be `--all.database.auto-upgrade=true`.

**Comment by MrCreosote** [comment]
OK, that is confusing, especially for a newbie like me - the logs definitely steered me wrong. Why is the starter a different executable, out of curiosity?

The flag change works, but it looks like the server continually restarts. The logs contain 
```
	2019-08-22T17:25:04Z [5831] INFO [0de5e] database upgrade passed
	2019-08-22T17:25:04Z [5831] INFO [7da27] {startup} server will now shut down due to upgrade, database initialization or admin restoration.
```
... among other things, over and over, until I `^C` the process and restart the server without the upgrade flag.

BTW, one of the queries I'm working on is >1000x faster on 3.5.0 vs 3.4.6, so I'm pretty happy about that.

Thanks for the help!

**Comment by maxkernbach** [comment]
Hi @MrCreosote,

**1.** The `arangod` executable starts a single ArangoDB server, which is sufficient to run a Single Instance deployment. To run more complex deployments (e.g. Cluster, Active Failover) multiple `arangod` processes are required.

For example a Cluster with 3 agents, 2 dbservers and 2 coordinators requires 8 arangod processes in total. More can be found in the [Cluster - Manual Start](https://www.arangodb.com/docs/stable/deployment-cluster-manual-start.html) documentation.

In order to simplify the deployment the `arangodb` starter tool can be used. The execution of `arangodb` initializes an `arangod` process for each dbserver, coordinator and agent. E.g. using `arangodb --starter.local` to start a local 3 node cluster starts 9 `arangod` processes internally: 3 dbservers, 3 coordinators and 3 agents. The running `arangod` processes can be checked with `ps auxw | grep arangod`.

An exemplary output can be seen below:
```
ps auxw | grep arangod
max       8099  1.9  0.1 114712  8736 pts/0    Sl+  14:47   0:00 arangodb --starter.local
max       8118  3.9  2.5 635016 203736 pts/0   Sl+  14:47   0:00 /usr/sbin/arangod -c /home/max/Documents/starter/test/local-slave-2/agent8551/arangod.conf --database.directory /home/max/Documents/starter/test/local-slave-2/agent8551/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/local-slave-2/agent8551/apps --log.file /home/max/Documents/starter/test/local-slave-2/agent8551/arangod.log --log.force-direct false --javascript.copy-installation true --agency.activate true --agency.my-address tcp://localhost:8551 --agency.size 3 --agency.supervision true --foxx.queues false --server.statistics false --agency.endpoint tcp://localhost:8531 --agency.endpoint tcp://localhost:8541
max       8165 10.5  2.6 676548 215908 pts/0   Sl+  14:47   0:01 /usr/sbin/arangod -c /home/max/Documents/starter/test/agent8531/arangod.conf --database.directory /home/max/Documents/starter/test/agent8531/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/agent8531/apps --log.file /home/max/Documents/starter/test/agent8531/arangod.log --log.force-direct false --javascript.copy-installation true --agency.activate true --agency.my-address tcp://localhost:8531 --agency.size 3 --agency.supervision true --foxx.queues false --server.statistics false --agency.endpoint tcp://localhost:8541 --agency.endpoint tcp://localhost:8551
max       8168  5.4  2.6 705236 216828 pts/0   Sl+  14:47   0:00 /usr/sbin/arangod -c /home/max/Documents/starter/test/local-slave-2/dbserver8550/arangod.conf --database.directory /home/max/Documents/starter/test/local-slave-2/dbserver8550/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/local-slave-2/dbserver8550/apps --log.file /home/max/Documents/starter/test/local-slave-2/dbserver8550/arangod.log --log.force-direct false --javascript.copy-installation true --cluster.my-address tcp://localhost:8550 --cluster.my-role PRIMARY --foxx.queues false --server.statistics true --cluster.agency-endpoint tcp://localhost:8531 --cluster.agency-endpoint tcp://localhost:8541 --cluster.agency-endpoint tcp://localhost:8551
max       8171  4.8  2.5 641160 204968 pts/0   Sl+  14:47   0:00 /usr/sbin/arangod -c /home/max/Documents/starter/test/local-slave-1/agent8541/arangod.conf --database.directory /home/max/Documents/starter/test/local-slave-1/agent8541/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/local-slave-1/agent8541/apps --log.file /home/max/Documents/starter/test/local-slave-1/agent8541/arangod.log --log.force-direct false --javascript.copy-installation true --agency.activate true --agency.my-address tcp://localhost:8541 --agency.size 3 --agency.supervision true --foxx.queues false --server.statistics false --agency.endpoint tcp://localhost:8531 --agency.endpoint tcp://localhost:8551
max       8302  6.4  2.6 696532 216668 pts/0   Sl+  14:47   0:00 /usr/sbin/arangod -c /home/max/Documents/starter/test/dbserver8530/arangod.conf --database.directory /home/max/Documents/starter/test/dbserver8530/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/dbserver8530/apps --log.file /home/max/Documents/starter/test/dbserver8530/arangod.log --log.force-direct false --javascript.copy-installation true --cluster.my-address tcp://localhost:8530 --cluster.my-role PRIMARY --foxx.queues false --server.statistics true --cluster.agency-endpoint tcp://localhost:8531 --cluster.agency-endpoint tcp://localhost:8541 --cluster.agency-endpoint tcp://localhost:8551
max       8304 26.7  2.4 744684 199052 pts/0   Sl+  14:47   0:02 /usr/sbin/arangod -c /home/max/Documents/starter/test/local-slave-2/coordinator8549/arangod.conf --database.directory /home/max/Documents/starter/test/local-slave-2/coordinator8549/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/local-slave-2/coordinator8549/apps --log.file /home/max/Documents/starter/test/local-slave-2/coordinator8549/arangod.log --log.force-direct false --javascript.copy-installation true --cluster.my-address tcp://localhost:8549 --cluster.my-role COORDINATOR --foxx.queues true --server.statistics true --cluster.agency-endpoint tcp://localhost:8531 --cluster.agency-endpoint tcp://localhost:8541 --cluster.agency-endpoint tcp://localhost:8551
max       8306  5.8  2.6 711380 215200 pts/0   Sl+  14:47   0:00 /usr/sbin/arangod -c /home/max/Documents/starter/test/local-slave-1/dbserver8540/arangod.conf --database.directory /home/max/Documents/starter/test/local-slave-1/dbserver8540/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/local-slave-1/dbserver8540/apps --log.file /home/max/Documents/starter/test/local-slave-1/dbserver8540/arangod.log --log.force-direct false --javascript.copy-installation true --cluster.my-address tcp://localhost:8540 --cluster.my-role PRIMARY --foxx.queues false --server.statistics true --cluster.agency-endpoint tcp://localhost:8531 --cluster.agency-endpoint tcp://localhost:8541 --cluster.agency-endpoint tcp://localhost:8551
max       8318 27.5  2.5 760064 202456 pts/0   Sl+  14:47   0:02 /usr/sbin/arangod -c /home/max/Documents/starter/test/coordinator8529/arangod.conf --database.directory /home/max/Documents/starter/test/coordinator8529/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/coordinator8529/apps --log.file /home/max/Documents/starter/test/coordinator8529/arangod.log --log.force-direct false --javascript.copy-installation true --cluster.my-address tcp://localhost:8529 --cluster.my-role COORDINATOR --foxx.queues true --server.statistics true --cluster.agency-endpoint tcp://localhost:8531 --cluster.agency-endpoint tcp://localhost:8541 --cluster.agency-endpoint tcp://localhost:8551
max       8321 32.8  2.5 764160 202212 pts/0   Sl+  14:47   0:02 /usr/sbin/arangod -c /home/max/Documents/starter/test/local-slave-1/coordinator8539/arangod.conf --database.directory /home/max/Documents/starter/test/local-slave-1/coordinator8539/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /home/max/Documents/starter/test/local-slave-1/coordinator8539/apps --log.file /home/max/Documents/starter/test/local-slave-1/coordinator8539/arangod.log --log.force-direct false --javascript.copy-installation true --cluster.my-address tcp://localhost:8539 --cluster.my-role COORDINATOR --foxx.queues true --server.statistics true --cluster.agency-endpoint tcp://localhost:8531 --cluster.agency-endpoint tcp://localhost:8541 --cluster.agency-endpoint tcp://localhost:8551
```

When specifying an option with the starter `arangodb` as `--server.storage-engine rocksdb`, this option is passed to all the starter's `arangod` processes.

A detailed overview for various deployment modes can be found in the documentation's [Deployment chapter](https://www.arangodb.com/docs/stable/deployment.html).

**2.** Currently the `arangod` process upgrades and quits whenever the `--database.auto-upgrade` flag is set (in this case passed through the `arangodb` starter). When the starter (`arangodb`) notices that an internal `arangod` process is shut down, it tries to recover and restarts the same `arangod` process. Therefore, as you noticed, the `arangod` server continually restarts. A [feature request](https://github.com/arangodb/arangodb/issues/1631) that changes this behavior was already opened on github.

However, this is not the recommended way to upgrade starter (`arangodb`) deployments. A much easier approach to upgrade starter (`arangodb`) deployments can be found in our documentation, see [Upgrading Starter Deployments](https://www.arangodb.com/docs/stable/upgrading-starter.html).
