### ISSUE TITLE
Trying to get distinct document attribute values from a large collection fails

### ISSUE THREAD

**Issue by steinerj** [arangodb/arangodb#987]
Hi,

I'm trying to retrieve the equivalent of a SELECT DISTINCT from a large (> 4,000,000) collection of documents via arangosh. So far I've tried two approaches: 

- using COLLECT
- using the UNIQUE function

Sample queries used.

```javascript
stmt = db._createStatement({"query":"FOR u IN user COLLECT level = u.level1 INSERT {\"group\": level} IN foo"} );
cursor = stmt.execute();
```
(Insert distinct values of a document attribute in to another collection)

```javascript
stmt = db._createStatement({"query":"FOR foo IN UNIQUE((FOR u IN user RETURN u.level1)) RETURN {\"group\":foo}"} );
cursor = stmt.execute();
```

In both cases arangosh fails after a while with a 2001 timeout error. On some occasions (couldn't identify a pattern here) arangod crashes as well. I've tried tweaking the request and server timeouts to no avail. I used both Windows and Ubuntu on a reasonably specced machine (8gig RAM).
 
I'm fairly new to ArangoDB, so it's probably me doing something wrong. Could you please advise?

Edit: I found the critical point to be around 2m documents by experimenting with a LIMIT-clause. Obviously, I've been able to work around the issue and I appreciate that this kind of query is not necessarily a sweet spot for a document store..

**Comment by jsteemann** [comment]
Revisiting this one with ArangoDB 2.4.2 and 2.5/devel:
The query with the `COLLECT` clause needs to process all documents from the collection in sorted order, with `user.level1` being the sort criterion. If there is a sorted (skiplist) index present on this attribute, the sort will be optimized away and the `COLLECT` will process the documents in already sorted index order. This will be far better than fetching all documents, then sorting them, and then creating the distinct result set.

I just tried the query on a collection with 4M documents and 90 distinct numeric values in `level1`. The query took about 4 seconds with a skiplist index and about 25 seconds without. But clearly the execution times will vary when using different value type (e.g. strings), a different data distribution etc.

The query containing the `UNIQUE()` function call will definitely have to read all documents to extract their `level1` values, and then do a sort on these values in order to make them unique. It took around 9 seconds with my test data.


I guess you initially ran the queries on an ArangoDB 2.2, so I retried it with that version for a comparison: 
The `COLLECT` version of the query did not finish after 3.5 minutes, so I stopped it.
The version with `UNIQUE()` finished in around 20 seconds with my test data.

So it looks like 2.4/2.5 have improved when compared with 2.2, though I would still like it to be faster for these queries.

**Comment by jsteemann** [comment]
Update for 2.6: 
the `COLLECT` version of the query takes about 3.5 seconds in 2.6 with the test data, with or without an index. The `UNIQUE` version takes about 8 seconds.

So for the `COLLECT` version without an index we have:

* 2.2: 3.5 minutes
* 2.4: 25 seconds
* 2.5: 25 seconds
* 2.6. 3.5 seconds

And for the `UNIQUE` version:
* 2.2: 20 seconds
* 2.4: 9 seconds
* 2.5: 9 seconds
* 2.6: 8 seconds

**Comment by jsteemann** [comment]
Seems it got a lot better when compared to the original execution times, so I'll be closing this issue now.

**Comment by steinerj** [comment]
Cheers... impressive numbers and thanks for following up.

**Comment by jsteemann** [comment]
It was about time to get this done.
